### ISSUE TITLE
regex - righe con spazio iniziale

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#1]
ho la necessità di selezionare tutte le righe, di un dataset, che iniziano con uno spazio, ho usato questa stringa:

`^(\s)([A-Za-z0-9áèéíóúüÁÉÍÓÚÜ!''?\-:,.& ]{1,})`

qui un test: https://regexr.com/4820q

io mi aspetto la selezione di due righe e non tre come da test allegato.

cosa sbaglio??

**Comment by aborruso** [comment]
Ciao totò, tutte le righe che iniziano con spazio è semplicemente `^ .+$`:

- `^ ` > spazio a inizio riga;
- `.+` > un carattere qualsiasi almeno una volta;
- `$` > fine riga

Qui in azione (sul tuo sito c'è qualcosa che non mi torna) https://regex101.com/r/l0HqzL/1/

Se la cosa ti "fila", chiudi la issue :)

P.S. da questa issue dovremmo estrarre https://regex101.com e metterlo in una lista dei siti consigliati per argoento

**Comment by aborruso** [comment]
@pigreco aggiungo una nota che probabilmente è l'origine del tuo problema `\s` corrisponde a qualsiasi "whitespace" (\r\n\t\f\v ), quindi anche tab e "a capo"

**Comment by pigreco** [comment]
@aborruso 
nella mia stringa ho usato i gruppi perché mi servono successivamente per una sostituzione,
nel tuo [test ](https://regex101.com/r/l0HqzL/1/)come posso usare i gruppi??

**Comment by aborruso** [comment]
@pigreco per favore quando apri una issue, definisci per intero il caso d'uso. 

Se i gruppi devono essere quello dello spazio e poi tutto il resto, diventa `(^ )(.*)$`.

**Comment by pigreco** [comment]
> @pigreco aggiungo una nota che probabilmente è l'origine del tuo problema `\s` corrisponde a qualsiasi "whitespace" (\r\n\t\f\v ), quindi anche tab e "a capo"

ecco il motivo, grazie!!!
chiudo issues
