### ISSUE TITLE
scaricare dati raw presenti in un git

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#10]
In questo [git](https://gist.github.com/aborruso/503df6c6477c341431e23bc51bc37149), creato da @aborruso, è presente un file `01_demanio.csv`: come scaricare il file usando il bottore `raw`??
![image](https://user-images.githubusercontent.com/7631137/52620741-b143c180-2ea5-11e9-804e-869384927e2a.png)

ho seguito questa procedure:
1. usando il bottore `raw`;
2. ctrl+a - seleziono tutto;
3. ctrl+c - copio selezione;
4. ctrl+v - incollo; 

usando Notepad++ ritrovo solo 16k righe circa su oltre 32k
![image](https://user-images.githubusercontent.com/7631137/52620953-5494d680-2ea6-11e9-9e79-0e7151bfe22a.png)

**Comment by aborruso** [comment]
tra i modi possibili:

- tasto destro su RAW e poi salva link con nome;
- o tasto destro e copi il link e poi `wget -O "nomefile" link`

**Comment by pigreco** [comment]
@aborruso 
grazie, tasto destro e salva link con nome è la mia preferita, grazie

![image](https://user-images.githubusercontent.com/7631137/52621454-9d00c400-2ea7-11e9-9ee6-4b357535e41c.png)

**Comment by pigreco** [comment]
per usare quasto metodo occorre aspettare che la pagina carichi:
>ho seguito questa procedure:

>1. usando il bottore `raw`;
>2. ctrl+a - seleziono tutto;
>3. ctrl+c - copio selezione;
>4. ctrl+v - incollo;

io facevo subito ctrl+a selezionando solo una parte dei dati :-)
