### ISSUE TITLE
[geocoding] estrarre coppia coordinate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#101]
A partire da questo formato di indirizzo:

```
Vicolo Sponta, 6, LUCOLI
```

ed usando le API di OSM, volevo tirare fuori le coordinate lat e lon usando questo comando:

```
=JOIN(",", ImportXML(CONCATENATE("http://nominatim.openstreetmap.org/search/?format=xml&q=",E2), "//place[1]/@lat | //place[1]/@lon"))
```

ma ni segnala un errore.

qui sheet:

https://docs.google.com/spreadsheets/d/1A88Ns3RnCCJ7eWcGZ6mAtNaTLj4ZJH41EfolGjAic4s/edit?usp=sharing

**Comment by gbvitrano** [comment]
Da una ricerca veloce su OSM, non viene trovato nessun risultato per quellìindirizzo

![2020-01-07_16h48_33](https://user-images.githubusercontent.com/20488693/71908028-8c1b0a00-316d-11ea-9344-0291001df4ea.png)

**Comment by aborruso** [comment]
Caro @pigreco il server OSM per ora è un po' giù :(

In ogni caso inserendo un indirizzo "noto" ho avuto un risultato. In XML si può avere anche l'esito, in modo che tu possa sapere se hai avuto un set vuoto.
Ma non riesco per ora a fare rispondere il server.

Se vuoi usare i dati OSM , con alle spalle un server che risponde meglio ti puoi creare un account su OpenCage https://opencagedata.com/

Ti verrà fornita una chiave di API, da custodire ovviamente.

**Comment by pigreco** [comment]
Caro @aborruso ,
grazie per l'ottimo suggerimento.

Ho fatto un test e `opencagedata` tira fuori quasi sempre le stesse coordinate:

![image](https://user-images.githubusercontent.com/7631137/71912786-76f6a900-3176-11ea-81ff-499034ff30fb.png)

**Comment by aborruso** [comment]
Ciao @pigreco questo non dipenderà dalle API, ma dalla banca dati.

Purtroppo OSM in alcune aree è carente

**Comment by pigreco** [comment]
ho scritto questo breve blog post con l'aiuto di @aborruso (grazie)

https://pigrecoinfinito.com/2020/01/08/openstreetmap-e-i-numeri-civici/
