### ISSUE TITLE
[QGIS] Trasferire attributi per posizione

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#102]
Sto giocando con i dati INGV suii terremoti avvenuti in Italia nel 2019, visto che l'informazione di regione, provincia e comune non sono presenti, (c'è solo un campo **Zona** con questa info tipo **6 km E Norcia (PG)** ) avevo pensato di usare i poligoni dei confini ISTAT per trasferire le informazioni mancanti.

Ma come fare quando i punti ricadono in mare aperto e fuori dai poligoni dell'Istat? 
Volevo suddividere gli enti per le varie regioni :-)

![2020-01-07_17h16_08](https://user-images.githubusercontent.com/20488693/71910484-4745a200-3172-11ea-8f4b-55957f2069a7.png)

**Comment by pigreco** [comment]
Caro @gbvitrano,

- nel caso dei punti sovrapposti puoi usare lo strumento che trovi in Processing `Unisci attributi per posizione` ed usi il predicato `interseca` o `contiene`, cosi puoi trasferire tutti gli attributi che vuoi;
- nel caso in cui i punti cadono fuori dai poligoni occorre usare altro algoritmo che tiene conto della vicinanza del punti al poligono, in questo caso ti consiglio il mio ultimo [blog post](https://pigrecoinfinito.com/2020/01/07/qgis-join-attributes-by-nearest/)

**Comment by aborruso** [comment]
@gbvitrano secondo me ciò che è a mare rimane non assegnato.

**Comment by pigreco** [comment]
@gbvitrano 
per me puoi chiuderla e non occorre ricetta :-)

**Comment by gbvitrano** [comment]
Scusate il ritardo :-(
