### ISSUE TITLE
[HTML] scala numerica su legenda continua

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#103]
Grazie a questo codice HTML (by Ludovico Frate @ludovico85)  preso da [qui](https://www.youtube.com/channel/UCuD_TCWBCpHTqQEFnBDOFOQ) è possibile aggiungere una legenda continua, come questa:

![image](https://user-images.githubusercontent.com/7631137/71980051-77974a00-321f-11ea-900b-d2a7bbef15ff.png)

questo il codice:

```html
<html>
<body>
<body style="background-color:white">
<p style="font-size:14px;font-family:arial;">my title</p>
<p style="font-size:12px;font-family:arial;">lowest value</p>
<canvas id="myCanvas" width="50" height="300">
</canvas>
<p style="font-size:12px;font-family:arial;">highest value</p>
 <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');
      context.rect(0, 0, canvas.width, canvas.height);


      // add linear gradient
      var grd = context.createLinearGradient(0,0,0,300, canvas.width, canvas.height);
      // light blue
      grd.addColorStop(0, '#2b83ba');   
      // dark blue
      grd.addColorStop(0.25, '#9dd3a7');
       // dark blue
      grd.addColorStop(0.50, '#ffedaa');
       // dark blue
      grd.addColorStop(0.75, '#f99e59');
       // dark blue
      grd.addColorStop(1, 'red');
      
      context.fillStyle = grd;
      context.fill();
    </script> 
</body>
</html>
```

vorrei aggiungere, sul lato destro, una scala di valori (es: 0,25,50,75,100) 

![image](https://user-images.githubusercontent.com/7631137/71980160-b2997d80-321f-11ea-8e64-e593a72af0e8.png)

grazie!

**Comment by gbvitrano** [comment]
Puoi dofificare la scala come meglio credi, è molto semplice, la posizione dei colori è data dai numeri **1**, **0.90**, **0.60** e cosi via, la posizione intermedia è lo **.050** il colore lo modifichi cambiamdo il codice
![immagine](https://user-images.githubusercontent.com/20488693/71980630-d4dfcb00-3220-11ea-97a0-4cb7a0966436.png)
![2020-01-08_14h12_07](https://user-images.githubusercontent.com/20488693/71980642-db6e4280-3220-11ea-8e67-e5dd1320976e.png)

**Comment by gbvitrano** [comment]
il colore che vuoi aggiungere tu in questo caso è **#001932**

**Comment by gbvitrano** [comment]
```<html>
<body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<body style="background-color:white">
   <table width="200" border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td colspan="3"><p style="font-size:14px;font-family:arial;">my title</p></td>
    </tr>
    <tr>
      <td colspan="3"><p style="font-size:12px;font-family:arial;">lowest value</p></td>
    </tr>
    <tr align="center">
      <td width="60" height="320"><canvas id="myCanvas" width="50" height="300">
  </canvas>
  <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');
      context.rect(0, 0, canvas.width, canvas.height);


      // add linear gradient
      var grd = context.createLinearGradient(0,0,0,300, canvas.width, canvas.height);
      // light blue
      grd.addColorStop(0, '#2b83ba');   
      // dark blue
      grd.addColorStop(0.25, '#9dd3a7');
       // dark blue
      grd.addColorStop(0.50, '#ffedaa');
       // dark blue
      grd.addColorStop(0.75, '#f99e59');
       // dark blue
      grd.addColorStop(1, 'red');
      
      context.fillStyle = grd;
      context.fill();
    </script></td>
      <td width="5" height="320">&nbsp;</td>
      <td width="140" height="320" align="left" valign="top"><div id="0" style="position: relative; top:5px;"><i class="fa fa-angle-left" aria-hidden="true"> - </i>0</div>
      <div id="50" style="position: relative; top:135px;""><i class="fa fa-angle-left" aria-hidden="true"> - </i>50</div>
      <div id="100" style="position: relative; top:260px;"><i class="fa fa-angle-left" aria-hidden="true"> - </i>100</div></td>
    </tr>
    <tr>
      <td colspan="3"><p style="font-size:12px;font-family:arial;">highest value</p></td>
    </tr>
    </tbody>
</table>
</body>
</html>
```

**Comment by gbvitrano** [comment]
![2020-01-09_10h58_07](https://user-images.githubusercontent.com/20488693/72057935-8d644800-32cf-11ea-9d0d-e20fc701503b.png)

**Comment by gbvitrano** [comment]
Ho inerito lo script della scala del colore dentro una tabella
![immagine](https://user-images.githubusercontent.com/20488693/72058257-167b7f00-32d0-11ea-9538-c4efa0dc8409.png)
visto che non conosco la posizione definitiva dove va inserito l'oggetto, ho posizionato i div con le scritte 0 50 e 100 in una posizione relativa alla tabella, modicando il valore **top** puoi adattarli alla tua pagina, se necessario

**Comment by gbvitrano** [comment]
il segno **<** è un font awesome, per cui dei far caricare anche il css esterno 
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">`
già inserito nel codice html :-)

**Comment by pigreco** [comment]
@gbvitrano devo usare lo script nel compositore di stampe di QGIS:

1. avvio il compositore;
2. aggiungo una etichetta 
3. incollo lo script
4. metto la spunta su HTML

![image](https://user-images.githubusercontent.com/7631137/72059096-a0781780-32d1-11ea-8c48-1d831c28b93b.png)

**Comment by gbvitrano** [comment]
![2020-01-09_11h25_16](https://user-images.githubusercontent.com/20488693/72059700-ceaa2700-32d2-11ea-9dee-625202cdeb70.png)

forse ho capito il problema... invece di usare un'etichetta ho usato aggiungi file html, ma ho fatto caricare il file da un server esterno

**Comment by gbvitrano** [comment]
Come pensavo, non viene caricato il css esterno quindi occore commentare 
****

**Comment by gbvitrano** [comment]
Ecco il nuovo codice, ma le freccine sono più brutte :-) 
`<html>
<body>

<body style="background-color:white">
   <table width="200" border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td colspan="3"><p style="font-size:14px;font-family:arial;">my title</p></td>
    </tr>
    <tr>
      <td colspan="3"><p style="font-size:12px;font-family:arial;">lowest value</p></td>
    </tr>
    <tr align="center">
      <td width="60" height="320"><canvas id="myCanvas" width="50" height="300">
  </canvas>
  <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');
      context.rect(0, 0, canvas.width, canvas.height);
      // add linear gradient
      var grd = context.createLinearGradient(0,0,0,300, canvas.width, canvas.height);
      // light blue
      grd.addColorStop(0, '#2b83ba');   
      // dark blue
      grd.addColorStop(0.25, '#9dd3a7');
       // dark blue
      grd.addColorStop(0.50, '#ffedaa');
       // dark blue
      grd.addColorStop(0.75, '#f99e59');
       // dark blue
      grd.addColorStop(1, 'red');
      context.fillStyle = grd;
      context.fill();
    </script></td>
      <td width="5" height="320">&nbsp;</td>
      <td width="140" height="320" align="left" valign="top"><div id="0" style="position: relative; top:5px;"><-0</div>
      <div id="50" style="position: relative; top:135px;"><- 50</div>
      <div id="100" style="position: relative; top:260px;"><-100</div></td>
    </tr>
    <tr>
      <td colspan="3"><p style="font-size:12px;font-family:arial;">highest value</p></td>
    </tr>
    </tbody>
</table>
</body>
</html>`

**Comment by ludovico85** [comment]
Si bisogna utilizzare l'etichetta e spuntare visualizza come html e non aggiungere direttamente l'html.

**Comment by gbvitrano** [comment]
![2020-01-09_11h38_12](https://user-images.githubusercontent.com/20488693/72060578-91469900-32d4-11ea-83c2-0f193f60b625.png)

etichetta, visualizza come html ed ho elimato il css esterno :-)

**Comment by pigreco** [comment]
@gbvitrano e @ludovico85 

![image](https://user-images.githubusercontent.com/7631137/72062213-9fe27f80-32d7-11ea-99d9-15725ca19086.png)

**Comment by pigreco** [comment]
potrei girarla, ma il testo no!!!

![image](https://user-images.githubusercontent.com/7631137/72068687-f22a9d00-32e5-11ea-9e02-355bdd260980.png)

**Comment by pigreco** [comment]
questo codice

```html
<body>
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->
<body style="background-color:white">
   <table width="200" border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td colspan="3"><p style="font-size:20px;font-family:arial;">Grazie Gianni
    <tr>
      <td colspan="3"><p style="font-size:15px;font-family:arial;">cose che pampine</p></td>
    </tr>
    <tr align="center">
      <td width="50" height="300"><canvas id="myCanvas" width="50" height="300">
  </canvas>
  <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');
      context.rect(0, 0, canvas.width, canvas.height);
      // add linear gradient
      var grd = context.createLinearGradient(0,0,0,300, canvas.width, canvas.height);
      // light blue
      grd.addColorStop(0, '#2b83ba');   
      // dark blue
      grd.addColorStop(0.25, '#9dd3a7');
       // dark blue
      grd.addColorStop(0.50, '#ffedaa');
       // dark blue
      grd.addColorStop(0.75, '#f99e59');
       // dark blue
      grd.addColorStop(1, 'red');
      context.fillStyle = grd;
      context.fill();
    </script></td>
      <td width="0" height="320">&nbsp;</td>
      <td width="140" height="300" align="left" valign="top">
	  <div id="0" style="position: relative; top:0px;">→ 0</div>
	  <div id="25" style="position: relative; top:55px;">→ 25</div>
      <div id="50" style="position: relative; top:110px;">→ 50</div>
	  <div id="75" style="position: relative; top:165px;">→ 75</div>
      <div id="100" style="position: relative; top:220px;">→ 100</div></td>
    </tr>
    <tr>
      <td colspan="3"><p style="font-size:16px;font-family:arial;">Grazie Ludovico</p></td>
    </tr>
    </tbody>
</table>
</body>
</html>
```

genera questo

![image](https://user-images.githubusercontent.com/7631137/72072218-bd224880-32ed-11ea-9548-d7a5c1f88e4e.png)


`HTML VIEWER`
https://jsonformatter.org/html-viewer/64367a

**Comment by ludovico85** [comment]
Orizzontale!
[](https://jsfiddle.net/ludovico85/qk28fnu7/)
`<body>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<body style="background-color:white">
   <table width="200" border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td colspan="3"><p style="font-size:14px;font-family:arial;">my title</p></td>
    </tr>
    <tr>
      <td colspan="3"><p style="font-size:12px;font-family:arial;">lowest value</p></td>
    </tr>
    <tr align="center">
      <td width="60" height="320">
	  <canvas id="myCanvas" width="50" height="300">
	  </canvas>
  <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');
      context.rect(0, 0, canvas.width, canvas.height);
      // add linear gradient
      var grd = context.createLinearGradient(0,0,0,300, canvas.width, canvas.height);
      // light blue
      grd.addColorStop(0, '#2b83ba');   
      // dark blue
      grd.addColorStop(0.25, '#9dd3a7');
       // dark blue
      grd.addColorStop(0.50, '#ffedaa');
       // dark blue
      grd.addColorStop(0.75, '#f99e59');
       // dark blue
      grd.addColorStop(1, 'red');
      context.fillStyle = grd;
      context.fill();
    </script>
	</td>
      <td width="5" height="320">&nbsp;</td>
      <td width="140" height="320" align="left" valign="top"><div id="0" style="position: relative; top:5px;">0</div>
      <div id="50" style="position: relative; top:135px;">50</div>
      <div id="100" style="position: relative; top:260px;"> 100</div></td>
    </tr>
    <tr>
      <td colspan="3"><p style="font-size:12px;font-family:arial;">highest value</p></td>
    </tr>
    </tbody>
</table>

<table width="200" border="0" cellspacing="0" cellpadding="0">
    <tr>
	<td colspan = "5" align="center" style="position: relative; left:0px; text-align:center">my legend YlGn</td>
	</tr>
	<tr>
	<td colspan = "2" align="center" width="25%" style="position: relative; left:0px; text-align:center">lowest<br>value</td>
	<td align="left" width="50%" style="position: relative; left:0px;">&nbsp;</td>
    <td colspan = "2" align="center" width="25%" style="position: relative; left:0px; text-align:center">highest<br>value</td>
	</tr>
	<tr align="center">
	  <td width="5" height="10">&nbsp;</td>
	  <td  colspan = "3" width="320" height="60"><canvas id="myCanvas1" width="300" height="50">
  </canvas>
  <script>
      var canvas = document.getElementById('myCanvas1');
      var context = canvas.getContext('2d');
      context.rect(0, 0, canvas.width, canvas.height);
      // add linear gradient
      var grd = context.createLinearGradient(0,0,300,0, canvas.width, canvas.height);
      // light blue
      grd.addColorStop(0, '#ffffcc');   
      // dark blue
      grd.addColorStop(0.25, '#c2e699');
       // dark blue
      grd.addColorStop(0.50, '#78c679');
       // dark blue
      grd.addColorStop(0.75, '#31a354');
       // dark blue
      grd.addColorStop(1, '#006837');
      context.fillStyle = grd;
      context.fill();
    </script>
	</td>
	<td width="5" height="10">&nbsp;</td>
    </tr>
	<tr>
	<td colspan = "2" align="center" width="25%" style="position: relative; left:0px;text-align:center">0</td>
    <td align="center" width="50%">50</td>
    <td colspan = "2" align="center" width="25%" style="position: relative; left:0px;text-align:center">100</td>
	</tr>
</table>
</body>
</html>`

**Comment by ludovico85** [comment]
Orizzontale ma un po' più pulito e con qualche miglioria

https://jsfiddle.net/ludovico85/qk28fnu7/6/

```
<html>
<style>
body {
  font-size: 12px;
  font-family: arial;
}
</style>
<body style="background-color:white; font">
<table width="200" border="0" cellspacing="0" cellpadding="0">
    <tr>
	<td colspan = "5" align="center" style="position: relative; left:0px; text-align:center"><h3>
  my legend YlGn</h3>
  </td>
	</tr>
	<tr>
	<td colspan = "2" align="center" width="25%" style="position: relative; left:0px; text-align:center">lowest<br>value<br>&#8681</td>
	<td align="left" width="50%" style="position: relative; left:0px;">&nbsp;</td>
    <td colspan = "2" align="center" width="25%" style="position: relative; left:0px; text-align:center">highest<br>value<br>&#8681</td>
	</tr>
	<tr align="center">
	  <td width="5" height="10">&nbsp;</td>
	  <td  colspan = "3" width="320" height="60"><canvas id="myCanvas1" width="300" height="50">
  </canvas>
  <script>
      var canvas = document.getElementById('myCanvas1');
      var context = canvas.getContext('2d');
      context.rect(0, 0, canvas.width, canvas.height);
      // add linear gradient
      var grd = context.createLinearGradient(0,0,300,0, canvas.width, canvas.height);
      // light yellow
      grd.addColorStop(0, '#ffffcc');   
      // light green
      grd.addColorStop(0.25, '#c2e699');
       // green
      grd.addColorStop(0.50, '#78c679');
       // green
      grd.addColorStop(0.75, '#31a354');
       // dark green
      grd.addColorStop(1, '#006837');
      context.fillStyle = grd;
      context.fill();
    </script>
	</td>
	<td width="5" height="10">&nbsp;</td>
    </tr>
	<tr>
	<td colspan = "2" align="center" width="25%" style="position: relative; left:0px;text-align:center">0</td>
    <td align="center" width="50%">50</td>
    <td colspan = "2" align="center" width="25%" style="position: relative; left:0px;text-align:center">100</td>
	</tr>
</table>
</body>
</html>
```

**Comment by pigreco** [comment]
Ciao @ludovico85 (grazie)
il codice di sopra si comporta diversamente in QGIS, (il primo è QGIS)
![image](https://user-images.githubusercontent.com/7631137/72074451-3c198000-32f2-11ea-8680-52d7abd0e07a.png)

**Comment by ludovico85** [comment]
Non elegante ma devi giocare con i parametri width in % delle due colonne vuote che sono poste a destra e sinistra del div contenente il riempimento (cerca <td **width="18%"** height="0%">&nbsp;</td>)

```
<html>
<style>
body {
  font-size: 12px;
  font-family: arial;
  width: 100%;
}
</style>
<body>
<table width="200" border="0" cellspacing="0" cellpadding="0">
  <tr>
	  <td colspan = "5" align="center" style="position: relative; left:0px; text-align:center">
    <h3>my legend YlGn</h3>
    </td>
  </tr>
	<tr>
	  <td colspan = "2" align="center" width="25%" style="position: relative; left:0px; text-align:center">
      lowest<br>value<br>&#8681
    </td>
	  <td align="left" width="50%" style="position: relative; left:0px;">&nbsp;</td>
    <td colspan = "2" align="center" width="25%" style="position: relative; left:0px; text-align:center">
    highest<br>value<br>&#8681
    </td>
	</tr>
	<tr align="center">
	  <td width="18%" height="0%">&nbsp;</td>
	  <td  colspan = "3" width="320" height="30">
    <canvas id="myCanvas1" width="300" height="50"></canvas>
        <script>
      		var canvas = document.getElementById('myCanvas1');
      		var context = canvas.getContext('2d');
      		context.rect(0, 0, canvas.width, canvas.height);
      		// add linear gradient
      		var grd = context.createLinearGradient(0,0,300,0, canvas.width, canvas.height);
      		// light yellow
      		grd.addColorStop(0, '#ffffcc');   
      		// light green
      		grd.addColorStop(0.25, '#c2e699');
       		// green
      		grd.addColorStop(0.50, '#78c679');
       		// green
      		grd.addColorStop(0.75, '#31a354');
       		// dark green
      		grd.addColorStop(1, '#006837');
      		context.fillStyle = grd;
      		context.fill();
    		</script>
	  </td>
	  <td width="18%" height="0%">&nbsp;</td>
  </tr>
	<tr>
	  <td colspan = "2" align="center" width="25%" style="position: relative; left:0px;text-align:center">0</td>
    <td align="center" width="50%">50</td>
    <td colspan = "2" align="center" width="25%" style="position: relative; left:0px;text-align:center">100</td>
	</tr>
</table>
</body>
</html>
```

**Comment by pigreco** [comment]
@ludovico85 
risolto
avevo creato un riquadro piccolo, appena l'ho ridimensionato sono apparse le cifre, grazie

![image](https://user-images.githubusercontent.com/7631137/72083106-8eae6880-3301-11ea-8f7a-6828059a7e04.png)

ora mi tocca fare una bella ricetta!!! ;-)

**Comment by pigreco** [comment]
chiudo issue
spero presto di fare ricetta.

grazie a tutti

**Comment by pigreco** [comment]
qui plugin per QGIS 3

https://www.geoproc.com/be/bccbar3.htm

![image](https://user-images.githubusercontent.com/7631137/73611718-f5fbc780-45e4-11ea-9243-02022cb2bdf1.png)
