### ISSUE TITLE
Aggiungi Sticker

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#104]
Ciao @aborruso,
usando come esempio il tuo sticker `T'ansigrari` ho creato un altro sticker `apriISSUE`
se puoi lo aggiungi alla collezione??

https://github.com/opendatasicilia/tansignari/blob/master/risorse/stickerTelegram/stickerApriIssue.png

**Comment by aborruso** [comment]
Aggiunto (non so se il refresh è immediato)
