### ISSUE TITLE
come fare leggere un file .MD a ReadtheDocs

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#106]
finora ho utilizzato file .RST su Guthub che vengono letti da ReadtheDocs.
Se voglio far leggere un file .MD, oltre ai file .RTS, a ReadtheDocs quali impostazioni devo settare e dove?
Grazie

**Comment by aborruso** [comment]
Caro @cirospat di base il formato di default è RST e diciamo che è ottimizzato per RST.

tansignari è proprio un esempio di un RTD in cui si può scrivere in MD. Ad esempio [questo](https://github.com/opendatasicilia/tansignari/blob/master/galateo.md) il galatero in MD e [qui](http://tansignari.opendatasicilia.it/it/latest/galateo.html) la pagina in HTML.

L'ho impostato io in questo modo, ma confesso di non ricordare tutto.

Due i file da guardare:

- `requirements` con i requisiti di moduli da installare https://github.com/opendatasicilia/tansignari/blob/master/requirements.txt
- [`conf.py`](https://github.com/opendatasicilia/tansignari/blob/master/conf.py), il file di configurazione che tu conosci bene, in cui in [queste linee](https://github.com/opendatasicilia/tansignari/blob/master/conf.py#L33-L48) si imposta la configurazione che abilita il markdown.

**Comment by cirospat** [comment]
@aborruso grazie moltissimo degli input!
Chiaro.

### Domanda 1: 
nel file **`conf.py`** non devo anche includere il contenuto della linea 50?
https://github.com/opendatasicilia/tansignari/blob/master/conf.py#L50
che è:   **`source_suffix = ['.rst', '.md']`**   ?
Cioè devo dire a RTD di leggere sia i file di Github in formato `.RST` che i file in formato `.MD`
Giusto?

### Domanda 2:
nel file **`conf.py`** non devo **anche** includere il contenuto della linea 52, e cioè:
**`extensions = ['sphinx.ext.ifconfig','sphinx_markdown_tables']`**  ?

Grazie sempre.

**Comment by aborruso** [comment]
> ### Domanda 1:
> nel file **`conf.py`** non devo anche includere il contenuto della linea 50?
> https://github.com/opendatasicilia/tansignari/blob/master/conf.py#L50
> che è: **`source_suffix = ['.rst', '.md']`** ?
> Cioè devo dire a RTD di leggere sia i file di Github in formato `.RST` che i file in formato `.MD`
> Giusto?

Yessa

> 
> ### Domanda 2:
> nel file **`conf.py`** non devo **anche** includere il contenuto della linea 52, e cioè:
> **`extensions = ['sphinx.ext.ifconfig','sphinx_markdown_tables']`** ?

Questo non è obbligatorio, ma è meglio, perché ti consente di scrivere tabelle in markdown

**Comment by cirospat** [comment]
ok grazie tantissimo, 
ho fugato i dubbi.
Quindi devo arricchire il file **`conf.py`** con i contenuti da te indicati e devo creare il file **`requirements`** con i requisiti di moduli da installare.
Capito tutto. 

Chiuso issue dopo aver provato e confermato che funziona.
Praticamente ho scoperto un componente aggiuntivo di Google doc che mi converte testo in .MD e committa su Github automaticamente. Si chiama "**Gabriel MD**"

**Comment by cirospat** [comment]
@aborruso buongiorno
ho aggiunto file `requirements.txt`
e aggiunto al file` conf.py` quanto da te indicato,
tuttavia il progetto su RTD non mi compila: https://readthedocs.org/projects/cirospat/builds/
c'è qualcosa da sistemare sicuramente ma mi sono perso

**Comment by aborruso** [comment]
Mi rendi admin di quel progetto su RTD e mi inviti anche qui https://github.com/cirospat/newproject ?

**Comment by cirospat** [comment]
@aborruso 
sei già collaborators sul progetto github
e aggiunto su RTD

**Comment by aborruso** [comment]
Hai beccato questo baco https://stackoverflow.com/questions/59846065/read-the-docs-build-fails-with-cannot-import-name-packagefinder-from-pip-in

Dovrei avere risolto

**Comment by cirospat** [comment]
> Dovrei avere risolto

Grazie!
c'è qualcosa che devo sapere per comportamenti precisi da seguire in futuro?

**Comment by aborruso** [comment]
Caro Ciro,
non lo so, ma non credo.



______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il mer 22 gen 2020, 13:16 ciro spataro <notifications@github.com> ha
scritto:

**Comment by cirospat** [comment]
Una cosa:
ho aggiunto nella directory principale questo file:
https://github.com/cirospat/newproject/blob/master/.readthedocs.yml
perchè me lo suggeriva RTD all'inizio dei messaggi di non compilazione con un link che mi riportava qui: https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by cirospat** [comment]
comunque a parte una decina di minuti in cui compilava, ora continua a non compilare
https://readthedocs.org/projects/cirospat/builds/

**Comment by cirospat** [comment]
ok leggendo la risposta al link che mi hai fornito
https://stackoverflow.com/questions/59846065/read-the-docs-build-fails-with-cannot-import-name-packagefinder-from-pip-in
arrivo a questa procedura da seguire:
https://docs.readthedocs.io/en/stable/guides/wipe-environment.html
che spiega come agire in maniera semplice.
L'ho provato e la compilazione viene effettuata.
Grazie @aborruso

**Comment by aborruso** [comment]
@cirospat e funziona la visualizzazione del file md??

Se sì, chiudiamo

**Comment by cirospat** [comment]
praticamente per questa spiegazione fornita qui per far compilare i progetti di RTD andrebbe aperta un issue dedicata. Perchè questa spiegazione che è stata trovata permette di far compilare tanti progetti di RTD!
Comunque possiamo anche congelarla qui.

Per quanto riguarda la visualizzazione dei file in **`.MD`** praticamente ho notato che il testo viene renderizzato in HTML correttamente, ma per quanto riguarda le tabelle, malgrado sui file dentro Github viene visualizzata la tabella correttamente, in formato HTML su RTD non avviene la stessa cosa.

Ho un idea in mente.
Unire un po di forze per **creare un componente aggiuntivo per Google doc che permette di far scrivere testo all'utente e poi tramite un tasto fare il "commit" in formato Markdown su Github**.
Questo permetterebbe a tante persone di fare documentazione su Read the Docs. Ci vuole un po di sviluppo ma l'obiettivo è utilissimo.

**Comment by aborruso** [comment]
@cirospat io la chiuderei, con un ricetta di base che dice come abilitare la cosa

**Comment by gbvitrano** [comment]
@cirospat le tabelle le puoi sempre formattare con il css, adattandole al desktop e mobile

**Comment by cirospat** [comment]
> @cirospat le tabelle le puoi sempre formattare con il css, adattandole al desktop e mobile

caro @gbvitrano 
quello a cui penso io è uno strumento da usare in maniera facile per persone molto meno smanettone di noi.
Immagina un componente aggiuntivo per Google doc, un plug-in. Tu editi normalmente testo, tabelle, inserisci immagini, link, iframe, ecc. Poi con un clic nel componente aggiuntivo fai il commit in formato .MD automaticamente su un repository di Github di tutto quello che c'è in quel Google doc, che come sappiamo compila il tutto su Read the Docs (in html). Ecco per ora penso a questo. 
Non voglio pensare a sbattermi con CSS o altro in quanto una persona media nella PA non smanetta con sintassi e istruzioni .rST, .MD, CSS, eccetera. Cioè concentrarsi sui contenuti e sulla documentazione da pubblicare online e non sul software.
Penso alla semplicità - testo normale su un Google doc - che genera file su Github in linguaggi che noi conosciamo. Spero un giorno qualcuno sviluppi un plug-in per Google doc che fa questo lavoro.

Come consigliato da @aborruso penso a scrivere una ricetta per Tansignari sulla soluzione fornita come risposta alla mia domanda oggetto di questa issue, e poi chiudo la saracinesca, ehm.. voglio dire l'issue.
Grazie per leggermi :)

**Comment by cirospat** [comment]
@gbvitrano 
ho predisposto directory ricetta argomento **`Read the Docs`** con file (in `.MD`) della ricetta e file `index`:
https://github.com/opendatasicilia/tansignari/tree/master/ricette/ReadtheDocs

Please dacci un occhiata per vedere se tutto è a posto.

**Comment by cirospat** [comment]
ecco la ricetta su Tansignari
http://tansignari.opendatasicilia.it/it/latest/ricette/ReadtheDocs/index.html

**Comment by cirospat** [comment]
close #109
