### ISSUE TITLE
[Telegram] perché le gif animate sono visualizzate male??

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#107]
Da qualche tempo a questa parte ho notato che le gif animate allegate in Telegram vengono visualizzate male dal destinatario, cioè le vede piccole e sgranate.
Da cosa dipende?? è possibile ovviare??

esempio, questa gif animata:

![QGIStrendsItaly](https://user-images.githubusercontent.com/7631137/72985798-0c38a500-3de7-11ea-932a-fe2c67238a2b.gif)

viene visualizzata cosi su desktop:

![image](https://user-images.githubusercontent.com/7631137/72985987-79e4d100-3de7-11ea-8132-4076b32378c2.png)

**Comment by aborruso** [comment]
Caro @pigreco la soluzione che propongo non è scienza, ma soltanto frutto dell'esperienza.

Per produrre GIF che siano zoomabili e non perdano qualità faccio semplicemente questo: converto la mia GIF in mp4  e poi la trascino in drag&drop su Telegram Desktop (al momento l'ho provato soltanto lì).

La conversione si può fare in mille modi. Una che ho testato con esito positivo è usare [ffmpeg](https://www.ffmpeg.org/), utility open source a riga di comando, disponibile per qualsiasi sistema operativo.

Il comando è

```
ffmpeg -f gif -i input.gif -filter_complex "loop=1:32767:0,scale=trunc(iw/2)*2:trunc(ih/2)*2" -preset slow -pix_fmt yuv420p output.mp4
```

Si potrà fare sicuramente anche direttamente a partire da un mp4 e disabilitando il suono (telegram lo trasfroma in GIF), ma partire da una GIF probabilmente ti fa produrre alla fine del giro un file più piccolo.

**Comment by pigreco** [comment]
@aborruso grazie per la tempestiva risposta.
Per adesso non ho modo di provarlo in quanto non ho capito ancora come installare `ffmpeg`, ma con l'aiuto di google credo di riuscirci.

grazie, chiudo issue

**Comment by aborruso** [comment]
@pigreco la riapro. Verifichiamo prima che la soluzione va e poi chiudiamo.

L'install è:

- su Linux https://www.tecmint.com/install-ffmpeg-in-linux/
- su windows https://windowsloop.com/install-ffmpeg-windows-10/

Fammi sapere

**Comment by pigreco** [comment]
@aborruso

ho provato solo la soluzione su Linux, funziona bene, ecco i passi:

```
sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install ffmpeg
ffmpeg -version
```

uno dopo l'altro.

grazie
