### ISSUE TITLE
Dati pagamenti SIOPE

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#108]
Buongiorno,
mi rivolgo sopratutto a @gpirrotta che conosce bene questi dati. Su [SoldiPubblici](http://soldipubblici.gov.it/it/developers) si legge del dataset "Dati pagamenti". Due domande:

- qual è l'URL di download?
- ci sono soltanto per il 2014 e il 2015?

Grazie

![image](https://user-images.githubusercontent.com/30607/73120242-f30d3100-3f6b-11ea-98ae-6fe53eb67ff6.png)

**Comment by piersoft** [comment]
una cosa sono i dati bulk (anagrafica e dati), altra sono le API che integrano i dati del 2018 e sono predisposte per il prossimo aggiornamento di gennaio 2019. se ti serve c'è un codice php che usammo per il bot soldipubblici e che è usato in alcuni bot di amministrazioni locali.

**Comment by gpirrotta** [comment]
Buongiorno,
> mi rivolgo sopratutto a @gpirrotta <https://github.com/gpirrotta> che
> conosce bene questi dati.
>
Ciao Andy

>
>    - qual è l'URL di download?
>
> i dati SIOPE li trovi sul sito www.siope.it e puoi effettuare il download
massivo al seguente url:
https://www.siope.it/Siope/dispatchEsportaDatiMassivo.action


>
>    - ci sono soltanto per il 2014 e il 2015
>
> i dati SIOPE sono aggiornati molto frequentemente. Ad esempio oggi 25
gennaio trovi i dati aggiornati al 23 gennaio.
Questo se ti servono i dati grezzi. Su soldipubblici.gov non so ogni quanto
aggiornano i dati.

Ciao

>

**Comment by aborruso** [comment]
Grazie @piersoft sulle API (fra l'altro credo ne parlammo tempo fa) non ho difficoltà.

Volevo capire la nota sui dati bulk. Mi ha risposto @gpirrotta , vado a vedere

E benvenuto in "tansignari" :)

**Comment by aborruso** [comment]
Ok, grazie a @gpirrotta apprendo che la nota su soldipubblici è carente e che si da probabilmente per scontato che la fonte sia  https://www.siope.it/Siope/

Il download massivo da lì

![image](https://user-images.githubusercontent.com/30607/73120921-5602c600-3f74-11ea-85cd-af85c2656aaa.png)

**Comment by piersoft** [comment]
ah ok. da siope hai sempre tutto. è soldi pubblici che non li ha aggiornati

**Comment by aborruso** [comment]
chiudo la issue

Non scrivo "ricetta", perché essenzialmente la cosa è senza esito.

Grazie a tutti
