### ISSUE TITLE
[issue] come si chiudono le issues

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#109]
@aborruso, come hai fa ha chiudere una issue in questo modo??

![image](https://user-images.githubusercontent.com/7631137/73124369-df2cf380-3f9a-11ea-90c4-e110b8b15d31.png)

**Comment by aborruso** [comment]
Basta che nel messaggio di commit, fai riferimento alla issue e usi uno dei verbi previsti: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

Il mio commit era [`close #107`](https://github.com/opendatasicilia/tansignari/commit/43ea02aa906ff3b3ff1a7fa7b50d854616b10d51)

**Comment by pigreco** [comment]
Caro @aborruso , che dire ... 

close #109

**Comment by aborruso** [comment]
Esatto, non appena fai la cartella per GIT, questa potrebbe essere la prima ricetta.

Basta che usi quel commit
