### ISSUE TITLE
Dati Opendemanio

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#11]
Buongiorno :-)
volevo ralizzare una mappa con i dati di opendemanio rielaborati da @aborruso [qui](https://gist.github.com/aborruso/503df6c6477c341431e23bc51bc37149) 

su 32226 punti qualcuno ricade fuori dai confini italini, 9 per la precisone, c'è modo di migliorare la la localizzazione o posso eliminarli? 

![screenshot 12](https://user-images.githubusercontent.com/20488693/52621050-9faee980-2ea6-11e9-9620-36682503fd21.jpg)
![screenshot 11](https://user-images.githubusercontent.com/20488693/52621060-a50c3400-2ea6-11e9-9218-5b8253bfddec.jpg)

anche a volerli localizzare manualmente, non c'è l'indirizzo

![screenshot 13](https://user-images.githubusercontent.com/20488693/52621205-fd433600-2ea6-11e9-8155-ef5e596e9274.jpg)

**Comment by aborruso** [comment]
@gbvitrano la domanda non la capisco. Vuoi un giudizio sulla posizione? Un geocoding automacio? Un filtro automatico?

**Comment by aborruso** [comment]
La chiudiamo?

**Comment by gbvitrano** [comment]
@aborruso la domanda era... posso eliminare i POI che ricadono fuori dallo Stato Italiano e non c'era modo di geolocalizzarli correttamente?

Per realizzare la mappa li ho eliminati.
Ho aggiunto anche i **Fari**, i **Cammini e Percorsi** e gli **Immobili lungo i cammini** 

![photo5990141307084975692](https://user-images.githubusercontent.com/20488693/52848149-4f39c500-310e-11e9-9ff3-539767190f97.jpg)
![photo5990141307084975693](https://user-images.githubusercontent.com/20488693/52848150-51038880-310e-11e9-97c1-8fe48d3f3777.jpg)
![photo5990141307084975694](https://user-images.githubusercontent.com/20488693/52848155-52cd4c00-310e-11e9-8050-f542f9b4a182.jpg)
![photo5990141307084975695](https://user-images.githubusercontent.com/20488693/52848161-54970f80-310e-11e9-8c3f-1ccd5c171be7.jpg)
