### ISSUE TITLE
[bash] come evitare di scrivere più volte il nome del file da scaricare

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#110]
Ho realizzato questo script che scarica e unzippa il file scaricato:

 `QGIS-OSGeo4W-3.4.9-1-Setup-x86_64.exe`

```bash
#!/bin/bash

set -x

curl http://download.osgeo.org/qgis/win64/QGIS-OSGeo4W-3.4.9-1-Setup-x86_64.exe >QGIS-OSGeo4W-3.4.9-1-Setup-x86_64.exe
7z x QGIS-OSGeo4W-3.4.9-1-Setup-x86_64.exe
```

ogni volta che cambia il file da scaricare devo scrivere tre volte il nome del file:
- una volta nel `curl`;
- una volta come nome di output;
- una volta per unzipparlo;

 come posso fare o cosa posso fare per scriverlo una sola volta??

**Comment by aborruso** [comment]
Prima del curl crea la variabile nomefile.

nomefile="miofile.exe"

Poi nel comando sostituisci miofile.exe con (comprese le virgolette) "$nomefile".

In questo modo dovrai soltanto scrivere una volta il nome del file.

Scusami la brutta formattazione, ma sono da cellulare.

**Comment by pigreco** [comment]
Caro @aborruso, 

è cosi semplice??

```bash
#!/bin/bash

set -x

versione="QGIS-OSGeo4W-3.4.9-1-Setup-x86_64.exe"

curl http://download.osgeo.org/qgis/win64/"$versione" >"$versione"
7z x "$versione"

**Comment by aborruso** [comment]
Non ti resta che provare

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il mar 28 gen 2020, 23:58 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
Caro @aborruso ,

grazie 1000, funziona tutto. :-)

**Comment by pigreco** [comment]
Ecco lo script finale:

```bash
#!/bin/bash

set -x

versione="QGIS-OSGeo4W-3.4.15-1-Setup-x86_64.exe"
nome=$(sed -r 's/(QGIS-)(.+)(-Setup-x86_64.exe)/\2/g' <<<"$versione")
echo "$nome"

curl http://download.osgeo.org/qgis/win64/"$versione" >"$versione"
7z x "$versione"
mv '$_25_' OSGeo4W
mv '$PLUGINSDIR' OSGeo4W
cd OSGeo4W/bin
mv qgis-ltr.bat.tmpl qgis-ltr.bat
cd ../apps/qgis-ltr/bin
curl -L "https://github.com/pigreco/QGIS_portable_3x/raw/master/file/win64/win64.zip" >win64.zip
7z x win64.zip
rm win64.zip
cd ../../../../
7z a "$nome".7z OSGeo4W
```

**Comment by pigreco** [comment]
qui [ricetta](https://github.com/opendatasicilia/tansignari/blob/master/ricette/utilities/come%20_creare_portable_QGIS.md)

aspetto consigli per migliorarla e dopo la mettiamo nell'index
