### ISSUE TITLE
[bash] estrarre substring variabile in lunghezza

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#111]
Ho necessità di estrarre una substring variabile in lunghezza, cioè:

 da questa `versione="QGIS-OSGeo4W-3.4.9-1-Setup-x86_64.exe"`

voglio estrarre la parte centrale `OSGeo4W-3.4.9-1` che è sempre variabile (la parte numerica)

allego un esempio che risolvo con i `regex`, ma che non riesco a fare in `bash`, trovo troppe info nel web che mi confondono

https://regex101.com/r/xM2Xi5/1

**Comment by aborruso** [comment]
caro @pigreco anche se ti confondi, prova, e poi aggiungi nella richiesta i test che hai fatto.

Prendo la tua regex e uso `sed`

```
echo "QGIS-OSGeo4W-3.10.2-2-Setup-x86_64.exe" | sed -r 's/(QGIS-)(.+)(-Setup-x86_64.exe)/\1\2/g'
```

In termini di codice

```bash
versione="QGIS-OSGeo4W-3.4.9-1-Setup-x86_64.exe"
centrale=$(sed -r 's/(QGIS-)(.+)(-Setup-x86_64.exe)/\1\2/g' <<<"$versione")
# stampa per debug
echo "$centrale"
```

**Comment by pigreco** [comment]
Caro @aborruso, 

funziona tutto,

una sola osservazione, a me serve solo la parte centrale e quindi:

`centrale=$(sed -r 's/(QGIS-)(.+)(-Setup-x86_64.exe)/\2/g' <<<"$versione")`

senza `\1` che prenderebbe anche la prima parola

grazie
