### ISSUE TITLE
[QGIS] come realizzare una versione Portable di QGIS 3.x

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#112]
Le issue #110 e #111 sono state aperte per ottimizzare lo [script bash](https://github.com/pigreco/QGIS_portable_3x/blob/master/script.sh) per la creazione di versioni [`Portable`](https://github.com/pigreco/QGIS_portable_3x#che-cosa-%C3%A8-una-versione-portable) di [QGIS](https://qgis.org/it/site/) (Il più diffuso Software GIS Desktop nel mondo Open Source).

Originariamente lo `script bash` era cosi:

```bash
#!/bin/bash

set -x

curl http://download.osgeo.org/qgis/win64/QGIS-OSGeo4W-3.4.10-1-Setup-x86_64.exe >QGIS-OSGeo4W-3.4.10-1-Setup-x86_64.exe
7z x QGIS-OSGeo4W-3.4.10-1-Setup-x86_64.exe
mv '$_25_' OSGeo4W
mv '$PLUGINSDIR' OSGeo4W
cd OSGeo4W/bin
mv qgis-ltr.bat.tmpl qgis-ltr.bat
cd ../apps/qgis-ltr/bin
curl -L "https://github.com/pigreco/QGIS_portable_3x/raw/master/file/win64/win64.zip" >win64.zip
7z x win64.zip
rm win64.zip
cd ../../../../
7z a OSGeo4W_3410.7z OSGeo4W
```

- dove occorreva scrivere **tre** volte il nome del file da scaricare (`QGIS-OSGeo4W-3.4.10-1-Setup-x86_64.exe`) con potenziali errori connessi;
- nell'ultima riga dello script occorreva formulare il nome (`OSGeo4W_3410.7z`) della cartella finale da zippare;

con le ottimizzazioni:
- scrivo **una** sola volta il nome del file da scaricare in una variabile (`versione`);
- il nome della cartella finale viene estratto automaticamente grazie all'uso di [`sed`](https://it.wikipedia.org/wiki/Sed_(Unix)) che lo associa alla variabile `nome`;

ecco lo script ottimizzato:

```bash
#!/bin/bash

set -x

versione="QGIS-OSGeo4W-3.4.15-1-Setup-x86_64.exe"
nome=$(sed -r 's/(QGIS-)(.+)(-Setup-x86_64.exe)/\2/g' <<<"$versione")
echo "$nome"

curl http://download.osgeo.org/qgis/win64/"$versione" >"$versione"
7z x "$versione"
mv '$_25_' OSGeo4W
mv '$PLUGINSDIR' OSGeo4W
cd OSGeo4W/bin
mv qgis-ltr.bat.tmpl qgis-ltr.bat
cd ../apps/qgis-ltr/bin
curl -L "https://github.com/pigreco/QGIS_portable_3x/raw/master/file/win64/win64.zip" >win64.zip
7z x win64.zip
rm win64.zip
cd ../../../../
7z a "$nome".7z OSGeo4W
```

## riferimenti
- **Index of /qgis/win64/** : http://download.osgeo.org/qgis/win64/
- **repository** : https://github.com/pigreco/QGIS_portable_3x
- **Impara X in Y minuti** : https://learnxinyminutes.com/docs/it-it/bash-it/

**Comment by aborruso** [comment]
@pigreco bello

In una nuova cartella `bash` inserirei una ricetta dedicata

**Comment by pigreco** [comment]
Ecco la [ricetta ](https://github.com/opendatasicilia/tansignari/blob/master/ricette/bash/come_ottimizzare_script_bash.md)

aspetto consigli per migliorarla e dopo la mettiamo nell'index
