### ISSUE TITLE
Dove è (e qual è) l'istruzione da dare su Github per fare aprire su RTD i link in una pagina esterna?

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#116]
**Problema**
Sui progetti di documentazione esposti su Read the Docs ad un determinato link voglio far aprire la pagina correlata in una pagina diversa da quella che sto leggendo.

**Considerazione**
Io uso il plugin GGeditor su Google doc che mi committa le pagine doc automaticamente su un repository su Github e i link interattivi (sulla pagina doc) me li converte nel file in formato RST su Github direttamente con l'istruzione di far aprire i link in una pagina esterna, ma siccome io non vedo l'istruzione data nel plugin non riesco a capire quale sia tale istruzione.  

**Domanda**
Dove è (e qual'è) l'istruzione da dare su Github per fare aprire su RTD i link in una pagina esterna?
Dove è nel senso in quale file su Github è?

Grazie per l'attenzione

**Comment by gbvitrano** [comment]
Ciao @cirospat il comando che cerchi si trova nel con.py nel gruppo **html_theme_options** 
![immagine](https://user-images.githubusercontent.com/20488693/74055284-009ccf00-49e0-11ea-954a-b421c21c86f6.png)
basta aggiungere questa riga `'style_external_links': True`

[Qui](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_style) trovi tutte le info per aggiungere tutti i vari  **[html_theme_options](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_style)**

Se invece vuoi forzare tutte le pagine ad aprirsi in una nuova finestra ho tovato uno script su [stackoverflow.com](https://stackoverflow.com/questions/11716781/open-a-link-in-a-new-window-in-restructuredtext) che potrebbe fare al caso tuo.

Ti basta aggiungere questo script nella pagina layout.html, prima della chiusa del blocco finale, dove solitamente inseraimo tutti gli script.

![2020-02-07_19h35_46](https://user-images.githubusercontent.com/20488693/74055811-0b0b9880-49e1-11ea-8770-32ff6430813d.png)

`<script type="text/javascript">
    
    $(document).ready(function () {
      $('a[href^="http://"], a[href^="https://"]').not('a[class*=internal]').attr('target', '_blank');
    });
  </script>`

Per fare un test ho usato [ixmapsdoc.opendatasicilia.it](http://ixmapsdoc.opendatasicilia.it/)

**Comment by cirospat** [comment]
Grazie @gbvitrano 
faccio ricetta.

close [116](https://github.com/opendatasicilia/tansignari/issues/116)

**Comment by cirospat** [comment]
close [116](https://github.com/opendatasicilia/tansignari/issues/116)

**Comment by cirospat** [comment]
close [116](https://github.com/opendatasicilia/tansignari/issues/116)
