### ISSUE TITLE
[GIS] dove posso fare tiles online con geotiff?

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#117]
Ho georiferito la `index map`  della collezione presente in questo [sito](https://legacy.lib.utexas.edu/maps/ams/italy_50k/?fbclid=IwAR1oQYYcKOHTTkzzxZ1PRrEZyUOw8rzFRU0bW_Cn79ievC7VA-QDbUCNlDw)  (mappe storiche **Series 4229, U.S. Army Map Service, 1941**)

come posso condividerla pubblicamente in modo da usarla come tiles xyz in qualsiasi software GIS??

 ---

## script per georeferenziazione

```
# download the image
curl -L "http://legacy.lib.utexas.edu/maps/ams/italy_50k/index_map.jpg" >./output.jpg
# add control points
gdal_translate -of GTiff -gcp 3089.03 2204.96 14 37 -gcp 3270.39 745.796 19 40 -gcp 1391.07 140.891 15 46 -gcp 371.406 1851.43 6 44 -gcp 245.288 403.987 10 48 -gcp 1611.71 1963.66 10 41 -gcp 2015.5 772.647 15 43 ./output.jpg ./output_mm.tif
# apply the proj parameters
gdalwarp -dstnodata "0 0 0" -overwrite -r near -order 2 -co COMPRESS=PACKBITS  -t_srs "+proj=longlat +ellps=bessel +towgs84=656.5,138.2,506.5,5.187,-2.540,5.256,-12.61 +units=m +no_defs" ./output_mm.tif ./index50kP2.tif
```
**allego file**

[index50kP2.zip](https://github.com/opendatasicilia/tansignari/files/4170152/index50kP2.zip)

**Comment by cirospat** [comment]
**Mapwarper** fa questi servizi se georeferenzi immagini nel loro portale.
Guarda un esempio: https://mapwarper.net/maps/19482
Tra i servizi c'è: 
Tiles (Google/OSM scheme): https://mapwarper.net/maps/tile/19482/{z}/{x}/{y}.png

https://mapwarper.net/maps/tile/19482/{z}/{x}/{y}.png rappresenta il tile che puoi dare sia a servizi come uMap che immagino anche a software GIS.

**Comment by pigreco** [comment]
Grazie @cirospat 

>Mapwarper fa questi servizi se georeferenzi immagini nel loro portale.

ma ho necessità di usare il file allegato che è una `geotiff`, 
come vedi dallo script allegato, non credo sia possibile adottare i stessi paramentri in Mapwarper o sbaglio??

**Comment by aborruso** [comment]
Caro @pigreco scritto di corsa questo README https://github.com/aborruso/gdal2tiles_su_github

**Comment by gbvitrano** [comment]
![Screenshot_20200207_121112_org mozilla firefox](https://user-images.githubusercontent.com/20488693/74025546-78e59f00-49a4-11ea-933f-9d7fc0a246e1.jpg)
Si può esportare direttamente il geotiff

**Comment by pigreco** [comment]
Caro @gbvitrano 

>Si può esportare direttamente il geotiff

lo so che è possibile esportare, il problema è l'upload che non supporta i geotiff , corretto??

**Comment by aborruso** [comment]
@gbvitrano il problema di @pigreco è l'inverso: lui hai un geotiff pronta e cerca un posto dove creare/ospitare le tiles.

Se su mapwarper si può fare l'upload di una geotiff, senza che sia necessario poi georiferire, mapwarper è ottimo

**Comment by gbvitrano** [comment]
Avevo capito male. Si in upload  geotiff  viene letto come una semplice immagine, abbiamo avuto lo stesso problema con la carta Omira di Palermo

**Comment by pigreco** [comment]
Aggiungo:

1. `gdal2tiles.py --zoom=6-11 index50kP2.tif` per livelli di zoom tra 6 e 11;
2. per scegliere i livelli di zoom, guardare il primo numero di questa mappa : https://www.openstreetmap.org/#map=8/37.508/14.310
