### ISSUE TITLE
ogr2ogr: symbol lookup error:

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#12]
Ho creato un file `input.vrt`:

```XML
<OGRVRTDataSource>
    <OGRVRTLayer name="opendemanio_3857" relativeToVRT="1">
        <SrcDataSource>./opendemanio_3857.shp</SrcDataSource>
    </OGRVRTLayer>
    <OGRVRTLayer name="regioni_3857" relativeToVRT="1">
        <SrcDataSource>regioni_3857.shp</SrcDataSource>
    </OGRVRTLayer>
</OGRVRTDataSource>
```
da richiamare in una ricetta `ogr2ogr`:

```
ogr2ogr -f CSV opendemanio_tmp.csv input.vrt -dialect sqlite -sql "select A.*, B.COD_REG, B.DEN_REG from opendemanio_3857 AS A, regioni_3857 AS B WHERE ST_Intersects(A.geometry,B.geometry)"
```
obiettivo è quello di usare GDAL/OGR per associare il nome delle regioni a dei punti (che vi ricadono dentro spazialmente)
 
ma ottengo il seguente messaggio di errore:
```
ogr2ogr: symbol lookup error: /usr/lib/libgdal.so.20: undefined symbol: sqlite3_column_table_name
```
![image](https://user-images.githubusercontent.com/7631137/52635668-c7b04400-2eca-11e9-92cd-1b9dc167dbf8.png)

--
**EDIT**
dati: 
[dati.zip](https://github.com/opendatasicilia/tansignari/files/2856012/dati.zip)

**Comment by aborruso** [comment]
Ciao Totò,
non posso testare, non ho i file. Sembra tutto corretto. La proprietà `relativeToVRT="1"` è da associare al tag `SrcDataSource`.

```xml
<OGRVRTDataSource>
    <OGRVRTLayer name="fileUno">
        <SrcDataSource relativeToVRT="1">./fileUno.shp</SrcDataSource>
    </OGRVRTLayer>
    <OGRVRTLayer name="fileDue">
        <SrcDataSource relativeToVRT="1">./fileDue.shp</SrcDataSource>
    </OGRVRTLayer>
</OGRVRTDataSource>
```

Fai un test in ambiente Win, dalla shell di ogr e se puoi allega i file.

**Comment by pigreco** [comment]
@aborruso  ho allegato i dati (vedi parte bassa issue)

sto testando in ambiente win con shell osgeo4w: ha creato il file `opendemanio_tmp.csv` ma gira ancora (son passati 10 min e ancora gira...)
![image](https://user-images.githubusercontent.com/7631137/52639110-d64f2900-2ed3-11e9-8784-6f4196e78722.png)

**Comment by aborruso** [comment]
Ciao Totò,
sembra tutto ok, ho corretto soltanto come sotto. 

I tempi, visto la query non ottimizzata, sono lunghi. 10/15 minuti è un tempo che ha senso per 32000 record (vado di ipotesi, non li ho aperti). 
Su come ottimizzare la query e con che tool sai più di me.

```
<OGRVRTDataSource>
    <OGRVRTLayer name="opendemanio_3857">
        <SrcDataSource relativeToVRT="1">./opendemanio_3857.shp</SrcDataSource>
    </OGRVRTLayer>
    <OGRVRTLayer name="regioni_3857">
        <SrcDataSource relativeToVRT="1">regioni_3857.shp</SrcDataSource>
    </OGRVRTLayer>
</OGRVRTDataSource>
```

**Comment by pigreco** [comment]
Ciao Andrea,
il processo è terminato dopo 60 minuti circa:
![image](https://user-images.githubusercontent.com/7631137/52641840-10232e00-2eda-11e9-8904-0f2c8a3e16f9.png)
un tempo decisamente troppo lungo anche se la query non è ottimizzata.

Ho usato il tuo vrt ma nulla, in ambiente linux compare sempre lo stesso errore.

**Comment by aborruso** [comment]
Per tornare all'oggetto del post: purtroppo hai della sporcizia nel sistema operativo, con sovrapposizione di moduli. Purtroppo io non so però come risolvere la cosa, perché ho avuto un problema simile e non ne sono venuto a capo

**Comment by pigreco** [comment]
Ciao Andrea,
immaginavo fosse quello il problema (munnizza), chiudo issue.

grazie
