### ISSUE TITLE
[scraping] changelog QGIS 3.12 da GitHub

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#125]
Ogni nuova `Feature` viene proposta, nel repository GitHub di [QGIS](https://github.com/qgis/QGIS), tramite una `PR` (Pull Request) dove si discute, si fanno modifiche e poi, se va bene, viene fatto il `merge` al ramo principale.

Ogni sviluppatore aggiunge il **tag** `Feature` assieme ad altri **tag** più specifici che ne identificano la categoria (`processing`, `expressions`,`label`, ecc..).

Ogni 4 mesi esce una nuova versione QGIS e contestualmente vengono redatte i `changelog`, una pagina web in cui è possibile vedere tutte le nuove `feature` introdotte.

Usando questo `filtro`:

```
is:pr is:closed label:feature merged:2019-10-25T00:00:00Z..2020-02-21T00:00:00Z
```
in questa pagina: https://github.com/qgis/QGIS/pulls

ottengo tutte le **PR** (con `tag:feature`) per la nuova versione di **QGIS**.

Come estrarre i dati (_autore_, _titolo_, _tags_, _data merged_, _numero PR_ e _milestone_)??

--

@aborruso mi ha proposto il seguente script:

```bash
#!/bin/bash
# filtro github: is:pr is:closed label:feature merged:2019-10-25T00:00:00Z..2020-02-21T00:00:00Z 
set -x

curl "https://github.com/qgis/QGIS/pulls?page=1&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A2019-10-25T00%3A00%3A00Z..2020-02-21T00%3A00%3A00Z&utf8=%E2%9C%93" | scrape -be ".pr-md-2" | xq '.html.body.div[]|{titolo:.a."#text",tag:[.span[1].a[]."#text"?],autore:.div.span[0].a."#text"}' | mlr --j2c unsparsify>pag1.csv
```

funziona bene ma ha alcuni limiti che non riesco a superare:

- [x] il link presente nel `curl` (dello script di sopra) restituisce i dati solo della prima pagina, ma potrebbero essere più di una (nel caso specifico sono tre);
- [x] lo script di sopra restituisce solo i dati relativi a: (_autore_, _titolo_, _tags_);
- [x] lo script genera un file csv per pagina, e se lanciato più volte per estrerre la 2° e 3° pagina i campi del csv non corrispondono (cioè il campo autore non occupa lo stesso posto nel file csv).

**Comment by pigreco** [comment]
possibile soluzione al primo punto, con questo script:

```bash
#!/bin/bash
# filtro github: is:pr is:closed label:feature merged:2019-10-25T00:00:00Z..2020-02-21T00:00:00Z 
set -x

curl "https://github.com/qgis/QGIS/pulls?page=1&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A2019-10-25T00%3A00%3A00Z..2020-02-21T00%3A00%3A00Z&utf8=%E2%9C%93" | scrape -be ".pr-md-2" | xq '.html.body.div[]|{titolo:.a."#text",tag:[.span[1].a[]."#text"?],autore:.div.span[0].a."#text"}' | mlr --j2c unsparsify>pag1.csv

curl "https://github.com/qgis/QGIS/pulls?page=2&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A2019-10-25T00%3A00%3A00Z..2020-02-21T00%3A00%3A00Z&utf8=%E2%9C%93" | scrape -be ".pr-md-2" | xq '.html.body.div[]|{titolo:.a."#text",tag:[.span[1].a[]."#text"?],autore:.div.span[0].a."#text"}' | mlr --j2c unsparsify>pag2.csv

curl "https://github.com/qgis/QGIS/pulls?page=3&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A2019-10-25T00%3A00%3A00Z..2020-02-21T00%3A00%3A00Z&utf8=%E2%9C%93" | scrape -be ".pr-md-2" | xq '.html.body.div[]|{titolo:.a."#text",tag:[.span[1].a[]."#text"?],autore:.div.span[0].a."#text"}' | mlr --j2c unsparsify>pag3.csv
```

creando tre file csv: pag1,pag2 e pag3

**Comment by aborruso** [comment]
Caro @pigreco ,
di base la soluzione a tutto questo sarebbe usare le API di facebook, per le quali sicuramente c'è il metodo per avere indietro l'output che cerchi in JSON. C'è da leggersi la documentazione.

Per le pagine puoi fare un for loop. Qualcosa come:

```
for Variabile in {1..3}
do
    echo "pagina $Variabile"
done
```

Al posto di echo dovrai inserire il tuo comando.

Se hai CSV con colonne ordinate diversamente, puoi usare Miller, che non fa caso all'ordine. A partire dalla cartella in cui hai in ouput i CSV lancia qualcosa come:

```
mlr --csv unsparsify *.csv >merge.csv
```

Per avere data merged, numero PR e milestone, c'è da cambiare il filtro sul JSON. Appena posso ci guardo.

**Comment by aborruso** [comment]
Ecco una prima versione grezza della query JSON aggiornata, con i campi che hai chiesto:

```
curl "https://github.com/qgis/QGIS/pulls?page=1&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A%3E2019-10-25&utf8=%E2%9C%93" | \
scrape -be ".pr-md-2"  | \
xq '.html.body.div[]|{pr:.a["@href"]?,titolo:.a["#text"]?,tag:[.span[1].a[]["#text"]?],autore:.div.span[0].a["#text"]?,milestone:.div.span[2]?.a["@aria-label"]?,datetime:.div.span[0]["relative-time"]["@datetime"]}' | \
mlr --j2c unsparsify | vd -f csv
```

**Comment by pigreco** [comment]
Per favore correggi questo script che genera il file merge.csv vuoto:

```bash
#!/bin/bash
# filtro github: is:pr is:closed label:feature merged:2019-10-25T00:00:00Z..2020-02-21T00:00:00Z 
set -x

for p in {1..3}
do
    curl "https://github.com/qgis/QGIS/pulls?page=""$p""&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A%3E2019-10-25&utf8=%E2%9C%93" | scrape -be ".pr-md-2"  |xq '.html.body.div[]|{pr:.a["@href"]?,titolo:.a["#text"]?,tag:[.span[1].a[]["#text"]?],autore:.div.span[0].a["#text"]?,milestone:.div.span[2]?.a["@aria-label"]?,datetime:.div.span[0]["relative-time"]["@datetime"]}' | mlr --j2c unsparsify *.csv >merge.csv
done;
```

**Comment by pigreco** [comment]
@aborruso 
ho capito errore, questo funziona

```bash
#!/bin/bash
# filtro github: is:pr is:closed label:feature merged:2019-10-25T00:00:00Z..2020-02-21T00:00:00Z 
set -x

for p in {1..3}
do
    curl "https://github.com/qgis/QGIS/pulls?page=""$p""&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A%3E2019-10-25&utf8=%E2%9C%93" | scrape -be ".pr-md-2"  |xq '.html.body.div[]|{pr:.a["@href"]?,titolo:.a["#text"]?,tag:[.span[1].a[]["#text"]?],autore:.div.span[0].a["#text"]?,milestone:.div.span[2]?.a["@aria-label"]?,datetime:.div.span[0]["relative-time"]["@datetime"]}' | mlr --j2c unsparsify>>merge.csv
done

vd merge.csv
```

**Comment by pigreco** [comment]
Caro @aborruso, (non ho fretta :-) )
noto che il file merge.csv ha dei problemi:

1. l'intestazione viene ripetuta nel `merge`;
2. non è rispettato l'ordine dei campi e quindi c'è un miscuglio di dati.

![image](https://user-images.githubusercontent.com/7631137/75097880-fec23680-55af-11ea-9531-a0d899d6c130.png)

**Comment by aborruso** [comment]
Totò, io avevo suggerito un'altra cosa.

Crea tre file di output e poi fuori dal loop fai il merge dei CSV con miller.

Aggiungi allo script, all'inizio, la cancellazione dei CSV presenti in partenza nella cartella di lavoro

**Comment by pigreco** [comment]
@aborruso **GRAZIE ASSAI** - Funziona!!!

```bash
#!/bin/bash
# filtro github: is:pr is:closed label:feature merged:2019-10-25T00:00:00Z..2020-02-21T00:00:00Z 
set -x

rm *.csv

for p in {1..3}
do
    curl "https://github.com/qgis/QGIS/pulls?page=""$p""&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A%3E2019-10-25&utf8=%E2%9C%93" | scrape -be ".pr-md-2"  |xq '.html.body.div[]|{pr:.a["@href"]?,titolo:.a["#text"]?,tag:[.span[1].a[]["#text"]?],autore:.div.span[0].a["#text"]?,milestone:.div.span[2]?.a["@aria-label"]?,datetime:.div.span[0]["relative-time"]["@datetime"]}' | mlr --j2c unsparsify >pag"$p".csv
done

mlr --csv unsparsify *.csv >merge.csv

vd merge.csv
```

**Comment by pigreco** [comment]
Ricetta su `Tansignari-me`

https://festive-bohr-4ac225.netlify.com/ricette/scraping/changelogqgis312/
