### ISSUE TITLE
[visidata] concatenare campi con separatore diverso dal tab

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#128]
Ho concatenato alcuni campi di un CSV usando il foglio delle colonne `shift+c`, noto che il separatore è il `tab` (o uno spazio);

come posso cambiare il separatore e usarne uno a piacere??

allego file csv, i campi da concatenare sono i tags

[merge.txt](https://github.com/opendatasicilia/tansignari/files/4241537/merge.txt)

**Comment by aborruso** [comment]
Ciao @pigreco ,
non ho aperto il file, ma ti faccio un esempio rapido nell'immagine di sotto.

VisiData è un foglio elettronico basato su Python, quindi puoi usare le espressioni Python (molto simili a quelle del tuo amato HFCQgis).

![](https://i.imgur.com/KYcHY0Q.gif)

**Comment by pigreco** [comment]
Caro @aborruso 
purtroppo con i campi che ho non funziona, i campi che devo concatenare si chiamano: `tag:0` , `tag:1` , `tag:2` e `tag:3`

`tag:0 + ';' + tag:1 + ';' + tag:2 + ';' + tag:3`

![image](https://user-images.githubusercontent.com/7631137/75115414-a433e380-565e-11ea-9e17-4ddf7c4a691f.png)

e mi restituisce un errore:

![image](https://user-images.githubusercontent.com/7631137/75115424-b4e45980-565e-11ea-8228-351a3f7d75cb.png)

ho provato con:

`"tag:0" + ';' + "tag:1" + ';' + "tag:2" + ';' + "tag:3"`

e non va, ripete sempre lo stesso valore.

**Comment by aborruso** [comment]
Il nome campo non può contenere il `:`.

Quindi puoi:

- aprire vista colonne `shift + c`;
- andare nella prima colonna e pigiare `g*` (trova e sostituisci);
- scrivere `:/_` e dare INVIO per sostituire `:` con `_`;
- torna alla tua tabella e concatena, ora i nomi di campo sono OK

**Comment by pigreco** [comment]
Che spettacolo, grazie @aborruso

**Comment by pigreco** [comment]
Ricetta fatta e pubblicata su `Tansignari-md`

https://festive-bohr-4ac225.netlify.com/ricette/csv-tsv/concatena_campi_con_visidata/
