### ISSUE TITLE
[python] come usare regex in visitata

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#129]
Ho un file testuale che verrà salvato in `markdown`, un suo campo è popolato cosi:

```
/qgis/QGIS/pull/53256
```

dove varia solo il numero finale.

Per ottenere questo:

```
[53256](https://github.com/qgis/QGIS/pull/53256)
```

ho usato questa ricetta regex:

```
(.+\/)(.+) e poi [$2](https://github.com/qgis/QGIS/pull/$2)
```
ma non funziona in Visidata, come fare??

--
https://regex101.com/r/V0N1Oh/3

**Comment by aborruso** [comment]
Caro @pigreco 

ecco un esempio semplificato

```
(.+\/)(.+)/\2
```

![](https://i.imgur.com/IOM0n3M.gif)

**Comment by pigreco** [comment]
Caro @aborruso 
quindi bastava usare `\` al posto di `$`

```
(.+\/)(.+) e poi [\2](https://github.com/qgis/QGIS/pull/\2)

grazie
```

**Comment by aborruso** [comment]
@pigreco yes è l'altra modalità per fare riferimento ai gruppi

**Comment by pigreco** [comment]
Caro @aborruso 
per riassumere: esistono solo due modi per far riferimento ai gruppi??

- `$` generico
- `\` python

**Comment by aborruso** [comment]
@pigreco io conosco questi due

**Comment by pigreco** [comment]
Ricetta fatta e cucinata

https://festive-bohr-4ac225.netlify.com/ricette/regex/riferimento_gruppi/
