### ISSUE TITLE
label per issue

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#13]
Ciao,
propongo di definire delle label per etichettare le issue, di seguito alcune:

label | descrizione
------|--------
`regex` | per le espressioni regolari
`GIS` | Tutto quello che riguarda il mondo dei Sistemi Informativi Geografici
`Script` | Script SQL, Bash e tutto il mondo dello scripting

a voi altre label
con la preghiera di utilizzarle per ogni issue aperta

**Comment by aborruso** [comment]
@pigreco la chiuderei. Alcune note:

- le Label non sono tag, e per questa ragione sono assegnabili soltanto dagli utenti che hanno permesso di scrittura nel repo. Quindi un nuovo arrivato qui, non potrà utilizzarle in autonomia. Sarà poi uno degli utenti con permessi più alti ad assegnarle in seguito;
- inserisco pertanto nel galateo l'invito a usare nel titolo delle etichette ([GIS] o #GIS).

**Comment by ninokeys** [comment]
Anche se chiusa, aggiungerei di non usare il maiuscolo per le labels, e.g. Script.

**Comment by aborruso** [comment]
@ninokeys hai fatto benissimo e si possono sempre riaprire le issue. Modificata Label!
