### ISSUE TITLE
[visidata] annulla ultimo comando

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#130]
Ho applicato un cerca e sostituisci tramite `regex`, in particolare usando `g*` su una colonna.

Dopo aver avviato il comando, noto un errore nel `trova/sostituisci` e vorrei tornare indietro, ho provato con `ctrl+c` ma non funziona.

Dove sbaglio??

**Comment by aborruso** [comment]
Nella versione stabile non c'è, c'è in quella develop https://github.com/saulpw/visidata/issues/141#issuecomment-483491481

Al momento puoi dare soltanto un `CTRL + r` per fare il reload completo dello sheet

**Comment by pigreco** [comment]
Ottima notizia, grazie.

PS. non trovo `CTRL + r` nel `Cheat Sheet` che hai realizzato.
