### ISSUE TITLE
[CSV-TSV] come realizzare un group_concat

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#131]
Data una  colonna (**_tags_**) che contiene più volte lo stesso valore, come raggruppare per questa e concatenare i valori di un'altra (**_pr_**)??

allego file `TXT`, `utf8`, delimiter `,`:

[cha312_tags.txt](https://github.com/opendatasicilia/tansignari/files/4261070/cha312_tags.txt)

**Comment by aborruso** [comment]
Con Miller,
puoi fare così

```bash
mlr --csv cut -f tags,pr then nest --implode --values --across-records -f pr cha312_tags.csv >out.csv
```

- `cut -f tags,pr` per estrarre i due campi
- `nest --implode --values --across-records -f pr` per implodere i valori, attraverso le righe della colonna `pr`

**Comment by pigreco** [comment]
Ricetta fatta!

https://festive-bohr-4ac225.netlify.com/ricette/csv-tsv/realizzare_group_concat/
