### ISSUE TITLE
[QGIS] geocoding usando il field calc

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#132]
Per fare geocoding usando il calcolatore di campi di QGIS occorre creare una funzione personalizzata:

```python
# the function n

from qgis.core import *
from qgis.gui import *

from geopy.geocoders import Nominatim
locator = Nominatim(user_agent="myGeocoder")


@qgsfunction(args='auto', group='Custom')
def geocode(field, feature, parent):
    """
    Geocoding
    field: string field of the original layer made like 'piazza navona, rome, italy'
    
    returns a simple string of lat and long, like '43.56565 17.45454'
    """
    location = locator.geocode(field)
    lat = location.latitude
    long = location.longitude
    tot = f'{lat} {long}'
    
    return tot
```
CODICE by Matteo Ghetta </br>
https://gist.github.com/ghtmtt/53d8592eabd2fddc8617b40146075e59

---

dopo aver installato il modulo python `geopy`

```
py3_env
pip3 install geopy
```
![image](https://user-images.githubusercontent.com/7631137/75919879-a1a36c00-5e5e-11ea-978c-4fb4db8efec1.png)

in **QGIS**:

![image](https://user-images.githubusercontent.com/7631137/75920140-15de0f80-5e5f-11ea-8144-3064c032c50f.png)

**Comment by aborruso** [comment]
promemoria per farne ricetta o chiudere la issue

Grazie

**Comment by pigreco** [comment]
> promemoria per farne ricetta o chiudere la issue

la chiudo perché non funziona bene!
