### ISSUE TITLE
[GDAL] Come usare un CSV remoto come source in QGIS,  forzando il tipo di campo?

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#133]
Uso questo [CSV](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv), presente su [repo](https://github.com/pcm-dpc/COVID-19) GitHub, in QGIS tramite protocollo HTTPS ma i campi risultano tutti testuali, come posso forzare il tipo di campo??

**Comment by aborruso** [comment]
Carò totò,
potresti usare come source un [Virtual File Format](https://gdal.org/drivers/vector/vrt.html#virtual-file-format) di GDAL/OGR.

Ho creato questo file di input di esempio https://gist.github.com/aborruso/e1e23ab4ec132831bd33db85e8c82603

Se lo usi nativamente in QGIS e GDAL tutti i campi sono interpretati come testo. In un VRT puoi impostare una [sorgente file di rete](https://gdal.org/user/virtual_file_systems.html#network-based-file-systems) usando [vsicurl](https://gdal.org/user/virtual_file_systems.html#vsicurl).

E puoi anche impostare il tipo di campo.

Se voglio a partire da quel CSV, definire la sorgente remota e il campo `ESRI_OID` come tipo `integer` mi basta definire una sorgente VRT come quella di sotto.

```XML
<OGRVRTDataSource>
<OGRVRTLayer name="strutture">
    <SrcDataSource relativeToVRT="0">/vsicurl/https://gist.github.com/aborruso/e1e23ab4ec132831bd33db85e8c82603/raw/5fbc1b24153302a218755f0908a62c42167a17c5/strutture.csv</SrcDataSource>
    <GeometryType>wkbPoint</GeometryType>
    <LayerSRS>WGS84</LayerSRS>
	<Field name="ESRI_OID" type="Integer" />
	<Field name="PRO_COM_T" type="String" />
    <GeometryField encoding="PointFromColumns" x="x" y="y"/>
</OGRVRTLayer>
</OGRVRTDataSource>
```

Salvala come file sul tuo disco e testala con `ogrinfo tmp_a.vrt strutture`. In output vedrai che il campo è un intero.

```
OGRFeature(strutture):5
  ESRI_OID (Integer) = 3
  PRO_COM_T (String) = 085004
  POINT (14.0608916 37.4951368)
```

**Comment by pigreco** [comment]
@aborruso 
ricetta fatta: https://festive-bohr-4ac225.netlify.com/ricette/mappe/virtual_file_format_ogr/

purtroppo su win non funziona:
https://github.com/qgis/QGIS/issues/35016
