### ISSUE TITLE
[scraping] creare file CSV con i link agli Stemmi delle regioni italiane

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#134]
Da questa pagina https://it.wikipedia.org/wiki/Stemmi_delle_regioni_italiane, riesco a grattare i dati della colonna `link stemmi`

regione|link stemma
--------|----------
Abruzzo|//upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Regione-Abruzzo-Stemma.svg/100px-Regione-Abruzzo-Stemma.svg.png
Basilicata|//upload.wikimedia.org/wikipedia/commons/thumb/0/07/Regione-Basilicata-Stemma.svg/100px-Regione-Basilicata-Stemma.svg.png
Calabria|//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Coat_of_arms_of_Calabria.svg/100px-Coat_of_arms_of_Calabria.svg.png

usando un [gsheet ](https://docs.google.com/spreadsheets/d/10V0pjVjHrjZZFQG3uTrimsJ_yqmszBCIHTowYF-tOWE/edit?usp=sharing) e il comando:

```
IMPORTXML("https://it.wikipedia.org/wiki/Stemmi_delle_regioni_italiane";"//td/a/img/@src")
```
ma come posso aggiungere la colonna `regione`??

**Comment by aborruso** [comment]
È la prima colonna della seconda tabella presente nella pagina, che in XPATH è `//table[2]//td[1]`

Quindi in sheet è

```
=IMPORTXML("https://it.wikipedia.org/wiki/Stemmi_delle_regioni_italiane","//table[2]//td[1]")
```

**Comment by pigreco** [comment]
Caro @aborruso 
grazie, da me funziona solo se metto `;` 

```
=IMPORTXML("https://it.wikipedia.org/wiki/Stemmi_delle_regioni_italiane";"//table[2]//td[1]")
```

![image](https://user-images.githubusercontent.com/7631137/76645725-d9df3480-6559-11ea-8129-06851b2d9c61.png)

**Comment by aborruso** [comment]
@pigreco quello dipende dall'impostazione del foglio.

Io uso sempre quella inglese, perché tutto è sempre più simile alle guide online, ai tutorial, ai forum.

**Comment by pigreco** [comment]
ricetta fatta, grazie chiudo

https://festive-bohr-4ac225.netlify.com/ricette/scraping/stemmi_regioni_italiane/
