### ISSUE TITLE
[ISTAT] come esportare semplici file CSV

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#135]
Non riesco in nessun modo a scaricare una semplice tabella con due campi: Regione | popolazione residente

ho provato in tutti i modi da qui:

http://dati.istat.it/Index.aspx?DataSetCode=DCIS_POPRES1#

**Comment by aborruso** [comment]
Caro @pigreco l'interfaccia non è per me comoda e spesso è molto lenta.

Potresti modificare colonne di output e quindi schema dati, ma è veramente lento. Scarica i dati grezzi, e poi seleziona per step (con VisiData o SQL è un attimo) tutte le righe in cui le colonne di attributi hanno il valore "totale" (o simile).

E poi filtra soltanto per codice composto da esattamente 4 caratteri. Nota, ogni volta che faccio una selezione per "totale", mi apro la tabella che contiene i valori appena selezionati.

Puoi fare tutto spegnendo e accendento campi nell'interfaccia ISTAT, ma è lenta.

![toto](https://user-images.githubusercontent.com/30607/76792091-84f22700-67c2-11ea-908d-37820229cba2.gif)

**Comment by pigreco** [comment]
Caro @aborruso 
mi sentivo scemo, credevo fossi io l'incapace.

grazie per la rapida soluzione.

![image](https://user-images.githubusercontent.com/7631137/76794253-e1efdc00-67c6-11ea-9f7e-dde3a87b91a8.png)
 W Visidata

**Comment by aborruso** [comment]
Si può fare, ma è lento e scomodo

**Comment by pigreco** [comment]
ricetta fatta
https://festive-bohr-4ac225.netlify.com/ricette/utilities/csv_popolazione_reisidenteistat/

grazie
