### ISSUE TITLE
[CSV] aggiungere un carattere ogni N caratteri di un testo

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#139]
Ho un CSV con un campo popolato da testo abbastanza lungo e ho la necessità di aggiungere, per ogni riga, un carattere ogni N caratteri, l'ideale sarebbe introdurre il carattere in corrispondenza del primo spazio utile dopo gli N caratteri.

allego file CSV

[test.txt](https://github.com/opendatasicilia/tansignari/files/4432532/test.txt)

**Comment by pigreco** [comment]
Una prima soluzione trovata è la seguente:

```
$ cat test.csv | sed 's/.\{50\}/&-*/g'>>out.csv
```
dove inserisco ogni 50 caratteri, due caratteri `-*`

**Comment by aborruso** [comment]
Puoi per favore aggiungere un esempio di output con intestazione e due righe di dati?

Come mai serve inserire questo carattere? Che elaborazione poi dovrà esserne fatta?

**Comment by pigreco** [comment]
Buongiorno @aborruso 
> Puoi per favore aggiungere un esempio di output con intestazione e due righe di dati?


> Come mai serve inserire questo carattere? Che elaborazione poi dovrà esserne fatta?

Sono dati che descrivono siti Geologici:

- "Calcari mal stratificati o massicci (rudstone e floatstone), grossolanamente bioclastici. Subordinatamente contengono orizzonti di calcari micritici a tessitura mudstone e wackestone e calcari oolitici; anche in questa litofacies sono frequenti i veli irregolari calcareo-marnosi di colore giallastro o verdastro."

la legenda, in QGIS, non permette di andare a capo e per farglielo capire occorre mettere dei caratteri speciali.

Un carattere ogni 50 potrebbe cadere anche all'interno di una parola (es: `grossol*anamente`) e rendere poco chiara la lettura. Chiedevo se fosse possibile inserire un carattere entro un range (tra 45 e 60 per esempio) in modo da inserire un carattere in corrispondenza di uno spazio:

```
"Calcari mal stratificati o massicci (rudstone e floatstone),* grossolanamente bioclastici. Subordinatamente* contengono orizzonti di calcari micritici* a tessitura mudstone e wackestone e calcari oolitici;* anche in questa litofacies sono frequenti i veli* irregolari calcareo-marnosi di colore giallastro* o verdastro."
```

in modo da vederlo in legenda cosi:

```
Calcari mal stratificati o massicci (rudstone e floatstone),
 grossolanamente bioclastici. Subordinatamente
 contengono orizzonti di calcari micritici a
 tessitura mudstone e wackestone e calcari oolitici;
 anche in questa litofacies sono frequenti i veli
 irregolari calcareo-marnosi di colore giallastro
o verdastro.
```

**Comment by aborruso** [comment]
Quindi totò non bisogna inserire il carattere speciale nel file, ma soltanto nel campo che contiene la descrizione? Corretto?

Un sorta di world wrap

**Comment by pigreco** [comment]
> Quindi totò non bisogna inserire il carattere speciale nel file, ma soltanto nel campo che contiene la descrizione? Corretto?

Esatto.

**Comment by aborruso** [comment]
Adesso che hai descritto gli obiettivi, e che hai inserito un esempio, penso che potresti usare la mitica `fold` (è un'utility Linux che dovresti avere già installato) accoppiata con `miller`.

Farei così:

```
mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n >testww.txt
```

II comando fa questo:

- estrae la colonna descrizione
- applica il word wrap a 50 caratteri, alla colonna descrizione, senza spezzare le parole
- aggiunge un campo ID progressivo

A questo punto con il file di output puoi fare il JOIN con il file di input (se non c'è in questo l'ID progressivo, lo aggiungi)

**Comment by pigreco** [comment]
Caro @aborruso 

funziona benissimo ed è quello che cercavo, ma non funziona nella legenda di QGIS.

devo necessariamente aggiungere un carattere speciale, solo con quello posso mandare a capo il testo nella legenda (sicuramente è un bug e lo segnalerò).

![image](https://user-images.githubusercontent.com/7631137/78472086-86b26900-7736-11ea-82f6-59d2c7eab2ff.png)

**Comment by pigreco** [comment]
ecco un esempio, se mettessi come carattere la `m` per andare a capo:
![image](https://user-images.githubusercontent.com/7631137/78472328-21f80e00-7738-11ea-8815-ff5e5ea0aeda.png)

**Comment by pigreco** [comment]
ecco, ho messo un `*` e tutto funziona:

![image](https://user-images.githubusercontent.com/7631137/78472595-7ac8a600-773a-11ea-9443-3b47ad6dc980.png)

per aggiungere asterisco ho fatto i salti mortali:
1. ho usato il file CSV, output del comando di sopra;
2. in Notepad++ e usando i regex, ho aggiunto `*`
3. poi, sempre in notepad, ho sostituito gli a capo (`\n`) con nulla, cosi da ottenere unica riga per ogni fid;
4. ho tolto ultimo `*` a fine frase
5. poi in QGIS una join

pazzesco.
Ma credo si possa fare in modo più intelligente.

Grazie per il tempo dedicato.

**Comment by aborruso** [comment]
Ciao totò,
una soluzione che estende il comando di prima è questa

```
mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n | perl -pe 's/\n/*/g;s/\r/\r\n/g' >testww.txt
```

A quanto descritto sopra, faccio un trova un doppio trova e sostituisici per ottenere `*` ogni 50, e mantenere `\r\n` per ogni linea.

Uso perl, che dovrebbe essere già installato su Linux

**Comment by pigreco** [comment]
questo comando :

```
mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n >testww.txt
```
applicato al file `text.txt`

trasforma un testo da cosi:

```
Calcari mal stratificati o massicci (rudstone e floatstone), grossolanamente bioclastici. Subordinatamente contengono orizzonti di calcari micritici a tessitura mudstone e wackestone e calcari oolitici; anche in questa litofacies sono frequenti i veli irregolari calcareo-marnosi di colore giallastro o verdastro.
```
a cosi:

```
Calcari mal stratificati o massicci (rudstone e
floatstone), grossolanamente bioclastici.
Subordinatamente contengono orizzonti di calcari
micritici a tessitura mudstone e wackestone e
calcari oolitici; anche in questa litofacies sono
frequenti i veli irregolari calcareo-marnosi di
colore giallastro o verdastro.
```
ma che carattere nascosto c'è alla fine di ogni linea di testo?? (esempio: alla fine di `Calcari mal stratificati o massicci (rudstone e` che carattere nascosto c'è??)

se riuscissi a capire questo, in QGIS sarebbe tutto risolto.

**Comment by aborruso** [comment]
@pigreco ma hai provato il nuovo comando? Non è la risposta al tuo caso?

> mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n >testww.txt

Il carattere di a capo di questo output lo puoi vedere attivando la visualizzazione dei caratteri nascosti. Come vedi sotto, per gli a capo di cella è un LF, ovvero un `\n`, per quello di riga è un CRLF, ovvero `\r\n`.



![image](https://user-images.githubusercontent.com/30607/78500831-10732e00-7759-11ea-9a5e-b353168045e8.png)

**Comment by pigreco** [comment]
@aborruso

> @pigreco ma hai provato il nuovo comando? Non è la risposta al tuo caso?
> 
> > mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n >testww.txt

purtroppo no.

È utile per etichettare ma non per la legenda nel compositore di stampe che vede sempre tutto in una sola riga.

**Comment by aborruso** [comment]
Aggiungo una mini modifica al comando non provato

```
mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n | perl -pe 's/\r\n/~/g;s/\n/*/g;s/~/\r\n/g' >testww.txt
```

**Comment by pigreco** [comment]
Ciao @aborruso , scusami ma non ho vista questa tua risposta

> Ciao totò,
> una soluzione che estende il comando di prima è questa
> 
> ```
> mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n | perl -pe 's/\n/*/g;s/\r/\r\n/g' >testww.txt
> ```
 è ottima, unica cosa aggiunge, come descritto nel primo caso, un numero con un asterisco iniziale:

![image](https://user-images.githubusercontent.com/7631137/78501607-7c0aca80-775c-11ea-825a-2468716d2ad8.png)

**Comment by pigreco** [comment]
> Aggiungo una mini modifica al comando non provato
> 
> ```
> mlr --csv cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv cat -n | perl -pe 's/\r\n/~/g;s/\n/*/g;s/~/\r\n/g' >testww.txt
> ```

wow
questa è perfetta

**Comment by aborruso** [comment]
Altra mini correzione, perché riga 26 in input è diversa, non ha le `"`

```
mlr --csv --quote-all --ors '\r\n' cut -f DESCRIZIONE test.txt | fold -sw 50 | mlr --csv --ors '\r\n' --quote-all cat -n  | perl -pe 's/\r\n/~/g;s/\n/*/g;s/~/\r\n/g' >testww.txt
```

**Comment by pigreco** [comment]
https://github.com/qgis/QGIS/issues/35597

**Comment by pigreco** [comment]
Scritto blog post
https://pigrecoinfinito.com/2020/04/09/qgis-e-la-legenda-lunga-delle-carte-geologiche/

**Comment by aborruso** [comment]
> Scritto blog post
> https://pigrecoinfinito.com/2020/04/09/qgis-e-la-legenda-lunga-delle-carte-geologiche/

Grazie!

**Comment by pigreco** [comment]
creata e aggiunta ricetta:

https://festive-bohr-4ac225.netlify.com/ricette/bash/aggiungere_carattere_ogni_n/

grazie chiudo
