### ISSUE TITLE
Cerca e sostituisci QGIS

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#14]
Buongiorno, 
vorrei modificare solo il valore **"weight": "7"** nella colonna _umap_options come in figura
come posso fare?
![screenshot 14](https://user-images.githubusercontent.com/20488693/52701777-4c5a9b00-2f7b-11e9-9a68-3b58e4fdf4d5.jpg)

Altra Domanda...
Per comodità mia vorrei aggiungere al campo **URL_IMMAGINE** una parte di indirizzo wdb
esempio... **https://dati.agenziademanio.it/cammini/resources/images/**
si può fare?
![screenshot 15](https://user-images.githubusercontent.com/20488693/52702098-e3275780-2f7b-11e9-917a-fdca24d23642.jpg)

**Comment by pigreco** [comment]
Ciao @gbvitrano 
* per la prima domanda potresti usare la funzione [`regexp_replace`](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/stringhe_di_testo/regexp_replace.html)
* per la seconda domanda, usando il field calc e aggiornando il campo:
'https://dati.agenziademanio.it/cammini/resources/images/'||"URL_IMMAGINE"
![image](https://user-images.githubusercontent.com/7631137/52705763-0524d800-2f84-11e9-8483-1831d0eb7d5f.png)

**Comment by gbvitrano** [comment]
Grazie, grande QGIS
