### ISSUE TITLE
CSV remoto - google sheet  

### ISSUE THREAD

**Issue by gimmybruce** [opendatasicilia/tansignari#142]
Ciao.
Vorrei leggere con QGIS (vers. 3.10) un file .CSV di dati puntuali (con colonne LAT e LON)  che ho su Google Drive come foglio di calcolo. Il foglio di calcolo che sto usando come test è raggiungibile al seguente link: https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv
L'obiettivo è di leggere in real time le modifiche effettuate sul foglio di calcolo direttamente in QGIS. 
Sto provando con il formato VRT ma non va:
```
<OGRVRTDataSource>
<OGRVRTLayer name="test_vsicurl">
    <SrcDataSource relativeToVRT="0">/vsicurl/hhttps://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv</SrcDataSource>
    <GeometryType>wkbPoint</GeometryType>
    <LayerSRS>WGS84</LayerSRS>
	<Field name="ID" type="Integer" />
	<Field name="comune" type="String" />
    <GeometryField encoding="PointFromColumns" x="LAT" y="LON"/>
</OGRVRTLayer>
</OGRVRTDataSource>
```
Grazie

**Comment by pigreco** [comment]
Ciao e benvenuto su T'ansignari,
purtroppo i file vrt non sono attualmente ben letti da QGIS, a tal proposito ho aperto questa issue https://github.com/qgis/QGIS/issues/35016, ma sembra abbandonata.

**Comment by gimmybruce** [comment]
Ciao e grazie. Sono su Linux ma credo sia lo stesso problema. Domani vedo di nuovo dal PC. Anche con ogrinfo non sono riuscito ad estrarre le informazioni presenti nel csv menzionato sopra. Farò altre prove. Grazie.

**Comment by aborruso** [comment]
ciao @gimmybruce non ti arrendere subito, specie se ci sono gdal e ogr di mezzo

Per sorgenti di questo tipo parti sempre dal comando base, non creare subito VRT. O fallo soltanto dopo che sai per bene quello che fai.

Il comando di base è 

```
ogrinfo CSV:"/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv"
```

In risposta sul mio PC ho

```
INFO: Open of `CSV:/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv'
      using driver `CSV' successful.
1: pub?gid=1205794028&single=true&output=csv (None)
```

Che è una buona notizia. In risposta ho un'informazione molto importante, il nome del layer, che è `pub?gid=1205794028&single=true&output=csv`. Allora posso andare oltre e chiedere info sul layer

```
ogrinfo CSV:"/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv" "pub?gid=1205794028&single=true&output=csv"
```

Che in risposta mi conferma che è tutto ok

```
INFO: Open of `CSV:/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv'
      using driver `CSV' successful.

Layer name: pub?gid=1205794028&single=true&output=csv
Geometry: None
Feature Count: 2
Layer SRS WKT:
(unknown)
ID: String (0.0)
LAT: String (0.0)
LON: String (0.0)
comune: String (0.0)
localita: String (0.0)
OGRFeature(pub?gid=1205794028&single=true&output=csv):1
  ID (String) = 1
  LAT (String) = 41.51054842
  LON (String) = 15.31931947
  comune (String) = Lucera
  localita (String) = Lucera

OGRFeature(pub?gid=1205794028&single=true&output=csv):2
  ID (String) = 2
  LAT (String) = 41.89817
  LON (String) = 15.90292
  comune (String) = Ischitella
  localita (String) = Belvedere
```

E se gli aggiungi la lettura dei campi LAT e LON, lo vedrà come una geometria:

```
ogrinfo CSV:"/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv" "pub?gid=1205794028&single=true&output=csv" -oo X_POSSIBLE_NAMES=LON -oo Y_POSSIBLE_NAMES=LAT
```

che ti restituirà

```
INFO: Open of `CSV:/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&single=true&output=csv'
      using driver `CSV' successful.

Layer name: pub?gid=1205794028&single=true&output=csv
Geometry: Point
Feature Count: 2
Extent: (15.319319, 41.510548) - (15.902920, 41.898170)
Layer SRS WKT:
(unknown)
ID: String (0.0)
LAT: Real (0.0)
LON: Real (0.0)
comune: String (0.0)
localita: String (0.0)
OGRFeature(pub?gid=1205794028&single=true&output=csv):1
  ID (String) = 1
  LAT (Real) = 41.51054842
  LON (Real) = 15.31931947
  comune (String) = Lucera
  localita (String) = Lucera
  POINT (15.31931947 41.51054842)

OGRFeature(pub?gid=1205794028&single=true&output=csv):2
  ID (String) = 2
  LAT (Real) = 41.89817
  LON (Real) = 15.90292
  comune (String) = Ischitella
  localita (String) = Belvedere
  POINT (15.90292 41.89817)
```

**Comment by aborruso** [comment]
@gimmybruce @pigreco e funziona anche in QGIS, come vrt

```xml
<OGRVRTDataSource>
  <OGRVRTLayer name="foo">
    <SrcDataSource relativeToVRT="0">CSV:/vsicurl_streaming/https://docs.google.com/spreadsheets/d/e/2PACX-1vTwuYdMYS7vKJnTETwycLEGPFG2pwhxIlPMeChXuluRLjApQwhzEy_gUgsw_9lVRrAmGhAHWEj9LDV7/pub?gid=0&amp;single=true&amp;output=csv</SrcDataSource>
    <SrcLayer>pub?gid=0&amp;single=true&amp;output=csv</SrcLayer>
    <GeometryType>wkbPoint</GeometryType>
    <LayerSRS>WGS84</LayerSRS>
    <GeometryField encoding="PointFromColumns" x="LON" y="LAT"/>
  </OGRVRTLayer>
</OGRVRTDataSource>
```

**Comment by aborruso** [comment]
@gimmybruce qui trovi evidenziate tutte le cose che dovresti cambiare nel tuo vrt

https://gist.github.com/aborruso/afaff0e2eed29a943cc033642adccc60/revisions#diff-3660a0f2caadf041ca317e5b5eabfcc7

**Comment by gimmybruce** [comment]
Mi avevi detto che non eri un MAGO :D. Stavo appunto vedendo di capire le differenze. GRAZIE. Troppo forte sta cosa!!!!! GRAZIE...mi piace assai :D .

**Comment by gimmybruce** [comment]
Benissimo, funziona alla grande .
Sto vedendo le diverse modifiche che hai fatto,  tra cui 'vsicurl_streaming' (ho provato anche con solo 'vsiculr/....' e funziona)

Faccio il riepilogo :)
opzione A) Così funziona tutto
```
<OGRVRTDataSource>
    <OGRVRTLayer name="pub?gid=1205794028&amp;single=true&amp;output=csv">
    <SrcDataSource relativeToVRT="0">CSV:/vsicurl/https://docs.google.com/spreadsheets/d/e/2PACX-1vT89Gvg-StE8M0zapI3A-WYRR1EbrnbUMZSi4QGFpJy5P4aM5r1HJ3I3Ro_OJceWZBygmFbLZVMJok6/pub?gid=1205794028&amp;single=true&amp;output=csv</SrcDataSource>
    <GeometryType>wkbPoint</GeometryType>
    <LayerSRS>WGS84</LayerSRS>
    <Field name="ID" type="Integer" />
    <Field name="comune" type="String" />
    <Field name="localita" type="String" />
    <GeometryField encoding="PointFromColumns" x="LON" y="LAT"/>
  </OGRVRTLayer>
</OGRVRTDataSource> 
```
opzione B) 
ma è meglio con un nome meno strano come hai suggerito sopra dove però non visualizzo il contenuto delle colonne 'comune' e 'localita'.....cerco di capire

```
<OGRVRTDataSource>
  <OGRVRTLayer name="esempionome">
    <SrcDataSource relativeToVRT="0">CSV:/vsicurl_streaming/https://docs.google.com/spreadsheets/d/e/2PACX-1vTwuYdMYS7vKJnTETwycLEGPFG2pwhxIlPMeChXuluRLjApQwhzEy_gUgsw_9lVRrAmGhAHWEj9LDV7/pub?gid=0&amp;single=true&amp;output=csv</SrcDataSource>
    <SrcLayer>pub?gid=0&amp;single=true&amp;output=csv</SrcLayer>
    <GeometryType>wkbPoint</GeometryType>
    <LayerSRS>WGS84</LayerSRS>
    <Field name="ID" type="Integer" />
    <Field name="comune" type="String" />
    <Field name="localita" type="String" />
    <GeometryField encoding="PointFromColumns" x="LON" y="LAT"/>
  </OGRVRTLayer>
</OGRVRTDataSource>
```
Intanto...straordinario! Grazie.

**Comment by pigreco** [comment]
Ciao @gimmybruce 
come avrai letto nel [Galateo](https://github.com/opendatasicilia/tansignari/blob/master/galateo.md): 

`se sei soddisfatta/o della risposta, sei invitata/o a rimborsare, creando un testo, una ricetta, che racconti per bene il problema che hai riscontrato e come è possibile risolverlo (vedi sotto)`

puoi seguiere questi template: https://github.com/opendatasicilia/tansignari/blob/master/tempalte_ricette.md

e guarda le altre ricette per capire come scriverla.

grazie

**Comment by gimmybruce** [comment]
Ciao. Sì, sono molto soddisfatto. In questi giorni lo rivedo e faccio la ricetta. Grazie.

**Comment by gimmybruce** [comment]
Ciao, scusatemi. Diversi giorni fa ho scritto la ricetta. Vorrei sapere se vi risulta oppure ho sbagliato qualcosa?

**Comment by pigreco** [comment]
> Ciao, scusatemi. Diversi giorni fa ho scritto la ricetta. Vorrei sapere se vi risulta oppure ho sbagliato qualcosa?

Ciao, NO a me non risulta nulla.
Dove la hai messa??

**Comment by gimmybruce** [comment]
L'avevo messe in ricette ma non la vedo. Inoltre avevo modificato da ### tempalte_ricette.md a ### template_ricette.md ma non vedo nemmeno questa....mh..boh.

**Comment by gimmybruce** [comment]
L'avevo fatta così --> http://collabedit.com/j24xj

**Comment by pigreco** [comment]
> L'avevo fatta così --> http://collabedit.com/j24xj

Ciao, ho usato il tuo file e impostato la ricetta.

Non toccare la parte iniziale, puoi modificare da `Caso d'uso` in giù

https://github.com/opendatasicilia/tansignari-md/blob/master/content/it/ricette/CSV-TSV/leggere_csv_remoto.md

**Comment by pigreco** [comment]
@gimmybruce 
la ricetta è completa? posso chiudere issue?

**Comment by gimmybruce** [comment]
Ciao. Sì, grazie.
