### ISSUE TITLE
[scraping] risultato inatteso

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#145]
Con lo script bash che segue, gratto i dati da queste [pagine](https://github.com/qgis/QGIS/pulls) ma non capisco un risultato:

```bash
#!/bin/bash
# filtro github: is:pr is:closed label:feature merged:2020-02-22T00:00:00Z..2020-05-15T12:00:00Z
set -x
# rimuove eventuali file CSV
rm *.csv
# crea ciclo, 5 sono il numero delle pagine WEB
for p in {1..5}
do
    curl "https://github.com/qgis/QGIS/pulls?page=""$p""&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A2020-02-22T00%3A00%3A00Z..2020-05-15T12%3A00%3A00Z&utf8=%E2%9C%93" | scrape -be ".pr-md-2"  |xq '.html.body.div[]|{PR:.a["@href"]?,Description:.a["#text"]?,tag:[.span[1].a[]["#text"]?],Author:.div.span[0].a["#text"]?,Milestone:.div.span[2]?.a["@aria-label"]?,Datetime:.div.span[0]["relative-time"]["@datetime"]}' | mlr --j2c unsparsify >pag"$p".csv
done
# mergia tutti i file CSV
mlr --csv unsparsify *.csv >merge.csv
```

il filtro utilizzato richiede anche `label:feature` (cioè deve contenere il termine `feature`), ma nei file `pag"$p".csv` o quello finale `merge.csv` ci sono righe senza `label` cioè tag, ma come è possibile??

**Comment by aborruso** [comment]
@pigreco c'era un piccolo errore nella query JSON, perché dava per scontato che tutte le PR avessero almeno due tag.

Guarda questo nuovo comando per la solita pagina 1

```
curl "https://github.com/qgis/QGIS/pulls?page=1&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A2020-02-22T00%3A00%3A00Z..2020-05-15T12%3A00%3A00Z&utf8=%E2%9C%93" | scrape -be ".pr-md-2"  |xq '.html.body.div[]|{PR:.a["@href"]?,Description:.a["#text"]?,tag:.span[1].a,Author:.div.span[0].a["#text"]?,Milestone:.div.span[2]?.a["@aria-label"]?,Datetime:.div.span[0]["relative-time"]["@datetime"]}' | mlr --j2c unsparsify then cut -r -f '(PR|Descr|text|Auth|Miles|Date)' | vd -f csv
```

Mi sembra corretto. Se lo è, non ti resta che applicarlo

**Comment by aborruso** [comment]
@pigreco se i tuoi CSV hanno ordine di colonne diverso, l'unione (senza forzare l'ordine delle colonne "a mano") è quasi magia. 

Per fortuna Miller (tra le cose incredibili che fa) fa l'unione di CSV non eterogenei fra loro, con campi in ordine sparso, con numeri di campo diversi, e con nomi campo diversi.

Sostituisci il tuo `mlr --csv unsparsify *.csv >merge.csv` con `mlr --csvlite unsparsify  *.csv >merge.csv`.

Il formato `csvlite` è quello che consente di essere più "sporchi" nel merge tra file distinti

**Comment by pigreco** [comment]
Caro @aborruso,
finalmente tutto funziona, ecco lo script bash finale:

```bash
#!/bin/bash
# filtro github: is:pr is:closed label:feature merged:2020-02-22T00:00:00Z..2020-05-15T12:00:00Z
set -x
# rimuove eventuali file CSV
rm *.csv
# crea ciclo, 5 sono il numero delle pagine WEB
for p in {1..5}
do
    curl "https://github.com/qgis/QGIS/pulls?page=$p&q=is%3Apr+is%3Aclosed+label%3Afeature+merged%3A2020-02-22T00%3A00%3A00Z..2020-05-15T12%3A00%3A00Z&utf8=%E2%9C%93" | scrape -be ".pr-md-2"  |xq '.html.body.div[]|{PR:.a["@href"]?,Description:.a["#text"]?,tag:.span[1].a,Author:.div.span[0].a["#text"]?,Milestone:.div.span[2]?.a["@aria-label"]?,Datetime:.div.span[0]["relative-time"]["@datetime"]}' | mlr --j2c unsparsify then cut -r -f '(PR|Descr|text|Auth|Miles|Date)'  >pag"$p".csv
done
# merges all CSV files
mlr --csv unsparsify *.csv >merge.csv
# concatenate the fields
mlr -I --csv put -S '$tags=${tag:#text}."; ".${tag:0:#text}."; ".${tag:1:#text}."; ".${tag:2:#text}."; ".${tag:3:#text}."; ".${tag:4:#text}' merge.csv
# delete fields not listed
mlr --csv cut -o -f Description,Author,Milestone,Datetime,PR,tags merge.csv >merge_mod.csv
# removes the CSV files starting with pag
rm pag*.csv
# view the file with VisiData
vd merge_mod.csv
```

unica nota:

`mlr --csvlite unsparsify *.csv >merge.csv` non funziona ed ho lasciato quello di prima.

grazie

**Comment by pigreco** [comment]
@aborruso 
allego i 5 file CSV

[viva-andy.zip](https://github.com/opendatasicilia/tansignari/files/4585486/viva-andy.zip)

**Comment by pigreco** [comment]
Grazie chiudo, una ricetta simile esiste già

https://github.com/opendatasicilia/tansignari-md/blob/master/content/it/ricette/Scraping/changelogQGIS312/index.md
