### ISSUE TITLE
[Miller] cerca e sostituisci in un campo

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#146]
Ho un file csv con alcuni campi e vorrei pulire un campo specifico (tags) da testo indesiderato: 

- `; ` iniziali e finali
- Feature
- Needs Documentation
- backport release-3_10
- backport release-3_12
- Squash!
- Requires Tests!
- Changelog

da ricerche sul web ho trovato [questo](https://johnkerl.org/miller/doc/cookbook.html#Search-and-replace_over_all_fields) ma non so come usarlo.

`mlr --csv $tags=gsub($tags, "Feature", "") merge_mod.csv >test1.csv`

mi dice che è errato: `-bash: syntax error near unexpected token `('`

allego file csv

[merge_mod.txt](https://github.com/opendatasicilia/tansignari/files/4586700/merge_mod.txt)

**Comment by aborruso** [comment]
Puoi usare il verbo [put](http://johnkerl.org/miller/doc/reference-verbs.html#put) e la fuzione [gsub](http://johnkerl.org/miller/doc/reference-dsl.html#gsub), che fa un trova e sostituisci globale usando regex in standard posix.2

Qui sotto un esempio con due trova e sostituisci, separati da `;`.

```
mlr --csv put '$tags=gsub($tags,"Needs Documentation","");$tags=gsub($tags,"Feature","")' input >output
```

**Comment by pigreco** [comment]
caro @aborruso  funziona tutto.

ho usato lo scriptino di sotto, ma rimane qualche `;` di fine riga che non riesco a eliminare, per il rsto tutto ok

```
mlr --csv put '$tags=gsub($tags,"^(; ){1,}",""); $tags=gsub($tags,"(; ){1,}$","");$tags=gsub($tags,".?Needs Documentation.?",""); $tags=gsub($tags,".?Feature.?",""); $tags=gsub($tags,".?Squash!.?","");$tags=gsub($tags,".?Requires Tests!.?","");$tags=gsub($tags,".?Changelog.?",""); $tags=gsub($tags,".?backport release-3_1..?","")' merge_mod.csv | vd -f csv
```

grazie

**Comment by pigreco** [comment]
ricetta create, grazie chiudo

https://github.com/opendatasicilia/tansignari-md/blob/master/content/it/ricette/Utilities/concatenare_campi_miller.md

**Comment by pigreco** [comment]
ricetta fatta. grazie chiudo

https://github.com/opendatasicilia/tansignari-md/blob/master/content/it/ricette/Utilities/cerca_sostituisci_con_miller.md
