### ISSUE TITLE
[GIS] creare db spaziale da riga di comando

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#15]
Come creare un database sqlite con estensione spaziale da riga di comando??

ho provato con `$ sqlite3 nomeDb.sqlite`

ma genera un database senza capacità spaziali.

**Comment by aborruso** [comment]
Ciao @pigreco,
creato il db, poi come importi i dati all'interno? VirtualOGR? 
Se sì, VirtualOGR deve essere caricato tramite modulo (se mappato nel path, basta `.load  libgdal.so`).


Non altre info, quindi mi fermo qui

**Comment by pigreco** [comment]
Ciao Andrea,
riformulo la domanda:
ho installato sqlite3 e caricato la libreria `.load /usr/local/lib/mod_spatialite.so`
esiste un modo per creare, da subito, un db con estensione spaziale oppure occorre prima creare un db normale e poi importare un vettore?? da [qui ](https://www.gaia-gis.it/spatialite-1.0a/SpatiaLite-tutorial.html#t3.2)sembra che occorra importare un vettore per rendere il db spaziale

perché questa domanda:

ho creato un db sqlite: `sqlite3 > sqlite3 nomeDb.sqlite`;

ho importato un file csv che contiene i campi longitudine e latitudine; sulla base di questi campi volevo trasformare la tabella (appena importata) in una tabella spaziale, ma non ci riesco perché il db non è spaziale:
```
.load /usr/local/lib/mod_spatialite.so
.mode csv 01_demanio
.import 01_demanio.csv opendemanio

SELECT  AddGeometryColumn ('opendemanio','geometry',3857,'POINT','XY');

UPDATE opendemanio SET geometry =
MakePoint(CAST(X AS float),CAST(Y AS float),3857);
```
questo piccolo script mi da errore

![image](https://user-images.githubusercontent.com/7631137/52709034-ed515200-2f8b-11e9-8073-61b905aa528d.png)

**Comment by aborruso** [comment]
Devi inizializzare il db con `SELECT InitSpatialMetaData();`.

È lento e c'è da capire se c'è un modo per velocizzarlo

**Comment by aborruso** [comment]
Ok, risolto: basta usare `SELECT InitSpatialMetaData(1);`

Quindi

```
.load /usr/local/lib/mod_spatialite.so
.mode csv 01_demanio
.import 01_demanio.csv opendemanio

SELECT InitSpatialMetaData(1);

SELECT  AddGeometryColumn ('opendemanio','geometry',3857,'POINT','XY');

UPDATE opendemanio SET geometry =
MakePoint(CAST(X AS float),CAST(Y AS float),3857);
```

**Comment by pigreco** [comment]
Ciao Andrea,

<Ok, risolto: basta usare `SELECT InitSpatialMetaData(1);`

funziona benissimo e crea anche le virtualKNN

grazie,
chiudo

**Comment by pigreco** [comment]
Script bash : nome `geometry.sh` e poi dargli i permessi di esecuzione con `chmod +x geometry.sh` e poi lo lanci con `./geometry.sh`

```bash
#!/bin/bash

sqlite3 nomeDb.sqlite <<EOF

.load /usr/local/lib/mod_spatialite.so
.mode csv 01_demanio
.import 01_demanio.csv opendemanio

SELECT InitSpatialMetaData(1);

SELECT  AddGeometryColumn ('opendemanio','geometry',3857,'POINT','XY');

UPDATE opendemanio SET geometry =
MakePoint(CAST(X AS float),CAST(Y AS float),3857);

EOF
```
