### ISSUE TITLE
[regex] acchiappa prima parte del testo

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#150]
Ho delle righe cosi fatte:

```
ciao-ciao,notte-cia,cucu-settete,bella-brutto -- prima riga
we-ddd,sedr-fffff,toto-pigreco -- seconda riga
```

cioè si ripete lo schema per ogni riga `testo1-testo2,testo3-testo4,....`

come posso ottenere `testo1,testo3,...`  cioè acchiappare solo la prima parte del testo (con numero dispari)??

qui ho salvato un esempio:

https://regex101.com/r/sDvUk4/1/

**Comment by pigreco** [comment]
Ho fatto un passo avanti con questa stringa regex, ma non funziona per la parte finale della riga:

`(.+?)-(.+?),`

https://regex101.com/r/sDvUk4/2

**Comment by aborruso** [comment]
Non so se ho capito. Così https://regex101.com/r/Je1E7Z/1/ ?

`[^-, ]` vuol dire tutto ciò che non è o `-` o `,`.

**Comment by pigreco** [comment]
> Non so se ho capito. Così https://regex101.com/r/Je1E7Z/1/ ?

Esatto!!!

Grazie mille @aborruso
