### ISSUE TITLE
[windows terminal] wt non funziona bene

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#153]
Ho installato l'app Windows Terminal Preview

ma non funziona come dovrebbe, digitando `wt` nella barra dei percorsi win, apre il terminale sempre allo stesso percorso e non tiene conto della cartella di lancio.

![image](https://user-images.githubusercontent.com/7631137/88428176-a1e3da00-cdf4-11ea-8eff-4b4627444a34.png)

**Comment by aborruso** [comment]
Non posso accedere al mio PC.


Ma dovrebbe bastare cambiare le impostazioni in questo modo
https://github.com/microsoft/terminal/issues/620#issuecomment-621951962

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il ven 24 lug 2020, 21:29 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
@aborruso 

ha funzionato alla grande!!!

grazie.
![image](https://user-images.githubusercontent.com/7631137/88430738-41a36700-cdf9-11ea-90a9-127097915ac6.png)
