### ISSUE TITLE
[script] alberi monumentali aggiornati al 24-07-2020

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#155]
Elenco degli alberi monumentali d'Italia ai sensi della Legge n. 10/2013 e 
del Decreto 23 ottobre 2014 è stato aggiornato al 24-07-2020.

qui il sito e i file *.xls:
https://www.politicheagricole.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/11260

I file xls sono stati modificati rispetto a qualche tempo fa, vedasi questo interessantissimo blog post di @aborruso : https://medium.com/tantotanto/dove-sono-gli-alberi-monumentali-ditalia-ffd7d0d6d860

Per ottenere un unico file csv, occorre seguire questi passi:

1. download dei 21 file xls; (fatto manualmente)
2. conversione file da xls a csv; (fatto usando `find . -name '*.xls' -exec ssconvert -T Gnumeric_stf:stf_csv {} \;`
3. append dei file per ottenere unica tabella; (fatto usanso `cat your-file-pattern*.csv >> concatenatio-file.csv`)
4. togliere spazi nelle coordinate (`42° 05' 14,02'' | 14° 20' 34,97''`); (fatto usando libreOffice)
5. sostituire `,` con `.` nella parte decimale delle coordinate; (fatto usando libreOffice)

un primo output (in geojson) è qui:
https://gist.github.com/pigreco/c9e5680d7db7e6e7c405f73dce2c3c47

come creo un unico script che segua i punti elenco di sopra??

**Comment by pigreco** [comment]
da un suggerimento di @aborruso :
1. download file xls:
```
curl "https://www.politicheagricole.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/11260" | scrape -be ".blob-element-download .viewLinkIMG" | xq -r '.html.body.a[]|[."@href",."#text"]|@tsv'  | parallel --colsep '\t' wget  {1} -O {2}.xls
```
ottenendo:
```
Abruzzo 24.7.2020.xls
Basilicata 24.7.2020.xls
Bolzano 24.7.2020.xls
Calabria 24.7.2020.xls
Campania 24.7.2020.xls
Emilia Romagna 24.7.2020.xls
Friuli Venezia Giulia 24.7.2020.xls
Lazio 24.7.2020.xls
Liguria 24.7.2020.xls
Lombardia 24.7.2020.xls
Marche 24.7.2020.xls
Molise 24.7.2020.xls
Piemonte 24.7.2020.xls
Puglia 24.7.2020.xls
Sardegna 24.7.2020.xls
Sicilia 24.7.2020.xls
Toscana 24.7.2020.xls
Trento 24.7.2020.xls
Umbria 24.7.2020.xls
Valle d'Aosta 24.7.2020.xls
Veneto 24.7.2020.xls
```

**Comment by pigreco** [comment]
2. conversione file da xls a csv; (fatto usando `find . -name '*.xls' -exec ssconvert -T Gnumeric_stf:stf_csv {} \;`)

lanciando `find . -name '*.xlsx' -exec ssconvert -T Gnumeric_stf:stf_csv {} \;`

**Comment by pigreco** [comment]
3. append dei file per ottenere unica tabella; (fatto usanso `cat *.csv >>lista.csv`)

ma lanciando `cat *.csv >>lista.csv` nel file avrò ripetuto l'intestazione 21 volte, quindi occorre una successiva pulitura

**Comment by pigreco** [comment]
4. togliere spazi nelle coordinate (`42° 05' 14,02'' | 14° 20' 34,97''`); (fatto usando libreOffice)
5. sostituire `,` con `.` nella parte decimale delle coordinate; (fatto usando libreOffice)

ho provato a farlo con VisiData, ma non ci riesco :-(

**Comment by aborruso** [comment]
> ma lanciando `cat *.csv >>lista.csv` nel file avrò ripetuto l'intestazione 21 volte, quindi occorre una successiva pulitura

`cat` non sa cosa è l'heading, per lui le righe sono tutte uguali. QUindi le rimuovi tutte (con `sed`), poi unisci il tutto e poi rimetti intestazione.
O usi tool che sanno gestire intestazione, come miller, e dai `mlr --csv cat *.csv >merge.csv`

**Comment by aborruso** [comment]
> ho provato a farlo con VisiData, ma non ci riesco :-(

Qui come farlo https://github.com/ondata/guidaVisiData/blob/master/testo/README.md#concatenare-tabelle

**Comment by pigreco** [comment]
Riassumendo:

```
# scarico i file
curl "https://www.politicheagricole.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/11260" | scrape -be ".blob-element-download .viewLinkIMG" | xq -r '.html.body.a[]|[."@href",."#text"]|@tsv'  | parallel --colsep '\t' wget  {1} -O {2}.xls
# li converto in csv
find . -name '*.xls' -exec ssconvert -T Gnumeric_stf:stf_csv {} \;
# mergio tutti i CSV, ottenendo unico file
mlr --csv cat *.csv >merge.csv
```

per il punti 4 e 5 utilizzo VisiData per pulire il dataset

```
vd merge.csv
gd
g*
\s/
```

per sostituire a `,` il `.`:

```
gd
g*
,/.
```
grazie @aborruso

**Comment by aborruso** [comment]
@picomiles  alleghi il file merge?

**Comment by pigreco** [comment]
@aborruso 
ecco il file finale

[merge_fine.txt](https://github.com/opendatasicilia/tansignari/files/4995648/merge_fine.txt)

**Comment by aborruso** [comment]
@pigreco sono stato impreciso.

Vorrei il file che ti esce da `mlr --csv cat *.csv >merge.csv`.
E per favore mi aggiungi uno dei CSV regionali che viene dalla conversione da XLS a csv.

Grazie

**Comment by pigreco** [comment]
@aborruso 
allego file *.zip con i due file richiesti.

[x_andy.zip](https://github.com/opendatasicilia/tansignari/files/4995738/x_andy.zip)

**Comment by aborruso** [comment]
Nel file "Trento" c'è un campo non presente in tutti gli altri (ultimo).

![image](https://user-images.githubusercontent.com/30607/88822008-9d883a00-d1c3-11ea-8b2a-46f082f6bb64.png)

Quando fai il merge allora dei CSV, ti si crea una colonna vuota senza nome (vedi in merge_fine, la virgola alla fine)

![image](https://user-images.githubusercontent.com/30607/88822118-c8728e00-d1c3-11ea-9707-369b5f009ec5.png)

VisiData lo legge, ma in realtà è un CSV non valido.

Una versione in bash potrebbe essere quella di sotto (uso parallel, miller, [pyexcel-cli](https://github.com/pyexcel/pyexcel-cli) e [pyexcel-xls](https://github.com/pyexcel/pyexcel-xls))

```bash
#/bin/bash

set -x

mkdir -p ./rawdata
mkdir -p ./processing

# cancella file xls
rm ./rawdata/*.xls

# scrica i file xls
curl "https://www.politicheagricole.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/11260" |
  # estrai dati sui file XLS degli alberi
  scrape -be ".blob-element-download .viewLinkIMG" |
  # estrai proprietà href e text (URL e nome file)
  xq -r '.html.body.a[]|[."@href",."#text"]|@tsv' |
  # fai partire il download
  parallel --colsep '\t' wget {1} -O ./rawdata/{2}.xls

for i in ./rawdata/*.xls; do
  #crea una variabile da usare per estrarre nome e estensione
  filename=$(basename "$i")
  #estrai estensione
  extension="${filename##*.}"
  #estrai nome file
  filename="${filename%.*}"
  # converti file XLS in CSV
  pyexcel transcode --sheet-index 0 "$i" ./processing/"$filename".csv
done

# unisci i file, tenendo conto di eventuali campi in più e fai pulizia di eventuali spazi bianchi in più
mlr --csv unsparsify then clean-whitespace ./processing/*.csv >./alberi.csv

# dalle coordinate rimuovi spazi e sostituisci "," con "."
mlr -I --csv put '${LATITUDINE SU GIS}=gsub(${LATITUDINE SU GIS}," ","");${LONGITUDINE SU GIS}=gsub(${LONGITUDINE SU GIS}," ","");${LATITUDINE SU GIS}=gsub(${LATITUDINE SU GIS},",",".");${LONGITUDINE SU GIS}=gsub(${LONGITUDINE SU GIS},",",".")' ./alberi.csv
```

**Comment by pigreco** [comment]
per installarli nel mio wls1:
```
python3 -m pip install --upgrade --user pyexcel-cli
python3 -m pip install --upgrade --user pyexcel-xls
```

**Comment by pigreco** [comment]
@aborruso 
grazie per la collaborazione e lo script

chiudo issue, qui ricetta:
https://festive-bohr-4ac225.netlify.app/ricette/script/alberi_monumentali/
