### ISSUE TITLE
Gif animate tramite url e gist

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#156]
Ho creato un [gist ](https://gist.github.com/pigreco/3b93978316ba1ff226de69885d758cf0)in formato `markdowm` con testo e immagini animate tramite URL.

le gif animate le richiamo in questo modo:

```
![](link_URL)
```

![image](https://user-images.githubusercontent.com/7631137/90515495-0a5b7800-e163-11ea-9d56-eb3340ed160e.png)

Alcuni GIF vengono visualizzate altre no e non capisco il perché; tutte le GIF sono caricate in un sito Wordpress e sono visibili se richiamate singolarmente, ecco un esempio:

<https://pigrecoinfinito.files.wordpress.com/2020/08/webp-net-gifmaker-1.gif?raw=true>

cosa sbaglio??

**Comment by aborruso** [comment]
Purtroppo non vedo errori di sintassi.

Il browser mostra qual è l'errore, ma non capisco perché sia valido soltanto per alcune immagini :(

![image](https://user-images.githubusercontent.com/30607/90517471-b900b800-e165-11ea-91e4-b2f57c6580b4.png)

**Comment by pigreco** [comment]
@aborruso grazie.
