### ISSUE TITLE
[bash] come ottenere un output su più righe

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#158]
ho realizzato questo script bash per estrarre alcuni dati dal WMS Catasto:

```
#!/bin/bash

rm ./outputCatasto2.txt

while IFS=$'\t' read -r lon lat; do
lon=$lon
lat=$lat
curl -sKL "https://wms.cartografia.agenziaentrate.gov.it/inspire/ajax/ajax.php?op=getDatiOggetto&lon=$lon&lat=$lat" >>./outputCatasto2.txt
done <./input2.tsv
```

questo il file di `input.tsv`

```
13.3506684757671	38.1387133482979
13.3596985068089	38.1411107968398
13.3598245316266	38.1365525853503
```

l'output è in una sola riga:

```
{"SIGLA_PROV":"PA","COD_COMUNE":"G273","DENOM":"PALERMO (PA)","SEZIONE":" ","FOGLIO":"33","ALLEGATO":"A","SVILUPPO":"null","NUM_PART":"673","TIPOLOGIA":"PARTICELLA"}{"SIGLA_PROV":"PA","COD_COMUNE":"G273","DENOM":"PALERMO (PA)","SEZIONE":" ","FOGLIO":"35","ALLEGATO":"null","SVILUPPO":"null","NUM_PART":"3077","TIPOLOGIA":"PARTICELLA"}{"SIGLA_PROV":"PA","COD_COMUNE":"G273","DENOM":"PALERMO (PA)","SEZIONE":" ","FOGLIO":"35","ALLEGATO":"null","SVILUPPO":"null","NUM_PART":"2419","TIPOLOGIA":"PARTICELLA"}
```

come ottenere in output una riga per ogni riga dell'input??

```
{"SIGLA_PROV":"PA","COD_COMUNE":"G273","DENOM":"PALERMO (PA)","SEZIONE":" ","FOGLIO":"33","ALLEGATO":"A","SVILUPPO":"null","NUM_PART":"673","TIPOLOGIA":"PARTICELLA"}
{"SIGLA_PROV":"PA","COD_COMUNE":"G273","DENOM":"PALERMO (PA)","SEZIONE":" ","FOGLIO":"35","ALLEGATO":"null","SVILUPPO":"null","NUM_PART":"3077","TIPOLOGIA":"PARTICELLA"}
{"SIGLA_PROV":"PA","COD_COMUNE":"G273","DENOM":"PALERMO (PA)","SEZIONE":" ","FOGLIO":"35","ALLEGATO":"null","SVILUPPO":"null","NUM_PART":"2419","TIPOLOGIA":"PARTICELLA"}
```

**Comment by aborruso** [comment]
Ciao @pigreco con l'output che ottieni, se l'obiettivo è avere poi una tabella, puoi anche lanciare (sfruttando jq e Miller)

```
< outputCatasto2.txt | jq -s . | mlr --j2c cat
```

Ma vado alla tua domanda. Un modo è aggiunge un "a capo" con `echo`

```bash
#!/bin/bash

rm ./outputCatasto2.txt

while IFS=$'\t' read -r lon lat; do
  lon=$lon
  lat=$lat
  curl -sKL "https://wms.cartografia.agenziaentrate.gov.it/inspire/ajax/ajax.php?op=getDatiOggetto&lon=$lon&lat=$lat" >>./outputCatasto2.txt
  echo -e "\r" >>./outputCatasto2.txt
done <./input.tsv
```

**Comment by pigreco** [comment]
> Ciao @pigreco con l'output che ottieni, se l'obiettivo è avere poi una tabella, puoi anche lanciare (sfruttando jq e Miller)
> 
> ```
> <outputCatasto2.txt | jq -s . | mlr --j2c cat
> ```

@aborruso 
non capisco come usarlo :-(

**Comment by aborruso** [comment]
> > Ciao @pigreco con l'output che ottieni, se l'obiettivo è avere poi una tabella, puoi anche lanciare (sfruttando jq e Miller)
> > ```
> > <outputCatasto2.txt | jq -s . | mlr --j2c cat
> > ```
> 
> @aborruso
> non capisco come usarlo :-(

Nel trascriverti il comando l'ho scritto male, sorry.

Provalo così

```bash
#!/bin/bash

rm ./outputCatasto2.txt

while IFS=$'\t' read -r lon lat; do
  lon=$lon
  lat=$lat
  curl -sKL "https://wms.cartografia.agenziaentrate.gov.it/inspire/ajax/ajax.php?op=getDatiOggetto&lon=$lon&lat=$lat" >>./outputCatasto2.txt
done <./input.tsv

<outputCatasto2.txt jq -s . | mlr --j2c cat
```

**Comment by pigreco** [comment]
> Provalo così
> 
> ```shell
> #!/bin/bash
> 
> rm ./outputCatasto2.txt
> 
> while IFS=$'\t' read -r lon lat; do
>   lon=$lon
>   lat=$lat
>   curl -sKL "https://wms.cartografia.agenziaentrate.gov.it/inspire/ajax/ajax.php?op=getDatiOggetto&lon=$lon&lat=$lat" >>./outputCatasto2.txt
> done <./input.tsv
> 
> <outputCatasto2.txt jq -s . | mlr --j2c cat
> ```

ecco cosa mi dice

![image](https://user-images.githubusercontent.com/7631137/95010415-7c135680-0629-11eb-828e-75cb6a884bc9.png)

**Comment by pigreco** [comment]
Scusa, stamani dormo ancora, funziona!!!

**Comment by pigreco** [comment]
@aborruso 
nel mio caso ho adattato i nomi dei file

```
#!/bin/bash

rm ./outputCatasto2.txt

while IFS=$'\t' read -r lon lat; do
  lon=$lon
  lat=$lat
  curl -sKL "https://wms.cartografia.agenziaentrate.gov.it/inspire/ajax/ajax.php?op=getDatiOggetto&lon=$lon&lat=$lat" >>./outputCatasto2.txt
done <./input2.tsv

<outputCatasto2.txt jq -s . | mlr --j2c cat
```

ma ottengo una stampa a schermo:

![image](https://user-images.githubusercontent.com/7631137/95010523-458a0b80-062a-11eb-833a-9b7aa7702eff.png)


il file `outputCatasto2.txt` è :

![image](https://user-images.githubusercontent.com/7631137/95010540-6eaa9c00-062a-11eb-952c-6e9789dd922e.png)

**Comment by aborruso** [comment]
@pigreco secondo me oggi hai pensieri

Hai la stampa a schermo, perché questo c'è nel codice.
Se vuoi salvare un file, fai come sempre, ovvero usa un segno di maggiore e cambia

```
<outputCatasto2.txt jq -s . | mlr --j2c cat
```

in

```
<outputCatasto2.txt jq -s . | mlr --j2c cat >./vivatoto.csv
```
