### ISSUE TITLE
[script] da JSON a GeoJSON

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#159]
Ho molti file JSON cosi strutturati:

```
{
  "GEOMETRIA": [
    "{ \"type\": \"Polygon\", \"coordinates\": [ [ [15.260129, 37.9355868], [15.2604029, 37.9355868], [15.2604029, 37.9358597], [15.260129, 37.9358597], [15.260129, 37.9355868] ] ] }"
  ]
}
```
e ho necessità di ottenere un file leggibile da Software GIS, quindi devo convertirlo in GeoJSON.

La prova che ho fatto è la seguente, ho creato un file GeoJSON con QGIS e poi ho guardato la struttura:

```
{
"type": "FeatureCollection",
"name": "test_ORS",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [15.2656621, 37.9349878], [15.2661117, 37.9349878], [15.2661117, 37.9352813], [15.2656621, 37.9352813], [15.2656621, 37.9349878] ] ] } }
]
}
```
quindi la parte dopo `features:` la posso estrarre dal mio JSON e per farlo ho usato:

```
#!/bin/bash
set -x

mkdir -p ./rawdata

for i in $(ls *.json)
do
	 cat "$i" | jq '.[] | .[]'| sed -e "s/^\"//g" |  sed -e "s/\"$//g">./rawdata/"$i"
done
```

rimane ora ricostruire la struttura del GeoJSON, cosa che ho provato a fare così:

```
#!/bin/bash

set -x

mkdir -p ./rawdata

i1="{"type": "FeatureCollection","name":"
i2=","crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },"features": [{ "type": "Feature", "properties": { }, "geometry":"
i3="}]}"

for i in $(ls *.json)
do
	"${i1} $i ${i2}" cat "$i" | jq '.[] | .[]'| sed -e "s/^\"//g" | sed -e "s/\"$//g
done
```
ma ho il seguente errore:

![image](https://user-images.githubusercontent.com/7631137/96337223-ad5a4080-1085-11eb-98a6-6df7fff411ea.png)

**Comment by aborruso** [comment]
caro @pigreco ,
non riesco a correggere il tuo codice. 

L'ho riscritto però cercando di mantenere uno stile simile

```bash
#!/bin/bash

set -x

mkdir -p ./rawdata

i1='{"type": "FeatureCollection","name":'
i2=',"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },"features": [{ "type": "Feature", "properties": { }, "geometry":'
i3='}]}'

rm ./out-*.json

for i in $(ls *.json); do
  geom=$(cat "$i" | jq -r '.[] | .[]' | sed -e "s/^\"//g" | sed -e "s/\"$//g")
  echo -e "$i1 \"$i\"\n$i2$geom\n$i3" | jq . >./out-"$i"
done
```

L'ho provato in una cartella con un solo file json all'intenro.

**Comment by aborruso** [comment]
Una cosa sul tuo codice: manca sicuramente una virgoletta di chiusura

![image](https://user-images.githubusercontent.com/30607/96338708-41310a00-1090-11eb-8ffc-66bc327833e3.png)

**Comment by pigreco** [comment]
@aborruso 
il tuo script di sopra crea i file ma sono vuoti e osservando la shell trovo questo messaggio:
![image](https://user-images.githubusercontent.com/7631137/96339607-16e24b00-1096-11eb-805e-8a8860d28a1a.png)

allego alcuni file JSON:
[esempiJSON.zip](https://github.com/opendatasicilia/tansignari/files/5395837/esempiJSON.zip)

**Comment by aborruso** [comment]
A me funziona, appena posso testo.

Sorry

**Comment by pigreco** [comment]
@aborruso 
scusami tu, ma ora funziona
non chiedermi perché
grazie :-)

**Comment by pigreco** [comment]
@aborruso 
grazie, ricetta creata
https://tansignari.opendatasicilia.it/ricette/script/modificare_json_geojson/
