### ISSUE TITLE
Creare file .md con indice issue chiuse

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#16]
Per facilitare la ricerca di una issue e magari avere un quadro sinottico degli argomenti trattati, sarebbe utile creare un unico file (.md) con elenco (magari cronologico) delle issue.
Un posto dove raccogliere e leggere facilmente tutti i quesiti posti.

Fin a che le issue sono poche si puo' fare manualmente, ma occorrerebbe implementare uno script che faccia questo lavoro per noi.

[qui](https://github.com/opendatasicilia/tansignari/blob/WIP/in_costruzione/indice_argomenti_issue_chiuse.md) ho creato una prima bozza

**Comment by ninokeys** [comment]
perche' invece non usare github per questo? 
Abbiamo il tab issues e una ricerca filtrata. per adesso sarebbe fattibile avere un md con le issue ma al crescere si andrebbe a creare del backlog e si potrebbero anche perdere non credete?

**Comment by aborruso** [comment]
caro @pigreco, devo dire che mi ritrovo con @ninokeys la ricerca e la ricerca avanzata delle issue (https://help.github.com/articles/searching-issues-and-pull-requests/) è sicuramente meglio di qualsiasi lista fissa possiamo mettere insieme. Anche un petrusino sarebbe meno efficiente.

Perché volevi fare una lista fissa, oltre al search?

**Comment by pigreco** [comment]
Beh! mi metto nei miei panni e di chi non conosce bene GitHub: le issue chiuse non sono immediatamente visibili, la ricerca avanzata non è per tutti.
A me piacerebbe poter consultare, facilmente e rapidamente, un elenco di issue chiuse.
In alternativa occorrerebbe spiegare come effettuare le ricerche. :)

Le vostre osservazioni sono preziose e corrette.

**Comment by ninokeys** [comment]
mmm, in realta' funziona tutto in maniera intuitiva, basta cliccare sul tab chiuse che la ricerca avanzata si aggiorna (e consente di aggiungere chiavi di ricerca):

<img width="715" alt="screen shot 2019-02-15 at 19 28 34" src="https://user-images.githubusercontent.com/34175873/52879805-09095380-3158-11e9-8b69-aa7f3910636a.png">

Il mio dubbio rimane nel lungo termine, errare e' umano, e di certo qualcosa si perderebbe. Inoltre eviterei di mettere una spiegazione su questo perche altrimenti ci tocca fare il manuale di github :)
