### ISSUE TITLE
come sistemare un CSV per farlo leggere ad un GIS

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#163]
Ho un file CSV con questa struttura:

```
Layer,Text
ID_Punto,"127"
Coordinate,"1752571.62;5143346.69"
Quota,"1014.646"
ID_Punto,"126"
Coordinate,"1752553.60;5143363.05"
Quota,"1016.618"
```

vorrei ottenere:

ID_Punto | Coordinate | Quota
-----------|-------------|---------
127 | 1752571.62;5143346.69 | 1014.646
126 | 1752553.60;5143363.05 | 1016.618

grazie

**Comment by aborruso** [comment]
Ciao @pigreco ,
un modo è ad esempio questo 

```
<input.csv tail -n +2 | sed -r 's/ID_/\nID_/g;s/^(.+),(.+)$/\1 \2/;s/"//g' | mlr --x2c cat
```

Sfrutto [Miller](https://miller.readthedocs.io/en/latest/index.html) che ha come formato di input e output l'XTAB, che è fatto così

```
ID_Punto   127
Coordinate 1752571.62;5143346.69
Quota      1014.646

ID_Punto   126
Coordinate 1752553.60;5143363.05
Quota      1016.618
```

Con il comando di sopra lo porto in XTAB e poi lo converto in CSV.

**Comment by pigreco** [comment]
@aborruso 
grazie per la soluzione e soprattutto per la spiegazione 

![image](https://user-images.githubusercontent.com/7631137/98165220-c9fbd280-1ee5-11eb-925d-4c61b8354daa.png)

**Comment by pigreco** [comment]
Buongiorno @aborruso,
al file iniziale è stato aggiunto un altro campo e quindi ora risulta:

```
Layer,Text,quotag
ID_Punto,"127",964.36741
Coordinate,"1752571.62;5143346.69",964.36741
Quota,"1014.646",964.36741
ID_Punto,"126",966.33807
Coordinate,"1752553.60;5143363.05",966.33807
Quota,"1016.618",966.33807
```

ho modificato lo scriptino in :

```
<input.csv tail -n +2 | sed -r 's/ID_/\nID_/g;s/^(.+),(.+),(.+)$/\1 \2 \3/;s/"//g' | mlr --x2c cat
```

ma ottengo:

![image](https://user-images.githubusercontent.com/7631137/98214563-f3991600-1f46-11eb-886c-d72cb60123b1.png)

vorrei ottenere:

ID_Punto | Coordinate | Quota  | quotag
-----------|-------------|---------|-----------
127 | 1752571.62;5143346.69 | 1014.646 | 964.36741
126 | 1752553.60;5143363.05 | 1016.618 | 966.33807

cosa sbaglio?

**Comment by aborruso** [comment]
Ciao @pigreco 
non ci posso ragionare, quindi ti propongo una soluzione mia.

A partire da

```
Layer,Text,quotag
ID_Punto,"127",964.36741
Coordinate,"1752571.62;5143346.69",964.36741
Quota,"1014.646",964.36741
ID_Punto,"126",966.33807
Coordinate,"1752553.60;5143363.05",966.33807
Quota,"1016.618",966.33807
```

e lanciando

```
mlr --csv reshape -s Layer,Text input.csv
```

si ottiene

```
quotag,ID_Punto,Coordinate,Quota
964.36741,127,1752571.62;5143346.69,1014.646
966.33807,126,1752553.60;5143363.05,1016.618
```

È quello che serve?

**Comment by aborruso** [comment]
E con visidata è così http://youtu.be/UBAJnvt1fzU?hd=1

**Comment by pigreco** [comment]
@aborruso grazie mille, Visidata è straordinario, Miller insuperabile.

**Comment by pigreco** [comment]
ricetta fatta e pubblicata
grazie, chiudo

https://festive-bohr-4ac225.netlify.app/ricette/csv-tsv/sistemare_un_csv_per_gis/
