### ISSUE TITLE
[VisiData] come ottenere una tabella (o più tabelle) da una pagina web, usando solo vd ?

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#164]
Come posso scaricare questa tabella [0] utilizzando solo [VisiData ](https://www.visidata.org/)?

![image](https://user-images.githubusercontent.com/7631137/99191863-eca4ab80-276f-11eb-8e09-f335a8d30598.png)

ho provato cosi e sembra funzionare 😛

```
curl -kL "https://www.tuttitalia.it/regioni/popolazione/" | vd -f html +:table_0::
```

[0] https://www.tuttitalia.it/regioni/popolazione/

**Comment by aborruso** [comment]
@pigreco è come dici

Qualche nota:

- `-f html ` per impostare il formato di input;
- `+:table_0::` per scegliere quale tabella, delle tante possibili in una pagina aprire. La `0` è la prima. La sintassi completa opzionale è `+:<sheet>:<row>:<col>`
- se hai una pagina multitabella e vuoi vedere l'elenco di tutte, basta non indicarne alcuna. Ad esempio 

```
curl -kL "https://en.wikipedia.org/wiki/Olympic_medal" | vd -f html
```

Questa la issue dove è stato chiesto di introdurre questa modalità https://github.com/saulpw/visidata/issues/214#issue-383997505

**Comment by pigreco** [comment]
Osservazione:

questa stringa comando
```
curl -kL "https://www.tuttitalia.it/regioni/popolazione/" | vd -f html +:table_0::
```
restituisce, in questo caso:

![image](https://user-images.githubusercontent.com/7631137/99196414-85492480-278c-11eb-8c18-33803619af6a.png)

ma basta selezionare i campi in più e nasconderli.

**Comment by pigreco** [comment]
ricetta fatta, grazie mille

https://tansignari.opendatasicilia.it/ricette/script/scraping_tabelleweb_con_visidata/

**Comment by pigreco** [comment]
Spostata nella sezione `scraping`

https://tansignari.opendatasicilia.it/ricette/scraping/scraping_tabelleweb_con_visidata/

**Comment by aborruso** [comment]
Caro @pigreco ,
l'autore ci [ricorda](https://twitter.com/saulfp/status/1328260475839078402) che si può usare direttamente `vd` senza passare da `curl`:

```
vd "https://www.tuttitalia.it/regioni/popolazione/"  +:table_0::
```

Appena puoi, modificherei l'articolo, inserendo soltanto questa modalità

**Comment by pigreco** [comment]
@aborruso 
allora è ancora più facile WOW

ricetta modificata!
