### ISSUE TITLE
Esempio di Outer Join

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#165]
dati due file csv senza intestazione, come fare un outer join in bash

**Comment by aborruso** [comment]
In bash uso [Miller](https://github.com/johnkerl/miller) per queste cose.

Da quello che so, in realtà tu vuoi farlo con TSV. Nel caso adattare a CSV è facile.

In input hai `uno.tsv`

```
1	a
2	a
3	b
4	a
```

e `due.tsv`

```
1
4
```

e vuoi ottenere tutto ciò che non va in JOIN, ovvero


```
2       a
3       b
```


Il comando è

```
mlr --tsv --implicit-csv-header join --np  --ul  -j 1 -f uno.tsv then unsparsify due.tsv | tail -n +2
```

Note:

- `--implicit-csv-header` per assegnare un header numerico ai due TSV senza header, un header implicito (`1       2      ...`)
- `--np  --ul` per impostare un output con tutto ciò che non si accoppia in left JOIN;
- `-j 1` per usare la prima colonna dei due file, per fare JOIN

**Comment by pigreco** [comment]
@aborruso 
grazie mille, qui ricetta

https://tansignari.opendatasicilia.it/ricette/riga_comando/outer_join/

**Comment by pigreco** [comment]
@aborruso questo diagramma di piace?

![image](https://user-images.githubusercontent.com/7631137/99720306-dff4c000-2aad-11eb-8e05-3803b827fb55.png)

**Comment by aborruso** [comment]
Molto, grazie
