### ISSUE TITLE
Salvataggio file xls in csv - alcuni caratteri vengono sostituiti in un �

### ISSUE THREAD

**Issue by giuragu** [opendatasicilia/tansignari#166]
Ciao,
stavo tentando di salvare da Excel di Office 2007 in csv a partire da un xls e mi modifica i caratteri come quelli accentati in un �.
Su Libreoffice riesco e funziona. Il problema quindi lo riscontro se voglio esportare in csv da Office 2007. 

Allego un file di test dove riporto un campo con i caratteri incriminati: [test export in csv da xls.xlsx](https://github.com/opendatasicilia/tansignari/files/5589133/test.export.in.csv.da.xls.xlsx)

Come risolvere?

**Comment by aborruso** [comment]
@giuragu non ho Office.

Qui c'è una modalità, ma non so se valida su tutti gli excel https://www.youtube.com/watch?v=FVFW-dcCseU

Su libreoffice è una delle opzioni di output. Ci vuole qualcuno che ha EXCEL

![csvUTF-8](https://user-images.githubusercontent.com/30607/100083086-49c3ef80-2e49-11eb-9e20-6fca122bc526.gif)

**Comment by aborruso** [comment]
Giuseppe puoi allegare il CSV di output?

**Comment by gbvitrano** [comment]
Se il problema si pone quando apri un csv da execel la cosa si risilve facilmente.
Execel quando apre un csv applica una codifica diversa da utf-8 per ovviare a quest problema fai le seguenti semplici passaggi

1. Apri Microsoft Excel.
2. Fai clic sulla voce DATI nella barra dei menu.
3. Fai clic sull’icona “Da testo/CSV”.
4. Seleziona la posizione del file che si desidera importare. Fai clic sul nome file e quindi sul pulsante Importa. La procedura guidata per l’importazione del testo apparirà sullo schermo.
5. Scegli il tipo di file che meglio descrive i tuoi dati: larghezza delimitata o fissa.
6. Scegli  Unicode (UTF-8) dall’elenco a discesa che appare accanto a Origine file. 
7. Clicca sul pulsante Avanti per visualizzare l’Importazione guidata testo.
8. Metti un segno di spunta accanto al delimitatore utilizzato nel file che desideri importare
9. Clicca sul pulsante Avanti per visualizzare l’Importazione guidata testo.
10. Scegli il formato dati appropriato per ogni colonna di dati che desideri importare. Hai anche la possibilità di non importare una o più colonne di dati, se lo desideri.
11. Clicca sul pulsante Fine per completare l’importazione dei dati in Microsoft Excel.


[Fonte:]( https://www.evemilano.com/csv-utf8/)

**Comment by giuragu** [comment]
@aborruso su Office 2007 non trovo questa possibilità che mi mostri.
> Giuseppe puoi allegare il CSV di output?

Non mi fa allegare csv. Potrei condividerlo via gsheet ma non avrebbe senso credo.

@gbvitrano dopo il salvataggio del csv, aprendolo con Excel non da il problema. Me lo da riaprendolo con Libreoffice. 

Potresti dirmi "e cosa comporta questo problema allora?". La risposta che ti darei e ti do è questa: "devo importare il csv in APP IO per inviare messaggi in un sol colpo a più destinatari, importando da csv appunto. E APP IO mi trasforma i caratteri pure lei come Libreoffice.

**Comment by aborruso** [comment]
> Non mi fa allegare csv. Potrei condividerlo via gsheet ma non avrebbe senso credo.

Basta che lo zippi e lo metti qui

**Comment by giuragu** [comment]
> Basta che lo zippi e lo metti qui

scarso sono io 
[test.export.in.csv.da.zip](https://github.com/opendatasicilia/tansignari/files/5590189/test.export.in.csv.da.zip)

**Comment by aborruso** [comment]
giu se il problema è riaprirlo in libreoffice, basta usare i parametri giusti 

![image](https://user-images.githubusercontent.com/30607/100102100-6c630200-2e63-11eb-9cd2-1cdd0f384536.png)

**Comment by gbvitrano** [comment]
@giuragu non sono errori è solo un problema di codici, window salva il file in windows (ansi), quano lo apri in libreoffice lo devi aprire con lo stesso codice, che trovarai nella tendina, in libreoffice lo apri con il codice di sistema

![immagine](https://user-images.githubusercontent.com/20488693/100102121-71c04c80-2e63-11eb-85d8-45492af6a6bd.png)

**Comment by giuragu** [comment]
Grazie @aborruso e @gbvitrano!
Ho capito. Problema risolto per riaprire in Libreoffice e penso di aver intuito come fare per APP IO.

**Comment by aborruso** [comment]
Ma è mai possibile che office 2007 non abbia la possibilità di impostare l'encoding di output??
Purtroppo sembra che sia così

**Comment by giuragu** [comment]
Abbiamo risolto con @aborruso 
In pratica una soluzione è la seguente:

- Salvare il file da Excel in csv;
- Aprire il file con un editor (es.: Notepad++), qui selezionare Formato > Converti in UTF-8, quindi salvare.

Il nostro file a quel punto sarà aperto con caratteri corretti anche da Libreoffice in UTF-8 e  nel caso specifico pronto correttamente per invio su APP IO

@aborruso il video non l'ho fatto per il momento per questioni di tempo. Lo farò :)

**Comment by aborruso** [comment]
La cosa assurda è che EXCEL 2007 sembra non in grado di esportare in UTF-8, nonostante a schermo si scelga di farlo

**Comment by aborruso** [comment]
@giuragu mettiti un segnaposto, per il video :)

**Comment by giuragu** [comment]
> @giuragu mettiti un segnaposto, per il video :)

in che senso @aborruso ?

**Comment by aborruso** [comment]
> @aborruso il video non l'ho fatto per il momento per questioni di tempo. Lo farò :)

Così è più chiaro @giuragu ? :)

**Comment by giuragu** [comment]
> > @aborruso il video non l'ho fatto per il momento per questioni di tempo. Lo farò :)
> 
> Così è più chiaro @giuragu ? :)

Si :D

**Comment by aborruso** [comment]
Chiudo, è passato troppo tempo
