### ISSUE TITLE
[CSV] un modo elegante per duplicare le righe e appendere nello stesso file

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#167]
Ho l'esigenza di duplicare (triplicare ecc...) le righe di un  file CSV e accodarle all'esistente, qui un esempio:

file di partenza:

```
a,b,c,d
1,2,3,4
5,6,7,8
```
file di output dopo duplicazione:

```
a,b,c,d
1,2,3,4
5,6,7,8
1,2,3,4
5,6,7,8
```
esiste un modo elegante di farlo ed evitare di aprire il file CSV e fare un copia ed incolla (una volta per duplicare e due volte per triplicare)??

**Comment by aborruso** [comment]
Caro @pigreco ,
via script, associ un id e poi fai un for loop per id.

Via utility, ad esempio [Miller](https://github.com/johnkerl/miller), è

```
mlr --csv repeat -n 3 ./input.csv
```

Dove `-n` è il numero di volte

```
a,b,c,d
1,2,3,4
1,2,3,4
1,2,3,4
5,6,7,8
5,6,7,8
5,6,7,8
```

**Comment by pigreco** [comment]
@aborruso , grazie!

ricetta fatta e pubblicata
https://tansignari.opendatasicilia.it/ricette/csv-tsv/duplicare_righe_appenderle/
