### ISSUE TITLE
Come ottenere operatore IN fuori da ambiente SQL

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#169]
Ho la necessita di filtrare dei dati strutturati come i CSV usando l'operatore `IN` ;
in ambiente SQLite è facilissimo ecco un esempio:

```sql
SELECT "id", "CODICE", "foglio", "prov", "cod_com"
FROM "nomeTabella"
WHERE "foglio" IN (20,21,22)
```
come potrei fare usando la riga di comando (per esempio in VisiData o/e Miller)?

id|NUM_PART|foglio|prov|cod_com
--|------|--------|------|----
43|49|21|PA|Axxx
44|51|21|PA|Axxx
45|54|21|PA|Axxx
46|55|20|PA|Axxx
47|58|20|PA|Axxx
48|61|22|PA|Axxx
49|62|1|PA|Axxx
50|63|10|PA|Axxx
51|65|1|PA|Axxx
52|66|11|PA|Axxx
53|68|1|PA|Axxx

**Comment by pigreco** [comment]
In VisiData ho capito come fare utilizzando i `regex` in questo modo:

posiziono il focus sulla colonna `foglio`, digito ` |` (che serve a selezionare tramite regex) e come regex: `(20|21|22)
funziona benissimo

**Comment by aborruso** [comment]
> posiziono il focus sulla colonna `foglio`, digito ` |` (che serve a selezionare tramite regex) e come regex: `(20|21|22)`

E come ti è venuto in mente :D :D ??

In Miller è molto simile. Se hai

```
name,amt,tax1,tax2
producta,$50.00,$2.50,$4.50
productb,$60.00,$3.00,$5.40
productc,$70.00,$3.50,$6.30
productd,$80.00,$4.00,$7.20
producte,$90.00,$4.50,$8.10
```

E vuoi filtrare soltanto `producta` e `producte` puoi scrivere

```
mlr --csv filter '$name=~"(producta|producte)"' input.csv
```

Sempre regex

**Comment by pigreco** [comment]
@aborruso 
con il file CSV di sopra (allego [test.txt](https://github.com/opendatasicilia/tansignari/files/5681004/test.txt)), il comando:

```
mlr --csv filter '$foglio=~"(20|21|22)"' test.txt
Expression does not evaluate to boolean: got MT_ERROR.
```

**Comment by aborruso** [comment]
Devi aggiungere "-S" dopo filter, perché usi regex su un campo numerico.
Con questa opzione lo forzi a stringa

**Comment by pigreco** [comment]
@aborruso 
grazie mille, ora funziona

```
 mlr --csv filter -S '$foglio=~"(20|21|22)"' test.csv
```

e restituisce:

```
id,NUM_PART,foglio,prov,cod_com
43,49,21,PA,Axxx
44,51,21,PA,Axxx
45,54,21,PA,Axxx
46,55,20,PA,Axxx
47,58,20,PA,Axxx
48,61,22,PA,Axxx
```

**Comment by pigreco** [comment]
Grazie mille @aborruso 
ho scritto e pubblicato ricetta

https://tansignari.opendatasicilia.it/ricette/csv-tsv/operatore_in_no_sql/

**Comment by aborruso** [comment]
grazie @pigreco farei una piccola modifica

Se il tuo input è fatto così

```
id,NUM_PART,foglio,prov,cod_com
43,49,21,PA,Axxx
44,51,21,PA,Axxx
440,54,21,PA,Axxx
```

vuoi estrarre id 43 e 44 e usi come regex `(43|44)`, estrarresti anche `440`. Se deve essere uguale all'operatore `IN` che confronta la stringa con il contenuto dell'intera cella, e quindi estrarre soltanto 43 e 44, devi modificare la regex in `^(43|44)$`.

**Comment by pigreco** [comment]
@aborruso 
giusta osservazione, ho aggiunto le modifiche

https://regex101.com/r/adgRHj/1
