### ISSUE TITLE
[bash] come dividere un file CSV usando i valori univoci di un suo campo

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#170]
Ho questo [file CSV](https://raw.githubusercontent.com/IlSole24ORE/QDV/main/20201214_QDV2020_001.csv) con otto campi

```
"NOME PROVINCIA (ISTAT)","CODICE NUTS 3 2021","CODICE PROVINCIA ISTAT (STORICO)","DENOMINAZIONE CORRENTE","VALORE","INDICATORE","UNITA' DI MISURA","RIFERIMENTO TEMPORALE","FONTE ORIGINALE"
```
e devo dividerlo secondo i valori presenti nel sesto campo `INDICATORE`, in modo da ottenere 90 file CSV distinti, uno per ogni valore univoco del campo.

Ho fatto alcune [ricerche](https://stackoverflow.com/questions/30900331/how-to-split-a-csv-file-into-multiple-files-based-on-column-value), ma non trovo nulla di utile se non questo ciclo `while` ma ottengo degli output errati e mi segnale `-bash: ${f}.csv: ambiguous redirect`

```
 while IFS="," read -r a b c d e f g; do echo "$a,$b,$c,$d,$e,$f,$g" >> ${f}.csv; done <qdv.csv
```
dove sbaglio nel ciclo while? esiste una soluzione più elegante?

**Comment by aborruso** [comment]
caro @picomiles , per casi come questo uso Miller.

Nel file di input, nei valori del campo `INDICATORE` ci sono caratteri che possono dare fastidio ai nomi di file nella shell. Detto questo puoi fare così:

```
mlr --csv put '$INDICATORE=gsub($INDICATORE,"/","-")' input.csv | mlr  --csv  put -q 'tee > $INDICATORE.".csv", $*'
```

Note:

- prima rimuovo da `INDICATORE` il carattere `/` e lo sostituisco con `-`;
- poi sfrutto il verbo [`tee`](https://miller.readthedocs.io/en/latest/reference-verbs.html#tee) di Miller, che creerà dei file di output filtrando su valori di `INDICATORE` distinti.

**Comment by pigreco** [comment]
@aborruso funziona perfettamente:

![image](https://user-images.githubusercontent.com/7631137/102192919-b1ef7980-3ebb-11eb-8af6-8f88630555dc.png)

**Comment by pigreco** [comment]
@aborruso 
ricetta fatta
https://tansignari.opendatasicilia.it/ricette/bash/dividere_csv_valori_univoci/
