### ISSUE TITLE
[ISTAT] dataset con oltre 3 milioni di righe

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#171]
L'ISTAT ha reso disponibile [0] i dati sulla popolazione residente per  sesso ed età in un file CSV con oltre 3 milioni di righe (oltre 640 Mb) ed è impossibile da gestire con Excel o altri programmi con gui;

Come estrarre i dati salienti come popolazione totale suddivisa per: **comuni**, **province** e **regioni**? 

il dataset ISTAT ha i seguenti campi:

name|value
----|-----
ITTER107|ITC12
Territorio|Vercelli
TIPO_DATO_CENS_POP|RESPOP_MIN_AV
Tipo dato|popolazione residente fino a 17 anni
SEXISTAT1|M
Sesso|maschi
ETA1|Y_UN17
Classe di etÃ |fino a 17 anni
STATCIV2|ALL
Stato civile|totale
CITTADINANZA|ITL
Cittadinanza|italiano-a
ISO|ALL
Area geografica e paesi di cittadinanza|tutte le voci
PROV_DEST_Z|ALL
Luogo di dimora abituale 1 anno prima rispetto alla dimora attuale|tutte le voci
TIME|2018
Seleziona periodo|2018
Value|10651
Flag Codes|
Flags|

sarebbe bello ottenere solo questi campi (per tre file `Comuni`, `Province` e `Regioni`; per gli anni 2018 e 2019):

name|value
----|-----
ITTER107|ITC12
Territorio|Vercelli
TIME|2019
Value|10651

[0] https://esploradati.censimentopopolazione.istat.it/databrowser/#/it/censtest/BULKDOWNLOAD

**Comment by pigreco** [comment]
In pratica occorrerebbe una query che restituirebbe i campi

name|value
----|-----
ITTER107|ITC12
Territorio|Vercelli
TIME|2019
Value|10651

e  con condizione WHERE

campo | valore
--------|-------
ETA1 | TOTAL
CITTADINANZA | TOTAL
Tipo di dato | popolazione residente
Sesso | totale

questo restituirebbe un dataset leggero e facile da aggregare successivamente in Comuni, province e regioni

**Comment by aborruso** [comment]
Ciao @pigreco uno strumento a riga di comando, ottimo per questi filtri su file CSV grossi è [xsv](https://github.com/BurntSushi/xsv)

Il comando che puoi lanciare è

```
xsv search -d "|" -s ETA1 '^TOTAL$' Caratteristiche\ demografiche\ e\ cittadinanza\ -\ intero\ ds.csv | xsv search -s CITTADINANZA '^TOTAL$' | xsv search -s Sesso '^totale$' | xsv search -s 'Tipo dato' '^popolazione residente$' >./output.csv
```

Nota: con `-d` imposti il separatore di campo.

Poi il resto sono comandi a cascata, con i vari filtri sui campi, usando espressioni regolari.

In output un umano e gestibile file da 16000 righe

**Comment by pigreco** [comment]
@aborruso 
veramente veloce, in tre secondi ottengo l'output, veramente notevole!

Ecco un esempio di estrazione dati, popolazione residente 2019 ripartizione geografica:

ID|ITTER107|Territorio|TIME|Value
--|--------|----------|----|----
1|ITC|Nord-ovest|2019|15988679
2|ITD|Nord-est|2019|11627537
3|ITE|Centro|2019|11831092
4|ITF|Sud|2019|13707269
5|ITG|Isole|2019|6486911

**Comment by pigreco** [comment]
OSSERVAZIONE:
1. da questo [sito ISTAT](http://dati.istat.it/Index.aspx?DataSetCode=DCIS_POPRES1#) i dati non corrispondono
![image](https://user-images.githubusercontent.com/7631137/102537200-f12fed00-40aa-11eb-8277-fe4a575ef776.png)

2. 2. da questo [sito ISTAT](http://dati-censimentipermanenti.istat.it/#) i dati sono uguali:
![image](https://user-images.githubusercontent.com/7631137/102537184-ec6b3900-40aa-11eb-83d2-931c4bd233e5.png)

**Comment by aborruso** [comment]
Sono due censimenti diversi.
Leggendo la documentazione immagino troverai il perché.

**Comment by pigreco** [comment]
Per visualizzare solo alcuni campi, il comando di sopra diventa:

```
xsv search -d "|" -s ETA1 '^TOTAL$' Caratteristiche\ demografiche\ e\ cittadinanza\ -\ intero\ ds.csv | xsv search -s CITTADINANZA '^TOTAL$' | xsv search -s Sesso '^totale$' | xsv search -s 'Tipo dato' '^popolazione residente$' | xsv select ITTER107,Territorio,TIME,Value>./output2.csv
```

ovvero basta usare:

```
xsv select ITTER107,Territorio,TIME,Value
```

**Comment by pigreco** [comment]
Per avere i CSV per suddivisione territoriale:

- ripartizione geografica:

```bash
 xsv search -d "|" -s ETA1 '^TOTAL$' Caratteristiche\ demografiche\ e\ cittadinanza\ -\ intero\ ds.csv \
 | xsv search -s CITTADINANZA '^TOTAL$' \
 | xsv search -s Sesso '^totale$'  \
 | xsv search -s 'Tipo dato' '^popolazione residente$' \
 | xsv search -s 'ITTER107' '^IT.$'  \
 | xsv search -s 'TIME' '2019' \
 | xsv select ITTER107,Territorio,TIME,Value>./pop_res_ISTAT19_rip.csv
```

- regioni:

```bash
 xsv search -d "|" -s ETA1 '^TOTAL$' Caratteristiche\ demografiche\ e\ cittadinanza\ -\ intero\ ds.csv \
 | xsv search -s CITTADINANZA '^TOTAL$' \
 | xsv search -s Sesso '^totale$'  \
 | xsv search -s 'Tipo dato' '^popolazione residente$' \
 | xsv search -s 'ITTER107' '^IT..$'  \
 | xsv search -s 'TIME' '2019' \
 | xsv select ITTER107,Territorio,TIME,Value>./pop_res_ISTAT19_reg.csv
```

- province:

```bash
 xsv search -d "|" -s ETA1 '^TOTAL$' Caratteristiche\ demografiche\ e\ cittadinanza\ -\ intero\ ds.csv \
 | xsv search -s CITTADINANZA '^TOTAL$' \
 | xsv search -s Sesso '^totale$'  \
 | xsv search -s 'Tipo dato' '^popolazione residente$' \
 | xsv search -s 'ITTER107' '^IT...$'  \
 | xsv search -s 'TIME' '2019' \
 | xsv select ITTER107,Territorio,TIME,Value>./pop_res_ISTAT19_prov.csv
```

- comuni:

```bash
 xsv search -d "|" -s ETA1 '^TOTAL$' Caratteristiche\ demografiche\ e\ cittadinanza\ -\ intero\ ds.csv \
 | xsv search -s CITTADINANZA '^TOTAL$' \
 | xsv search -s Sesso '^totale$'  \
 | xsv search -s 'Tipo dato' '^popolazione residente$' \
 | xsv search -s 'ITTER107' '^(?!IT).*'  \
 | xsv search -s 'TIME' '2019' \
 | xsv select ITTER107,Territorio,TIME,Value>./pop_res_ISTAT19_com.csv
```

**Comment by pigreco** [comment]
@aborruso 
grazie per tutto
ricetta fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/bash/estrarre_dati_da_csv_enormi/
