### ISSUE TITLE
[generico] spostare gruppi di file all'interno di cartelle specifiche

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#172]
Ho una cartella con oltre 6000 file, il nome del file tipico è cosi fatto:

`abcdef-ghiefg-cucu.svg`

per ogni prefisso (`abcdef`) ho `n` file, come posso spostare questi gruppi di file che hanno stesso prefisso all'interno di una cartella con nome uguale al prefisso? (naturalmente dovrei creare anche le cartelle.

ecco un esempio con prefisso `google`
![image](https://user-images.githubusercontent.com/7631137/103694488-53d62380-4f9b-11eb-861e-e949bce6e405.png)

dovrei creare una cartella `google` e spostare tutti i file all'interno.

altro esempio con prefisso `apple`
![image](https://user-images.githubusercontent.com/7631137/103694738-c0512280-4f9b-11eb-9c28-c949917b8c7a.png)

qui la cartella con tutti i file:
https://t.co/fe7gXfW1VH?amp=1

**Comment by aborruso** [comment]
Ciao @pigreco che prove hai già fatto? Cosa non funziona?

**Comment by pigreco** [comment]
> Ciao @pigreco che prove hai già fatto? Cosa non funziona?

@aborruso , ho estratto la lista dei prefisso usando visidata, qui un estratto:

```
youtube
zip
xamarin
zodiac
xing
xml
xmpp
y
yahoo
yeast
yin
yoga
yurt
zend
zigbee
```

per creare le cartelle:

```
#!/bin/bash

set x

for i in $(cat prefisso.csv);do
	mkdir $i
done
```
ma non capisco perché mette un puntino alla fine del nome cartella:

![image](https://user-images.githubusercontent.com/7631137/103750347-f5468f00-5006-11eb-83b2-e94e747b6e9d.png)

**Comment by pigreco** [comment]
@aborruso ,
ho capito il motivo del puntino a fine nome cartella, deriva dal fatto che visidata ha creato un file  `CR+LF` invece che `LF`.

**Comment by pigreco** [comment]
...infine, sembra funzionare:

```bash
#!/bin/bash

set x

for i in $(cat prefisso.csv);do
	mkdir -p $i
	cp $i*.svg ./$i
done
```

**Comment by pigreco** [comment]
devo capire come creare il file dei prefissi con `sed`

**Comment by aborruso** [comment]
> devo capire come creare il file dei prefissi con `sed`

Che test hai fatto con sed? Cosa non ti funziona? Come gli passi l'elenco delle cartelle?

**Comment by pigreco** [comment]
> Che test hai fatto con sed? Cosa non ti funziona? Come gli passi l'elenco delle cartelle?

ho lanciato questo dalla cartella che contiene tutti i file *svg

` ls | sed 's/^(\w+).+$/1/g'`

ma  praticamente non estrae nulla, visualizza la lista di partenza

https://regex101.com/r/BJ3Rjn/1/

**Comment by pigreco** [comment]
forse ci sono, ma questo comando estrae ma la lista è raddoppiata:

`ls | sed -E 's/^(\w+).+$/\1/g`

**Comment by aborruso** [comment]
caro @pigreco per usare regex in sed devi usare `-r`.


Con questo input

```
a-1 - Copia (2).svg
a-1 - Copia (3).svg
a-1 - Copia.svg
a-1.svg
b-1 - Copia (2).svg
b-1 - Copia.svg
b-1.svg
```

e con questo comando

```
sed -r 's/-.*//g'
```

avresti

```
a
a
a
a
b
b
b
```

che con `sed -r 's/-.*//g' | sort | uniq` diventa

```
a
b
```

**Comment by pigreco** [comment]
grazie @aborruso 
funziona anche così

`ls *.svg | sed -E 's/^(\w+).+$/\1/g' | uniq`

**Comment by aborruso** [comment]
Sono regex funziona sempre in mille modi

**Comment by pigreco** [comment]
@aborruso ho provato la tua espressione con i miei dati:

![image](https://user-images.githubusercontent.com/7631137/103755616-66d60b80-500e-11eb-82b4-285562534f95.png)

non va!

**Comment by aborruso** [comment]
@pigreco e che mi cunti :) ??

Ti ho fatto l'esempio con il mio input. Per darti una cosa di senso e poi fare fare a te adattamento.ù

Mi incolli per favore qualche riga di input dei tuoi?

**Comment by pigreco** [comment]
caro @aborruso , ti cuntu che non va con i miei dati, ma ho capito il ragionamento ed è la cosa importante.

Grazie! :-)

**Comment by pigreco** [comment]
ecco lo scriptino

```
#!/bin/bash
set x

# lista i file *.svg, estrae il prefisso e crea file 
ls *.svg | sed -E 's/^(\w+).+$/\1/g' | uniq >prefisso.csv

# ciclo per creare le cartelle e copiare i file
for i in $(cat prefisso.csv);do
	mkdir -p $i
	cp $i*.svg ./$i
done
```

**Comment by pigreco** [comment]
ricetta fatta e pubblicata.

https://tansignari.opendatasicilia.it/ricette/bash/creare_cartelle_da_file/
