### ISSUE TITLE
Richiesta di aiuto per recupero dati su Disabilità e Caregiver Familiari

### ISSUE THREAD

**Issue by AntonioDEM** [opendatasicilia/tansignari#173]
Buongiorno, mi chiamo Antonio Demarcus, sono Caregiver Familiare, studente nell'Università di Ingegneria di Cagliari e appartengo al Gruppo Operativo di [CONFAD](https://www.confad.eu) - Coordinamento Nazionale Famiglie con Disabilità. 

In particolare per Confad mi occupo del tema [Caregiver Familiari Universitari](https://tinyurl.com/y3bnx2aj) di cui potete ascoltare un intervento, della gestione del [canale Youtube](https://tinyurl.com/y9nypsex) e della ricerca di dati che ci aiutino a spiegare meglio le condizioni che sotto vi esporrò.

Qualche giorno fà, mandai su telegram un messaggio al nostro caro amico @pigreco - Totò Fiandaca e su twitter ad @aborruso , facendo loro richiesta per un aiuto mirato al recupero di alcuni dati ISTAT o INPS che non riesco a trovare. Totò mi ha chiesto di inserire una richiesta su opendatasicilia. 

Come sappiamo l'Open Data in Italia e non solo, in molto casi si rivela solamente una grande fantasia. Spesso l'Amministrazione Pubblica e gli istituti quali ISTAT, INPS, INAIL, Regioni e altri, ci mettono a disposizione solamente dati parziali, spesso mal confezionati, non corretti e spesse volte non mettono a disposizione dati potenzialmente utili.

Nel caso particolare della mia richiesta, CONFAD (sopratutto oggi con il COVID-19) ha necessità di avere dati sulla distribuzione delle **PERSONE con Disabilità** in Italia e nella regioni regioni italiane. Perchè?

Perché CONFAD si occupa e si preoccupa di portare avanti **la causa** che riguarda sia l**e tutele** che **la dignità** che dovrebbero ricevere le **persone con Disabilità** tutte, sia l**e tutele** che **la dignità** che dovrebbe essere riconosciuta ai **Caregiver Familiari**.

***********************************************************************************************
**Chi è Caregiver Familiare?**
Il Caregiver Familiare è una mamma, un papà, un figlio, una figlia, un fratello o una sorella che fa un gesto di amore e di responsabilità, decidendo di accudire a casa propria, un parente (figlio/figlia, fratello/sorella, genitore, zia/o) in condizioni di disabilità grave e non autosufficienza.
***********************************************************************************************

Come si evince da questa definizione, il Caregiver Familiare è una **figura Universale** che si occupa della tutela una persona affetta da grave disabilità (la Disabilità stessa è un tema Universale), alla quale è stata assegna dall'INPS sia l'**invalidità al 100%** che la **104 art.3 comma3**.

Purtroppo lo Stato considera i Caregiver Familiari, come dei FANTASMI che fanno risparmiare ogni anno all'ammirazione pubblica milioni di euro, scaricando ogni tipo di responsabilità su su di noi. Ma non voglio dilungarmi troppo.

Dopo questa doverosa e forse troppo lunga premessa, passo alla richiesta:

Vi chiedo la cortesia di aiutarmi, se possibile, a recuperare dei set di dati ISTAT o INPS in cui siano presenti le distribuzioni regionali e nazionali riguardanti le persone con disabilita. Il set di dati potrebbe essere cosi fatto: 

       |Regione|Provincia|Località|Tipo di Disabilità|Età|Grado Di Disabilità| 104 art3 comma1|104 art3 comma3|status|

- grado di disabilità <100%
- grado di disabilità > 100%  - no 104 art3 comma3 o comma1
- grado di disabilità > 100% - si 104 art3 comma1 
- grado di disabilità > 100% - si 104 art3 comma3
- età : maggiorenne, minorenne;
- tipo: disabilità dalla nascita, mentale, neurologica, linfoma, cancro, psicologica, distrofia muscolare ....etc etc
- status: ex lavoratore/trice, studente/ssa, pensionato....;

potrebbero essere presenti anche altri articoli riguardanti i vari livelli o tipi di disabilità.

Perché abbiamo necessità di questi dati?

per tre motivi principali:

1. Ad ogni persona con disabilità grave - gravissima (grado di disabilità > 100% - si 104 art3 comma3) corrisponde (o dovrebbe) nella gran parte dei casi un Caregiver Familiare; Questo dato ci consentirebbe di conoscere la distribuzione dei Caregiver Familiari in Italia e nelle regioni e com'e la loro concentrazione locale all'interno delle singole regioni.
2. Conoscere Età e il Tipo di Disabilità ci consentirebbe di sapere quante persone con disabilità sono figli e quindi capire le enormi difficoltà genitoriali causate dall'abbandono di Stato (riguardante non solo la scuola) in questo lungo periodo COVID, cosi anche per le persone anziane.
3. Questi dati sono estremamente utili per metterli davanti alla politica nazionale e regionale e quindi rafforzare la richiesta per una legge di tutela a favore dei Caregiver Familiari.

Probabilmente in questo momento mi sta sfuggendo qualche particolare, sicuramente più dati abbiamo, più l'analisi può essere approfondita e puntuale.

Ringraziandovi infinitamente per aver ospitato la mia richiesta su opendatasicilia, spero vivamente possiate darci una mano a recuperare e ad analizzare questi preziosi dati, creando delle carte sintetiche e puntuali come quelle che produce @pigreco (Salvatore Findaca), che siano utili ad una **Causa Universale** quale quella della **Disabilità** e dei **Caregiver Familiari**

Ringraziandovi nuovamente, cordialmente

Antonio Demarcus

**Comment by aborruso** [comment]
Ciao @AntonioDEM e benvenuto.

Su questo tipo di dati non ho esperienza, quindi non ho una risposta pronta e semplice. 

Spesso nelle azioni sui dati che porto avanti con la mia associazione ci muoviamo su dati che sappiamo esistere, di cui sappiamo chi è il gestore, e che magari sono visibili e pubblici, ma non in forma di dati. Qui non ho idea di nulla.

Ti faccio subito una domanda: nelle ricerche che avrai già fatto, che dati hai trovato? Quali sono gli URL? Cosa manca?

Quali PA raccolgono questi dati? 

Grazie

**Comment by AntonioDEM** [comment]
Ciao @aborruso e grazie per la pronta risposta. 

Ho fatto delle ricerche più tosto generiche su google tipo: database disabili Istat ( Inps),  banca dati disabili Istat ( Inps). Non sono molto esperto nella ricerca di questo di dati, anche per me è un campo nuovo ed è soprattutto Bper questo che chiedo aiuto a te e @pigreco , essendo sicuramente più esperti di me anche nella ricerca.

Per quanto riguarda le PA: 
Questa tipologia di dato provengono:
1) dall' INPS, in quanto é l'INPS che assegna i gradi di invalidità e che conosce tutti gli aspetti del disabile. 

2) i comuni devo per forza avere dei dati in merito perché nei comuni viene fatta ad esempio la richiesta per
  - usufruire della 162/98 e leggi di settore;
  - ai vigili tagliando invalidi permanente;

3) Ospedali, perché appunto sono i medici della ASL che certificano il primo stato di invalidità del paziente che in seguito verrà analizzato dalle commissioni INPS;

4) i medici di base, perché fanno le richieste per l'accesso alla commissione Inps;

5) i CAF che inoltrano le richieste del medico di base, ma in alcune occasioni seguono il disabile o il Careviver per ulteriori richieste

6) ISTAT : perché fa i report

https://www.istat.it/it/archivio/disabili

E come fa a fare i report senza dati? E dove sono questi dati spuri?

**Comment by aborruso** [comment]
Ciao @AntonioDEM ,
a questi dati di ISTAT possiamo accedere. Sono di interesse?

|iddataflow  |descrizione                                                   |iddatastructure  |URL                                                         |
|------------|--------------------------------------------------------------|-----------------|------------------------------------------------------------|
|159_17     |Alunni con disabilità                                         |DCIS_ALUNNIDIS  |http://dati.istat.it/Index.aspx?DataSetCode=DCIS_ALUNNIDIS|
|159_18     |Scuole con alunni con disabilità e figure per l'integrazione  |DCIS_SCUOLEDIS  |http://dati.istat.it/Index.aspx?DataSetCode=DCIS_SCUOLEDIS|
|56_77      |Servizi per gli alunni con disabilità                         |DCIS_SANSCUOLE  |http://dati.istat.it/Index.aspx?DataSetCode=DCIS_SANSCUOLE|

**Comment by aborruso** [comment]
Ok, chiudo, è passato troppo tempo senza riscontri

**Comment by AntonioDEM** [comment]
> Ok, chiudo, è passato troppo tempo senza riscontri

Ciao @aborruso scusa per non aver dato riscontri. ho scritto anche ad ISTAT e i dati sono sempre questi. Purtroppo per quanto le università non si sa niente o si sta appena iniziando a capire che esistono studenti caregiver. Notizia tristissima ma reale. Inoltre per quanto riguarda gli studenti con disabilità ISTAT non tiene conto nelle sue tabelle degli studenti universitari, che usufruiscono di un sistema totalmente diverso da quello utilizzato nelle scuole primarie, medie e superiori. chissà che nel prossimo millennio arriveremo a inquadrare meglio le cose. Ti ringrazio comunque molto per l'aiuto e per la pazienza.

**Comment by aborruso** [comment]
@AntonioDEM grazie a te. A me dispiace non essere stato d'aiuto, ma confesso di avere compreso molto; colpa mia
