### ISSUE TITLE
[bash] errore di sintassi

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#174]
Ho realizzato questo script, usando [Miller ](https://miller.readthedocs.io/en/latest/index.html)ma ottengo risultati errati sicuramente legati alla sintassi (non ho errore, ma risultati errati).

Lo script è:

```bash
#!/bin/bash

set -x

# variabili con numero fogli
M011="15|25|33|50"
F900="10|22|30"

# filtra per codice e per numeo fogli, ragguppa e conta
mlr --csv filter -S '($foglio=~($M011) && $cod_com=="M011") || ($foglio=~($F900) && $cod_com=="F900")' /
then uniq -c  -g cod_com,foglio,NUM_PART then cut -f cod_com then count -o nro_particelle -g cod_com / 
EN-M011-particelle.csv EN-F900-particelle.csv
```

output con valori errati:

![image](https://user-images.githubusercontent.com/7631137/105586163-31ad1580-5d91-11eb-8781-b2cf0346e689.png)

valori attesi:

![image](https://user-images.githubusercontent.com/7631137/105586838-615c1d80-5d91-11eb-8f36-47f25dc0abec.png)

**Comment by aborruso** [comment]
Caro @pigreco , alcune note, concentrandomi su un esempio minimo:

- una variabile esplode tra virgolette, tra virgolette

da `'$foglio=~($M011)'` a `'$foglio=~("$M011")'`

- un variabile non esplode mai tra apici singoli

da `'$foglio=~("$M011")'`, ne fai l'escape `'$foglio=~('"$M011"')'`

- la condizione da verificare in Miller la devi mettere tra virgolette

da `'$foglio=~"('"$M011"')"'`

**Comment by pigreco** [comment]
caro @aborruso, finalmente funziona, grazie

```bash
#!/bin/bash

set -x

# variabili con numero fogli
M011="15|25|33|50"
F900="10|22|30"

# filtra per codice e per numeo fogli, ragguppa e conta
mlr --csv filter -S '($foglio=~"('"$M011"')" && $cod_com=="M011") || ($foglio=~"('"$F900"')" && $cod_com=="F900")' /
then uniq -c  -g cod_com,foglio,NUM_PART then cut -f cod_com then count -o nro_particelle -g cod_com / 
EN-M011-particelle.csv EN-F900-particelle.csv
```
ecco output corretto:
![image](https://user-images.githubusercontent.com/7631137/105607190-baca4980-5d9d-11eb-888c-436e20dcb8be.png)

**Comment by pigreco** [comment]
@aborruso la chiudo, non credo sia utile una ricetta
