### ISSUE TITLE
ffmpeg convertire una gif in mp4

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#176]
Per convertire una gif in video mp4 ho usato:

```
ffmpeg -f gif -i infile.gif outfile.mp4 
```
il tutto va in porto, ma se condivido il video mp4 su telegram riesco a vederlo da PC (Telegram desktop) ma non da cellulare.

questa è la gif:

![atlas_multi_foto](https://user-images.githubusercontent.com/7631137/109856799-300d2200-7c5a-11eb-83cb-6c12df09c3cc.gif)

questo è il file mp4

https://user-images.githubusercontent.com/7631137/109856857-45824c00-7c5a-11eb-87df-72764483e589.mp4

![image](https://user-images.githubusercontent.com/7631137/109857066-89755100-7c5a-11eb-8739-8d0d69466707.png)

## allego gif zippata
[atlas_multi_foto.zip](https://github.com/opendatasicilia/tansignari/files/6078459/atlas_multi_foto.zip)

**Comment by aborruso** [comment]
Su telegram devi inviare direttamente il file mp4 che verrà convertito in
gif.

Invialo a me per prova

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il mer 3 mar 2021, 19:58 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
chiudo perché problema già risolto qui:

https://github.com/opendatasicilia/tansignari/issues/107

grazie e scusate per il rumore :-)

**Comment by pigreco** [comment]
per togliere ogni traccia audio

```
ffmpeg -i input_file.mp4 -vcodec copy -an output_file.mp4
```
