### ISSUE TITLE
Caricare file immagine in .block di gist.github

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#177]
Buona sera, ho scoperto da poco i .block di gist.github, aggiungere più file testuali al gist è molto semplice, ma aggiungere un file immagine e po complicato, almeno per me. Ho provato con github desktop e con git gui, ma il commit non va buon fine.

**Come si caricano le immagini in un gist?**

**Comment by aborruso** [comment]
Caro Gianni,
io uso un'estensione molto comoda di visual studio:
https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs

Notte

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il gio 18 mar 2021, 23:52 Giovan Battista Vitrano ***@***.***>
ha scritto:

**Comment by gbvitrano** [comment]
Grazie grazie  adesso è tutto più semplice :-)
