### ISSUE TITLE
query per overpass-turbo per ottenere un file geojson con l'individuazione delle caserme

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#178]
come si fa un interrogazione a [overpass-turbo](https://overpass-turbo.eu/) di OSM per chiedere un file formato geojson delle **caserme** di Palermo? 
Vorrei capire l'esatta sintassi per la query.

**Comment by cirospat** [comment]
ho studiato questa ricetta:
https://tansignari.opendatasicilia.it/ricette/mappe/estrarre_punti_di_interesse_da_osm/
ma non capisco

**Comment by aborruso** [comment]
Caro @cirospat stai entrando in un mondo grosso e ricco.
È possibile che non ci sia un modo rapido e immediato per arrivare al tuo goal. 

Un elemento di base è entrare un po' dentro OSM. La guida di base è https://learnosm.org/en/
Qui è utile vedere come funziona OSM nella classificazione degli oggetti, l'utilizzo dei tag https://learnosm.org/en/hot-tips/tagging/

La prima domanda infatti è: come si etichetta (tagga) una caserma?

E se [cerchi sul web](openstreetmap tag "caserma" militare), ottieni tra le pagine questa https://wiki.openstreetmap.org/wiki/Template:IT:Map_Features:military

Qui ottieni una prima info utile per cercare in OverPass, che devi cercare `barracks`.

![image](https://user-images.githubusercontent.com/30607/112823165-39d34b00-9089-11eb-82b4-55302a5fcf69.png)

Allora la prima modalità, per iniziare è questa:

- apri https://overpass-turbo.eu/ 
- zoommi su Palermo
- fai click su Wizard, nel pop-up inserisci `barracks` e poi lanci la query

![image](https://user-images.githubusercontent.com/30607/112823515-ae0dee80-9089-11eb-8f2c-03a4a9bd59bf.png)

- in mappa avrai qualcosa come

![image](https://user-images.githubusercontent.com/30607/112823571-c0882800-9089-11eb-9579-f65395cd73a7.png)

- e potrai esportare in vari formati

![image](https://user-images.githubusercontent.com/30607/112823667-ddbcf680-9089-11eb-8e3b-f1d6139c44ef.png)

Questo per iniziare.

Overpass fa [MOLTO MA MOLTO di più](https://osm-queries.ldodds.com/tutorial/index.html), ma inizierei in modo basic

**Comment by cirospat** [comment]
grazie @aborruso 
ci lavoro un po su e ti confermo se ho capito e se riesco...
:)

**Comment by UO-TransizioneDigitaleComunePalermo** [comment]
@aborruso 
seguendo le tue indicazioni sono riuscito a fare la query per le caserme (barracks) anche se ho notato che alcune caserme di Palermo non sono taggate come `barracks` su OSM.

**Comment by cirospat** [comment]
@aborruso
seguendo le tue indicazioni sono riuscito a fare la query per le caserme (barracks) anche se ho notato che alcune caserme di Palermo non sono taggate come barracks su OSM.

**Comment by aborruso** [comment]
@cirospat ci sarebbe sempre la regolina di tansignari.

Se non te la senti, chiudi la issue.

**Comment by cirospat** [comment]
Si potrebbe aggiungere (come integrazione) ad una ricetta già presente su tansignari riguardo a overpass turbo fatta da Gabriele Francescotto. Vedo.

**Comment by cirospat** [comment]
ho aggiornato la [ricetta su OSM inizialmente creata da Gabriele Francescotto](https://tansignari.opendatasicilia.it/ricette/mappe/estrarre_punti_di_interesse_da_osm/) = 

https://github.com/opendatasicilia/tansignari/blob/master/ricette/mappe/estrarre_punti_di_interesse_da_OSM.md

+

https://github.com/opendatasicilia/tansignari-md/blob/master/content/it/ricette/Mappe/estrarre_punti_di_interesse_da_OSM.md

**Comment by aborruso** [comment]
@cirospat grazie!
