### ISSUE TITLE
[GitHub] Come citare un commento della issue in un commit?

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/tansignari#179]
Ho sempre utilizzato GitHub in solitaria, o per la saltuaria pull request in qualche altro progetto. Per me il mondo delle issue è totalmente nuovo. Prima di contaminare ulteriormente lo spazio con messaggi commit che non hanno senso, ho pensato di chiedere una mano qui.

Come si fa a citare un commento in una issue nel titolo di un commit? Sono "riuscito" a mettere una reference a tutta la issue, predisponendo un hashtag seguito dal numero della issue (es. \#issue), ma come posso fare a targetizzare un particolare commento? Spulciando superficialmente qualche risorsa, ho provato ad usare questo formato: \#issue@commento ma non sembra aver funzionato. Qualcuno sa come fare? Vorrei insignarmi e appeddirimi. Grazie a tutti!

**Comment by aborruso** [comment]
@gabacode a me non risulta che si possa fare e che tu possa inserire soltanto la citazione dell'intera issue.

Del resto sono pensate per essere molto verticali e strette.

**Comment by gabacode** [comment]
Grazie @aborruso ! Allora mi sembra di capire che sia meglio aprire, e gestire le issues separatamente, per ogni topic. Effettivamente, se ho capito bene, ha senso per tenere il tutto più ordinato.
