### ISSUE TITLE
Creare un branch per il WIP

### ISSUE THREAD

**Issue by ninokeys** [opendatasicilia/tansignari#18]
Visto che si sta costruendo e si possono avere opinioni che vanno a modificare le idee iniziali, forse sarebbe (magari piu' in la) opportuno creare un branch develop o inprogress dove applicare i commit (invece di usare il master) e ad ogni modifica o gruppo di modifiche creare una pull request che verra' poi revisionata.
in alternativa si potrebbero creare n branches per ogni modifica ma forse e' eccessivo

**Comment by pigreco** [comment]
Ho creato un branch per il WIP

grazie @ninokeys per l'idea.
