### ISSUE TITLE
[bash] come unire enne file CSV con stessa struttura

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#180]
Oggi ho la necessità di unire (`fare append`) di enne file CSV, stessa struttura

usando questo comando

` cat *.csv >out.csv`

ottengo l'unione ma anche delle intestazioni, come posso ovviare?

**Comment by aborruso** [comment]
Ciao @pigreco `cat` non è un'applicazione "csv aware", ovvero non tiene conto delle specifiche del formato e quindi la prima riga è uguale alla 37. Lui di base stampa righe.

Quindi puoi estrarre la prima riga con `head -n 1` e la metti in un file e poi in for loop con `tail -n +2` estrai da riga 2 in poi da tutti e vai in append su quel file con l'intestazione-

Oppure usi una utility che tenga conto del formato, come [Miller](https://github.com/johnkerl/miller) e lanci:

```
mlr --csv cat ./*.csv >./output.csv
```

**Comment by pigreco** [comment]
Ricetta pubblicata

https://tansignari.opendatasicilia.it/ricette/bash/unire_n_file_csv/

grazie!
