### ISSUE TITLE
[regex] aggiunta di caratteri in fase di ricerca

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#181]
Usando le regex, in fare di definizione del pattern di ricerca è possibile aggiungere dei caratteri non presenti nella stringa?

Esempio, ho questa stringa

```
A048     5      4 358         SPIGOLO S.O. MANUFATTO IN C.A.                                               42.807    -6183.721 50    5      4 181010 2010531100      BASE SPIGOLO S.O. MANUFATTO IN C.A.                                     4     9999.000
```
e il seguente pattern di ricerca:

```
^(.{4})(.{1}).{1}(.{4}).{1}(.{1}).{1}(.{4}).{1}(.{11}).{1}(.{70}).{1}(.{12}).{1}(.{12}).{1}(.{2}).{1}(.{4}).{1}(.{1}).{1}(.{4}).{1}(.{6}).{1}(.{15}).{1}(.{70}).{1}(.{2}).{1}(.{12})$
```
il gruppo 14esimo è `(.{6})` che cattura elementi  così `181010`, che rappresentano date (GGMMAA), esiste un modo per ottenere `18/10/10` direttamente come valore, invece che `181010`?

https://regex101.com/r/O0tSBa/1

**Comment by aborruso** [comment]
Ciao @pigreco il come fare un po' dipende da contenitore e dagli obiettivi veri di fondo.

Puoi cambiare la regex https://regex101.com/r/kEWrLf/1

O, mi sembra ancora meglio, nell'ambiente dove raccogli `181010`, gli dici con un funzione che quella è una data in formato `GGMMAA`, che vuoi formatto come `GG/MM/AA`.

Queste funzioni esistono un po' per tutti i linguaggi/app.

**Comment by pigreco** [comment]
@aborruso 

> Puoi cambiare la regex https://regex101.com/r/kEWrLf/1

vedo che aggiungi `/` nella sostituzione, io chiedevo prima della sostituzione, perché non ho modo di agire nella sostituzione.

![image](https://user-images.githubusercontent.com/7631137/118972350-c22ae980-b970-11eb-9a3a-693456bd2727.png)

hai ragione, è meglio agire nell'ambiente dove raccolgo e credo di fare cosi, grazie.

**Comment by aborruso** [comment]
> vedo che aggiungi `/` nella sostituzione, io chiedevo prima della sostituzione, perché non ho modo di agire nella sostituzione.

Non capisco cosa vuol dire. Se hai `181010`, prima il PC lo deve leggere e poi ne deve fare l'elaborazione. Che sia regex o che sia una funziona data, sempre "dopo" sarà

**Comment by pigreco** [comment]
> Non capisco cosa vuol dire. Se hai `181010`, prima il PC lo deve leggere e poi ne deve fare l'elaborazione. Che sia regex o che sia una funziona data, sempre "dopo" sarà

Analisi perfetta, anche io ho pensato cosi, ma speravo di sbagliare.

chiudo issue 
grazie
