### ISSUE TITLE
[regex] come selezionare prima virgola

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#182]
Ho un certo numero dei seguenti casi (sono righe di un file csv) in cui nella stessa riga ci sono più virgole `,`

```
form_mode,What the form is used for, like AddFeatureMode, SingleEditMode, MultiEditMode, SearchMode, AggregateSearchMode or IdentifyMode as string.
```
devo trasformarlo in:

```
[form_mode](./variabili/form_mode.md) | What the form is used for, like AddFeatureMode, SingleEditMode, MultiEditMode, SearchMode, AggregateSearchMode or IdentifyMode as string.
```
ma per farlo, devo usare i `regex`, ma non riesco a selezionare la prima `,` dopo `form_mode`:

cerco di farlo usando:

`(^.+),(.+)`  ma seleziona l'ultima virgola

cosa sbaglio?

https://regex101.com/r/rqP0YE/1

**Comment by pigreco** [comment]
forse ho trovato una soluzione:

`(^.+?),(.+)`

**Comment by aborruso** [comment]
Ciao @picomiles mi sembra corretto. 

Se non è così, fischia.

P.S. stranissimo quel CSV, se è così è un CSV non valido, mancano doppie virgole.

**Comment by pigreco** [comment]
@aborruso 
funziona!

> P.S. stranissimo quel CSV, se è così è un CSV non valido, mancano doppie virgole.

se fosse stato un csv normale non avrei avuto nessun problema.
g
r
a
z
i
e
