### ISSUE TITLE
Incorporare file

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#183]
Buongiorno :-) 
ho la necessità di incorporare dentro un file md un altro file proveniente dallo stesso repo, ma anche da repo e gist diversi.
Cerco su google, ma cerco in modo errato e non riesco a trovare nulla che mi interessa.
Come si scrive il codice per farlo?

**Comment by gbvitrano** [comment]
Risolto :-)

ecco come si fa
`{% include 'nome_file.md' %}`

**Comment by cirospat** [comment]
molto interessante. Grazie.
E se devo inserire file .MD da altri repo (sempre dello stesso proprietario ad es.) come è la sintassi?

**Comment by aborruso** [comment]
> ecco come si fa
> `{% include 'nome_file.md' %}`

@gbvitrano credo tu debba specificare che è così che si fa in mkdocs. Dico bene?

**Comment by gbvitrano** [comment]
Si, nel mio caso, un progetto realizzato con Material for MkDocs, la chiamata `{% include 'nome_file.md' %}`  ad un altro file  .md si può fare perché ho installato il plugin **mkdocs-macros**


> > ecco come si fa
> > `{% include 'nome_file.md' %}`
> 
> @gbvitrano credo tu debba specificare che è così che si fa in mkdocs. Dico bene?
