### ISSUE TITLE
ricerca di parole all'interno di molti file

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#184]
Ho migliaia di file `*.json` in varie cartelle e devo ricercare la presenza (all'ìnterno dei file) di alcune parole: `ERR`, `[]`, `null` ecc...

la struttura delle cartelle è:

`./rawdata/..../geo/`

dove i `....` sono i segnaposto di cartelle con nomi diversi ma con 4 caratteri (es: A123, E345)

esempio: 
- `D:\GitHub\pippo\rawdata\A015\geo`
- `D:\GitHub\pippo\rawdata\A311\geo`
- `D:\GitHub\pippo\rawdata\E418\geo`

come fare questa ricerca usando Linux?

per adesso utilizzo **_everything_** cartella per cartella (usando i filtri `D:\GitHub\pippo\rawdata\A015\geo\ content:ERR`) e siccome le cartelle sono oltre 50 cerco un modo veloce (ho provato a farlo con everything su tutte le cartelle `D:\GitHub\pippo\rawdata\` ma crasha o impiega un tempo infinito)

mentre il filtro `D:\GitHub\pippo\rawdata\*\geo\ content:ERR` non trova nulla

**Comment by aborruso** [comment]
ciao @pigreco due risposte rapide:

- con search Everything, potresti fare qualcosa come questa (occhio al doppio `\` usato per fare l'escape al back slash)

```
regex:"D:\\GitHub\\pippo\\rawdata\\.+\\geo" ext:json content:ERR
```

-  a riga di comando, per cercare contenuti uso sopratutto `ripgrep`. Entra nella cartella `pippo/rawdata` via shell e poi lancia

```
rg -l --no-ignore --hidden --type json ERR  | grep -Ei '/.{4}/geo'
```

**Comment by pigreco** [comment]
con search Everything:

con questa stringa funziona: `regex:"D:\\GitHub\\bbox_ade_FG\\rawdata\\L273\\geo"`

![image](https://user-images.githubusercontent.com/7631137/129445499-6434cc72-97df-4fed-80d2-b24f95f5edd0.png)

appena generalizzo, cioè uso: `regex:"D:\\GitHub\\pippo\\rawdata\\.+\\geo" ext:json content:null`

ricerca per molto tempo, ancora aspetto esito.

quindi funziona ma è questione di tempo.

devo provare la soluzione a riga di comando

**Comment by pigreco** [comment]
caso da riga di comando, ho lanciato:

`rg -l --no-ignore --hidden --type json null | grep -Ei '/L273/geo'`

ma non ho nessun esito, ricerca senza dare output

**Comment by pigreco** [comment]
probabilmente la lentezza è legata al mio vecchio laptop, ma utilizzando solo:

`rg -l --no-ignore --hidden --type json null` 

sembra ci siano degli output, ma il processo è parecchio lento

**Comment by pigreco** [comment]
in questi casi specifici è molto più rapido filtrare la dimensione del file e in 30 secondi si ha la risposta:
![image](https://user-images.githubusercontent.com/7631137/129452700-ce236091-4d3d-48cd-bb01-c5581a65c0bd.png)

```
time find . -type f -name '*.json' -size -40c -exec grep -H 'null' {}
\;
```

con la stessa tecnica in everything è immediato:

```
"D:\GitHub\bbox_ade_FG\rawdata" ext:json size:<=40 content:null
```
![image](https://user-images.githubusercontent.com/7631137/129452761-555634e8-4ca4-4ff2-bbaa-dfde682ca62c.png)

**Comment by pigreco** [comment]
grazie @aborruso 

ricetta fatta e pubblicata . https://tansignari.opendatasicilia.it/ricette/regex/ricerca_parole_in_molti_file/

chiudo
