### ISSUE TITLE
[vscode] come collegarlo a github

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#187]
aprire il terminale presente in vscode e digitare, uno dopo l'altro:

`git config --global user.email "tuo indirizzo email usato"`
`git config --global user.name "tuo username"`

**Comment by pigreco** [comment]
NB: probabilmente è un processo incompleto!

**Comment by gbvitrano** [comment]
Io uso il pulgin [github repository manager ](https://marketplace.visualstudio.com/items?itemName=henriqueBruno.github-repository-manager)
