### ISSUE TITLE
[GIS] Estrarre lettera da stringa

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#19]
Data una stringa qualsiasi `AAAAAABBBBCCCCCDDDDDDDDD` come estrarre la lettera maggiormente presente?? nell'esempio sarebbe la `D`. Mi piacerebbe trovare una soluzione qualsiasi da replicare, poi, in uno strumento GIS

fid|test|lettera prevalente
---|----|---
1|ACDAADADCBADACDBDBCDADB
2|ADDDCDBCC
3|DDDBDACBDBBAACCACDDADDACABDDACBADDBD
4|BCCABDBDDBACAADDAABBCCCCDACBCDDCBBBDABDADCDBCBB
5|AACADDBCCABBDABBDABBCAABABBDCDC
6|BCDBBDCBCBADCDBBADCAACBDABCCBCDBCCAABDACACCDCDACDDCCBACBB
7|BACCBBAABCBBD
8|BBACABCDADCACAACCDCBAC

se utile potrei ottenere questa formattazione:

fid|test|lettera prevalente
--|----|----
1|A,A,A,A,A,A,A,B,B,B,B,C,C,C,C,D,D,D,D,D,D,D,D
2|A,B,C,C,C,D,D,D,D
3|A,A,A,A,A,A,A,A,A,B,B,B,B,B,B,B,C,C,C,C,C,C,D,D,D,D,D,D,D,D,D,D,D,D,D,D
4|A,A,A,A,A,A,A,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,C,C,C,C,C,C,C,C,C,C,C,C,D,D,D,D,D,D,D,D,D,D,D,D
5|A,A,A,A,A,A,A,A,A,B,B,B,B,B,B,B,B,B,B,C,C,C,C,C,C,D,D,D,D,D,D
6|A,A,A,A,A,A,A,A,A,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,D,D,D,D,D,D,D,D,D,D,D,D
7|A,A,A,B,B,B,B,B,B,C,C,C,D
8|A,A,A,A,A,A,A,B,B,B,B,C,C,C,C,C,C,C,C,D,D,D

da ricerche, in italiano o inglese, non trovo nulla :-(

**Comment by aborruso** [comment]
Caro @pigreco ,
la cosa più comoda è forse usare un linguaggio di scripting.

per ogni cella puoi dare qualcosa come quella di sotto:

```python
testList = list("AFEFAABBGCA")
print(max(set(testList), key = testList.count))
```

Che ti da `A`

**Comment by pigreco** [comment]
Ciao @aborruso 
lo script funziona anche nella console python di QGIS:
![image](https://user-images.githubusercontent.com/7631137/53116187-587cc480-3548-11e9-9dc6-e3609a702fd0.png)

quindi il passaggio successivo è quello di creare una funzione personalizzata che prenda la lista da un campo della tabella attributi.

grazie

**Comment by pigreco** [comment]
@aborruso 
wow
ho **RISOLTO** usando solo **QGIS**  e un plugin [ArrayPlus](https://framagit.org/jbdesbas/arrayPlus)
plugin documentato anche nel nostro HfcQGIS, in particolare la funzione [array_majority](http://hfcqgis.opendatasicilia.it/it/latest/gr_funzioni/arrays/array_majority.html)

```
array_majority( 
string_to_array(
aggregate(
layer:='Edifici', 
aggregate:='concatenate', 
expression:="categoria",
filter:=intersects( $geometry, geometry(@parent)),
concatenator:=',')
) 
)
```
![image](https://user-images.githubusercontent.com/7631137/53118768-24a49d80-354e-11e9-9d04-46b06a68cc70.png)
