### ISSUE TITLE
confrontare due tabelle

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#190]
Ho due tabelle cosi strutturate:

la prima:

comune|fogli
--------|----
villa|1-11-20
rosa|2-14-16-21

la seconda:

comune|fogli
--------|----
villa|1-111-200
rosa|3-14-16-21

come confrontarle per evidenziare i valori uguali nel campo `fogli`?

mi aspetterei un'altra tabella cosi fatta:

comune|fogli
--------|----
villa|1
rosa|14-16

ovvero nel campo `fogli` solo i valori uguali tra le due tabelle, oppure un modo per capire quali sono i valori uguali

**Comment by aborruso** [comment]
Caro @pigreco ,
uno strumento meraviglioso del mondo Linux/UNIX e `diff`. Fa uno sola cosa e bene: confronta stringa di testo.

Lanciando 

`diff uno.csv due.csv`

avresti

![image](https://user-images.githubusercontent.com/30607/135576185-cce87c85-dd65-4d98-ac02-3b61e04527e7.png)

È uno strumento che non sa cosa sia un CSV, quindi non tiene conto di separatore di campi, ma legge una riga nel complesso.

La parola `diff' è chiave. Se cerchi qualcosa come `sql make string diff` trovi come fare queste operazioni in un contesto SQL.

A riga di comando, per CSV (e altri formati) c'è uno strumento bellissimo che si chiama [`daff`](https://github.com/paulfitz/daff).

Se  lanci `daff  uno.csv due.csv` (è il comando base, ci sono mille opzioni di output), ottieni


| @@ | comune | fogli |
| --- | --- | --- |
| -> | villa | 1-11-20->1 |
| -> | rosa | 2-14-19-21->14-16 |


Da questi punti di partenza, ti tocca soltanto fare tuning e studiare le varie opzioni disponibili.

**Comment by pigreco** [comment]
Buongiorno @aborruso 

a me accade questo, dove sbaglio?

![image](https://user-images.githubusercontent.com/7631137/135580423-f6070c57-7679-45e7-a194-7c8a7686bbbb.png)

se noti visualizza i due file e non la diff

**Comment by pigreco** [comment]
@aborruso allego i due file di test
[due.txt](https://github.com/opendatasicilia/tansignari/files/7264945/due.txt)
[uno.txt](https://github.com/opendatasicilia/tansignari/files/7264946/uno.txt)

**Comment by pigreco** [comment]
ho fatto altri test, credovo fosse il formato txt, quindi ho creato due csv ma nulla, non stampa la differenza;

altra modifica, il csv aveva accapo alla windows, la ho trasformata in Linux, ma nulla non riesco ad avere l'output atteso.

**Comment by pigreco** [comment]
Ho provato in QGIS e utilizzando gli ARRAY.
Realizzo unica tabella con due campi in cui metti i valori da confrontare
![image](https://user-images.githubusercontent.com/7631137/135644652-eb6a065f-5861-47c8-8384-d9ce5b9413b7.png)
poi utilizzo la seguente espressione e ottengo il campo `output`

```
array_to_string(
        array_majority( array_cat(
        string_to_array(replace("fogli1",'|',',')),
        string_to_array(replace("fogli2",'|',','))
)))
```

**Comment by pigreco** [comment]
qui ricetta usando QGIS:

https://tansignari.opendatasicilia.it/ricette/csv-tsv/confrontare_campi_tabella/
