### ISSUE TITLE
verificare cambiamenti in remoto usando vscode

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#195]
Un repository su GitHub lo edito, in locale, tramite vscode.
Dopo tempo ho aperto , con vscode, un repository e mi accorgo che ci sono ben 5 commit (vedi screenshot):

![image](https://user-images.githubusercontent.com/7631137/144450306-4bc00054-eb3e-48c3-bb87-ad0a77ed85ac.png)

ma come posso fare a vedere questi commit da vscode? o da GitHub? prima di aggiornare la cartella in locale?

**Comment by pigreco** [comment]
da github lo vedo da qui:

https://github.com/opendatasicilia/HfcQGIS-md/commits/main

ma da vscode?

**Comment by aborruso** [comment]
> ma da vscode?

Non c'è un modo diretto, credo tu debba installare estensioni, come GitLens.

**Comment by pigreco** [comment]
grazie @aborruso
