### ISSUE TITLE
ordinare numericamente un array alfanumerico

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#196]
Ho una colonna di un CSV caratterizzata da una serie di numeri separati da `-` come in figura:

![image](https://user-images.githubusercontent.com/7631137/149374235-c0791747-d962-4f67-8a7f-b3ddf1b1704b.png)

come ordinare numericamente ([Natural Sorting](https://en.wikipedia.org/wiki/Natural_sort_order)) i valori all'interno delle celle nella colonna `scritta`?

esempio:

da:
`5/A-5-16/B-4-18-8-15-22-3-14-12-6-16/A-9-11-13-7-21-1-19-10-7/A-17-20-2`

a:
`1-2-3-4-5-5/A-6-7-7/A-8-9-10-11-12-13-14-15-16/A-16/B-17-18-19-20-21-21`

usare la funzione `array_sort` ordinerebbe alfabeticamente e non va.

allego un csv di prova
[ordinare_scritta.csv](https://github.com/opendatasicilia/tansignari/files/7864578/ordinare_scritta.csv)

**Comment by aborruso** [comment]
Caro totò,
con Miller 5 (dovresti avere questo), un modo non elegante è questo:

```
mlr --csv nest --explode --values --across-records -f scritta --nested-fs "-" then \
put -S '$toto=regextract($scritta,"[0-9]+")' \
then sort -f den_estesa -n toto then \
cut -x -f toto then \
nest --implode --values --across-records --nested-fs "-" -f scritta ordinare_scritta.csv
```

Di base mette tutto in colonna splittando per `-`, poi crea una colonna con i soli numeri, ordina per questa e poi rimetta tutto insieme

**Comment by aborruso** [comment]
Una versione, che ordina anche 12B, 12, 12A, per lo stesso record

```
mlr --csv nest --explode --values --across-records -f scritta --nested-fs "-" then \
put -S '$totoN=regextract($scritta,"[0-9]+");$totoT=regextract($scritta,"[a-zA-Z]+")' then unsparsify then sort -f den_estesa -n totoN -f totoT then cut -r -x -f "toto+" then nest --implode --values --across-records --nested-fs "-" -f scritta  ordinare_scritta.csv
```

**Comment by pigreco** [comment]
> Una versione, che ordina anche 12B, 12, 12A, per lo stesso record

funziona perfettamente, grazie:

![image](https://user-images.githubusercontent.com/7631137/149384324-d59e6837-ac44-4d7a-8506-d31c339f10b0.png)

**Comment by pigreco** [comment]
ricetta fatta e pubblicata,

grazie

https://tansignari.opendatasicilia.it/ricette/script/ordinare_elementi_array/

**Comment by aborruso** [comment]
Quanto voglio bene a @gpirrotta ?💜

**Comment by pigreco** [comment]
grazie mille @gpirrotta,
sono belle soluzioni, prima o poi inizierò a studiare Python sul serio.

**Comment by pigreco** [comment]
aggiungo anche l'ultima arrivata, soluzione usando le espressioni di QGIS

```py
array_to_string(
array_foreach(
	array_sort(
		with_variable('lista',
			string_to_array('5/A-5-4-8-3-14-6-9-7-1-10-7/B-2-7/A' ,'-'),
			array_foreach(generate_series(0, array_length(@lista)-1),
			lpad(regexp_substr( (@lista[@element]),'(\\d+)'),3,'0')
			||'|'||
			if(regexp_substr((@lista[@element]),'([a-zA-Z/]+)') !='',
			   regexp_substr((@lista[@element]),'([a-zA-Z/]+)'),
			   '/A')
			||'|'||
			@lista[@element]))),
regexp_replace( @element,'^.+\\|(.+)$','\\1'))
)
```

![image](https://user-images.githubusercontent.com/7631137/149572994-80c4adbb-9d90-4894-9b6d-19eb4b178cd4.png)

**Comment by Korto19** [comment]
Suggerirei questa forma per una funzione personalizzata che restituisca un array: 

![image](https://user-images.githubusercontent.com/36882050/149624218-9af75619-932f-46e2-af9d-a8211acad297.png)
commentando l'ultima riga e decommentando la penultima restituisce una stringa

```py
from qgis.core import *
from qgis.gui import *

@qgsfunction(args='auto', group='Custom', referenced_columns=[])
def array_sort_special(value1, feature, parent):'''

    Ordina un array alfanumerico numericamente
    <h2>Example usage:</h2>
    <ul>
      <li>array_sort_special('5/A-5-4-8-3-6-9-7-1-10-7/B-2-7/A') -> ['1', '2', '3', '4', '5', '5/A', '6', '7', '7/A', '7/B', '8', '9', '10']</li>
    </ul>

    data = value1.split('-')
    r = sorted(data, key=lambda item: (int(item.partition('/')[0])
    if item[0].isdigit() else float('inf'), item))
    #return (','.join(r))
    return r
```

**Comment by pigreco** [comment]
> Suggerirei questa forma per una funzione personalizzata che restituisca un array:

grazie @Korto19 , anche questa soluzione andrà nella ricetta :-)

**Comment by aborruso** [comment]
Ecco una soluzione ancora più light, che sfrutta il _natural sorting_ e le utility di sistema.

Nella shell infatti basta usare 

```
echo "15,1,2/AX,22,1/C,1/A,1/BA,2,3" | tr , "\n" | sort -V | paste -sd, -
```

per avere

```
1,1/A,1/BA,1/C,2,2/AX,3,15,22
```

E questo è portabile penso in tutti gli ambienti. In Miller c'è la funzione `system`. Ad esempio a partire da

```
a,b
1,"15,1,2/AX,22,1/C,1/A,1/BA,2,3"
```

si lancia

```
<input.txt mlr --c2p --barred cat  then put -S '$toto=system("echo ".$b." | tr , \"\n\" | sort -V | paste -sd, -")'
```

e si ottiene

```
+---+-------------------------------+-------------------------------+
| a | b                             | toto                          |
+---+-------------------------------+-------------------------------+
| 1 | 15,1,2/AX,22,1/C,1/A,1/BA,2,3 | 1,1/A,1/BA,1/C,2,2/AX,3,15,22 |
+---+-------------------------------+-------------------------------+
```

**Comment by pigreco** [comment]
La ricetta è stata fatta, chiudo

https://tansignari.opendatasicilia.it/ricette/script/ordinare_elementi_array/
