### ISSUE TITLE
regex - pulizia da (uno più) spazi iniziali e finali

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#2]
perdonatemi, sono agli inizi e non riesco a fare una cosa apparentemente banale:

devo pulire dei dati da eventuali spazi iniziali e finali (uno o più spazi iniziali - uno o più spazi finali);

con `^( )+(.+)` riesco a selezionare gli spazi iniziali e sostituisco con `$2`, tutto ok;
ma non riesco con gli spazi finali, cioè riesco solo ad intercettare ultimo spazio presente `(.+)( )$` [test](https://regex101.com/r/VfbpY9/1/) ma quando vado a sostituire con `$1`  si porta dietro gli spazi.

**Comment by aborruso** [comment]
"perdonatemi" qui non si può dire :)

Prova con `^(.+?)( +)$` https://regex101.com/r/VfbpY9/2/

**Comment by pigreco** [comment]
>Prova con `^(.+?)( +)$` https://regex101.com/r/VfbpY9/2/
funziona!!!
per favore, potresti spiegarlo a parole??
avevo provato con `^(.+)( +)$` ma con esito negativo; cosa fa `?` in questo caso?
grazie

**Comment by pigreco** [comment]
@aborruso credo di aver capito:
differenza tra selezione pigra o ingorda
https://www.youtube.com/watch?v=INDu5azwohw

**Comment by aborruso** [comment]
confermo @pigreco 

Occhio però le regex non funzionano in tutti gli ambienti allo stesso modo: l'uso ad esempio del `?` come in questo esempio non va bene con tool importanti come sed (e tanti altri).
