### ISSUE TITLE
[GIS] immagine tif/tfw leggo coordinate errate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#20]
Ho una immagine tif/tfw ma non riesco a posizionarla correttamente, come se non leggesse il file tfw:
l'immagine tif è accompagnata dal file tfw, entrambi i file hanno stesso nome ma caricandola in QGIS (per esempio con il drag&drop) e assegnando EPSG 3004, l'immagine si posiziona come se non avesse letto il world file.

Allego file:
[image.zip](https://github.com/opendatasicilia/tansignari/files/2891035/image.zip)

**Comment by aborruso** [comment]
Carò Totò è una follia: c'è un encoding che fa impazzire QGIS. Se lo cambi in UTF-8, si risolve.

Chissà cosa ha generato quel file

![image](https://user-images.githubusercontent.com/30607/53199746-30f92b00-3620-11e9-9487-c0ec24805716.png)

**Comment by pigreco** [comment]
Ciao @aborruso 
solo tu potevi pensare a questo problema della codifica: FUNZIONA!!!

grazie!
