### ISSUE TITLE
come conoscere rapidamente le caratteristiche di un CSV

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#201]
Alcune volte è utile conoscere le caratteristiche basi di un CSV, soprattutto se molto pesante, come:
1. numero righe;
2. numero colonne;
3. ispezionare solo le prime o ultime 10 righe;

è possibile farlo usando solo bash, oppure occorre installare altri tool?

qui alcuni file csv: 

- Calabria : https://www.istat.it/storage/cartografia/matrici_distanze/Calabria.zip
- Palermo : https://opendata.comune.palermo.it/js/server/uploads/dataset/gtfs/_01022022145201.zip

**Comment by pigreco** [comment]
per visualizzare le prime 10 righe o le ultime 10 righe, lanciare, nella bash, rispettivamente:

```
<Calabria.txt head
```

```
<Calabria.txt tail
```
![image](https://user-images.githubusercontent.com/7631137/154495722-e24749d3-b384-440f-b678-6eb6b8320e87.png)

Usando [Miller](https://github.com/johnkerl/miller), per ottenere numero righe e colonne, lanciare:

```
mlr --c2p --barred --ifs ";" tail -n 1 then put '$righe=NR;$colonne=NF-1' then cut -f righe,colonne Calabria.txt
```
## output

```
+---------+---------+
| righe   | colonne |
+---------+---------+
| 2985700 | 5       |
+---------+---------+
```

```
mlr --c2p --barred --ifs ";" head Calabria.txt
```
```
+--------------+---------+--------------+------------+------------+
| Name         | Origine | Destinazione | Total_Minu | Total_Mete |
+--------------+---------+--------------+------------+------------+
| 1042 - 78063 | 1042,00 | 78063,00     | 544,62     | 1068585,31 |
| 1042 - 78064 | 1042,00 | 78064,00     | 548,43     | 1072340,25 |
| 1042 - 78084 | 1042,00 | 78084,00     | 549,78     | 1078720,88 |
| 1042 - 78149 | 1042,00 | 78149,00     | 553,67     | 1071364,43 |
| 1042 - 78101 | 1042,00 | 78101,00     | 554,17     | 1072860,22 |
| 1042 - 78092 | 1042,00 | 78092,00     | 557,13     | 1086129,98 |
| 1042 - 78125 | 1042,00 | 78125,00     | 558,56     | 1079784,72 |
| 1042 - 78005 | 1042,00 | 78005,00     | 559,90     | 1078946,18 |
| 1042 - 78083 | 1042,00 | 78083,00     | 560,02     | 1096654,23 |
| 1042 - 78057 | 1042,00 | 78057,00     | 561,59     | 1105706,59 |
+--------------+---------+--------------+------------+------------+
```

**Comment by aborruso** [comment]
> per ottenere il numero di righe è possibile utilizzare `wc -l nomefile.csv`
> 
> credo che `wc` stia per _words couneter_ e `-l` per _lines_

Nella guida che sto scrivendo - parte non pubblica - nel capitolo su "esplorare" uno dei comandi è `wc`, eccezionale.
Soprattutto per prendere le misure di base.

Ma se hai un CSV come questo (e ce ne sono spesso di così)

```
Campo 1,Campo 2
"Cella con
A capo
Fastidiosi",Ipsum
Lorem,"uno
Due
Tre
Quattro
Cinque"
```

che sembra tutto sbagliato, ma in realtà è _compliant_, ma ha nelle celle degli "a capo". 
`wc` ragiona per righe (come la gran parte degli Unix tool) e non è CSV _aware_, ovvero non conosce le specifiche [`rfc 4810`](https://datatracker.ietf.org/doc/html/rfc4180), non sa che in una "riga" ci possono essere gli "a capo". Con `wc -l` qui avresti 9.

Grande strumento `wc`, da cui spesso si parte. Poi però, in dipendenza del formato, meglio usare un tool che sappia interpretare quel formato, altrimenti le "misure" potrebbero non essere esatte.

**Comment by aborruso** [comment]
Ciao @pigreco ecco la prima versione del capitolo per esplorare file di testo, della guida che sto scrivendo:
<https://arigadicomando.it/dati/esplora/>

Tocca tutti i punti di questo thread.

Penso che possa essere di interesse anche per @dennisangemi

**Comment by pigreco** [comment]
wow, complimenti
mai vista una sezione cosi ben fatta!!!

https://arigadicomando.it/dati/esplora/

**Comment by aborruso** [comment]
> wow, complimenti
> mai vista una sezione cosi ben fatta!!!

Grazie!

E oggi ho aggiunto dopo le "misure", le "forme" https://arigadicomando.it/dati/esplora/#le-forme-la-descrizione-dei-dati

**Comment by dennisangemi** [comment]
Ciao @aborruso , non posso che essere d'accordo con @pigreco : è un lavoro molto chiaro e ben fatto. Ergo grazie <3

**Comment by pigreco** [comment]
@dennisangemi, @aborruso è fortunato perché ci sono persone come noi che lo seguono e lo stimolano a divulgare hihihih

**Comment by aborruso** [comment]
> pareri?

Io una ricetta, con gli elementi di base che tu reputi più utile, la inserirei.

E poi se vuoi metti il link alla lunga pagina che ho fatto

**Comment by pigreco** [comment]
ricetta minima fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/bash/caratteristiche_csv/
