### ISSUE TITLE
Join tra du file con Visidata

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#203]
Buonasera :-)
Ho due file con una con la colonna **Nazione** in comune, vorrei fare una join con visidata, ma non ci riesco, mi perdo quando devo creare la colonna chiave nei due file.

Ho già fatto il join con QGIS e Google sheet, ma vorrei imparare a farlo con Visidata
prova con QGIS
![qgis_join](https://user-images.githubusercontent.com/20488693/154862483-020e6664-bde5-4e00-a3fd-606dd23f9eb1.png)

![qgis_join_01](https://user-images.githubusercontent.com/20488693/154862505-d608fe3a-2b83-4a6a-a05e-e011a50dc086.png)

prova con google sheet usando VLOOKUP
![google_join](https://user-images.githubusercontent.com/20488693/154862550-88572d2a-b810-488d-afee-44c6460447f6.png)
[res_italiani_stranieri_iso3166.csv](https://github.com/google/docsy/files/8104874/res_italiani_stranieri_iso3166.csv)
Questo dataset contiene i dati sulla popolazione residente a Palermo per Nazionalità e zona censuaria.
il file ha una struttura verticale 356.400 righe e 3 colonne

[Elenco_denominazioni_istat.csv](https://github.com/google/docsy/files/8104875/Elenco_denominazioni_istat.csv)
Questo file contieene l'elenco istat di codici e denominazioni al 31/12/202 per gli stati e continenti

**Comment by pigreco** [comment]
@gbvitrano per favore spiega i dataset, ho notato che uno dei due file CSV contiene nel campi Nazioni molte ripetizioni, cioè ogni Nazione è ripetuta 2700 volte; inoltre quale deve essere la tabella di sinistre e quale quella di destra.

**Comment by gbvitrano** [comment]
il file iniziare era file con una struttura orizzontale con 2700 righe e 133 colonne, per realizzare grafici con tableau mi è più utile  una struttura verticale, per cui con visidata ho  creato un foglio melted, quello postato è l'output di visidata

**Comment by pigreco** [comment]
STEP BY STEP
1. aprire la prima tabella `res_italiani_stranieri_iso3166.csv` (`vd res_italiani_stranieri_iso3166.csv`);
2. spostarsi nella colonna `Nazioni` e renderla colonna chiave pigiando `!`; ( La JOIN in VisiData viene fatto tra colonne chiave)
3. aprire la seconda tabella pigiando `o` e scrivendo `Elenco_denominazioni_istat.csv` (il TAB vi aiuta a completare il nome) ;
4. spostarsi nella colonna `Nazione` e renderla colonna chiave pigiando `!`;
5. aprire il “foglio dei fogli” digitando `shift+s` e selezionare, usando il tasto `s`, le due tabelle;
6. digitare `&` per realizzare e visualizzare la JOIN tra le due tabelle: scrivere o selezionare `inner` e invio.
7. 7. dopo qualche secondo vedrai la tabella con il join; `ctrl+s` per salvare

**Comment by gbvitrano** [comment]
Perfetto, ci sono riuscito.
Non capivo come aprire il secondo file
Grazie grazie :-)

![2022-02-20_22h15_11](https://user-images.githubusercontent.com/20488693/154864622-b8d2e700-9a62-4aac-8b5c-7527d442b1e8.png)

**Comment by aborruso** [comment]
> Non capivo come aprire il secondo file

Ciao Gianni, nelle guida, nell'[esempio di JOIN](https://ondata.github.io/guidaVisiData/fogli/?h=join#fare-join-tra-tabelle), è scritto come sotto.

Cosa non si capisce? Come lo modifichiamo?

Grazie

![image](https://user-images.githubusercontent.com/30607/154915861-bd5bc3f1-5aad-4be4-81b6-1d0cc37c5001.png)

**Comment by gbvitrano** [comment]
> > Non capivo come aprire il secondo file
> 
> Ciao Gianni, nelle guida, nell'[esempio di JOIN](https://ondata.github.io/guidaVisiData/fogli/?h=join#fare-join-tra-tabelle), è scritto come sotto.
> 
> Cosa non si capisce? Come lo modifichiamo?
> 
> Grazie
> 
> ![image](https://user-images.githubusercontent.com/30607/154915861-bd5bc3f1-5aad-4be4-81b6-1d0cc37c5001.png)

Letta ora, la guida è chiarissima, ma ieri ero io che non capivo :-)
Grazie
