### ISSUE TITLE
[CSV] find and replace che interessa i valori di un solo campo

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari#204]
Ciao @aborruso, nella tua guida c'è una sezione bellissima: [Fare un trova e sostituisci globale](https://arigadicomando.it/miller/ricette/#fare-un-trova-e-sostituisci-globale). Leggendola mi è sorta una domanda: sarebbe posibile fare un _find and replace_ che operi **solo** un campo e quindi NON globale?

**Comment by aborruso** [comment]
Ciao @dennisangemi ecco qui https://arigadicomando.it/miller/ricette/#fare-un-trova-e-sostituisci-per-campo

**Comment by dennisangemi** [comment]
Grazie mille @aborruso, appena posso creo ricetta anche per tansignari.

**Comment by dennisangemi** [comment]
P.s. tocchi con tasto dolente. Questo comando dovrei eseguirlo con un for giornaliero per tutte le volte che viene scritto "Denis" al posto di "Dennis" hahaha

**Comment by dennisangemi** [comment]
Ricetta aggiunta https://github.com/opendatasicilia/tansignari-md/commit/77d0af1f328cc6387fe8f3f80dcf9df042ae702f

online qui https://tansignari.opendatasicilia.it/ricette/csv-tsv/trova_sostituisci_campo_specifico/

Grazie @aborruso
