### ISSUE TITLE
Come installare allcontributors nei repo github

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#205]
Buonasera :-)
Come si installa [https://allcontributors.org/](https://allcontributors.org/) nei repo di github?

**Comment by pigreco** [comment]
STEP BY STEP

1. vai in questo [sito ](https://allcontributors.org/)e pigia forte sul bottone `Install the Bot`
2. clicca forte su `Install the GitHub App`: del punto 1. Install the AllContributors GitHub App;
3. ti portera in una pagina github e ti chiederà dove vuoi installare il bot:
![image](https://user-images.githubusercontent.com/7631137/155021425-85dff2ca-bd76-4707-9095-007ebd8e2194.png)
4. clicca sulla freccia di destra in corrispondenza a dove vuoi installarlo:
![image](https://user-images.githubusercontent.com/7631137/155022033-bd68a9de-5174-4f76-8bab-7a6c818cea59.png)
5. pigia fortissimo su `Install`
![image](https://user-images.githubusercontent.com/7631137/155022171-89bc53c5-cd46-4035-bb41-1f024e99a758.png)
6. vai nel repository dove hai installato il bot:
  6.1 apri una issue con oggetto: `Aggiungi all-contributors bot` e poi la chiudi;
  6.2 commenta la stessa issue scrivendo: `@all-contributors` please add `account da aggiunger` for `code, design, business, projectManagement, ideas,platform`
7. l'elenco dopo `for` lo ottieni da [qui](https://allcontributors.org/docs/en/emoji-key);
8. dopo aver confermato commento, il bot creerà una PR, che deve `mergiare`
9. fatto!!!

**Comment by cirospat** [comment]
Grazie @pigreco per lo spiegone.

**Comment by gbvitrano** [comment]
Grazie :-)

**Comment by dennisangemi** [comment]
Non è stata scritta la ricetta

**Comment by pigreco** [comment]
@gbvitrano @dennisangemi 
ci penso io a fare la ricetta

grazie

**Comment by gbvitrano** [comment]
@dennisangemi so dove va la ricetta, appena ho un pò di tempo eras già mia intensione scriverla.

**Comment by pigreco** [comment]
ricetta fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/git/allcontributors-git/

**Comment by dennisangemi** [comment]
> @dennisangemi so dove va la ricetta, era già mia intensione scriverla.

@gbvitrano non ho dubbi sul fatto che tu sappia dove pubblicare la ricetta ;) mi sembrava strano che la issue fosse stata chiusa senza prima aver pubblicato la ricetta.

Grazie @pigreco
