### ISSUE TITLE
Query Data.World

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#207]
Buonasera :-)
Ho rielaborato il dataset sugli stranieri residenti a Palermo nel 2020, il dataset è pubblicato **[qui](https://data.world/gbvitrano/popolazione-residente-a-palermo-2020)** al momento solo @aborruso e @pigreco hanno l'accesso.
Sarà reso pubblico contemporaneamente al sito in  Material for MkDocs  dedicato al progetto **Palermo Melting Pot | 2020**
A differenza del 2018, questa volta voglio mettere solo il dataset completo e qualche esempio di selezione per far capire come estrarre i dati.

Al momento ho fatto questi esempi:

![dataworld_02](https://user-images.githubusercontent.com/20488693/155558050-5438f68d-906a-4d94-8e1a-c49b9ae90a93.png)

![dataworld_03](https://user-images.githubusercontent.com/20488693/155558154-78ad1ad9-a74f-4807-b3a2-4f8387490b8f.png)

![dataworld_04](https://user-images.githubusercontent.com/20488693/155558182-9ae4fbb1-c8aa-4c51-9efe-6f4b47891044.png)

Vorrei inserire un ultimo esempio che filtri per somma...
Con visidata e facile:
Strranieri per **Circoscrizione** e **Sub-region (UNSD)**
![2022-02-24_16h31_43](https://user-images.githubusercontent.com/20488693/155556096-f8c7d004-1a99-4426-9e2e-e63b03a5f209.png)

Come si scrive la query in data.world per ottenere una tabella simile?

**Comment by aborruso** [comment]
@gbvitrano adesso non mi ci posso metter. Mi sembra una pivot.
Guarda qui https://docs.data.world/documentation/sql/concepts/advanced/PIVOT.html

**Comment by pigreco** [comment]
@gbvitrano seguendo la guida indicata da @aborruso, qui un piccolo esempio di query:

```sql
WITH table1 AS (
    SELECT t1.circoscrizione AS circoscrizione, denominazione_continente_it AS nome
      FROM palermo_residenti_ita_world_iso3166_territorio AS t1
)
SELECT *
  FROM table1
 PIVOT (COUNT (nome) FOR nome IN ("Asia", "Europa", "Africa"))
 ```

in output ottieni:

![image](https://user-images.githubusercontent.com/7631137/155572484-222be054-d825-4497-8650-e5ae1b81b490.png)

**Comment by gbvitrano** [comment]
Grazie @pigreco 
Con SQL devo conoscere già cosa contiene la colonna... con Visidata è moltooooo più semplice :-)

**Comment by pigreco** [comment]
> Con SQL devo conoscere già cosa contiene la colonna... con Visidata è moltooooo più semplice :-)

no, tramite altra query puoi recuperare quello che ti serve

**Comment by gbvitrano** [comment]
Appena posso faccio ricetta... :-) :-)

**Comment by pigreco** [comment]
> Appena posso faccio ricetta... :-) :-)

esiste già una ricetta sull'argomento,

https://tansignari.opendatasicilia.it/ricette/query/creare_tabella_pivot/
