### ISSUE TITLE
Mermaid gantt, impostare ora di inizio

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#209]
Ho realizzato questo diagramma [mermaid](https://github.com/mermaid-js/mermaid/blob/develop/docs/gantt.md):

```
gantt
dateFormat HH:MM:SS
title Field Calc di QGIS, Cosa è e come usarlo
axisFormat  %H:%M

section Introduzione
Antonio Cotroneo INTRO     :active, des1, 18:30:00, 5m
Totò Fiandaca INTRO        :des2, after des1, 10m
section Slide
Totò Fiandaca in QGIS      :des3, after des2, 40m
Domande Finali             :des4, after des3, 10m
```

l'output è:

![image](https://user-images.githubusercontent.com/7631137/161379577-b6191d01-a014-4d2c-9d76-30585a360320.png)

non riesco ad impostare l'ora di inizio (18:30:00), il codice imposta l'ora corrente

qui l'esempio dal vivo:

https://github.com/pigreco/field_calc_idraulica#marcatori-di-capitolo-video-youtube

**Comment by aborruso** [comment]
Ecco un esempio

```
gantt 
dateFormat HH:mm
axisFormat %H:%M
uno           :a, 17:49,40min
due           :after a,17min
```


```mermaid
gantt 
dateFormat HH:mm
axisFormat %H:%M
uno           :a, 17:49,40min
due           :after a,17min
```

**Comment by aborruso** [comment]
@pigreco nel tuo caso sbagli la sintassi. Cambia `HH:MM:SS` in `HH:mm:ss`.

**Comment by pigreco** [comment]
@aborruso 
grazie, funziona!

avevo provato a cambiare qualsiasi cosa tranne quello, come è ovvio l'errore è sempre dove non si cerca.
