### ISSUE TITLE
mettere in relazione diretta un file CSV sullo smartphone con un foglio Google spreadsheet

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#21]
c'è un app per smartphone ([ANGLECAM](https://play.google.com/store/apps/details?id=com.derekr.AngleCam)) che produce per ogni foto dati geografici.
Crea anche un file CSV.
Creo questa issue per capire come fare importare i dati di questo file CSV, che si trova nella memoria dello smartphone, da un file Google spreadsheet in automatico.

**Comment by gbvitrano** [comment]
Pre prima coso ho installato nel cel un'app per sincronizzare i file o cartelle con gdrive **[Autosync for Google Drive](https://play.google.com/store/apps/details?id=com.ttxapps.drivesync)**  
Una volta che sincronizzo il file di ([ANGLECAM](https://play.google.com/store/apps/details?id=com.derekr.AngleCam)) in gdrive come lo importo in Google spreadsheet, ho provato ad usare **importdata** utilizzando il link di condivisione del file csv, ma non funziona

**Comment by aborruso** [comment]
@gbvitrano puoi condividere l'URL di questo CSV, lo puoi rendere pubblico?

**Comment by gbvitrano** [comment]
eccolo
https://drive.google.com/file/d/1vNgyMXfC0B3YT_fiqYmv1wSxYId0JuSF/view?usp=sharing

**Comment by gbvitrano** [comment]
ho capito come fare.
Per fare importare il file ho aggiunto **&export=download** dopo il nome del file stesso **https://drive.google.com/uc?authuser=0&id=1vNgyMXfC0B3YT_fiqYmv1wSxYId0JuSF**

https://drive.google.com/uc?authuser=0&id=1vNgyMXfC0B3YT_fiqYmv1wSxYId0JuSF&export=download

**Comment by aborruso** [comment]
Esatto, altrimenti è una pagina HTML.

L'URL invece per puntare al file nella sua essenza è

`https://drive.google.com/uc?export=download&id=` + `ID del file`

Quindi ad esempio "https://drive.google.com/uc?export=download&id=1vNgyMXfC0B3YT_fiqYmv1wSxYId0JuSF"

**Comment by cirospat** [comment]
una cosa prima di chiudere la issue:
si può ottenere la foto  scattata con l'app ANGLECAM dentro una cella del google spreadsheet?
Ho visto altre applicazioni farlo (con IFTTT). Vedo un immagine dentro una cella. Certo questa immagine dovrebbe essere un file `.jpg` da qualche parte nel web. Nel caso dell'applicazione su IFTTT la foto si trovava dentro un repository creato dalla stessa IFTTT. 
In questo caso nostro, dove potrebbe essere il repo che ospita la foto e la visualizza sulla cella dello spreadsheet?

**Comment by cirospat** [comment]
per ora chiudo issue
