### ISSUE TITLE
Aggiornare immagine di un link su Telegram

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#214]
Ho aggiornato da tempo l'immagine social su GitHub di un [repository](https://github.com/pigreco/QGIS_portable_3x), ma nonostante questo, l'immagine nei post su Telegram è quella vecchia: come ovviare al problema?

![image](https://user-images.githubusercontent.com/7631137/168466073-88b65df5-ab63-4180-8ca6-6042fc80c05b.png)

**Comment by gbvitrano** [comment]
Le immagini di anteprima dei link su telegram vengono archiviate nella cache, per aggiornale basta seguire questi 3 semplici passaggi
- accedere al canale BOT [telegram.me/webpagebot](https://telegram.me/webpagebot) 
- inserire il link che si vuole aggiornare 
- Cliccare sul pulsante “Update Preview again” e attendi il caricamento dell’anteprima.

[Fonte](https://www.mirkomaiorano.it/come-aggiornare-anteprima-dei-link-pubblicati-sui-social-network/#Come_aggiornare_lanteprima_in_cache_di_un_link_su_Telegram)

**Comment by pigreco** [comment]
wow, funziona benissimo, grazie mille!!!

![image](https://user-images.githubusercontent.com/7631137/168466171-a1b53fc3-cd84-4d1c-af79-480fe2357c99.png)

**Comment by pigreco** [comment]
Ricetta fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/utilities/aggiornare_anteprima_social_telegram/
