### ISSUE TITLE
[gsheet] query: come aggiungere gli alias/label alle colonne calcolate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#216]
Ho la seguente query:

```
=query(raw!1:1000,"select A,D,(G/125000),(H/125000) ",-1)
```

che restituisce:

![image](https://user-images.githubusercontent.com/7631137/169658572-91eeac9f-7879-490f-bc2f-a81f5783a4cb.png)

come posso fare per leggere nella colonna C `Download` e nella colonna D `Upload`?
Non trovo facilmente la documentazione su questo argomento!

**Comment by dennisangemi** [comment]
@pigreco mi condividi uno sheet per favore? 

Dovrebbe essere una cosa del tipo

=query(raw!1:1000,"select A,D,(G/125000),(H/125000) label G/125000 'Download',  H/125000) 'upload'",-1)

**Comment by pigreco** [comment]
> Dovrebbe essere una cosa del tipo
> 
> `=query(raw!1:1000,"select A,D,(G/125000),(H/125000) label G/125000 'Download', H/125000 'upload' ",-1)`

che rapidità!

Esatto, funziona.
Quindi concordi con me che la documentazione su questo argomento è carente?

**Comment by pigreco** [comment]
@dennisangemi 
ecco il mio sheet

https://docs.google.com/spreadsheets/d/191kBuYNshHXveASP6uFqsa9snfEO-jyOevkH7yjHTEg/edit?usp=sharing

**Comment by dennisangemi** [comment]
> Quindi concordi con me che la documentazione su questo argomento è carente?

Yes! Ricordo che tempo fa "ci ho sbattuto" e mi sono appuntato sta cosa

**Comment by dennisangemi** [comment]
> @dennisangemi ecco il mio sheet
> https://docs.google.com/spreadsheets/d/191kBuYNshHXveASP6uFqsa9snfEO-jyOevkH7yjHTEg/edit?usp=sharing

Se funziona, non lo apro ;)

**Comment by pigreco** [comment]
> Yes! Ricordo che tempo fa "ci ho sbattuto" e mi sono appuntato sta cosa

ora la fissiamo come ricetta!!!

Grazie @dennisangemi

**Comment by pigreco** [comment]
Ricetta fata e pubblicata

https://tansignari.opendatasicilia.it/ricette/utilities/gsheet_label_query/
