### ISSUE TITLE
Operazioni Pianificate in Win 10 Pro

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#217]
Con il Task Scheduler di Win 10 è possibile pianificare delle azioni da avviare secondo i nostri desiceri.

Ho creato due azioni, la prima funziona perfettamente la seconda no:

1. avviare esecuzione di uno script bash (`C:\Windows\System32\wsl.exe` ; `/mnt/d/GitHub/speedtest-parabola/script/script.sh`) ogni mattina, e la ripete ogni 30 minuti (funziona);
2. avviare esecuzione di uno script bash (`"C:\Program Files\Git\git-bash.exe"` ; `/d/GitHub/speedtest-parabola/script/script_push.sh`) ogni mattina, e la ripete ogni 30 minuti (non funziona);

il primo script è questo:

```
#!/bin/bash

# crea variabili
data=`date +"%Y-%m-%dT%H:%M:%S%:z"`
valori=`speedtest -f csv`
# concatena
record=$data,$valori
# salva i record
echo $record >>/mnt/d/GitHub/speedtest-parabola/output/toto-migliorato.csv 2>&1
```

quello che non si avvia, ma non capisco se dovuto allo script o ad altro:

```
#!/bin/bash

git add -A -- "D:\GitHub\speedtest-parabola\output\toto-migliorato.csv"
git commit -m "update"
git push
```
(questo secondo script esegue un commit verso un repository)

avviandolo manualmente  `"C:\Program Files\Git\git-bash.exe"` e questo `/d/GitHub/speedtest-parabola/script/script_push.sh` funziona perfettamente.

il repository collegato:

https://github.com/pigreco/speedtest-parabola

**Comment by aborruso** [comment]
@pigreco quando lanci `script_push.sh` da Linux WSL funziona?

Se sì, perché passi da `git-bash`? Non potresti lanciare di nuovo `C:\Windows\System32\wsl.exe ; /mnt/d/GitHub/speedtest-parabola/script/script_push.sh`?

**Comment by aborruso** [comment]
> forse dovrei installare `git` sotto WSL?

no, fermati, per ora era un primo dubbio

**Comment by pigreco** [comment]
@aborruso 
ma c'è... è già installato

![image](https://user-images.githubusercontent.com/7631137/173314436-2371d43e-5c3a-460a-a1a7-8348a030909b.png)

**Comment by aborruso** [comment]
non uso le operazioni pianificate da un po'. Quando dici che non funziona, lo dici perché non vedi gli esiti o perché hai un log di errore nelle opereazioni pianificate? E se sì, quale errore?

**Comment by pigreco** [comment]
> Quando dici che non funziona

nessun esito, ovvero non fa il commit

devo rettificare una cosa, la seconda azione funziona solo se avviata cosi:

![image](https://user-images.githubusercontent.com/7631137/173315627-3aa74315-86d3-44a5-9d6b-42305e01cc77.png)


quindi credo sia un problema di percorsi

**Comment by aborruso** [comment]
> devo rettificare una cosa, la seconda azione funziona solo se avviata cosi:

quindi non funziona nemmeno la seconda tramite operazione pianificata, ma soltanto se apri la shell ed esegui tu i comandi?

**Comment by pigreco** [comment]
> quindi non funziona nemmeno la seconda tramite operazione pianificata, ma soltanto se apri la shell ed esegui tu i comandi?

esatto, funziona se faccio cosi:

1. avvio manualmente `C:\Program Files\Git\git-bash.exe`
2. scrivo uno dopo l'altro:

```
git add -A -- "D:\GitHub\speedtest-parabola\output\toto-migliorato.csv"
git commit -m "update"
git push
```

**Comment by pigreco** [comment]
Ho modificato la pianificazione avviando uno script bath al posto di un 'vero' programma, sotto lo script:

```bat
@echo off
C:\Program Files\Git\git-bash.exe
cd /d/GitHub/speedtest-parabola/script
git add -A -- "D:\GitHub\speedtest-parabola\output\toto-migliorato.csv"
git commit -m "update"
git push
```

però, se avvio lo script con doppio clic, alloro funziona bene;
ma se lo pianifico non funziona

**Comment by pigreco** [comment]
finalmente ho capito,
![image](https://user-images.githubusercontent.com/7631137/173417179-2009bf9f-2e40-4294-a67b-ae41fd678059.png)
 e funziona!!!

**Comment by aborruso** [comment]
@pigreco bravo

**Comment by pigreco** [comment]
ricetta pubblicata

https://tansignari.opendatasicilia.it/ricette/utilities/creare_attivita_pianificate_win/
