### ISSUE TITLE
[ogr2ogr] sintassi per fare una join tra due shapefile

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#218]
Ho due shapefile identici (`test1.shp`, `test2.shp`) come struttura dati e numero di righe:

ID, nome, valore

ho usato questa sintassi per fare una JOIN tra i due shapefile (devo unire il campo `valore`):

```
ogr2ogr -sql "select test1.*, test2.valore AS cucu FROM test1 JOIN './test2.shp'.test2 ON test1.valore = 'test2.shp'.valore" ./test.shp ./test1.shp
```

il file `test.shp` dovrebbe essere il terzo shapefile con la JOIN

errore:

```
ERROR 1: SQL Expression Parsing Error: syntax error, unexpected '.', expecting end of string. Occurred around :
shp'.test2 ON test1.valore = 'test2.shp'.valore
```

![image](https://user-images.githubusercontent.com/7631137/174774693-7e4b332b-22c9-4a9e-9468-3b089c1dbe56.png)

dati:
[andrea.zip](https://github.com/opendatasicilia/tansignari/files/8947840/andrea.zip)

![image](https://user-images.githubusercontent.com/7631137/174774253-03ff5978-bc11-4da6-a8e7-19d39c7cb4dc.png)

**Comment by pigreco** [comment]
Ho fatto altri test e qualche passo avanti:

il comando di sotto sembra funzionare parzialmente (non ho più errori), però non capisco perché non aggiunge i valori nel campo unito:

```
ogr2ogr -sql "select t1.*, t2.valore FROM test1 t1 JOIN './test2.shp'.test2 t2 ON t1.valore=t2.valore" ./testk.shp ./test1.shp
```

ecco output

![image](https://user-images.githubusercontent.com/7631137/175114695-60ac16af-83ed-4324-b3e7-ad375700a368.png)

**Comment by pigreco** [comment]
Ho capito, errore mio, il comando corretto è:

```
ogr2ogr -sql "select t1.*, t2.valore FROM test1 t1 LEFT JOIN './test2.shp'.test2 t2 ON t1.id=t2.id" ./testkk.shp ./test1.shp
```

![image](https://user-images.githubusercontent.com/7631137/175116887-e0820132-ba91-4624-ab76-d156e7e3526a.png)

**Comment by aborruso** [comment]
Grande Totò.

Mi spiace non avere potuto darti supporto, ma ero certo che avresti trovato la soluzione

**Comment by pigreco** [comment]
ricetta pubblicata

https://tansignari.opendatasicilia.it/ricette/bash/sintassi_join_ogr/
