### ISSUE TITLE
[frictionless] descrivere e validare json

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari#224]
Buongiorno! Sarei interessato alla descrizione e validazione di più file json ma non riesco ad utilizzare frictionless così come lo utilizzo per i csv. 

Se lancio

```bash
frictionless describe sources.json
```

ottengo questo errore
```
[resource-error] The data resource has an error: cannot extract metadata "sources.json" because ""
```

(ho installato `frictionless[json]`)

L'unica documentazione che ho trovato in rete è [questa](https://framework.frictionlessdata.io/docs/tutorials/formats/json-tutorial/) ma fa riferimento solo a python e non a cli.

Grazie in anticipo <3

**Comment by aborruso** [comment]
Ho messo nota qui https://arigadicomando.it/frictionless/ricette/#validare-un-file-json

**Comment by dennisangemi** [comment]
Grazie mille @aborruso, ho fatto come consigliato da te e funziona tutto perfettamente. Lascio aperto così appena ho 5 min di tempo scrivo ricetta

**Comment by aborruso** [comment]
5 minuti, solo 5 vedrai .... :)

**Comment by dennisangemi** [comment]
@aborruso i famosi 5 minuti sono arrivati haha

Credo di aver sbagliato qualcosa nella pubblicazione della ricetta perchè non risulta online https://tansignari.opendatasicilia.it/ricette/utilities/descrivere_json_frictionless

**Comment by aborruso** [comment]
> Credo di aver sbagliato qualcosa nella pubblicazione della ricetta perchè non risulta online

Non riesco a capire perché. Secondo tansignari ti vuole fare dei dispetti, pensava ti fossi dimenticato di lei/lui

**Comment by aborruso** [comment]
@pigreco ci butti un occhio tu, che ormai sei il più esperto??

Sarà una cosa da niente, ma non la vedo

**Comment by dennisangemi** [comment]
hai fatto qualcosa @pigreco ?

**Comment by pigreco** [comment]
@dennisangemi 
> hai fatto qualcosa @pigreco ?

nulla, solo aperto ricetta in `vscode`, ma non ho fatto commit

**Comment by aborruso** [comment]
> hai fatto qualcosa @pigreco ?

Yes, ha fatto la merge request https://github.com/opendatasicilia/tansignari-md/commit/317c07af4d4c65a327b58e6dd39bb715adb57da8

Io ieri non avevo visto la PR https://github.com/opendatasicilia/tansignari-md/pull/81

**Comment by dennisangemi** [comment]
Ma io non credo di aver fatto PR 😶

**Comment by aborruso** [comment]
È qui la PR https://github.com/opendatasicilia/tansignari-md/pull/81
