### ISSUE TITLE
[licenza] mappa storica di Firenze

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#226]
In Wikipedia Commons questa immagine sembra essere di pubblico dominio, vedi [permission](https://commons.wikimedia.org/wiki/File:1847_Molini_Pocket_Map_of_Florence_(Frienze),_Italy_-_Geographicus_-_Firenze-molini-1847.jpg)
![image](https://user-images.githubusercontent.com/7631137/188634597-8a2e8f0a-1aa3-4135-8fc1-661d122972fc.png)

Ma ho un dubbio, è possibile utilizzarla in parte come sfondo dello splashscreen di [QGIS ](https://www.qgis.org/it/site/)(è un software Open Source)?
sotto una bozza dell'ipotetico uso nello splashscreen

![photo_2022-09-04_13-56-31](https://user-images.githubusercontent.com/7631137/188635522-b83eb374-a8dc-4d00-8da9-b68d86b6834c.jpg)

**Comment by aborruso** [comment]
È in pubblico dominio, puoi andare sereno
