### ISSUE TITLE
 [GIS] Mappa QGIS per  #QGISUserConf2019

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#23]
Buon dì, vorrei realizzare una mappa per #QGISUserConf2019 usando i dati di @pigreco che gentilmente  ha reso disponibili nel [repository](https://github.com/pigreco/QGISUserConf2019)

Visto che gli utenti vengono da ogni parte del mondo, l'idea è quella di fare  una sorta di mappa di flusso in entrata a A Coruña (Spain) 

Un esempio su [Palermo](http://u.osmfr.org/m/131321/)  fatto con i dati Istat.

Come trasformo i dati di base per ottenere le linee di flusso in entrata A Coruña ?

**Comment by aborruso** [comment]
Ciao GB, a partire dalla tabella con le coordinate un modo per farlo è creare un colonna con la rappresentazione wkt  delle linee, con Coruna come primo punto.
E poi è soltanto un fatto di import/trasformazione.

Una linea in wkt è
LINESTRING (30 12, 11 30, ...).

**Comment by aborruso** [comment]
@gbvitrano a proposito della tua mappa ecco dati sul pendolarismo aggiornati http://www.corteconti.it/servizi/cruscotti_opencdc/?fbclid=IwAR1a_JSdQ-_jTZEjT6E4ZT3o56kq_8TZQ3A6gnda3M9HtjHvH1f2iE29Ckc

**Comment by pigreco** [comment]
Ciao @gbvitrano 
un altro modo per creare le linee che uniscono `A Coruña` con tutte le altre City - usando QGIS - è quella di utilizzare i [`Virtual Layer`](https://pigrecoinfinito.wordpress.com/2016/04/06/qgis-virtual-layer/), questi permettono di creare un nuovo layer (partendo da altri layer caricati nella TOC di QGIS) mediante SQL (dialetto Spatialite) in particolare usando questa query:

```SQL
SELECT t2.City, make_line(t1.geometry, t2.geometry) AS geom
FROM (SELECT * FROM "geocoding_QGIS" WHERE City = 'A Coruña' AND fid = 6) t1 , "geocoding_QGIS" t2
WHERE t1.fid!=t2.fid;
```
DOVE:
`geocoding_QGIS` è il file CSV importato in un geopackage in quanto ci serve in FID univoco;

il risultato è questo:

![image](https://user-images.githubusercontent.com/7631137/53575482-ef153b00-3b71-11e9-9367-085a5f695f95.png)

---
Un altro modo usando gli **_strumenti di processing_** di QGIS e l'algoritmo `Unisci con linee (hub) `

otterresti:
![image](https://user-images.githubusercontent.com/7631137/53577374-d575f280-3b75-11e9-8a48-a6d3f922edfc.png)

i parametri da usare sono questi:
![image](https://user-images.githubusercontent.com/7631137/53577474-0524fa80-3b76-11e9-8cae-a3e622843433.png)

1. geopackage con tutti i punti City e un campo `cucu` con valore unico, io ho messo 1;
2. `cucu` campo integer con valore costante uguale, io ho usato 1;
3. vettore puntuale con un solo punto `A Coruña` e con FID = 1; (puoi crearlo velocemente con il plugin [Geocoding](https://plugins.qgis.org/plugins/GeoCoding/)
4. campo univoco del vettore nel punto 3)  precedente;
5. poi, se vuoi tracciate delle `geodetiche` metti lo spunto.

![image](https://user-images.githubusercontent.com/7631137/53577969-ec691480-3b76-11e9-949c-6619d166db26.png)

ciao

**Comment by pigreco** [comment]
@aborruso @gbvitrano 
ecco come realizzare la soluzione di Andy con QGIS:
![image](https://user-images.githubusercontent.com/7631137/53582154-39e97f80-3b7f-11e9-92e2-4b0662674f03.png)

![image](https://user-images.githubusercontent.com/7631137/53582299-7ddc8480-3b7f-11e9-895d-7bcac10d84c3.png)

**Comment by gbvitrano** [comment]
Grazie Grazie :-)

**Comment by pigreco** [comment]
Esempio nro 26 nella Guida HfcQGIS by ODS in RTD

http://hfcqgis.opendatasicilia.it/it/latest/esempi/hub_lines.html

**Comment by gbvitrano** [comment]
Grazie al vostro aiuto sono riuscito a realizzare la mappa :-)

![qgisuser_01](https://user-images.githubusercontent.com/20488693/53603229-25be7600-3bb1-11e9-90a7-c1b97d196059.jpg)

![qgisuser_02](https://user-images.githubusercontent.com/20488693/53603233-28b96680-3bb1-11e9-97ce-8ce9771ce80a.jpg)
