### ISSUE TITLE
[regex] acchiappare il primo carattere, presente più volte, in una stringa

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#231]
Ho delle stringhe cosi fatte:

```
PR.CS|12|CS
PR.CS|1|CrS
PR.CS|35|Ce
```
e dovrei ottenere questo risultato:
```
PR.CS12|CS
PR.CS1|CrS
PR.CS35|Ce
```
ovvero, eliminare il primo `|` di ogni stringa.

Sono sicuro che esiste un modo più elegante di quello che ho usato:

```
(.+)(\|)(.+)(\|)(.+)
```
link: https://regex101.com/r/bJHx2s/1

**Comment by aborruso** [comment]
Ciao @pigreco io mapperei tutto così `^(.+?)(\|)(.+)$`

E poi fai il trova e sostituisci del caso https://regex101.com/r/aF37lv/1

**Comment by aborruso** [comment]
Il tema teorico chiave è quello delle regex 'lazy' e 'greedy' https://stackoverflow.com/a/2301298/757714

Quelle lazy si fermano alla prima occorrenza. Trovi centinaia di tutorial a tema.

**Comment by pigreco** [comment]
@aborruso grazie mille.

ricetta fata e pubblicata

https://tansignari.opendatasicilia.it/ricette/regex/selezionare_prima_occorrenza/
