### ISSUE TITLE
Da CSV su GitHub a spreadsheet excel.

### ISSUE THREAD

**Issue by CT-igiul** [opendatasicilia/tansignari#233]
Buongiorno a tutti,
Esiste una procedura che importa automaticamente un file CSV di GitHub in un foglio di lavoro excel quando viene aperto. IAW, si può collegare su GitHub un file CSV un qualsiasi file esterno?
Grazie 
Luigi

**Comment by gbvitrano** [comment]
Esempio con il file [PA Digitale 2026 PNRR](https://raw.githubusercontent.com/teamdigitale/padigitale2026-opendata/main/data/candidature_comuni_finanziate.csv)
![2022-11-30_14h38_16](https://user-images.githubusercontent.com/20488693/204811041-d958cd58-0baf-4fd0-b32b-695f92d06471.png)
![2022-11-30_14h38_41](https://user-images.githubusercontent.com/20488693/204811048-add83dbf-134e-45ff-8de0-02954a7c589e.png)

**Comment by aborruso** [comment]
@CT-igiul hai provato? Come è andata?

Hai risolto il altro modo
