### ISSUE TITLE
[script] Estrarre righe e mettere in colonne

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#234]
Ho un file testuale (il file è il risultato del comando `ogrinfo -al -so DBGT_10K_22_V01.gdb`) con migliaia di righe e vorrei estrarre le sole righe che iniziano con 
- `Layer name`
- `Feature count`
- `Geometry`
e creare un file csv con la seguente struttura:

layer_name | feature_count | geometry
-------------|----------------|-----------
pippo | 123 | None
pluto  | 12345 | 3D Multi Polygon

file:
[cucu_dbgt.csv](https://github.com/opendatasicilia/tansignari/files/10192656/cucu_dbgt.csv)

io riesco ad estrarre le singole righe usando:

`grep "Layer name" nomefile.csv`
`grep "Feature count" nomefile.csv`
`grep "Geometry" nomefile.csv`

ma non ho idea di come metterle assieme in un csv tramite uno script

PS: il [DBGT_10K_22_V01.gdb](https://www.sardegnageoportale.it/index.php?xsl=2420&s=40&v=9&c=95645&na=1&n=10&esp=1&tb=14401) (pesa oltre 5GB)

**Comment by aborruso** [comment]
Caro @pigreco con ogr 3.7 c'è finalmente l'output in JSON, quindi le info saranno dati e quindi sarà facilissimo ottenere quello che vuoi.

Adesso ogrinfo è un flusso di testo, strutturato, ma un po' scomodo.

A riga di comando si può fare in mille modi. Guardando la struttura penso a uno dei formati di Miller, l'[XTAB](https://miller.readthedocs.io/en/latest/file-formats/#xtab-vertical-tabular), che ricorda un po' quell'output. È fatto infatti così (di default non ci sono i `:`)

```
Layer name    PROVIN
Geometry      None
Feature Count 5

Layer name    PROVIN_PROVIN_NOM_T
Geometry      None
Feature Count 5
```
E alloro sfrutterei la cosa

```bash
# rimuovi prime righe inutili
<cucu_dbgt.csv tail -n +4 | \
# estrai soltanto le righe che servono e le righe bianche
grep -P '^(Layer na.+|Geometry:.+|Feature Count:.+|.{0,1})$' | \
# converti output in CSV
mlr --x2c --ips : clean-whitespace >cucu_dbgt_a.csv
```

Il comando miller:

- `--x2c`, per fissare come formato di input l'XTAB e come output il CSV
- `--ips :`, per fissare come separatore di coppie chiave valore, in input, i `:`
- `clean-whitespace`, per rimuovere spazi ridondanti.

Fammi sapere, che ho fatto di corsa

**Comment by pigreco** [comment]
@aborruso 
ottimo!!!
sotto il risultato, grazie mille(r)
![image](https://user-images.githubusercontent.com/7631137/206661419-31b44f0e-d403-4a05-8d9e-669de081919b.png)

**Comment by aborruso** [comment]
@pigreco in questo caso la mia modalità non è comodamente applicabile.

E farei qualcosa come:

- estrazione dei nomi dei layer;
- per ogni layer un query con ogr2ogr che mi dia in output (ad esempio in formato CSV) quello che serve

**Comment by pigreco** [comment]
> in questo caso la mia modalità non è comodamente applicabile.

ok, allora chiudo issue ;-)

**Comment by pigreco** [comment]
Ricetta fatta e pubblicata:

https://tansignari.opendatasicilia.it/ricette/bash/estrarre_righe_e_emetterle_in_colonne/

chiudo, grazie

**Comment by aborruso** [comment]
Grande
