### ISSUE TITLE
[ogr2ogr] le join sono molto lente, come velocizzarle

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#235]
Il seguente costrutto permette di fare una join tabellare tra uno **shapefile** e una tabella **dbf**; entrambi i file hanno meno di 3000 record, ma la join impiega oltre 40 secondi.

```
time ogr2ogr -progress -sql "select s.AC_VEI_SED AS AC_VEI_SED, s.ClassREF AS ClassREF, t.ZON_IN_TY AS ZON_IN_TY, t.ID AS ID, t.FONTE AS FONTE, t.LIVELLO AS LIVELLO from butta15a_Dissolve1 s left join './id15a_to_ZON_IN_12113_t.dbf'.id15a_to_ZON_IN_12113_t t on s.FIRST_SubR = t.SubRegID" ./shape_join4.shp ./butta15a_Dissolve1.shp
```

ho letto [qui ](https://gdal.org/user/ogr_sql_dialect.html#create-index)che è possibile velocizzare le join creando un indice:

```
ogrinfo -sql "CREATE INDEX ON butta15a_Dissolve1 USING FIRST_SubR" ./butta15a_Dissolve1.shp
```

ma non noto benefici, anzi sembra che impieghi più tempo, dai 46 sec a 48 sec.

cosa sbaglio?

forse l'indice va creato su entrambi i campi correlati?
no, non migliora :-(

![image](https://user-images.githubusercontent.com/7631137/212553397-7ce4c2ce-be02-45ea-b762-f9e6b7bf3d73.png)

--

file: 
[dati_test.zip](https://github.com/opendatasicilia/tansignari/files/10420615/dati_test.zip)

uso `GDAL 3.4.0, released 2021/11/04` su Ubuntu 20.04

**Comment by aborruso** [comment]
Ciao @pigreco nel tuo file di esempio il file si chiama `butta15b_Dissolve1` e non `butta15a_Dissolve1`.

E inoltre manca proprio quello con estensione shp, manca `butta15b_Dissolve1.shp`.

Non ho capito qualcosa io?

**Comment by pigreco** [comment]
@aborruso 
> Non ho capito qualcosa io?

ho sbagliato a copiare, ecco i file corretti
[dati_test2.zip](https://github.com/opendatasicilia/tansignari/files/10420778/dati_test2.zip)

**Comment by aborruso** [comment]
Caro @pigreco il kernel linux sotto wsl, è ottimizzato per girare nelle cartelle linux di wsl.

La tua home linux la raggiungi con `cd ~`. Se dai poi `pwd` avrai la stampa del percorso (non serve, è soltanto per curiosità).

Crea qui una cartella di lavoro `mkdir -p tmp` e poi entraci dentro.
Una volta dentro puoi aprirla in esplora risorse e metterci i tuoi file (basta che dai `explorer.exe .` per aprire la cartella)

Rilancia il comando dalla shell da quella cartella (`~/tmp`).

Detto questo, ogr non è una scheggia per queste cose, specie con i dbf. Da me lo fa in circa 8 secondi.

Magari da spatialite è tutto più rapido

**Comment by aborruso** [comment]
Un'altra modalità potrebbe essere quella di estrarre il CSV da `id15a_to_ZON_IN_12113_t` e poi usare mapshaper per un join tra l'shp e il CSV.
Immagino che sia molto veloce

```
ogr2ogr -f "CSV" id15a_to_ZON_IN_12113_t.csv id15a_to_ZON_IN_12113_t.dbf
```

E poi un esempio generale di JOIN in mapshaper è 

```
mapshaper states.shp -join demographics.txt keys=STATE_FIPS,FIPS string-fields=FIPS -o out.shp
```

Con `string-fields` forzi eventuali campi da forzare come stringa, e con `keys` i campi chiave.

**Comment by pigreco** [comment]
Caro @aborruso, ricordo che me lo hai già spiegato varie volte, ma utilizzandolo poco lo scordo sempre:
> Da me lo fa in circa 8 secondi.

da me poco meno di 4 sec:

![image](https://user-images.githubusercontent.com/7631137/212560260-c136374c-b467-4a04-9426-87a8e2edcc1f.png)

**Comment by pigreco** [comment]
@aborruso 
> Un'altra modalità potrebbe essere quella di estrarre il CSV ...

è imbarazzante, meno di un secondo:

![image](https://user-images.githubusercontent.com/7631137/212561598-889c9500-8352-45cc-81a2-51b47081c405.png)

**Comment by aborruso** [comment]
Sarà una bella ricetta

**Comment by pigreco** [comment]
Ricetta fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/bash/velocizzare_una_join_tabellare/

grazie mille
chiudo
