### ISSUE TITLE
Primo lancio di questo spazio

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#24]
Buongiorno,
secondo me siamo pronti per partire:

- abbiamo una versione comprensibile del [README](https://github.com/opendatasicilia/tansignari/blob/master/README.md) (che possiamo usare come post di lancio);
- abbiamo una prima versione del [galateo](https://github.com/opendatasicilia/tansignari/blob/master/galateo.md).

Che dite?

**Comment by pigreco** [comment]
Caro @aborruso 
dico che possiamo lanciare... sperando di 'colpire' più persone possibili.

grazie compare

**Comment by cirospat** [comment]
ok let's go

**Comment by aborruso** [comment]
Chiudo, domani mattina blog post

**Comment by ninokeys** [comment]
👏👏👏👏

Il giorno dom 3 mar 2019 alle 23:30 Andrea Borruso <notifications@github.com>
ha scritto:
