### ISSUE TITLE
[Miller] filtro con espressione

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#243]
Ho un file CSV così fatto:

![image](https://user-images.githubusercontent.com/7631137/218254924-789e1976-d95d-45e4-9554-67476374a0fa.png)

nella colonna `geom_type` ci sono vari valori (none, PointZ, MultiPolygonZ, MultiLineStringZM, ecc...)
dovrei raggruppare le righe che, nella colonna `geom_type`, hanno valori che contengono i seguenti termini:
- `none`
- `Point`
- `Line`
- `Polygon`

ho usato un filtro con Miller, ma usando `||` (or) devo scrivere tutti i vari casi possibili, sotto un esempio:
```
mlr --csv unsparsify then put 'filter $geom_type=="MultiPolygon" || $geom_type=="MultiPolygonZ" || $geom_type=="MultiPolygonZM"'
```

c'è un modo più snello?

[out2.csv](https://github.com/opendatasicilia/tansignari/files/10713470/out2.csv)

**Comment by aborruso** [comment]
Totò, le espressioni regolari ci sono anche qui.

Visto che non vuoi `MultiPolygonM`, potresti scrivere

```
mlr --csv filter '$geom_type=~"^MultiPolygon(Z|ZM)*$"' out2.csv
```

**Comment by aborruso** [comment]
> dovrei raggruppare le righe che, nella colonna `geom_type`, hanno valori che contengono i seguenti termini:

Non ho capito però l'obiettivo. In che senso raggruppare? Mi aggiungi un esempio di output?

**Comment by pigreco** [comment]
> Mi aggiungi un esempio di output?

qui un esempio di output per il caso `Polygon`

![image](https://user-images.githubusercontent.com/7631137/218255908-61bd3229-7cb9-4316-89c1-4978b77601a5.png)

**Comment by aborruso** [comment]
Quindi non vuoi raggruppare, ma soltanto filtrare. Ad esempio tutti i poligoni?

Se sì, puoi usare le regex

**Comment by pigreco** [comment]
@aborruso 
come faccio a fare espandere la variabile nel ciclo FOR?

```
for i in none Line Point Polygon; do
<out.json jq  -c '.layers[]|{name:.name,geom_type:(if (.geometryFields|length) > 0 then .geometryFields[].type else "none" end) }' |  mlr --ijsonl --ocsv unsparsify then filter '$geom_type=~"^.{0,}$i.{0,}$"'>output2/classe_$i.txt
done
```

lo script di sopra non va, non vede la `$i` dentro `$geom_type=~"^.{0,}$i.{0,}$"'`

**Comment by aborruso** [comment]
Devi attenerti alle regole del bash e fare attenzione ai caratteri speciali. Ti faccio un esempio con il CSV

```bash
for i in Line Point;do
<out2.csv  mlrgo --csv unsparsify then filter '$geom_type=~"'"$i"'"';
done
```

Perché questo strano `'"$i"'`?

- per fare esplodere una variabile, devi metterla tra virgolette > `"$i"`
- ma sei dentro apici singoli, sei dentro `'`, e lì dentro la variabile tra `"` non viene esplosa
- allora devi fare l'escape da `'` con una coppia di `'` > `'"$i"'`

**Comment by pigreco** [comment]
@aborruso grazie,

per me ha funzionato così:

```sh
#!/bin/bash

set -x
set -e
set -u
set -o pipefail

# lista valori::
# ogrinfo -so "D:\GitHub\ESRI_FileGeodatabase_GDAL\dati\DBGT_10K_22_V01.gdb"

# crea cartella di output
mkdir -p ./output2

# per ogni oggetto
for i in none Line Point Polygon; do
<out.json jq  -c '.layers[]|{name:.name,geom_type:(if (.geometryFields|length) > 0 then .geometryFields[].type else "none" end) }' |  mlr --ijsonl --ocsv unsparsify then filter '$geom_type=~"^.{0,}'"$i"'.{0,}$"'>output2/classe_$i.txt
done
```

**Comment by aborruso** [comment]
Esatto, dovevi applicare quanto ti ho scritto, altrimenti la variabile non si sarebbe espansa

**Comment by pigreco** [comment]
ricetta fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/bash/filtro_regex_con_miller/
