### ISSUE TITLE
[Miller] da enne righe a una riga

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#245]
Ho il seguente file csv con enne righe:

```
CL_AGR_CL_AGR_SUP
AATT
EDIFC_CR_EDF_ME_SR
EDIFC_CR_EDF_ME
EDIFC_CR_EDF_IS
BOSCO_BOSCO_SUP_SR
BOSCO
AC_VEI_AC_VEI_SUP_SR
AR_STR_AR_STR_SUP_SR
EDI_MIN_CR_EDF_ME_SR
EDI_MIN_CR_EDF_ME
EDI_MIN_CR_EDF_IS
ELE_CP
AC_VEI
```
e devo ottenere una sola riga, come sotto (separatore un spazio):

```
CL_AGR_CL_AGR_SUP AATT EDIFC_CR_EDF_ME_SR EDIFC_CR_EDF_ME EDIFC_CR_EDF_IS BOSCO_BOSCO_SUP_SR BOSCO AC_VEI_AC_VEI_SUP_SR AR_STR_AR_STR_SUP_SR EDI_MIN_CR_EDF_ME_SR EDI_MIN_CR_EDF_ME EDI_MIN_CR_EDF_IS ELE_CP AC_VEI
```

per far ciò utilizzo:

```
paste -s -d" " unica_linea.txt
```

come fare usando Miller?
[unica_linea.txt](https://github.com/opendatasicilia/tansignari/files/10716428/unica_linea.txt)

**Comment by pigreco** [comment]
con questo riesco a farlo, ma il file txt, essendo senza intestazione, devo aggiungerla con `--implicit-csv-header` ma il valore rimane:

```
mlr --csv --implicit-csv-header nest --ivar " " -f 1 unica_linea.txt
```

output:

```
1
CL_AGR_CL_AGR_SUP AATT EDIFC_CR_EDF_ME_SR EDIFC_CR_EDF_ME EDIFC_CR_EDF_IS BOSCO_BOSCO_SUP_SR BOSCO AC_VEI_AC_VEI_SUP_SR AR_STR_AR_STR_SUP_SR EDI_MIN_CR_EDF_ME_SR EDI_MIN_CR_EDF_ME EDI_MIN_CR_EDF_IS ELE_CP AC_VEI
```

**Comment by aborruso** [comment]
Ecco, ti stavo dicendo le regole di base: tu che test hai fatto?

Ottimo spunto, il modo per farlo è quello. Ci sono tanti flag preziosi: uno è `-N`, che imposta il "senza intestazione" sia in input che in output

```
mlr --csv -N nest --ivar " " -f 1 unica_linea.txt
```

**Comment by aborruso** [comment]
I flag https://miller.readthedocs.io/en/latest/reference-main-flag-list/index.html

**Comment by pigreco** [comment]
grazie Mille(r) @aborruso

**Comment by aborruso** [comment]
> grazie Mille(r) @aborruso

e la ricetta?

**Comment by pigreco** [comment]
> e la ricetta?

ops, ho cliccato nel bottone sbagliato

**Comment by pigreco** [comment]
ricetta fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/bash/da_enne_righe_a_una_miller/

**Comment by aborruso** [comment]
Applausi
