### ISSUE TITLE
[ogr2ogr] come far leggere la lista dei layer da importare da un file di testo

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#246]
Il seguente costrutto importa i layer `AC_CIC_AC_CIC_SUP_SR AR_VRD_AR_VRD_SUP EDIFC_CR_EDF_IS AR_STR_AR_STR_SUP_SR CANALE_CANALE_BSU ` da un FileGDB ad un altro:

```
ogr2ogr -f "OpenFileGDB" -progress x_Andy_only_Polygon.gdb "D:\GitHub\ESRI_FileGeodatabase_GDAL\dati\DBGT_10K_22_V01.gdb" AC_CIC_AC_CIC_SUP_SR AR_VRD_AR_VRD_SUP EDIFC_CR_EDF_IS AR_STR_AR_STR_SUP_SR CANALE_CANALE_BSU  -lco FEATURE_DATASET=sardegna
```

la lista dei layer da importare è l'output di un altro script che crea un file `lista_layer.txt`;
ho provato ad eseguire il seguente script:

```
ogr2ogr -f "OpenFileGDB" -progress x_Andy_only_Polygon_pesanti.gdb "D:\GitHub\ESRI_FileGeodatabase_GDAL\dati\DBGT_10K_22_V01.gdb" lista_layer.txt -lco FEATURE_DATASET=sardegna
```

dove al posto dell'elenco dei layer ho messo il file `lista_layer.txt`, ma ottengo un errore:

![image](https://user-images.githubusercontent.com/7631137/218327305-85dcb050-659c-4b5b-9e74-1ef03cf0f5c8.png)

il file è presente, ma come ovviare al problema?
purtroppo sono sotto windows, c'è un modo di far leggere a `ogr` la lista dei layer da un file?

**Comment by pigreco** [comment]
In batch:

- per stampare un file a video, si utilizza `type lista_layer.txt` che equivale al `cat lista_layer.txt` in bash
- per creare la variabile `lista` si utilizza `set lista= type lista_layer.txt`
- per stampare la variabile a video: `%lista%`

se utilizzo questi concetti:

```
ogr2ogr -f "OpenFileGDB" -progress x_Andy_only_Polygon_pesanti.gdb "D:\GitHub\ESRI_FileGeodatabase_GDAL\dati\DBGT_10K_22_V01.gdb" %lista% -lco FEATURE_DATASET=sardegna
```

errore:

![image](https://user-images.githubusercontent.com/7631137/218330699-b3a92b7c-98d0-4b0d-a349-8434a27bb91a.png)

**Comment by pigreco** [comment]
qui qualcosa di utile:
https://stackoverflow.com/questions/23521145/is-it-possible-to-pass-system-variables-to-ogr2ogr-in-batch-file

**Comment by aborruso** [comment]
Ciao @pigreco,
in bash hai tanti modi per raccogliere dati da un file esterno e renderli disponibili in uno script.

Uno semplice è questo. Immagina di avere il file `lista.txt`, che contiene `lorem ipsum`.

Crea uno script bash e usa una variabile per raccoglierne il contenuto in questo modo

```
lista=$(<./lista.txt)
```

A questo punto nello script esplodi la variabile lì dove ti serve

```
echo "Nell lista ci sono i valori: $lista"
```

E tu potrai mettere il tuo `$lista` laddove ti serve. Ricordandoti che la devi fare esplodere, degli eventuali escape, ecc..

Qui sotto uno script ciao mondo.

---

```bash
#!/bin/bash

lista=$(<./lista.txt)

echo "Nella lista ci sono i valori: $lista"
```

**Comment by pigreco** [comment]
Grazie @aborruso 
farò ulteriori test, ma sottolineo che sono su `batch` e non su `bash`

**Comment by aborruso** [comment]
> farò ulteriori test, ma sottolineo che sono su `batch` e non su `bash`

Ok, leggevo il subject e pensavo che non avessi vincoli di ambiente. Mi spiace

**Comment by pigreco** [comment]
altro link utile:
https://stackoverflow.com/questions/3068929/how-to-read-file-contents-into-a-variable-in-a-batch-file/3069068#3069068

**Comment by pigreco** [comment]
utilizzando quanto spiegato in questo [link](https://stackoverflow.com/questions/3068929/how-to-read-file-contents-into-a-variable-in-a-batch-file/3069068#3069068) ovvero creare la variabile in questo modo:

- `set /p lista2=<lista_layer.txt`
se stampassi la vairabile:
- `echo %lista2%` 

![image](https://user-images.githubusercontent.com/7631137/218433847-6edf59b1-d002-4598-8597-10c0b8ab9c9e.png)
 sembrerebbe ok, ma nel costrutto con `org` non va:

![image](https://user-images.githubusercontent.com/7631137/218434029-aa3a250c-d67f-4914-b202-25ad1a7a1def.png)
credo sia dovuto al fatto che la variabile racchiuda il testo tra virgolette.

**Comment by agiudiceandrea** [comment]
@pigreco qual è esattamente il contenuto del file `lista_layer.txt`? Da quello che vedo sembra che esso contenga già le virgolette.

**Comment by pigreco** [comment]
> qual è esattamente il contenuto del file `lista_layer.txt`?

[lista_layer.txt](https://github.com/opendatasicilia/tansignari/files/10729891/lista_layer.txt)

**Comment by pigreco** [comment]
@agiudiceandrea 
stamani rifaccio tutto:
1. `set /p lista2=<lista_layer.txt`
2. ogr2ogr -f "OpenFileGDB" -progress x_Andy_only_Polygon_pesanti.gdb "D:\GitHub\ESRI_FileGeodatabase_GDAL\dati\DBGT_10K_22_V01.gdb" %lista2% -lco FEATURE_DATASET=sardegna`

funziona!!! 
![image](https://user-images.githubusercontent.com/7631137/218671295-b42959eb-2521-4893-93f6-da6d2a6f41e1.png)

**Comment by agiudiceandrea** [comment]
Eseguendo il comando:
`set /p lista2=<lista_layer.txt`
e poi 
`echo %lista2%`
ottengo
```
CL_AGR_CL_AGR_SUP AATT EDIFC_CR_EDF_ME_SR EDIFC_CR_EDF_ME EDIFC_CR_EDF_IS BOSCO_BOSCO_SUP_SR BOSCO AC_VEI_AC_VEI_SUP_SR AR_STR_AR_STR_SUP_SR EDI_MIN_C
R_EDF_ME_SR EDI_MIN_CR_EDF_ME EDI_MIN_CR_EDF_IS ELE_CP AC_VEI
```

non:
```
"CL_AGR_CL_AGR_SUP AATT EDIFC_CR_EDF_ME_SR EDIFC_CR_EDF_ME EDIFC_CR_EDF_IS BOSCO_BOSCO_SUP_SR BOSCO AC_VEI_AC_VEI_SUP_SR AR_STR_AR_STR_SUP_SR EDI_MIN_C
R_EDF_ME_SR EDI_MIN_CR_EDF_ME EDI_MIN_CR_EDF_IS ELE_CP AC_VEI"
```
come nel tuo esempio.

**Comment by agiudiceandrea** [comment]
Quindi, quando hai eseguito il comando precedentemente e non ha funzionato, il file lista_layer.txt conteneva la stringa dei nomi dei layer racchiusa tra virgolette.

**Comment by agiudiceandrea** [comment]
L'"espansione" delle variabili nel command prompt di Windows non aggiunge virgolette al valore della variabile.

**Comment by pigreco** [comment]
@agiudiceandrea prima di scrivere una issue faccio molti test
e ti assicuro che le ho provate tutte, con apici e senza apici, forse quel screenshot riguardava il test con apici.

Stamani funziona, non so il perché, ti assicuro che avevo provato senza virgolette anche perché, il file `lista_layer.txt` è un output di un altro script.

Grazie per il tempo che ci hai dedicato.

**Comment by agiudiceandrea** [comment]
> Stamani funziona, non so il perché,

Evidentemente nelle varie prove che hai fatto c'è stata una svista e hai dimenticato di eliminare di virgolette che avevi aggiunto oppure hai dimenticato di riassegnare la variabile dopo aver eliminato le virgolette che avevi aggiunto o dopo aver ricreato il file senza virgolette...

**Comment by pigreco** [comment]
Ricetta fatta e pubblicata:

https://tansignari.opendatasicilia.it/ricette/bash/lista_layer_da_file_txt/
