### ISSUE TITLE
Mettere in collegamento automatico i moduli raccolta dati geografici di ONA con Google sheet

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#25]
supportato da @gbvitrano ho seguito le procedure per costruire un modulo su https://ona.io/ che mi consentisse di raccogliere informazioni geografiche soprattutto da mobile (testo, foto, latitudine-longitudine, ecc.).
Ho familiarizzato con il pannello di controllo sia per la costruzione del modulo che per la consultazione dei dati già raccolti grazie all'uso del modulo online usabile su browser.
Ho verificato, anche io dopo di voi, che il file di output in formato CSV che la piattaforma ONA produce non si aggiorna con i records derivanti dai continui data entry del modulo, quindi ad ogni data entry la piattaforma genera un nuovo CSV. Cosa che non consente di avere i dati costantemente aggiornati su un Google spreadsheet attraverso la funzione `=importdata`.
Esiste la funzione export file Google sheet ma una volta avviata (dopo aver agganciato il proprio account Google) da un errore:
![image](https://user-images.githubusercontent.com/3757525/53639311-20047700-3c29-11e9-899a-22f5ce5f0cc8.png)
che riporto di seguito.

```
Improperly formatted API response: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Ona</title>
    <meta name="description" content="Mobile data collection made easy. formhub is built on a belief that data collection and analysis should be fast, flexible and reliable. And open source, of course.">
    <meta name="author" content="">
    
    <meta name="google-site-verification" content="H0JRFrqLHnVfHuZaHRfz1Gmc5fub94N2Vd6RUufmgBg" />
    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    

    <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/screen.css?v=2809679b01" rel="stylesheet">
    <link href="/static/css/ona.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.0/css/font-awesome.css" rel="stylesheet">
    <!--[if lte IE 8]>
      <link href="//netdna.bootstrapcdn.com/font-awesome/3.0/css/font-awesome-ie7.css" rel="stylesheet">
    <![endif]-->
	  <link href="/static/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon.ico">
    <link rel="apple-touch-icon" href="/static/bootstrap/docs/assets/ico/bootstrap-apple-57x57.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/bootstrap/docs/assets/ico/bootstrap-apple-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/bootstrap/docs/assets/ico/bootstrap-apple-114x114.png">

    

    <!-- spot to insert stuff for google maps -->
    


  </head>

  
	

	<body style="padding-top: 20px !important">
		
<div id="language-bar" class="container">
<form action="/i18n/setlang/" method="post">
   <input type='hidden' name='csrfmiddlewaretoken' value='ARGwlyhtCGOjWK2BFw8Qc04nQlxi0w2Kh7ldclV5e45PM6pH57S8gX5bioY30xHI' />
   <input name="next" type="hidden" value="" />
   <select name="language" onchange="this.form.submit();">
      
      <option value="fr" >Français (fr)</option>
      
      <option value="en" selected="true" >English (en)</option>
      
      <option value="es" >Español (es)</option>
      
      <option value="it" >Italiano (it)</option>
      
      <option value="km" >ភាសាខ្មែរ (km)</option>
      
      <option value="ne" >नेपाली (ne)</option>
      
      <option value="nl" >Nederlands (nl)</option>
      
      <option value="zh" >中文 (zh)</option>
      
   </select>
</form>
</div>

		

<div class = "container">
	<div class=" row-fluid">
		<div class = "span12">
			<div class = "span2">
				<a class="brand" href="/" title="onadata"><img alt="onadata"
                    src="/static/images/onadata_logo.png" class="left"/></a>
			</div>
		<div class = "span8">
			<div class = "navigation">
				<ul id = "navlist">
					<li> <a href="/accounts/register/"> Sign Up </a> </li>
					<li> <a href="/forms/">Forms</a></li>
                    
					<li> <a href="/faq/"> FAQ </a> </li>
					<li> <a href="/support/">Support</a></li>
				</ul>
			</div>
		</div>
		<div class = "span2" id = "topbar_login"> <a href="/accounts/login/" class="btn btn-info pull-right" id="login_btn">Log In</a> </div>
		</div> <!-- Span 12 -->
	</div> <!-- row fluid -->
</div>



    <div class="container">
      
 
   
<h3>
	404 Error
</h3>

    </div>

    
<footer class="footer"> 
  <div class="container"> 
    <p>
        <a href="http://company.ona.io/">About Ona</a> | 
        <a href="/privacy">Privacy</a> | 
        <a href="/tos">Terms of Service</a> | 
        Copyright &copy; 2014 Ona
    </p>  
  </div> 
</footer> 
    

    <!-- Le javascript -->
	<script type="text/javascript" src="/jsi18n/"></script>
    <script src="/static/bower_components/jquery/jquery.min.js"></script>
    <script src="/static/bower_components/jquery/jquery-migrate.min.js"></script>
    <script src="/static/js/jquery.tablesorter.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <script src="/static/bootstrap/js/bootstrapx-clickover.js"></script>
    <script src="/static/bootstrap/js/bootstrapx-clickover-btns.js"></script>
    <script src="/static/js/application.js?v=201307251039"></script>

       
    
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-45510928-1', 'api.ona.io');
    ga('send', 'pageview');

    </script>
    

  </body>
  
</html>
```

Sarebbe utile capire come bypassare il problema di questo errore.
Grazie

**Comment by gbvitrano** [comment]
Occhio... Anche il Google sheet, se esportato con il pulsante export salva solo i dati al momento dell'esposizione, non resta collegato.
L'unico modo per collegarlo e mantenere i dati aggiornati è collegare Google shett come applicazione. Ed anche in quel caso mi da errore

**Comment by aborruso** [comment]
Buonasera,
al momento c'è un malfunzionamento su ona, perché normalmente è una cosa che si fa in un click.

Ma ona ha le [API](https://api.ona.io/static/docs/index.html), ed è possibile fare la "guerra".

Qui un primo esempio che potrebbe risolvere quanto richiesto.

Con `https://api.ona.io/api/v1/data?owner=nomeutente` si ha la lista dei progetti pubblici del signor "nomeutente".

Ad esempio [https://api.ona.io/api/v1/data?owner=gbvitrano](https://api.ona.io/api/v1/data?owner=gbvitrano) restituisce:

```json
[
  {
    "id": 386586,
    "id_string": "aKumLRpod6BV9NP5viye2u",
    "title": "Geolocalizza (form test)",
    "description": "form test per progetto Geolocalizza",
    "url": "https://api.ona.io/api/v1/data/386586"
  },
  {
    "id": 386670,
    "id_string": "aVXogAibtRyPggq7PhjF7v",
    "title": "Geolocalizzazione di...",
    "description": "",
    "url": "https://api.ona.io/api/v1/data/386670"
  },
  {
    "id": 387237,
    "id_string": "imp_publ_01",
    "title": "imp_publ",
    "description": "",
    "url": "https://api.ona.io/api/v1/data/387237"
  }
]
```

Se voglio i dati in CSV del progetto `Geolocalizza (form test)` (il primo), bisogna prendere il valore di `ulr` e aggiungere `.csv`, quindi [https://api.ona.io/api/v1/data/386586.csv](https://api.ona.io/api/v1/data/386586.csv).

Questo CSV sarà sempre quello aggiornato e può fare da source con google drive usando la funzione [IMPORTDATA](https://support.google.com/docs/answer/3093335?hl=en).

**Comment by cirospat** [comment]
spiegazione estremamente chiara.
Grazie @aborruso - vado ad applicare quanto ci hai specificato.
Appena mi torna tutto sul Google sheet chiudo issue. Faccio delle prove di inserimento dati nel modulo. Così mi posso preparare a scrivere una ricetta/tutorial.

**Comment by aborruso** [comment]
Nota sull'aggiornamento dati: la funzione IMPORTDATA() by default aggiorna i dati ogni ora.

Se in google sheet si vuole aggiornare ogni minuto (o altri intervalli) una fonte esterna CSV, si può scrivere uno script e attivare un trigger.

Gli script in un foglio si lanciano da

![image](https://user-images.githubusercontent.com/30607/53693654-d42a0d00-3da3-11e9-8657-adacae37d68e.png)


Uno script che importa CSV esterni in un foglio denominato "dati" è fatto così (c'è da inserire l'URL del CSV che fa sorgente)

```javascript
function importData() 
{
  var csvUrl = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT1rXQbF8ecOOiEDRFwaHZLiaxjUtUhFM29a-xuukkAzNZVFILq0r9mqKgncq4tqBiRQ4H9H8rR3u1X/pub?gid=0&single=true&output=csv";
  var csvContent = UrlFetchApp.fetch(csvUrl).getContentText();
  var csvData = Utilities.parseCsv(csvContent);
  
  var sheet = SpreadsheetApp.getActive().getSheetByName('dati')
  sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
}
```

L'intervallo di tempo di lancio dello script si imposta da

![image](https://user-images.githubusercontent.com/30607/53693668-0d627d00-3da4-11e9-9b4b-8364dae38772.png)

In questo modo si può impostare con aggiornamento anche al minuto.

**Comment by gbvitrano** [comment]
Grazie @aborruso proverò il metodo è sicuramente utile anche in mille altri casi :-)

**Comment by gbvitrano** [comment]
@aborruso seguendo la tua guida sono riuscito ad attivare l'aggiornamento automatico ad ogni minuto.
ho fatto un test con un singolo foglio è si è aggiornato in meno di 20 secondi.
Avendo più di un foglio da aggiornare ho modificato lo script come da immagine

![immagine](https://user-images.githubusercontent.com/20488693/53701079-b5eefc00-3df9-11e9-8665-3a202ee82080.png)

Lo script funziona su 3 fogli su 7

In questo foglio per esempio la funzione **IMPORTDATA** è visibile e di conseguenza non viene caricato l'aggiornamento.

![screenshot 191](https://user-images.githubusercontent.com/20488693/53701139-56452080-3dfa-11e9-80e3-72c82075a0fb.jpg)

ho sbagliato lo script?

**Comment by aborruso** [comment]
@gbvitrano per favore, quando c'è del codice, incolla il testo, non le immagini.

Lo script così non può funzionare. Se lo leggi dall'alto, chiami 7 volte la variabile csvURL, 7 CSV diversi associati alla stessa variabile, che quindi prima dell'update avrà sempre il valore dell'ultima chiamata.

Mentre dovresti avere qualcosa come:

```
csvURL1= ...
csvURL2= ...
...
```

E lo stesso vale per le altre variabili.
Potresti fare un array e fare un loop, ma partirei con la cosa che puoi fare in autonomia

**Comment by cirospat** [comment]
quindi riprendo una cosa della spiegazione dello script, per non dimenticarla e per tracciarla in questa issue: il **trigger** dello script.
Dopo aver impostato il codice dello script, si passa al Trigger. Si clicca (sempre nella stessa pagina dello script) l'icona a forma di orologio.
E si imposta:
- importdata
- head
- evento vincolato a specifiche temporali
- timer in minuti
- ogni minuto
- Impostazioni di notifica di errore: invia una notifica immediatamente (opzionale, serve solo ad essere informati tramite notifica in caso di errori

**Comment by cirospat** [comment]
questa issue traccia i passi da seguire (con l'aiuto di @aborruso @gbvitrano e @pigreco) per costruire una ricetta che spiega come creare moduli online di raccolta dati, con il servizio offerta da https://ona.io, inviando automaticamente i dati raccolti in un foglio Google, con aggiornamento temporale ogni minuto.
Le prove sono state fatte tutte,  a più mani, ed è stato verificato il corretto funzionamento del foglio Google: cioè è stato verificato che a seguito dell'inserimento dei dati nel modulo ONA, dopo un minuto i relativi dati sono disponibili nel foglio Google.
A breve verrà pubblicata la relativa ricetta che illustra i passi nel dettaglio.

**Comment by aborruso** [comment]
Tra onaio e GSheet è possibile una connessione diretta, ma da una settimana circa non funziona. Ho segnalato la cosa, e l'hanno potuta replicare.
Ci stanno lavorando.

![image](https://user-images.githubusercontent.com/30607/53723376-f38a6e00-3e67-11e9-9ca3-a0865154c7cd.png)

Le modalità definite sopra sono un modo alternativo e un'occasione per "sporcarsi le mani"

**Comment by aborruso** [comment]
@cirospat ha fatto la ricetta https://github.com/opendatasicilia/tansignari/blob/master/ricette/Modulo_ONA_raccola_dati_geografici_collegato_a_fogli_Google.md

Si chiude la issue 👍
