### ISSUE TITLE
[miller] e formato jsonl con errore

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#252]
ho questo file jsonl [1]

cerco di convertirlo in csv usando:

`mlr --j2c clean-whitespace toto2.jsonl >totoFeatureALL.csv`

ma ricevo questo errore:

`mlr: invalid character 'r' after object key:value pair.`

[1] [toto2.zip](https://github.com/opendatasicilia/tansignari/files/10951757/toto2.zip)

**Comment by pigreco** [comment]
forse ho beccato l'errore, alla riga 44:

![image](https://user-images.githubusercontent.com/7631137/224569752-cd9ab10c-6635-492c-906e-036ab66e19ee.png)

e altre righe:

![image](https://user-images.githubusercontent.com/7631137/224569856-113b3c0b-edf1-4c76-aace-f38f1a66eec4.png)
 
sembrano errori legati ai link ipertestuali, li ho tolti e funziona tutto.

Occorrerebbe capire come evitare a monte questo problema

**Comment by pigreco** [comment]
Gli errori li ho scoperti usando `fx` e NotePad++ assegnado il linguaggio JSON (HA esidenziato gli errori di parsing)

**Comment by aborruso** [comment]
Ciao totò,
l'errore è perché nel JSONL ci sono virgolette senza l'escape. 

Sono presenti coppie chiave valore come

```
"funded":"viva "totò" fiandaca"
```

che dovrebbe essere

```
"funded":"viva \"totò\" fiandaca"
```
