### ISSUE TITLE
[mlr] CSV header/data length mismatch

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari#255]
Sera!

Ho questo CSV (che mi sembra "sano")
```
id,command,duration,description
1,./launcher "./spawner ec 800000 885000 800000 5 0 best_individual" 25 100000 20 0.2 0.8 stats.csv,,blabla
```

ma se lancio
```
mlr --csv check file.csv
```

ottengo in output
```
mlr: mlr: CSV header/data length mismatch 4 != 1 at filename test.csv row 2.
.
```

Sbaglio qualcosa? C'è un modo per "forzare" il riconoscimento corretto del CSV?
Thx

---
Versione di miller: 6.73.0

**Comment by aborruso** [comment]
Caro @dennisangemi ,
il CSV più "giusto" è quello definito da [`RFC 4180`](https://datatracker.ietf.org/doc/html/rfc4180). E se cerchi tra le regole, vedi che il tuo CSV per le quotes non è compliant.
E quindi hai l'errore.

Tra i [formati CSV](https://miller.readthedocs.io/en/6.7.0/file-formats/#csvtsvasvusvetc) di Miller c'è il `csvlite`, che non è strictly `RFC 4180` compliant.

```
mlr --csvlite check file.csv
```

**Comment by dennisangemi** [comment]
questa mi mancava @aborruso, grazie!

**Comment by dennisangemi** [comment]
Grazie mille @aborruso, ricetta online: https://tansignari.opendatasicilia.it/ricette/csv-tsv/miller_sanity_check_csv/

**Comment by pigreco** [comment]
Grazie a entrambi, questa ricetta è veramente utile e istruttiva @dennisangemi @aborruso :-)

**Comment by aborruso** [comment]
> Grazie mille @aborruso, ricetta online: [tansignari.opendatasicilia.it/ricette/csv-tsv/miller_sanity_check_csv](https://tansignari.opendatasicilia.it/ricette/csv-tsv/miller_sanity_check_csv/)

Bel lavoro!
