### ISSUE TITLE
[duckdb] come applicare una funzione spaziale a un vettore importato

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#256]
Nel file che condivido ho un layer `polygon` e per estrarre il centroide scrivo la seguente query:

```
D load spatial
```

```sql
SELECT a.ClassREF, ST_Centroid (a.Shape) as shape
FROM ST_Read('x_andy.gdb',layer="polygon") a;
```

ma ricevo questo errore:

![image](https://github.com/opendatasicilia/tansignari/assets/7631137/6f0e0e18-3262-4a88-bba4-a632791c51f5)

[x_andy.gdb.zip](https://github.com/opendatasicilia/tansignari/files/12503658/x_andy.gdb.zip)

**Comment by aborruso** [comment]
@pigreco partirei da un formato di input più "normale". Fai una prova con un shp, e verifichi st_centroid?

**Comment by pigreco** [comment]
qui shapefile, ma lanciando:

```sql
SELECT ST_Centroid (geometry) as shape
FROM ST_Read(layer="shapefile");
```

![image](https://github.com/opendatasicilia/tansignari/assets/7631137/b2ca4325-e527-4102-b8b5-8e320bdf2d24)

[shp_x_andy.zip](https://github.com/opendatasicilia/tansignari/files/12503701/shp_x_andy.zip)

**Comment by pigreco** [comment]
Osservazioni:
credo che per richiamare la `geometry` del vettore occorre utilizzare `wkb_geometry`, infatti la seguente query restituisce un output:

```sql
SELECT a.wkb_geometry AS centroid
FROM ST_Read("shapefile.shp") a;
```
![image](https://github.com/opendatasicilia/tansignari/assets/7631137/30fad5ea-f645-495f-b88a-2a20b65f05b7)

**Comment by pigreco** [comment]
però se utilizzo la seguente query spaziale:

```sql
SELECT ST_Centroid(a.wkb_geometry) AS centroid
FROM ST_Read("shapefile.shp") a;
```

ho questo errore:
![image](https://github.com/opendatasicilia/tansignari/assets/7631137/bf06bc47-a1a4-4377-9c2d-8600acdaa9be)

**Comment by pigreco** [comment]
in duckdb la `geometry` è convertita in `wkb` quindi il nome del campo sarà `wkb_geometry`; 

per poter utilizzare la funzione `ST_Centroid()` occorre prima convertire la colonna `wkb_geometry` utilizzando la funzione `ST_GeomFromWKB()` , quindi la query da utilizzare è:

```sql
SELECT ST_Centroid(ST_GeomFromWKB(a.wkb_geometry)) AS centroid
FROM ST_Read("shapefile.shp") a;
```

![image](https://github.com/opendatasicilia/tansignari/assets/7631137/158c528b-1510-4ce1-8838-14ccc53670d6)

NOTA: non funziona usando lo shapefile allegato perché segnala questo errore:
`Error: Not implemented Error: Geometry type not supported`

lo shapefile allegato ha una geometry: `MultiPoligonZM`

--
rif.: <https://tech.marksblogg.com/duckdb-gis-spatial-extension.html>

**Comment by pigreco** [comment]
ricetta fatta e pubblicata qui
https://tansignari.opendatasicilia.it/ricette/riga_comando/duckdb_funzione_spaziale/
grazie @aborruso

**Comment by aborruso** [comment]
Grazie mille a te @pigreco !!!
