### ISSUE TITLE
[mastodon] come seguire account su server diversi?

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#257]
Ho un account mastodon su server `uno` https://mastodon.uno/, ma vorrei seguire un account presente su serve `social` https://mastodon.uno/@gdal@mastodon.social

come procedere?

**Comment by aborruso** [comment]
Puoi fare ad esempio così:

- recuperi il nome account di chi vuoi seguire, ad esempio `@gdal@mastodon.social`
- apri la home di uno https://mastodon.uno/home
- inserisci il nome utente nel search in alto a sinistra e cerchi
- ti apparirà nei risultati e lo potrai seguire (per certi account e certi server, ci può essere un blocco)

![image](https://github.com/opendatasicilia/tansignari/assets/30607/2ac6d5c1-58dc-48be-b233-96a324f9d0ea)

**Comment by pigreco** [comment]
ricetta fatta e pubblicata

https://tansignari.opendatasicilia.it/ricette/utilities/mastodon_seguire_account/

**Comment by aborruso** [comment]
Sei una persona seria e che si prende cura dei progetti.

Grazie
