### ISSUE TITLE
Importare file csv in un gpkg mantenendo i datatype degli attributi

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#264]
Il file csv ha questa struttura

OBJECTID|CUS03_I_liv|COMUNE_IST|area_ha
----------|------------|--------------|-----
1|0|"0"|278.51955966024
2|0|"090003"|18.8372408633517
3|0|"090006"|7.64683059980416

OBJECTID: int
CUS03_I_liv: int
COMUNE_IST: string
area_ha: float

come importarlo in un gpkg facendo rispettare il tipo di dato?

```sh
ogr2ogr -f "GPKG" -update -append \
-oo AUTODETECT_TYPE=YES \
-sql "SELECT CAST(OBJECTID AS INTEGER) AS OBJECTID,
             CAST(CUS03_I_liv AS INTEGER) AS CUS03_I_liv,
              COMUNE_IST AS COMUNE_IST,
              CAST(area_ha AS FLOAT) AS area_ha 
         FROM \"file\"" \
 "nome_geopackage" "file.csv"
```
ma restituisce errore, non trova il file

**Comment by aborruso** [comment]
Però la risposta l'hai avuta, mi raccomando!!

**Comment by pigreco** [comment]
> mi raccomando!!

ricetta fatta

https://tansignari.opendatasicilia.it/ricette/csv-tsv/importare_csv_in-gpkg/
