### ISSUE TITLE
Creare il "libro delle ricette" di questo repo

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#27]
Sono state create le [prime ricette](https://github.com/opendatasicilia/tansignari/tree/master/ricette). Per valorizzarle l'ideale è trasformarle in un ricettario ipertestuale.

Penso alla Read The Docs (piattaforma su cui è basato ad esempio il [manuale](https://hfcqgis.opendatasicilia.it/it/latest/) che ha creato @gbvitrano a partire dal lavoro di @pigreco ).

Di base assegnerei la cosa  a @gbvitrano  e @cirospat

**Comment by cirospat** [comment]
l'idea mi piace.
Per capire:
intendi un "read the docs" con una pagina per ricetta?

**Comment by aborruso** [comment]
@cirospat intendo che se ve la prendete in carico, siete liberi di impostarla come volete, ci fidiamo :)

**Comment by cirospat** [comment]
ok, vediamo se @gbvitrano e @pigreco condividono una pagina per ricetta e si inizia

**Comment by pigreco** [comment]
ciao @cirospat 

>ok, vediamo se @gbvitrano e @pigreco condividono una pagina per ricetta e si inizia

nella cartella [ricette](https://github.com/opendatasicilia/tansignari/tree/master/ricette) ci sono 9 ricette pronte, non ho capito cosa condividere??

**Comment by cirospat** [comment]
l'idea di una pagina per ricetta su read the docs

**Comment by aborruso** [comment]
Ecco la prima versione, grazie a @cirospat e @gbvitrano https://tansignari.readthedocs.io
