### ISSUE TITLE
Estrarre liste di elementi da una pagina web

### ISSUE THREAD

**Issue by lorenzoperone** [opendatasicilia/tansignari#29]
Ciao,
mi sono rimesso a studiare e vorrei prendere appunti e note sulle pagine web che studio estraendo rapidamente i titoli come un elenco (molte righe su una colonna) e vorrei farlo rimanendo in Chrome.
Ho provato con l'estensione DataMiner ma non riesco ad estrarre gli elementi che mi interessano (Nomi degli articoli).
Una pagina di esempio è quella di Demetra [0] e vorrei ottenere un elenco del tipo:
- Art. 1 - Elementi costitutivi della Regione
...
- Art. 13 - Attività di rilievo internazionale della Regione
Avete suggerimenti?

[0] http://bit.ly/2NLCchG

**Comment by aborruso** [comment]
@lorenzoperone  che sia chrome è un requisito, o va bene qualsiasi modo semplice con cui arrivare all'obiettivo?

E BENVENUTO

**Comment by lorenzoperone** [comment]
Chrome non é un requisito, ma farlo da browser sarebbe molto più comodo!

**Comment by aborruso** [comment]
Caro @lorenzoperone ,
la definizione di "comodo" è molto soggettiva. Io ad esempio non trovo molto comodo usare chrome per queste cose. Quindi purtroppo la mia è una risposta un po' off topic.

Di base comunque un modo tipico è fare una query XPATH.

I titoli degli articoli hanno questra struttura HTML

```html
<div class="articolo_rubrica">Elementi costitutivi della Regione</div>
```

La query XPATH è quindi `//div[@class="articolo_rubrica"]/text()`:

- `//div` > un div ovunque nella pagina
- `[@class="articolo_rubrica"] ` > a cui sia associata la classe `articolo_rubrica`
- `text()` > ti estra il testo contenuto nel div

Gli articoli li potresti numerare automaticamente, sono progressivi. 
Via XPATH , ragionando come sopra, è `//div[@class="articolo"]/text()`

A quel punto il tool che io trovo comodo è la shell e l'utility [scrape](https://github.com/aborruso/scrape-cli/releases) (vedi sotto):

```
# scarichi la pagina
curl "https://demetra.regione.emilia-romagna.it/al/articolo?urn=er%3Aassemblealegislativa%3Alegge%3A2005%3B13&dl_t=text%2Fxml&dl_a=y&dl_id=10&pr=idx%2C0%3Bartic%2C0%3Barticparziale%2C1&anc=tit1&fbclid=IwAR0Lcn8E89VosOWln-amBDx5N8rW1WiOsKjcBFv_7TjD7YsbJhWz0UtqUHk" >./pagina
# estrai i titoli e sostituisci il tab di output con a capo
<./pagina scrape -e '//div[@class="articolo_rubrica"]/text()' | tr "\t" "\n" >./titoli
# estrai numero articoli
<./pagina scrape -e '//div[@class="articolo"]/text()' | tr "\t" "\n" >./articoli
# metti insieme articoli e titoli
paste articoli titoli >./output
```

In output hai

```
Art. 1  Elementi costitutivi della Regione
Art. 2  Obiettivi
Art. 3  Politiche ambientali
Art. 4  Politiche del lavoro
Art. 5  Politiche economiche
Art. 6  Politiche sociali
Art. 7  Promozione dell'associazionismo
Art. 8  Le Autonomie locali
Art. 9  Le formazioni sociali
Art. 10 Sviluppo dei territori
Art. 11 Ordinamento europeo e internazionale
Art. 12 Partecipazione della Regione alla formazione e all'attuazione  del diritto comunitario
Art. 13 Attività di rilievo internazionale della Regione
```

## come installare scrape

Al momento non ho creato l'installer. Quindi puoi fare così

```bash
# lo scarichi
wget https://github.com/aborruso/scrape-cli/releases/download/v1.0/scrape
# gli dai permessi di esecuzione
chmod +x ./scrape
# lo sposti in una cartella presente nel PATH
sudo mv ./scrape /usr/bin
```

**Comment by lorenzoperone** [comment]
Ciao Andrea,
grazie per la soluzione. Putroppo nel computer che utilizzo per fare questo (windows 10) non posso usare *curl*. Ho visto che scrape è un eseguibile che non ha bisogno di installazione ma non posso utilizzare gli altri comandi.
Grazie comunque!

**Comment by aborruso** [comment]
Caro @lorenzoperone
tutto quello che ho fatto per costruire l'esempio, l'ho fatto su win10.
Installati Windows Linux Subsystem

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by lorenzoperone** [comment]
Caro @aborruso avevo immaginato, il mio problema è che non posso installare nulla a parte estensioni del browser. Un'alternativa che utilizzo è quella di applicazioni **portable**, in questo modo posso far girare anche *Open Refine*. La tua soluzione è ottima rapida e pulita ma mi costringerebbe a portarmi dietro un secondo portatile. Temo che i miei margini di manovra non consentano, in questo caso, di trovare una soluzione ragionevole. Sto utilizzando Microsoft Onenote ed evidenzio i testo importati attraverso la sua estensione per Chrome.

**Comment by aborruso** [comment]
Caro @lorenzoperone,
ti chiedo di fare - solo se ti va - un altro test.

Prova a installare questo:
https://babun.github.io/

Se riesci, sono a tua disposizione per fare i primi passi

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il gio 7 mar 2019, 22:21 lorenzo perone <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
@lorenzoperone ti confermo che in babun, in ambiente windows funziona. E babun si installa senza _admin right_.

Bisogna usare la versione per win di scrape, ma è una banalità nel caso 

![image](https://user-images.githubusercontent.com/30607/54015150-2a6dc600-417f-11e9-9d2a-e8ebd8318506.png)

**Comment by lorenzoperone** [comment]
Ciao @aborruso funziona tutto a meraviglia ed ho anche una linux shell!
Ma a questo punto non posso installare scrape in Cygwin?
Grazie infinite :)

**Comment by aborruso** [comment]
Ciao @lorenzoperone , avevo scritto

> Bisogna usare la versione per win di scrape, ma è una banalità nel caso

ed eccomi qui a dirti come fare: scarica l'exe per win di scrape (https://github.com/aborruso/scrape-cli/releases/download/v1.0/scrape.exe) e inseriscilo in una cartella del PATH di windows (se scrivi `PATH` nel prompt del DOS, hai l'elenco). 

Una volta fatto potrai usare scrape come sotto. Ripeto io faccio tutto in modo che tu possa replicare, quella sotto è un babun in windows 10 con scrape per win (nota che nel comando scrivo scrape e non scrape.exe).

![image](https://user-images.githubusercontent.com/30607/54036664-7e4ad000-41bc-11e9-92bc-ba24687def25.png)

Se non riesci a trovare una cartella nel path o non hai i permessi, basta che dai il path assoluto di dove hai salvato scrape (vai in quella cartella e dai `pwd`)

**Comment by aborruso** [comment]
@lorenzoperone probabilmente non avevo capito la domanda.

Sì, puoi usare scrape (sempre per win) in cygwin, ma l'ambiente babun è un cygwin AUMENTATO.

Se hai risolto, devi sapere che in questo spazio c'è un [galateo](https://github.com/opendatasicilia/tansignari/blob/master/galateo.md) in cui una delle voci è "se sei **soddisfatta/o** della risposta, sei invitato a **rimborsare**, creando un testo, una **ricetta**, che racconti per bene il problema che hai riscontrato e come è possibile risolverlo".

Quindi ti chiediamo di trasformare questa procedura, in una mini guida (ovviamente copiando da questa issue). Le stiamo mettendo qui https://github.com/opendatasicilia/tansignari/tree/master/ricette.
Appena puoi creala e fai un Pull Request :)

**Comment by lorenzoperone** [comment]
Ciao,
sono riuscito a d aggiungere *scrape* a PATH quindi comodissimo.
Non mi sottraggo di certo al galateo :)
Chiedo solo qualche giorno di proroga.
Baci.
l.

**Comment by aborruso** [comment]
@lorenzoperone tic tac tic tac tic tac ...

E non sai che poi automaticamente la ricetta si trasforma in questa forma https://tansignari.readthedocs.io/it/latest/ricette/script/Correzione_dati_usando_script.html

**Comment by lorenzoperone** [comment]
Ciao @aborruso avevo appena iniziato a scrivere la ricetta poi ho letto [questo](https://github.com/docksal/docksal/issues/1004), temo non sia utile a questo punto....

**Comment by aborruso** [comment]
ciao @lorenzoperone intanto è il modo che ti ha consentito in un ambiente "chiuso" di mettere in piedi un ambiente che ti consente di usare le utility a riga di comando del mondo Linux.
Quindi non è consigliata, ma è funzionante e risolutiva in caso di blocco
