### ISSUE TITLE
Se soddisfatti, rimborsate!

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#3]
Tutte le volte che chi fa la domanda è soddisfatto dalla risposta, dovrebbe aggiungere una ricetta in un volume di ricette a tema.

Così avremmo le ricette per le [espressioni regolari](https://github.com/opendatasicilia/tansignari/blob/master/ricette/regex.md), quelle per SQL, quelle per i Linked Open Data, ecc..

Che ne pensate?

@pigreco potresti ad esempio metterne una [qui](https://github.com/opendatasicilia/tansignari/blob/master/ricette/regex.md).

Potrebbe diventare un pezzo del **galateo** di **T'ansignari**

**Comment by pigreco** [comment]
> @pigreco potresti ad esempio metterne una [qui](https://github.com/opendatasicilia/tansignari/blob/master/ricette/regex.md).

come sempre ottima idea: fatto!

**Comment by aborruso** [comment]
@pigreco ho visto. 

Però deve comprensibile anche tra due mesi. Intendo dire che "sostituzione" si capisce perché la issue è fresca.

Io le "sostituzione" in ogni caso li rimuoverei, perché sono una conseguenza. Basta sapere come si fa un trova e sostituisci usando i gruppi.

I titoli delle ricette li farei iniziare sempre per lettura maiuscola.

E in fondo a ogni ricetta aggiungerei (quando possibile) qualcosa come

Vedi issue #2

**Comment by pigreco** [comment]
@aborruso ho apportato alcune modifiche
fammi sapere; sono disponibile a ulteriori migliorie.

**Comment by aborruso** [comment]
@pigreco così mi piace

**Comment by cirospat** [comment]
> _Tutte le volte che chi fa la domanda è soddisfatto dalla risposta, dovrebbe aggiungere una ricetta in un volume di ricette a tema._
Si mi piace, molto. Genera valore.

**Comment by aborruso** [comment]
È diventata una regola del [galateo](https://github.com/opendatasicilia/tansignari/blob/master/galateo.md). 

Chiudo
