### ISSUE TITLE
3 ore di formazione al Team open data su come usare strumenti di raccolta dati geo ed avere un database usabile

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#30]
Dopo l'issue:
https://github.com/opendatasicilia/tansignari/issues/25
e la ricetta:
https://github.com/opendatasicilia/tansignari/blob/master/ricette/Modulo_ONA_raccola_dati_geografici_collegato_a_fogli_Google.md
penso che sarebbe una bella idea (nel senso di "utile") fare una 3 ore di formazione su questo strumento, un mercoledì pomeriggio alla riunione del Team open data del comune di Palermo.
@gbvitrano @pigreco e @aborruso - insieme a me (tutte persone che ci siamo spesi su questa issue e ricetta) potremmo gestire queste 3 ore a dipendenti comunali referenti open data che generalmente frequentano le riunioni del Team open data con curiosità di apprendere.

Verso metà-fine aprile, così che possiamo strutturarci una narrazione. Possiamo spiegare mentre facciamo. E alla fine dimostrare come si usano questi strumenti che possono tornare utili a tanti dipendenti dei vari uffici.

E' un invito. Rifletteteci.
Ed è una proposta che si inserisce perfettamente nella filosofia di **Tansignari**.

**Comment by cirospat** [comment]
la proposta è postata anche in mailing list di opendatasicilia
https://groups.google.com/d/msg/opendatasicilia/AFzMAUD1lVU/HQ9RSxWcBAAJ

**Comment by aborruso** [comment]
@cirospat qui la chiudo e continuiamo in mailing list
