### ISSUE TITLE
[GIS] geocoding con openrefine senza usare GoogleMaps

### ISSUE THREAD

**Issue by ggattiglia** [opendatasicilia/tansignari#31]
Buon giorno a tutti.
Utilizzo OpenRefine per trasformare, luoghi, indirizzi, etc. in una coppia di coordinate da usare poi su una base GIS. NON voglio utilizzare GoogleMaps. Mi date qualche suggerimento?
Grazie

**Comment by cirospat** [comment]
ciao @ggattiglia 
dai un occhiata qui:
https://github.com/opendatasicilia/tansignari/blob/master/ricette/Geocoder.md

**Comment by aborruso** [comment]
Caro @ggattiglia ,
ti giro una vecchia ricetta fatta con Andria Zedda, basata su Nominatim.

A partire da

```
id,2geocode
1,"via terrasanta 82, Palermo, Italia"
2,"via dei Condotti, Roma, Italia"
```

- poi clickando su undo/redo

![image](https://user-images.githubusercontent.com/30607/53971189-b38fe900-40fc-11e9-8005-74a7b91bbefc.png)

- poi su apply

![image](https://user-images.githubusercontent.com/30607/53971236-c6a2b900-40fc-11e9-9f6b-57bf08040903.png)

- e infine incollando [questo codice](https://raw.githubusercontent.com/aborruso/geocode_openrefine/master/Nominatim/open_refine_nominatim.json) nella finestra che ti si apre e lanciando "perform operations".

È necessario che gli indirizzi da geocodificare siano in una colonna denominata "2geocode".

Chiaramente in alcuni luoghi Nominatim non funziona un gran bene. Si può usare anche opencage e qualsiasi altro geocoder, ma c'è da scrivere la procedura del caso.

**Comment by ggattiglia** [comment]
Grazie @aborruso 
funziona perfettamente!

**Comment by aborruso** [comment]
Caro @ggattiglia purtroppo c'è una brutta notizia per te :)

In questo spazio c'è un [galateo](https://github.com/opendatasicilia/tansignari/blob/master/galateo.md) in cui una delle voci è "se sei **soddisfatta/o** della risposta, sei invitato a **rimborsare**, creando un testo, una **ricetta**, che racconti per bene il problema che hai riscontrato e come è possibile risolverlo".

Quindi ti chiediamo di trasformare questa procedura, in una mini guida (ovviamente copiando da questo scambio). Le stiamo mettendo qui https://github.com/opendatasicilia/tansignari/tree/master/ricette

**Comment by ggattiglia** [comment]
Fatto.
Let me know
