### ISSUE TITLE
[GIS] Ricavare nome via, comune, ecc. a partire da coppia di coordinate

### ISSUE THREAD

**Issue by Giabbate** [opendatasicilia/tansignari#36]
Buongiorno, partendo da un foglio csv contenente identificativo punto le coordinate LAT e LON, vorrei popolare una tabella per la VIA/località, una tabella per il Comune e una tabella per la Provincia. Attualmente QGIS permette l'interrogazione di un solo punto con il plugin geocoding.

**Comment by aborruso** [comment]
@Giabbate sei interessato a una soluzione che sia dentro QGIS, o una soluzione generica di trasformazione di coppie di coordinate in  "VIA/località, Comune, Provincia"?

**Comment by Giabbate** [comment]
Se è dentro QGIS è meglio. grazie- Se è troppo laborioso anche il foglio va benissimo.

**Comment by pigreco** [comment]
@Giabbate una soluzione è quella di usare i fogli di Google Drive dopo aver installato il componente aggiuntivo **Two-way Geocoding** (grazie per la segnalazione @gbvitrano ).

Questo componente permette di fare un geocoding in entrambi i sensi; ma vediamo come risolvere il caso di tuo interesse:

dopo aver installato il componente:
![image](https://user-images.githubusercontent.com/7631137/54376996-90c57d80-4684-11e9-83b8-4c289efda745.png)
occorre settare, per il foglio, le impostazioni internazionali del Regno Unito (File –> impostazioni).

Creare un nuovo foglio:
![image](https://user-images.githubusercontent.com/7631137/54377229-09c4d500-4685-11e9-8a09-838056f80b8a.png)
in modo da ottenere questa impostazione dello sheet, usando il menu componenti aggiuntivi → Two-way Geocoding → Create new sheet

a questo punto non ti resta che popolare i campi delle coordinate (LATITUDE e LONGITUDE), potresti anche popolare gli altri campi NAME e DESCRIPTION.

Successivamente, ritorna nel menu `Componenti Aggiuntivi` e seleziona `Geocode → Coordinates`
![image](https://user-images.githubusercontent.com/7631137/54380403-9ffbf980-468b-11e9-8d5e-de4cde60fb9f.png).

Dopo qualche secondo verrà popolato il campo `ADDRESS` in questo formato:

ADDRESS|LATITUDE|LONGITUDE
----|-------|-----
Piazza del Parlamento, 1, 90129 Palermo PA, Italy|38.112213|13.352615
Foro Umberto I, 11, 90133 Palermo PA, Italy|38.119753|13.371337
Via Dell' Arsenale, 148, 90142 Palermo PA, Italy|38.135400|13.369116

**OSSERVAZIONI**
Con i dati cosi ottenuti puoi farci poco, leggi qui: https://goo.gl/6hYJh7
in particolare:
`
You can display Geocoding API results on a Google Map, or without a map. If you want to display Geocoding API results on a map, then these results must be displayed on a Google Map. It is prohibited to use Geocoding API data on a map that is not a Google map.
`

**Comment by Giabbate** [comment]
mi costringete a lavorare di notte... Ho provato ed è fantastico.Siete GRANDI.Gianfranco
    Il giovedì 14 marzo 2019, 19:13:25 CET, Salvatore Fiandaca <notifications@github.com> ha scritto:  
 
 
@Giabbate una soluzione è quella di usare i fogli di Google Drive dopo aver installato il componente aggiuntivo Two-way Geocoding (grazie per la segnalazione @gbvitrano ).

Questo componente permette di fare un geocoding in entrambi i sensi; ma vediamo come risolvere il caso di tuo interesse:

dopo aver installato il componente:

occorre settare, per il foglio, le impostazioni internazionali del Regno Unito (File –> impostazioni).

Creare un nuovo foglio:

in modo da ottenere questa impostazione dello sheet, usando il menu componenti aggiuntivi → Two-way Geocoding → Create new sheet

a questo punto non ti resta che popolare i campi delle coordinate (LATITUDE e LONGITUDE), potresti anche popolare gli altri campi NAME e DESCRIPTION.

Successivamente, ritorna nel menu Componenti Aggiuntivi e seleziona Geocode → Coordinates
.

Dopo qualche secondo verrà popolato il campo ADDRESS in questo formato:

| ADDRESS | LATITUDE | LONGITUDE |
| Piazza del Parlamento, 1, 90129 Palermo PA, Italy | 38.112213 | 13.352615 |
| Foro Umberto I, 11, 90133 Palermo PA, Italy | 38.119753 | 13.371337 |
| Via Dell' Arsenale, 148, 90142 Palermo PA, Italy | 38.135400 | 13.369116 |


OSSERVAZIONI
Con i dati cosi ottenuti puoi farci poco, leggi qui: https://goo.gl/6hYJh7
in particolare:
You can display Geocoding API results on a Google Map, or without a map. If you want to display Geocoding API results on a map, then these results must be displayed on a Google Map. It is prohibited to use Geocoding API data on a map that is not a Google map.

**Comment by pigreco** [comment]
Ciao @Giabbate,
in questo spazio abbiamo un [galateo](https://github.com/opendatasicilia/tansignari/blob/master/galateo.md) e una delle 'regole' è quella che
`se sei soddisfatta/o della risposta, sei invitata/o a rimborsare, creando un testo, una ricetta, che racconti per bene il problema che hai riscontrato e come è possibile risolverlo`; tutte le ricette faranno parte di un ricettario RTD.

Per favore facci sapere se vuoi **rimborsare**
