### ISSUE TITLE
[scripting] ciclo for e curl

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#38]
Il seguente ciclo `for` con `curl` 
```bash
#!/bin/bash
set -x
for i in $(cat lat_lon.csv); do
curl -L "http://nominatim.openstreetmap.org/reverse.php?format=json&"$i"&addressdetails=1" > output.json
done
```
non funziona perché URL viene interrotto e ottengo il seguente errore:

![image](https://user-images.githubusercontent.com/7631137/54394743-0abe2c80-46ae-11e9-9360-031bb7f0180f.png)

dati:
[test_bash.zip](https://github.com/opendatasicilia/tansignari/files/2968668/test_bash.zip)

**Comment by aborruso** [comment]
Caro @pigreco il "fine linea" negli script in bash è fondamentale.

Ti va in errore, perché il CSV è alla "Windows" con CRLF, mentre deve essere alla UNIX.

Dai il comando `dos2unix lat_lon.csv` e poi rilancia lo script (se non hai dos2unix, installalo con apt).

Lo script ha poi altri problemi, ma li scoprirai da solo :)

**Comment by pigreco** [comment]
@aborruso grazie per la tempestiva risposta

> Ti va in errore, perché il CSV è alla "Windows" con CRLF, mentre deve essere alla UNIX.

errore da neofita, avevo controllato per lo script e non per il file csv

Per l'append devo usare `>> output.json`

rimane il problema della decodifica del file json, ma questa sarà un'altra issue.

**Comment by aborruso** [comment]
Caro @pigreco lo puoi fare in mille modi. Qui ti mostro uno di quelli che uso.
Nota bene: il JSON è un formato che può avere una gerarchia molto ricca, è come un db relazionale con più tabelle dentro. Quindi le utility che fanno conversione diretta in CSV, se il JSON non è semplice, vanno in difficoltà.

Per i JSON, se vuoi usare un utlity a riga di comando (utilizzabile in tutti i sistemi operativi) l'utility più usata (per merito) è jq.

Per trasformare

```json
{
  "place_id": 120403399,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 191532974,
  "lat": "38.0052595",
  "lon": "12.9971424",
  "display_name": "Alcamo, TP, SIC, 91027, Italia",
  "address": {
    "town": "Alcamo",
    "county": "TP",
    "state": "SIC",
    "postcode": "91027",
    "country": "Italia",
    "country_code": "it"
  },
  "boundingbox": [
    "37.9874419",
    "38.0068403",
    "12.9894177",
    "13.000404"
  ]
}
```

in `"38.0052595","12.9971424","Alcamo, TP, SIC, 91027, Italia"`

La query jq è [`.|[.lat,.lon,.display_name]|@csv`](https://jqplay.org/s/VDNvyFq0Nq).

A riga di comando è

```bash
curl -L "http://nominatim.openstreetmap.org/reverse.php?format=json&lat=38&lon=13&addressdetails=1" | \
jq -r '.|[.lat,.lon,.display_name]|@csv'
```

- `.` per entrare nel JSON
- poi il pipe per creare l'array di valori (che in un JSON va messo tra quadre), composti da valore delle proprietà lat, lon e display_name;
- poi in pipe per trasformarlo in csv con `@csv`.

Questa è una query semplice. È possibile scendere negli alberi complessi di oggetti e usare e trasformare quello che serve
