### ISSUE TITLE
[scripting] come convertire un JSON in CSV usando la CLI

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#39]
Come convertire un JSON che contiene dati GIS (coordinate lat, lon) in CSV

se puo' essere di aiuto, il JSON proviene dalla issue #38

**Comment by aborruso** [comment]
@pigreco tante domande tutte insieme :)

> in un formato GIS (GeoJSON, CSV)

Quindi va bene anche un CSV?

**Comment by pigreco** [comment]
@aborruso ho modificato la domanda,
sì, da JSON a CSV usando al CLI
grazie

**Comment by aborruso** [comment]
Caro @pigreco lo puoi fare in mille modi. Qui ti mostro uno di quelli che uso.
Nota bene: il JSON è un formato che può avere una gerarchia molto ricca, è come un db relazionale con più tabelle dentro. Quindi le utility che fanno conversione diretta in CSV, se il JSON non è semplice, vanno in difficoltà.

Per i JSON, se vuoi usare un utlity a riga di comando (utilizzabile in tutti i sistemi operativi) l'utility più usata (per merito) è jq.

Per trasformare

```json
{
  "place_id": 120403399,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 191532974,
  "lat": "38.0052595",
  "lon": "12.9971424",
  "display_name": "Alcamo, TP, SIC, 91027, Italia",
  "address": {
    "town": "Alcamo",
    "county": "TP",
    "state": "SIC",
    "postcode": "91027",
    "country": "Italia",
    "country_code": "it"
  },
  "boundingbox": [
    "37.9874419",
    "38.0068403",
    "12.9894177",
    "13.000404"
  ]
}
```

in `"38.0052595","12.9971424","Alcamo, TP, SIC, 91027, Italia"`

La query jq è [`.|[.lat,.lon,.display_name]|@csv`](https://jqplay.org/s/VDNvyFq0Nq).

A riga di comando è

```bash
curl -L "http://nominatim.openstreetmap.org/reverse.php?format=json&lat=38&lon=13&addressdetails=1" | \
jq -r '.|[.lat,.lon,.display_name]|@csv'
```

- `.` per entrare nel JSON
- poi il pipe per creare l'array di valori (che in un JSON va messo tra quadre), composti da valore delle proprietà lat, lon e display_name;
- poi in pipe per trasformarlo in csv con `@csv`.

Questa è una query semplice. È possibile scendere negli alberi complessi di oggetti e usare e trasformare quello che serve

**Comment by pigreco** [comment]
wow,
@aborruso grazie per la veloce e dettagliata risposta.

a breve unirò questa issue con la #38 e realizzerò una ricetta.

**Comment by pigreco** [comment]
snippet by jqplay

https://jqplay.org/s/4fZpHUeQRJ
