### ISSUE TITLE
Scrivere galateo dello spazio "T'ansignari"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#4]
Scrivere i modi con cui vorremmo vivere questo spazio. Inserirlo come capitolo del README in home.

- [x] Se soddisfatti, rimborsate! (vedi #3 )
- [x] Prima di chiedere, cercare in giro
- [x] Prima di chiedere, prova ad affrontare il problema in autonomia
- [x] documentare la propria domanda
- [x] scrivere una guida su come sono organizzate file e cartelle e le "regole" da seguire (grazie @pigreco )
- [x] si accettano domande su temi vicini a quelli di opendatasicilia, quindi non è il posto dove chiedere di blender, di autocad o di leggi sul diritto del lavoro;
- [ ] Inserire nel titolo una "etichetta", per classificare il post (ad esempio `[scripting] Come fare a rimuovere i duplicati di una tabella`)

**Comment by pigreco** [comment]
... aggiungo:
- [ ] scrivere la prima lettera in minuscolo/maiuscolo per i file README nella sezione ricette

![image](https://user-images.githubusercontent.com/7631137/52532681-3eadd700-2d29-11e9-8b89-d7f354be1e74.png)

**Comment by aborruso** [comment]
Io chiuderei la issue, ma aspetto qualche feedback https://github.com/opendatasicilia/tansignari/blob/master/galateo.md
