### ISSUE TITLE
[scripting] Modificare stringhe di un CSV usando la CLI

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#42]
Ho un file CSV cosi strutturato
```csv
38.112704,13.378536
38.113295,13.378493
38.112704,13.378536
...
```
e vorrei trasformarlo cosi:
```csv
lat=38.112704&lon=13.378536
lat=38.113295&lon=13.378493
lat=38.112704&lon=13.378536
...
```
per ottenere il risultato di sopra ho usato questo:
```bash
sed -i -e 's/^/lat=/g' lat_lon_coordinates.csv
sed -i -e 's/,/\&lon=/g' lat_lon_coordinates.csv
```
funziona bene, ma ho usato due volte `sed`; 
se dovessi fare n sostituzioni io usere n volte `sed` , mi sembra una via non praticabile, come ovviare?

[lat_lon_coordinates.txt](https://github.com/opendatasicilia/tansignari/files/2972248/lat_lon_coordinates.txt)

**Comment by aborruso** [comment]
@pigreco devi abilitare sed alle espressioni regolari estese con `-r`.

E poi ad esempio è

    echo "38.112704,13.378536" | sed -r 's/^(.*),(.*)$/lat=\1\&lon=\2/g'

che ti da

    lat=38.112704&lon=13.378536

**Comment by pigreco** [comment]
@aborruso grazie per velocità e tempo dedicatomi
