### ISSUE TITLE
[scripting] pulitura file csv

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#43]
Ho scaricato quattro file CSV dal [Portale OpenData](https://opendata.comune.palermo.it/opendata-ultimi-dataset.php) del Comune di Palermo (allego file)

ho usato questo script Bash:

```bash
#!/bin/bash
for i in *.csv; 
do 
  mlr --csv uniq -a $i > output_$i;
done
```
per pulirli da eventuali record duplicati ma in due file ottengo questo messaggio di errore:

![image](https://user-images.githubusercontent.com/7631137/54477389-a3b48b00-4807-11e9-943b-961d8bcc1b60.png)

credo sia dovuto alla presenza del separatore `;` al posto della `,` ; modificare i file sostituendo la `,` al posto del `;` non è cosa semplice in quanto la `,` è presente quasi ovunque (numeri e testo e in più colonne)

dati
[sinistri_palermo.zip](https://github.com/opendatasicilia/tansignari/files/2974033/sinistri_palermo.zip)

**Comment by aborruso** [comment]
@pigreco il comune di Palermo e quell'ufficio dovrebbe uniformare il separatore di campo e dichiararlo.

In ogni caso Miller non lo può dedurre, quindi devi impostare il separatore come parametro:

    mlr --csv --fs ";" uniq -a sinistri_palermo_2015.csv >output.csv

`--fs` per impostare il field separator
