### ISSUE TITLE
creare dominio di terzo livello per questo spazio

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#45]
Sarà tansignari.opendatasicilia.it

**Comment by aborruso** [comment]
@gbvitrano creato `tansignari.opendatasicilia.it`.

Sarà attivo nelle prossime ore. A te configurare la cosa lato RTD.

Grazie

**Comment by gbvitrano** [comment]
Dominio configurato :-) 
grazie grazie
