### ISSUE TITLE
[GIS] Dati ATM Catania

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#46]
Buondi,
dal portale ATM di Catania http://www.amt.ct.it/?page_id=4623 seguendo le istruzioni ho scaricato i file json delle fermate  e delle linee.
Con QGIS sono riuscito a mappare le fermate, ma non riesco a capire come mappare le linee, ci sono coppie di colonne di coordinate per ogni punto, a differenza del classico gtfs, dove troviamo le colonne long, lat, id e sequenza dei punti.

[ATM.zip](https://github.com/opendatasicilia/tansignari/files/3016893/ATM.zip)

**Comment by aborruso** [comment]
Buongiorno, la soluzione deve essere realizzata via QGIS?

**Comment by aborruso** [comment]
In ogni caso qui c'è un repo con delle modalità che potrebbero ancora funzionare https://github.com/SiciliaHub/amtcatania

**Comment by gbvitrano** [comment]
Grazie @aborruso ho provato il comando curl del tuo repo, lo eseguo,  credo funzioni, ma non riesco a trovare il file dentro explorer di win 
teoricamente i file bash dovrebbero essere **C:\Utenti\NomeUtente\AppData\Local\lxss** ma nel mio pc non trovo la cartella **lxss**


![immagine](https://user-images.githubusercontent.com/20488693/55150638-d8500d00-514c-11e9-82d3-374ea9705db3.png)

**Comment by gbvitrano** [comment]
@aborruso la procedura ha funzionato benissimo
![linee_atm](https://user-images.githubusercontent.com/20488693/55150951-8491f380-514d-11e9-8498-518fee71bfa6.png)
il file è stato generato, non trovando la cartella **lxss** ho copiato il file linee.geojson dalla home a /mnt/c/tmp

resta il fatto che non trovo la cartella della home di ubuntu su explorer

**Comment by aborruso** [comment]
@gbvitrano se scrivi `pwd` scoprirai in che cartella sei.

Oppure prima di di lanciare lo script, vai in "c:\tmp" (o in una cartella simile) con `cd /mnt/c/tmp`

**Comment by gbvitrano** [comment]
Con i file che ho scarico e conventito in csv non si può arrivare alla soluzione? è solo una curiosità :-)

**Comment by aborruso** [comment]
@gbvitrano certo che sì, anche quelli possono essere trasformati in qualcosa come

```
idLinea,idPoint,x,y
...,...,...,...
...,...,...,...
```

**Comment by gbvitrano** [comment]
> 
> 
> @gbvitrano certo che sì, anche quelli possono essere trasformati in qualcosa come
> 
> ```
> idLinea,idPoint,x,y
> ...,...,...,...
> ...,...,...,...
> ```
 ...e come si trasformano...? 

Qui un primo test 
http://u.osmfr.org/m/308965/

**Comment by aborruso** [comment]
@gbvitrano richiede delle conosce di base, quindi devo preparare una sorta di tutorial.
La settimana prossima dovrei riuscire.

Il punto saliente è quello di rendere i dati "tidy", e trasformare quelle colonne da osservazioni in variabili, una sorta di traposizione

**Comment by pigreco** [comment]
Salve,
metto qui questo piccolo script per generare le linestring partendo da un file csv con le coordinate di tutti i vertici dei percorsi:
```
ogr2ogr -dialect sqlite -sql "SELECT lineID, MakeLine(MakePoint(CAST(longitude AS float),CAST(latitude AS float),4326)) AS geom FROM lineegb GROUP BY 1" lineCTgb.shp lineegb.csv
```
struttura csv vertici

lineID|point|latitude|longitude
------|-----|--------|--------
1|0|37.532127001273|15.108711370535
1|1|37.531958369679|15.108693848462
1|2|37.531810541059|15.108613382192
2|0|37.531746263079|15.108542391367
2|1|37.531692490655|15.108448426337

**Comment by aborruso** [comment]
@gbvitrano è necessario che il CSV di partenza sia correttamente ordinato per lineID,point? Se sì, lo metterei anche nello script

**Comment by gbvitrano** [comment]
@pigreco se sono i punti delle linee bus devono avere un ordine, altrimenti non si può ricostruire la linea, come per il file shapes dei GTFS

**Comment by pigreco** [comment]
@aborruso e @gbvitrano 
giuste osservazioni, ma partivo da un file csv già ordinato.
provvedo alla modifica dello script prima possibile. ;-)

**Comment by gbvitrano** [comment]
Mappa completa, quando  saranno pronti i vostri tutorial si pubblica :-)

http://u.osmfr.org/m/308965/

![amt_01](https://user-images.githubusercontent.com/20488693/55257953-be541e80-5261-11e9-8a5c-84b3f0bae720.png)
![amt_03](https://user-images.githubusercontent.com/20488693/55257954-be541e80-5261-11e9-9e0c-3262cbc0b289.png)
![amt_02](https://user-images.githubusercontent.com/20488693/55257955-be541e80-5261-11e9-98e5-69ebd6edf356.png)
