### ISSUE TITLE
Come creare un database dei Responsabili Transizione al Digitale da https://www.indicepa.gov.it

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#47]
Ho un esigenza: creare una tabella (per esempio su Google spreadsheet) dei Responsabili Transizione al Digitale presenti sul portale https://www.indicepa.gov.it.

Se cerco "**Responsabile transizione al digitale**" trovo un elenco sulla pagina html:
![image](https://user-images.githubusercontent.com/3757525/55310086-e610d580-545f-11e9-818d-2655f486e61c.png)
con 28 pagine di risultati.
Sarebbe molto utile alimentare automaticamente un foglio Google con tutti i dati presenti per ogni RTD (Resp. Trans. Digitale):

- Indirizzo Postale
- telefono
- email
- AOO di riferimento
- Codice univoco ufficio
- nome e cognome responsabile
- email responsabile
- telefono responsabile

Avere una tabella di questa figura aiuta a mettersi in contatto con le altre PA.
Grazie.

**Comment by aborruso** [comment]
Ciro sono a Milano sino a domani. In ogni caso dovrebbe essere semplice, perché loro pubblicano sia i dati che i web service.
Su quei dati si possono impostare query con aggiornamenti automatici su Google sheet

**Comment by gbvitrano** [comment]
Potresti usare **=IMPORTHTML**

=IMPORTHTML("https://www.indicepa.gov.it/ricerca/n-risultati-semplice.php?keysearch=Responsabile%20transizione%20al%20digitale&pag=1";"table"; 1)

**1** indica la prima tabella

**Comment by gbvitrano** [comment]
Dalla sezione OpenData https://www.indicepa.gov.it/documentale/n-opendata.php
link **Servizi delle U.O.**  magari ti può essere utile

![immagine](https://user-images.githubusercontent.com/20488693/55316159-17909d80-546e-11e9-8b7e-1ebf34a653a2.png)

**Comment by gbvitrano** [comment]
Ricerca [Responsabile alla transizione digitale](https://www.indicepa.gov.it/ricerca/n-risultati-semplice.php) 28 risultati
[transizione digitale](https://www.indicepa.gov.it/ricerca/n-risultati-semplice.php) 13637 Risultati

**Comment by cirospat** [comment]
Gianni gentilmente mi condividi il foglio in cui hai fatto l'importHTML ?
Grazie

**Comment by gbvitrano** [comment]
Sono fuori casa, il comando è questo 

=IMPORTHTML("https://www.indicepa.gov.it/ricerca/n-risultati-semplice.php?keysearch=Responsabile%20transizione%20al%20digitale&pag=1";"table"; 1)

**Comment by gbvitrano** [comment]
> 
> 
> @gbvitrano gentilmente mi condividi il foglio in cui hai fatto l'importHTML ? Grazie
> 
> Ho visto che gli open data sono in formato txt, non tabellare.

il file txt lo puoi importare con google sheet

**Comment by aborruso** [comment]
Ciao @cirospat come dice @gbvitrano puoi importare i file txt presenti nella sezione opendata di iPA, con la funzione `IMPORTDATA` di google sheet.

Ho messo tutto su dataworld, così si possono fare cose molto più ricche e interessanti: https://www.indicepa.gov.it/documentale/n-cosa-facciamo.php

Per i dati che cerchi, la [query](https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni/workspace/query?queryid=9b66c1cc-56ae-4158-be30-009516734cd0) potrebbe essere:

```sql
SELECT *
FROM servizi_delle_u_o where UPPER(nome_srv) like "%TRANS%DIGI%"
```

Che in output da questo CSV che puoi usare in google sheet, sempre come argomento di `IMPORTDATA` https://download.data.world/s/3pp3hlutbl6p2s255dab23ncodspf3

**Comment by cirospat** [comment]
grazie dei feedback

@aborruso 
https://docs.google.com/spreadsheets/d/1B5jAjNnx3GD_69kSyyWD9LfqELL9fT9lQVQj-KdmOm4/edit#gid=0
con questo importdata (https://download.data.world/s/3pp3hlutbl6p2s255dab23ncodspf3) me ne prende un poco (29 righe), ma ad esempio non c'è [il comune di Palermo ](https://www.indicepa.gov.it/ricerca/n-dettagliouffici.php?prg_ou=111151) che è registrato come Resp.Trans. Digitale sul sito IPA. 
Come mai secondo voi?

**Comment by aborruso** [comment]
@cirospat gli opendata sono "così c'è scritto" aggiornati ogni giorno.
Da quando il resp di Palermo è in elenco. Se c'è da più di 48 ore (così andiamo oltre limite), apri un ticket qui https://www.indicepa.gov.it/contatti/n-gest-segn-form1.php

Ma la query, aldilà di Palermo, non va bene? Vorresti i nomi delle PA?

**Comment by cirospat** [comment]
il Resp Trans Digitale di Palermo c'è da mesi sul sito indicepa.gov.it.
Cosa vorrei io? 
Una tabella con:
- nome della PA che ha nominato il Resp Trans Digitale 
- nome del Resp Trans Digitale di quella PA
- telefono del Resp Trans Digitale di quella PA
- email del Resp Trans Digitale di quella PA

mi basterebbe per contattarli :)

**Comment by aborruso** [comment]
@cirospat  ho incrociato elenco PEC e nomi della PA, sono circa 1500 https://download.data.world/s/wqg4hnz3mzuaqudyv2jgqbb56txfwm

La [query](https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni/workspace/query?queryid=6d0da4b7-2dce-417b-ba98-00637df0b3a1) è diversa:

```sql
SELECT amministrazioni.des_amm,elenco_pec.*
FROM elenco_pec
INNER JOIN amministrazioni ON elenco_pec.cod_amm=amministrazioni.cod_amm
WHERE elenco_pec.descrizione LIKE "%transizione%"
ORDER by amministrazioni.des_amm
```

Con le altre tabelle, via JOIN, si dovrebbe arrivare ai telefoni

**Comment by cirospat** [comment]
grazie @aborruso 
ecco i Resp. Trans. Digitali della Sicilia: 
https://docs.google.com/spreadsheets/d/1B5jAjNnx3GD_69kSyyWD9LfqELL9fT9lQVQj-KdmOm4/edit#gid=280906317

@gbvitrano mi servirebbero anche le email dei Resp. Trans. Digitale e i telefoni
come si può ottenere un altra tabella?
Thanks

Sto arrivando all'obiettivo finale :)

**Comment by aborruso** [comment]
@cirospat ho studiato e la tabella corretta al tuo scopo sembra quella degli uffici.

Fatta una [nuova query](https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni/workspace/query?queryid=34110c27-83e8-4ed0-a9bc-4a386f47b5b3):

```sql
SELECT amministrazioni.des_amm,ufficiTDSicilia.* FROM
(SELECT *
FROM unita_organizzative
WHERE unita_organizzative.regione LIKE "Sicilia" 
AND unita_organizzative.des_ou LIKE "%trans%digit%") ufficiTDSicilia
INNER JOIN amministrazioni ON ufficiTDSicilia.cod_amm=amministrazioni.cod_amm
ORDER BY amministrazioni.des_amm
```

Qui i dati in CSV https://download.data.world/s/dp5azaar4y4dtgja77x7l575evxhoj

**Comment by cirospat** [comment]
grazie @aborruso 

quindi si scarica tabella uffici
e poi si applica la query che hai scritto.
Ok capito.

Se voglio tutti gli uffici d'Italia mi puoi scrivere la sintassi della query, please
Grazie tantissimo.

**Comment by aborruso** [comment]
@cirospat prendila come occasione per fare un po' di lavoro con SQL.
In lingua italiana basta che rimuovi il filtro sulla Sicilia. Se ci perdi più di 10 minuti, fermati e te la scrivo.

La documentazione SQL su dataworld è ottima
https://docs.data.world/documentation/sql/concepts/basic/intro.html

**Comment by cirospat** [comment]
thanks @aborruso 
infatti era una buona occasione per navigare mari ancora sconosciuti a me

**Comment by cirospat** [comment]
quindi @aborruso immagino dovrebbe essere più o meno così:

```sql
SELECT amministrazioni.des_amm,uffici.* FROM
(SELECT *
FROM unita_organizzative
WHERE unita_organizzative 
AND unita_organizzative.des_ou LIKE "%trans%digit%") uffici
INNER JOIN amministrazioni ON uffici.cod_amm=amministrazioni.cod_amm
ORDER BY amministrazioni.des_amm
```

non so perchè ma c'è qualche errore, ... ho tolto "Sicilia" e "regione" dalla sintassi

**Comment by aborruso** [comment]
Bravo @cirospat. Qui dall'aeroporto mi sembra quasi giusta.

C'è sicuramente un errore. Devi rimuovere "AND" perché non hai più due condizioni, da qui: 

WHERE unita_organizzative.des_ou LIKE "%trans%digit%"

**Comment by cirospat** [comment]
già vero 
non ci avevo fatto caso.... non ho più 2 condizioni
si si
grazie

**Comment by gbvitrano** [comment]
Buon dì non riesco ad entrare in questa pagina https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni

![immagine](https://user-images.githubusercontent.com/20488693/55462039-33bf4680-55f6-11e9-97c1-314710d59a79.png)

**Comment by aborruso** [comment]
@gbvitrano colpa mia. Prova ora con

https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni

**Comment by gbvitrano** [comment]
Qui la [mappa ](http://umap.openstreetmap.fr/it/map/responsabile-transizione-digitale-sicilia_310910#8/37.723/14.919) dei Responsabili transizione digitale in Sicilia.

![RTD](https://user-images.githubusercontent.com/20488693/55462375-e42d4a80-55f6-11e9-99c2-b687d642eded.jpg)

**Comment by gbvitrano** [comment]
> 
> 
> @gbvitrano colpa mia. Prova ora con
> 
> https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni

Grazie ora funziona

**Comment by gbvitrano** [comment]
C'è un problema con i numeri di telefono fissi... manca lo **0** iniziale **091** diventa **91**

**Comment by aborruso** [comment]
@gbvitrano è l'import di dataworld. Appena posso vedo se è risolvibile

**Comment by aborruso** [comment]
> C'è un problema con i numeri di telefono fissi... manca lo 0 iniziale 091 diventa 91

@gbvitrano dovrei avere risolto

**Comment by gbvitrano** [comment]
> 
> 
> > C'è un problema con i numeri di telefono fissi... manca lo 0 iniziale 091 diventa 91
> 
> @gbvitrano dovrei avere risolto

Grazie, ho lo stesso problema con Google sheet, ho aperto una nuova [issue ](https://github.com/opendatasicilia/tansignari/issues/48)

**Comment by cirospat** [comment]
1 dataset generato da @aborruso (grazie) per gli indirizzi dei Responsabili Transizione al Digitale d'Italia:

https://download.data.world/s/ucmdmblpy4iiy2feepjjdtfqozbljx (**il CSV**)

https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni/workspace/query?queryid=27d648c4-f765-4e39-935e-4d504278cd22 (**la query**)
