### ISSUE TITLE
[import in google sheet] mantenere lo zero prima dei numeri telefonici

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#48]
Buon dì, ho un problema con alcune colonne che contengono numeri di telefono di rete fissa, google sheet fa sparire lo **zero** iniziale dei prefissi.

Esempio **091** diventa **91**

Il file che importo su google sheet è **[questo](https://data.world/opendatasicilia/ipa-indice-delle-pubbliche-amministrazioni/workspace/query?queryid=34110c27-83e8-4ed0-a9bc-4a386f47b5b3)** e le colonne che contengono i numeri di telefono sono formattate come testo è lo **zero** si vede

**Comment by pigreco** [comment]
Ciao,
non ho seguito tutto ma in questi casi io risolvo cosi, con una query cosi fatta:

```sql
SELECT amministrazioni.des_amm,ufficiTDSicilia.*,"'"||ufficiTDSicilia.tel as telefono
FROM
(SELECT *
FROM unita_organizzative
WHERE unita_organizzative.regione LIKE "Sicilia" 
AND unita_organizzative.des_ou LIKE "%trans%digit%") ufficiTDSicilia
INNER JOIN amministrazioni ON ufficiTDSicilia.cod_amm=amministrazioni.cod_amm
ORDER BY amministrazioni.des_amm
```
NB: troverai, troverai come ultimo campo `telefono` .

Volevo solo partecipare hihihih
ciao

**Comment by gbvitrano** [comment]
ho risolto cosi **=IF(ISBLANK(J2), " ", IF(J2<>"",IF(LEFT(J2,1)="9","0"&J2, IF(LEFT(J2,1)="3",J2, ""))))**
dove **J2** è la cella che contine il numero di telefono

Se la cella è vuota restistuisce cella vuota
se il numero iniza conr**9** aggiunge lo zero iniziale perchè telefono fisso
se le inizia per 3 restituisce il valore della cella perchè è un cellulare
