### ISSUE TITLE
Ricetta "uMap - Tematizzare i poligoni"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#49]
@gbvitrano mi sembra che manchi un pezzo (facile): una volta che in QGIS costruisci tutto, poi come lo integri in uMap? Esporti in GeoJSON? 

È scontato, ma lo aggiungerei.

**Comment by gbvitrano** [comment]
Si, è vero, @pigreco mi ha fatto notare, che non ho descritto come popolo il nuovo campo in QGIS, tra poco aggiungo, lo davo per scontato, ma non è così :-)

**Comment by gbvitrano** [comment]
Modifiche fatte :-)
