### ISSUE TITLE
Creare un Feed RSS di una pagina web

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#5]
salve
ripropongo qui come issue una richiesta fatta sulla mailing list di opendatasicilia.
https://groups.google.com/d/msg/opendatasicilia/mj4rOt3VUNg/CXN7VGtKGQAJ

**Creare un Feed RSS di una pagina web**

> _sono interessato a questa pagina degli eventi della Feltrinelli di Palermo:
https://www.lafeltrinelli.it/fcom/it/home/pages/puntivendita/negozi/trova/sicilia/RicordiMediaStores-Palermo.html (soprattutto per gli eventi rivolti ai bambini)
e vorrei creare un Feed RSS.
Ho provato con Feedburner: https://feedburner.google.com ma una volta immesso l'URL mi da un messaggio:
The URL does not appear to reference a valid XML file. We encountered the following problem: Error on line 4: Element type "t.length" must be followed by either attribute specifications, ">" or "/>".
Quindi qualcosa nella pagina HTML degli eventi di Palermo della Feltrinelli non piace a Feedburner di Google.
Ci sono altre vie da percorrere per creare un Feed RSS di una pagina come questa?
Grazie_ 

Andrea Borruso aveva dato la [risposta](https://groups.google.com/d/msg/opendatasicilia/mj4rOt3VUNg/mHYBpqNCDAAJ) nel thread a seguito della mia richiesta.
Ma vorrei seguire qui la procedura per testare questo metodo delle issue.
Quindi please @aborruso se vuoi gentilmente incollare qui la tua risposta, ma, ripeto, solo per didattica per come usare questa nuova metodologia delle issue su questo repository.
Grazie, e buona domenica

**Comment by aborruso** [comment]
Caro Ciro,
obbedisco. A te chiudere la issue, se soddisfa quanto da te chiesto. Se hai tempo, potresti scrivere una mini ricetta (come creare un feed RSS di una pagina web). Ma vado alla tua issue.

Per creare un feed RSS con feed43, devi partire dall'analizzare il codice HTML della pagina web sorgente, e cercare l’elemento che si ripete. Tasto destro sulla parte di pagina con un elemento da trasformare in feed e poi ispeziona il codice.
Devi cercare l’intero blocco di codice che si ripete per ogni elemento. Qui ad esempio è

```html
<div class="event clearfix"><img width="60" src="https://www.lafeltrinelli.it/mediaObject/eventi/2019/01/Spyrosil-Marinaio-Italiano-27624/resolutions/res-l60x10000/Spyrosil-Marinaio-Italiano-27624.jpg"/><div class="text"><h4 class="date">Martedì 5 Febbraio 2019 dalle ore 18:00</h4><h3><a href="https://www.lafeltrinelli.it/fcom/it/home/pages/puntivendita/eventi/Palermo/2019/Febbraio/Spyrosil-Marinaio-Italiano-27624.html">Spyros Il marinaio italiano</a></h3><div class="button-link button-detail clearfix"><a href="https://www.lafeltrinelli.it/fcom/it/home/pages/puntivendita/eventi/Palermo/2019/Febbraio/Spyrosil-Marinaio-Italiano-27624.html">SCOPRI</a></div></div></div>
```

Nella pagina originale non è indentato, così è più leggibile

```html
<div class="event clearfix">
   <img width="60" src="https://www.lafeltrinelli.it/mediaObject/eventi/2019/01/Spyrosil-Marinaio-Italiano-27624/resolutions/res-l60x10000/Spyrosil-Marinaio-Italiano-27624.jpg"/>
   <div class="text">
      <h4 class="date">Martedì 5 Febbraio 2019 dalle ore 18:00</h4>
      <h3><a href="https://www.lafeltrinelli.it/fcom/it/home/pages/puntivendita/eventi/Palermo/2019/Febbraio/Spyrosil-Marinaio-Italiano-27624.html">Spyros Il marinaio italiano</a></h3>
      <div class="button-link button-detail clearfix"><a href="https://www.lafeltrinelli.it/fcom/it/home/pages/puntivendita/eventi/Palermo/2019/Febbraio/Spyrosil-Marinaio-Italiano-27624.html">SCOPRI</a></div>
   </div>
</div>
```

Nel codice HTML devi cercare le parti variabili e sostituirle con `{%}`. Quindi prendendo il codice originale (quello non indentato) avrai

```html
<div class="event clearfix"><img width="60" src="{%}"/><div class="text"><h4 class="date">{%}</h4><h3><a href="{%}">{%}</a></h3><div class="button-link button-detail clearfix"><a href="{%}">SCOPRI</a></div></div></div>
```
![image](https://user-images.githubusercontent.com/30607/52532163-7401f700-2d20-11e9-9ba2-8ecca90450b2.png)

A quel punto potrai estrarre i vari item con feed43

E infine dirgli che `{%4}` è il titolo `{%3}` il link, ecc..

E alla fine avrai un RSS https://feed43.com/7445176480120553.xml

**Comment by cirospat** [comment]
grazie @aborruso 
certo, spetta ora a me creare una ricetta dentro l'apposito contenitore di questo repository.

**Comment by cirospat** [comment]
creata ricetta "Creare un Feed RSS di una pagina web" qui:
https://github.com/opendatasicilia/tansignari/blob/master/ricette/Creare_un_Feed_RSS_di_una_pagina_web.md

**Comment by aborruso** [comment]
@cirospat ho fatto un vile denominato[ "varie"](https://github.com/opendatasicilia/tansignari/blob/master/ricette/varie.md), in cui ho messo la tua. E poi ce ne saranno altre.

Ho aggiunto a inizio ricetta, issue di riferimento e autore ricetta. Che te ne pare?

Se la cosa ti fila, cancella la tua ricetta singola.

Grazie

**Comment by cirospat** [comment]
un file "varie" in cui ci potrebbero essere 10-20-30-... ricette diverse tra loro non lo riesco a vedere soprattutto se in prospettiva di alimentare un Read the Docs.
Vedo un file MD (o anche RST) per ogni ricetta che poi diventerebbe una pagina HTML di un Read the Docs. In tal maniera potremmo avere un indice di RTD molto ricco di pagine HTML (=ricette) che da l'idea della ricchezza delle ricette create.
Che ne dici dell'impostazione che ho in mente?
