### ISSUE TITLE
Ricetta Estrarre dati da un file XML: allegare file di input

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#52]
@pigreco inserirei nel testo la possibilità di scaricarsi il file XML, in modo da poter replicare tutto.

Grazie

https://tansignari.readthedocs.io/it/latest/ricette/script/Estrarre_dati_da_file_XML.html#estrarre-dati-da-un-file-xml

**Comment by pigreco** [comment]
@aborruso ottima idea, provvedo e ricompilo.

grazie
