### ISSUE TITLE
[spatialite] come registrare una geometria 2D in 3D con cambio di EPSG

### ISSUE THREAD

**Issue by Heryx** [opendatasicilia/tansignari#54]
Salve a tutti,

sto cercando di trasformare delle coordinate rilevate con un GPS WGS84 in RDN2008.
Dopo aver importato il mio shapefile su SpatiaLite, creo una tabella con questa query:

CREATE TABLE nome_tabella AS SELECT nome, x, y, z, ST_Transform(geom, SRID) AS geom FROM myTable;

inserendo il nome della nuova tabella e nella funzione **ST_Transform(geom, 6708)**.

dopodiché faccio un "check geometries" sull'attributo geom della nuova tabella appena creata. E infine effettuo il **recovery geomtry column** con il SR **6708**, **XYZM**, **POINT**, ma mi da un errore
![image](https://user-images.githubusercontent.com/11267377/56039168-f3697200-5d33-11e9-9daa-21c4d0116474.png)

Qui potete vedere l'errore: 
![image](https://user-images.githubusercontent.com/11267377/56039255-23187a00-5d34-11e9-8d8e-b61156de9fae.png)

Sto utilizzando SpatiaLite versione 5.0.0 beta.
Come posso risolvere?

[https://groups.google.com/d/topic/spatialite-users/nyqzVXPC-MQ/discussion](url)

**Comment by aborruso** [comment]
@Heryx soltanto come nota generale: condividi (se puoi) sempre i dati di partenza (anche soltanto un estratto).
Così chi vorrà rispondere, potrà testare pienamente quanto da te scritto.

Grazie e benvenuto

**Comment by pigreco** [comment]
Ciao @Heryx,
provo a capire il problema anche senza dati e seguendo le tue indicazioni:

la tua query:

```sql
CREATE TABLE nome_tabella AS 
SELECT nome, x, y, z, ST_Transform(geom, SRID) AS geom
FROM myTable;
```

crea solamente una geotabella seguendo la geometria dello shapefile e trasformando solo EPSG, quindi se la geometria era XY rimarrà XY.
L'errore è proprio questo, nel ricoverare la geometria hai selezionato una dimensione errata (XYZM) al posto di XY.

prova la seguente query:

```sql
CREATE TABLE "aggeo190409_new2" AS 
SELECT nome,x, y, z, makepointz(ST_x(geom), ST_y(geom), cast(z as double),6708) as geom
FROM "aggeo190409";
```

e poi lancia questa query per fare il Recover Geometry Column:
```
SELECT RecoverGeometryColumn('aggeo190409_new2', 'geom',6708, 'POINT', 'XYZ');
```

**Comment by Heryx** [comment]
> @Heryx soltanto come nota generale: condividi (se puoi) sempre i dati di partenza (anche soltanto un estratto).
> Così chi vorrà rispondere, potrà testare pienamente quanto da te scritto.
> 
> Grazie e benvenuto

Ciao Andrea, ok grazie mille

**Comment by Heryx** [comment]
> Ciao @Heryx,
> provo a capire il problema anche senza dati e seguendo le tue indicazioni:
> 
> la tua query:
> 
> ```sql
> CREATE TABLE nome_tabella AS 
> SELECT nome, x, y, z, ST_Transform(geom, SRID) AS geom
> FROM myTable;
> ```
> 
> crea solamente una geotabella seguendo la geometria dello shapefile e trasformando solo EPSG, quindi se la geometria era XY rimarrà XY.
> L'errore è proprio questo, nel ricoverare la geometria hai selezionato una dimensione errata (XYZM) al posto di XY.
> 
> prova la seguente query:
> 
> ```sql
> CREATE TABLE "nome_tabella_new" AS 
> SELECT nome,x, y, z, makepointz(ST_x(geom), ST_y(geom), cast(z as double),6708) as geom
> FROM "myTable";
> ```
> 
> e poi lancia questa query per fare il Recover Geometry Column:
> 
> ```sql
> SELECT RecoverGeometryColumn('nome_tabella_new', 'geom',6708, 'POINT', 'XYZ');
> ```

Grazie mille Totò, adesso funziona.

**Comment by pigreco** [comment]
Caro @Heryx  purtroppo c'è una brutta notizia per te :)

In questo spazio c'è un galateo in cui una delle voci è "se sei soddisfatta/o della risposta, sei invitato a rimborsare, creando un testo, una ricetta, che racconti per bene il problema che hai riscontrato e come è possibile risolverlo".

Quindi ti chiediamo di trasformare questa procedura, in una mini guida (ovviamente copiando da questo scambio). Le stiamo mettendo qui https://github.com/opendatasicilia/tansignari/tree/master/ricette

**Comment by Heryx** [comment]
Sì ho letto il galateo, infatti presto scriverò una ricetta ;)

Ad ogni modo complimenti a tutti voi, questa è una bellissima idea.
