### ISSUE TITLE
[accesso a documenti]: i turni di spazzamento di una municipalizzata

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#55]
Buonasera,
la RAP, l'azienda municipalizzata di Palermo che si occupa della gestione dei rifiuti non pubblica da credo più di una anno il piano di spazzamento; la cosa è apprezzabile nella copia della [pagina dedicata](https://web.archive.org/web/*/http://www.rapspa.it/site/spazzamento/), nel tempo.

Vorrei che pubblicassero (o voglio leggere) questa informazione, con i turni previsti per la città. Che tipo di richiesta potrei fare?

Grazie

**Comment by cirospat** [comment]
Accesso civico generalizzato
O
Accesso civico.
Qui gli esperti di accesso civico possono dare consigli.

Per conoscenza richiesta a contatti del comune (ambiente).

Per conoscenza richiesta inviata ai media.
In quanto è argomento di interesse molto pubblico.


Il sab 13 apr 2019, 18:21 Andrea Borruso <notifications@github.com> ha
scritto:

**Comment by giuragu** [comment]
Io farei una richiesta di accesso civico semplice chiedendone la pubblicazione nella sottosezione "atti amministrativi generali" che si trova nel percorso [Amministrazione Trasparente/Disposizioni Generali/Atti Generali/Atti Amministrativi generali](https://trasparenza.rapspa.it/pagina851_atti-amministrativi-generali.html) (dove devono stare come da [elenco obblighi by Anac](http://www.anticorruzione.it/portal/rest/jcr/repository/collaboration/Digital%20Assets/anacdocs/Attivita/Atti/determinazioni/2016/1310/Del.1310.2016.All.pdf) le " Direttive, circolari, programmi, istruzioni e ogni atto che dispone in generale sulla organizzazione, sulle funzioni, sugli obiettivi, sui procedimenti".

**Comment by aborruso** [comment]
Ho fatto come suggerito da @giuragu usando il mitio [FOIAPop](http://www.foiapop.it/) (vica @gpirrotta e @giuragu !)

Chiudo la issue e aspetto risposta. In base agli esiti scriverò ricetta.

Grazie a tutti

**Comment by aborruso** [comment]
Riapro la issue, perché la richiesta è stata respinta, in quanto i "turni di spazzamento" non sono un documento di cui c'è obbligo di pubblicazione in Amministrazione Trasparente.

Tra scartoffie e burocrazia, la V città di Italia non informa i cittadini sulla gestione della nettezza urbana. Però abbiamo la fibra. 

@giuragu che ne pensi? Scrivo una semplice PEC all'azienda?

L'azienda in ogni caso è stata messa in copia e valuterà la mia richiesta.

Saluti

[Istanza di accesso civico nota n. 646395 del 02.05.2019.pdf](https://github.com/opendatasicilia/tansignari/files/3137315/Istanza.di.accesso.civico.nota.n.646395.del.02.05.2019.pdf)

**Comment by giuragu** [comment]
Ciao @aborruso,
si direi una semplice PEC alla RAP in attesa che la stessa risponda a quanto inoltrato loro.
Nella risposta personalmente vorrei capire come lo classificano se non possiamo definirlo atto amministrativo generale. Atto...? 

Tienimi aggiornato

**Comment by aborruso** [comment]
La RAP mi ha risposto con il documento di sotto:

[001-0015026-GEN-2019.pdf](https://github.com/opendatasicilia/tansignari/files/3144280/001-0015026-GEN-2019.pdf)

Mi invitano a fare riferimento alla [Carta dei Servizi 2019](https://trasparenza.rapspa.it/archiviofile/rapspa/carta_dei_servizi_2019.pdf), in cui sui turni di spazzamento io vedo soltanto quanto riportato nell'immagine di sotto.
Ed è quindi impossibile capire per una certa strada quando è previsto lo spazzamento.
Anche nel [contratto di servizio](https://trasparenza.rapspa.it/moduli/downloadFile.php?file=oggetto_allegati/162001228230O__Ocontratto_servizio_rap.pdf) (che non rispetta norme su accessibilità) non trovo traccia di informazioni utili.

A me questa cosa sembra molto grave; in sé e poi nel dialogo con il cittadino :(

![image](https://user-images.githubusercontent.com/30607/57178246-c2c9b380-6e6d-11e9-8984-77225095ca13.png)

**Comment by cirospat** [comment]
caro Andrea
credo sia molto difficile che RAP dica al cittadino in quali giorni della
settimana, e in che ore, passa il personale per lo spazzamento nella via
taldeitali.
La vedo dura.
In altre città, è vero, lo dicono al cittadino.
Sicuramente hanno i dati dello spazzamento viario con turni per i quartieri
(o porzioni di quartieri) con il personale addetto (nomi-cognomi), con i
giorni e con gli orari previsti, ... avranno qualche excel o se va bene
qualche applicativo ad hoc. Ma che diano anche solo i giorni dello
spazzamento nella via taldeitali, la vedo molto difficile. Perchè? Non so
risponderti. Ma è una sensazione che mi fa dire che è difficile.
Probabilmente perchè se poi non rispettano i turni giornalieri si espongono
a forti critiche, è la motivazione che mi viene più facile pensare, anche
se non è una giustificazione per negare l'informazione al cittadino.






Il giorno sab 4 mag 2019 alle ore 13:27 Andrea Borruso <
notifications@github.com> ha scritto:

**Comment by aborruso** [comment]
@cirospat io non voglio sapere se vengono domenica 5.

Mi basta sapere che nella mia strada è previsto tre volte al mese. Soltanto se lo so, mi posso lamentare o complimentare.

Se vedo per 3 settimane c'è lo stesso mucchio di lattine di Coca Cola devo fare qualche segnalazione? Se  il turno è settimanale sì. E se lo so e se segnalo posso provare a fare seriamente pressione su Comune e RAP a cambiare le cose. Se non lo so, la mia azione sarà molto più debole.

**Comment by cirospat** [comment]
Andrea
capisco e condivido, anche io vorrei sapere la stessa cosa tua ma per la
mia strada, .... sempre lo stesso paio di pantaloni per terra da
settimane!!!

Dopo questa risposta che hai ricevuto, bisognerebbe richiedere per quella
via specifica quanti turni di spazzamento alla settimana o al mese sono
previsti. Specificando che dalla risposta che loro hanno fornito non si
evince questa informazione che si richiede ancora una volta.
Mi sembra il minimo, a parer mio.



Il giorno sab 4 mag 2019 alle ore 14:13 Andrea Borruso <
notifications@github.com> ha scritto:

**Comment by aborruso** [comment]
@cirospat ho già risposto come sotto.

E ho pure segnalato al difensore civico i problemi di accessibilità.

![image](https://user-images.githubusercontent.com/30607/57178910-f9a4c700-6e77-11e9-8054-c489d74a3796.png)

**Comment by cirospat** [comment]
Come sempre hai fatto la migliore e più giusta cosa.
Grazie anche a nome mio.

Il sab 4 mag 2019, 14:22 Andrea Borruso <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
Chiudo è stato un fallimento senza esito

**Comment by cirospat** [comment]
accesso civico generalizzato di nuovo ?






Il giorno dom 16 giu 2019 alle ore 17:53 Andrea Borruso <
notifications@github.com> ha scritto:

**Comment by giuragu** [comment]
@aborruso @cirospat 

> accesso civico generalizzato di nuovo ?

non sarebbe "di nuovo" perché la prima fu istanza di accesso civico semplice rigettata perché non di competenza (poi rispose RAP) ma soprattutto perché ritenuto un documento su cui non vige obbligo di pubblicazione in amm. trasparente.
 
Quindi suggerirei di presentare accesso civico generalizzato come diceva Ciro a RAP.

**Comment by aborruso** [comment]
La chiudo, zero esiti :(
