### ISSUE TITLE
Aggiungere sezione "sitografia" a fondo ricetta

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#57]
Su alcune delle ricette ci sono blog post correlati, o in modo diretto (post che replicano quanto scritto della ricetta) o in modo meno forte.

Potremmo mettere la raccolta di link in fondo alla ricetta, come ho fatto ad esempio qui [https://tansignari.readthedocs.io/it/latest/ricette/script/Estrarre_dati_da_file_XML.html#chi-ha-cucinato-questa-ricetta-o-ne-ha-tratto-ispirazione](https://tansignari.readthedocs.io/it/latest/ricette/script/Estrarre_dati_da_file_XML.html#chi-ha-cucinato-questa-ricetta-o-ne-ha-tratto-ispirazione).

Che ve ne pare?

**Comment by pigreco** [comment]
@aborruso 
ottima idea e grazie per averla applicata alla ricetta

grazie 👍

**Comment by gbvitrano** [comment]
Ottima idea
