### ISSUE TITLE
[GIS] file XML come sostituire/modificare alcuni dati

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#58]
Ho un file XML la cui struttura è quella di un file [QML](https://github.com/opendatasicilia/tansignari/files/3055033/tema.zip) (proveniente dalla tematizzazione - metodo categorizzato - di un layer vettoriale in QGIS) come potrei sostituire/modificare solo alcuni valori presenti nel file?? in realtà non è una semplice sostituzione da risolvere con un trova e sostituisci in quanto occorre trovare un dato (presente nella prima colonna della tabella `name="0"` - vedi sotto) e sostituire il dato della seconda colonna in `v=`: `<prop v="232,193,76,255" k="color"/>`

![image](https://user-images.githubusercontent.com/7631137/56123598-0fa82180-5f75-11e9-9df8-6746b2279e31.png)

![image](https://user-images.githubusercontent.com/7631137/56120970-817d6c80-5f6f-11e9-997c-34508387e045.png)

I dati da sostituire/modificare provengono da altro file QML e sono stati estrapolati seguendo issue #50, i dati sono

```
"0","232,193,76,255"
"1","48,218,227,255"
"10","231,108,155,255"
"11","237,177,124,255"
"12","63,175,231,255"
"13","210,214,92,255"
"14","234,16,38,255"
"15","239,110,81,255"
"16","50,235,192,255"
"17","160,107,220,255"
"18","98,66,238,255"
"19","34,233,131,255"
"2","224,59,169,255"
"3","163,225,124,255"
"4","162,15,210,255"
"5","68,239,48,255"
"6","179,235,59,255"
"7","219,21,209,255"
"8","18,39,233,255"
"9","120,204,137,255"
```
usando utility **[XMLSTARLET](http://xmlstar.sourceforge.net/doc/xmlstarlet.pdf)** e la guida, per un test su singolo valore:

```
<tema_rev.xml xmlstarlet fo -D | xmlstarlet ed -P -u '//symbols/symbol[layer/prop[@k="color"]]/@v' -v "232,193,76,255">./tema_u.xml
```
ottengo l'output ma senza la modifica

il file QML da modificare è qui:

[tema_rev.zip](https://github.com/opendatasicilia/tansignari/files/3079468/tema_rev.zip)

**Comment by gpirrotta** [comment]
In python puoi fare così:

```python
from bs4 import BeautifulSoup

myDict = {}

myDict['0']='232,193,76,255'
myDict['1']='48,218,227,255'
myDict['10']='231,108,155,255'
myDict['11']='237,177,124,255'
myDict['12']='63,175,231,255'
myDict['13']='210,214,92,255'
myDict['14']='234,16,38,255'
myDict['15']='239,110,81,255'
myDict['16']='50,235,192,255'
myDict['17']='160,107,220,255'
myDict['18']='98,66,238,255'
myDict['19']='34,233,131,255'
myDict['2']='224,59,169,255'
myDict['3']='163,225,124,255'
myDict['4']='162,15,210,255'
myDict['5']='68,239,48,255'
myDict['6']='179,235,59,255'
myDict['7']='219,21,209,255'
myDict['8']='18,39,233,255'
myDict['9']='120,204,137,255'

infile = open('tema_rev.xml','r')
contents = infile.read()
soup = BeautifulSoup(contents,'xml')
symbols = soup.select('symbol')
for symbol in symbols:
    if symbol['name'] in myDict:
        prop = symbol.find('prop', {'k' : 'color'})
        prop['v'] = myDict[symbol['name']]

xml = soup.prettify('utf-8')
with open('tema.xml', 'wb') as outfile:
    outfile.write(xml)
```

ciao
Giovanni

**Comment by pigreco** [comment]
ciao @gpirrotta 
ho salvato il tuo script come `script.py`, ma quando lo lancio:

![image](https://user-images.githubusercontent.com/7631137/56157557-1d36c900-5fc0-11e9-82c1-de4dfba29127.png)

cosa sbaglio?

**Comment by gpirrotta** [comment]
> cosa sbaglio?

prova a installare questa libreria

```
pip install lxml
```

fammi sapere, 
g.

**Comment by pigreco** [comment]
@gpirrotta 

```
pip3 install lxml
```

![image](https://user-images.githubusercontent.com/7631137/56162287-eb2b6400-5fcb-11e9-81da-556b0c7739bb.png)

grazie, funziona benissimo lo script.py

Ti chiedo un'altra cortesia, 
scrivere a mano l'intero dizionario è noioso e potrei commettere errori,
come potrei fare a sfruttare un file di input.csv con i dati dell'esempio??

grazie

**Comment by aborruso** [comment]
Ciao @pigreco,
con xmlstarlet puoi fare questo ciclo in bash

```
while IFS=$'\t' read -r col1 col2
do
    xmlstarlet ed --inplace -u '//symbols/symbol[@name='"$col1"']/layer/prop[@k="color"]/@v' -v "$col2" tema.xml
done < input.tsv
```

A partire da un TSV fatto così

```
0	232,193,76,255
1	48,218,227,255
10	231,108,155,255
11	237,177,124,255
12	63,175,231,255
13	210,214,92,255
14	234,16,38,255
15	239,110,81,255
16	50,235,192,255
17	160,107,220,255
18	98,66,238,255
19	34,233,131,255
2	224,59,169,255
3	163,225,124,255
4	162,15,210,255
5	68,239,48,255
6	179,235,59,255
7	219,21,209,255
8	18,39,233,255
9	120,204,137,255
```

**Comment by pigreco** [comment]
Ho chiesto a @gpirrotta 

> Ti chiedo un'altra cortesia,
scrivere a mano l'intero dizionario è noioso e potrei commettere errori,
come potrei fare a sfruttare un file di input.csv con i dati dell'esempio??

ecco la sua risposta:

```python
import csv

myDict = {}

with open('dict.txt', 'r') as dictfile:
    csvreader = csv.reader(dictfile, delimiter=',')
    for row in csvreader:
        myDict[row[0]] = row[1]

from bs4 import BeautifulSoup

infile = open('tema_rev.xml','r')
contents = infile.read()
soup = BeautifulSoup(contents,'xml')
symbols = soup.select('symbol')
for symbol in symbols:
    if symbol['name'] in myDict:
        prop = symbol.find('prop', {'k' : 'color'})
        prop['v'] = myDict[symbol['name']]

xml = soup.prettify('utf-8')
with open('tema_u2.xml', 'wb') as file:
    file.write(xml)
```
dove `dict.txt` rappresenta un file CSV con i dati dell'esempio.

grazie

**Comment by aborruso** [comment]
Solo per dare il benvenuto al professore @gpirrotta !!

**Comment by pigreco** [comment]
Caro @aborruso 
bella anche la tua soluzione grazie. :-)

**Comment by pigreco** [comment]
Grazie a questa issue ho risolto un bel problema su QGIS:

https://pigrecoinfinito.wordpress.com/2019/04/16/qgis-ricreare-la-legenda-a-partire-dal-colore-rgba-presente-nella-tabella-attributi/

domani pubblico blog post

**Comment by pigreco** [comment]
Ricetta pronta e impiattata 

https://github.com/opendatasicilia/tansignari/blob/master/ricette/script/Modificare_file_XML.md
