### ISSUE TITLE
IFTTT - come realizzare Servizi

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#6]
Buongiorno,
come posso realizzare un servizio IFTTT che mi notifichi in un gruppo telegram o whatsapp che in sito web è stato pubblicato un nuovo articolo?
O se su twitter è stato pubblicato un Twitt  con un determinato # ?
Grazie :-)

**Comment by aborruso** [comment]
Caro @gbvitrano non mi odiare: hai provato a farlo e non ha funzionato? Se sì, che errore/problema hai avuto?

Due note:

- una notifica alla variazione del cambio pagina di base non si può avere. Se la pagina ha un feed si può fare. Altrimenti devi creare il feed o altro sistema che mappa le variazioni di pagine;
- su whatsapp non è possibile fare quanto chiedi, in quanto le API non lo consentono.

**Comment by gbvitrano** [comment]
Come posso odiarti @aborruso  :-)
hai ragione... ho aperto... mi sono confuso e chiuso tutto.
Ci riprovo :-)

**Comment by aborruso** [comment]
Hai provato a seguire la guida ufficiale?

https://help.ifttt.com/hc/en-us/articles/360003121113-How-to-get-started-using-IFTTT-with-Telegram

**Comment by martinomaggio** [comment]
Ciao qui trova una discussione sul tema:
https://www.quora.com/How-can-I-setup-IFTT-to-monitor-a-website-for-changes-every-day

**Comment by aborruso** [comment]
Chiudo, è passato un anno
