### ISSUE TITLE
[script] join tra due tabelle csv/tsv usando Miller

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#60]
Ho due file testuali:
1. `layer.csv` con intestazione e due colonne; 
2. `out_regioni_xpath.tsv` senza intestazione e tre colonne;

vorrei utilizzare [Miller](http://johnkerl.org/miller/doc/reference-verbs.html#join) per fare un JOIN tra i due file ( csv 1a colonna, tsv 3a colonna), ho usato questo script

```
mlr --icsv --otsv cat layer.csv >layer_t.tsv
mlr --tsv --implicit-csv-header --headerless-csv-output  join  -j 1 -l {3} -r {1} --lp cucu --rp popo -f out_regioni_xpath.tsv layer_t.tsv >./out_regioni_xpath2.tsv
```
ma ottengo un file di output vuoto

allego i due file:

[layer.zip](https://github.com/opendatasicilia/tansignari/files/3084976/layer.zip)
[out_regioni_xpath.zip](https://github.com/opendatasicilia/tansignari/files/3084977/out_regioni_xpath.zip)

**Comment by aborruso** [comment]
Caro @pigreco adesso una risposta rapida.

Prima converto il file CSV in un TSV senza intestazione (NIDX è il nome di questo formato, in cui ogni campo ha soltanto il nome numerico ... 1 il primo, 2 il secondo, ecc.) e impostando il tab come separatore:

    mlr --icsv --onidx --ofs "\t" cat layer.csv >layer_t.tsv

Poi faccio il join tra il campo 3 del primo e 1 del secondo

    mlr --nidx --fs "\t" join -j 3 -r 1 --rp r -f out_regioni_xpath.tsv layer_t.tsv >out.tsv

ed ottengo

```
Lazio   6       219,67,239,255  179,235,59,255
Basilicata      1       220,156,129,255 48,218,227,255
Lombardia       8       230,217,130,255 18,39,233,255
Abruzzo 0       87,224,33,255   232,193,76,255
Molise  10      65,218,67,255   231,108,155,255
Marche  9       98,53,204,255   120,204,137,255
Liguria 7       38,239,98,255   219,21,209,255
Valle d'Aosta   18      149,203,79,255  98,66,238,255
Umbria  17      238,100,98,255  160,107,220,255
Campania        3       233,27,141,255  163,225,124,255
Toscana 15      85,213,196,255  239,110,81,255
Piemonte        11      73,120,239,255  237,177,124,255
Calabria        2       13,212,129,255  224,59,169,255
Puglia  12      194,216,64,255  63,175,231,255
Veneto  19      222,91,126,255  34,233,131,255
Friuli Venezia Giulia   5       183,107,236,255 68,239,48,255
Emilia-Romagna  4       205,172,125,255 162,15,210,255
Trentino-Alto Adige     16      139,223,237,255 50,235,192,255
Sicilia 14      50,157,238,255  234,16,38,255
Sardegna        13      217,51,190,255  210,214,92,255
```

**Comment by pigreco** [comment]
@aborruso funziona benissimo, grazie!

ma se volessi mantenere solo le due colonne centrali e quindi cancellare la 1a e 4a colonna??

**Comment by aborruso** [comment]
aggiungi il cut

    mlr --nidx --fs "\t" join -j 3 -r 1 --rp r -f out_regioni_xpath.tsv then cut -f 2,3 layer_t.tsv >out.tsv

**Comment by pigreco** [comment]
@aborruso funziona tutto benissimo

ecco lo script finale utilizzato:

```
mlr --icsv --onidx --ofs "\t" cat layer.csv >layer_t.tsv
mlr --nidx --fs "\t" join -j 3 -r 1 --rp r -f out_regioni_xpath.tsv then cut -f 1,r2 layer_t.tsv >out.tsv
```

grazie 👍

**Comment by pigreco** [comment]
Realizzata [ricetta ](https://github.com/opendatasicilia/tansignari/blob/master/ricette/script/Join_tra_file_testuali_usando_Miller.md)sezione script

grazie 👍
