### ISSUE TITLE
[SPARQL] perché una query su wikidata mi va in timeout?

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari#65]
Ciao,
apro una nuova issue, perché altrimenti rischio di portare fuori tema la #64 
E chiedo sempre una mano a @dtaibi @gpirrotta @ninokeys e tutti quelli che sono "agili" su questi temi.

Se lancio [questa query](https://query.wikidata.org/#SELECT%20%3Fprovincia%20%3FprovinciaLabel%20%3Fcapoluogo%20%3FcapoluogoLabel%20%3Fcoordinate%20WHERE%20%7B%0A%3Fprovincia%20wdt%3AP31%20wd%3AQ15089.%0A%3Fprovincia%20wdt%3AP635%20%3FistatIDProvincia.%0A%3Fprovincia%20p%3AP31%20%3Fstatement.%0AOPTIONAL%20%7B%20%3Fprovincia%20wdt%3AP36%20%3Fcapoluogo.%7D%0AOPTIONAL%20%7B%20%3Fcapoluogo%20wdt%3AP625%20%3Fcoordinate.%7D%0AFILTER%20NOT%20EXISTS%20%7B%20%3Fstatement%20pq%3AP582%20%3Fx%20%7D%0ASERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20"%5BAUTO_LANGUAGE%5D%2Cit".%20%7D%0A%7D%0AORDER%20BY%20%3Fcoordinate) in wikidata, ottengo le coordinate dei capoluoghi di **provincia attive** in Italia.

```
SELECT ?provincia ?provinciaLabel ?capoluogo ?capoluogoLabel ?coordinate WHERE {
?provincia wdt:P31 wd:Q15089.
?provincia wdt:P635 ?istatIDProvincia.
?provincia p:P31 ?statement.
OPTIONAL { ?provincia wdt:P36 ?capoluogo.}
OPTIONAL { ?capoluogo wdt:P625 ?coordinate.}
FILTER NOT EXISTS { ?statement pq:P582 ?x }
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],it". }
}
ORDER BY ?coordinate
```

Per filtrare soltanto le attive ho aggiunto `?provincia p:P31 ?statement.` e il filtro `P582`, in modo da mostrare tutte quelle per cui non è valorizzato l'_end date_.

Se rimuovo questo filtro e la [trasformo](https://query.wikidata.org/#SELECT%20%3Fprovincia%20%3FprovinciaLabel%20%3Fcapoluogo%20%3FcapoluogoLabel%20%3Fcoordinate%20WHERE%20%7B%0A%3Fprovincia%20wdt%3AP31%20wd%3AQ15089.%0A%3Fprovincia%20wdt%3AP635%20%3FistatIDProvincia.%0AOPTIONAL%20%7B%20%3Fprovincia%20wdt%3AP36%20%3Fcapoluogo.%7D%0AOPTIONAL%20%7B%20%3Fcapoluogo%20wdt%3AP625%20%3Fcoordinate.%7D%0ASERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cit%22.%20%7D%0A%7D%0AORDER%20BY%20%3Fcoordinate) in

```
SELECT ?provincia ?provinciaLabel ?capoluogo ?capoluogoLabel ?coordinate WHERE {
?provincia wdt:P31 wd:Q15089.
?provincia wdt:P635 ?istatIDProvincia.
OPTIONAL { ?provincia wdt:P36 ?capoluogo.}
OPTIONAL { ?capoluogo wdt:P625 ?coordinate.}
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],it". }
}
ORDER BY ?coordinate
```

il motore di query di wikidata mi va in timeout. Non capisco perché: la sintassi mi sembra corretta e omologa alla precedente. 
Cosa sbaglio?

Grazie

**Comment by gpirrotta** [comment]
Il problema potrebbe risiedere nella seconda OPTIONAL perchè ?capoluogo lo
metti già nella prima OPTIONAL e potrebbe non essere presente.
Annidando le OPTIONAL dovresti risolvere:

*SELECT ?provincia ?provinciaLabel ?capoluogo ?capoluogoLabel ?coordinate
WHERE {*
*?provincia wdt:P31 wd:Q15089.*
*?provincia wdt:P635 ?istatIDProvincia.*
* OPTIONAL {?provincia wdt:P36 ?capoluogo. *
*          OPTIONAL { ?capoluogo wdt:P625 ?coordinate.}*
* }*
*SERVICE wikibase:label { bd:serviceParam wikibase:language
"[AUTO_LANGUAGE],it". }*
*}*
*ORDER BY ?coordinate*

Bye


Se rimuovo questo filtro e la trasformo
> <https://query.wikidata.org/#SELECT%20%3Fprovincia%20%3FprovinciaLabel%20%3Fcapoluogo%20%3FcapoluogoLabel%20%3Fcoordinate%20WHERE%20%7B%0A%3Fprovincia%20wdt%3AP31%20wd%3AQ15089.%0A%3Fprovincia%20wdt%3AP635%20%3FistatIDProvincia.%0AOPTIONAL%20%7B%20%3Fprovincia%20wdt%3AP36%20%3Fcapoluogo.%7D%0AOPTIONAL%20%7B%20%3Fcapoluogo%20wdt%3AP625%20%3Fcoordinate.%7D%0ASERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cit%22.%20%7D%0A%7D%0AORDER%20BY%20%3Fcoordinate>
> in
>
> SELECT ?provincia ?provinciaLabel ?capoluogo ?capoluogoLabel ?coordinate WHERE {
>
> ?provincia wdt:P31 wd:Q15089.
>
> ?provincia wdt:P635 ?istatIDProvincia.
>
> OPTIONAL { ?provincia wdt:P36 ?capoluogo.}
>
> OPTIONAL { ?capoluogo wdt:P625 ?coordinate.}
>
> SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],it". }
>
> }
>
> ORDER BY ?coordinate
>
>

**Comment by aborruso** [comment]
Caro @gpirrotta ,
nonostante il tuo reply via email abbia distrutto la formattazione della query (maledetti mac :) ), funziona perfettamente, grazie.

Ed è proprio come dici, il problema è per i casi in cui la proprietà non è presente.

Se infatti faccio riferimento alle sole province attive, posso usare la mia query di sopra, perché per tutte le province attive "capoluogo" è definito. La query è

```
SELECT ?provincia ?provinciaLabel ?capoluogo ?capoluogoLabel ?coordinate WHERE {
?provincia wdt:P31 wd:Q15089.
?provincia wdt:P635 ?istatIDProvincia.
?provincia p:P31 ?statement.
OPTIONAL { ?provincia wdt:P36 ?capoluogo.}
OPTIONAL { ?capoluogo wdt:P625 ?coordinate.}
FILTER NOT EXISTS { ?statement pq:P582 ?x }
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],it". }
}
ORDER BY ?coordinate
```

Grazie

**Comment by gpirrotta** [comment]
>
>
> nonostante il tuo reply via email abbia distrutto la formattazione della
> query (maledetti mac :) )
>
prima o poi riuscirò a farti passare al lato oscuro... ;-)
