### ISSUE TITLE
[encoding] terminatore dichiarazione SQL (punto e virgola)

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#66]
Il carattere punto e virgola è un terminatore dichiarazione. Fa parte dello standard ANSI SQL-92.

Ho scoperto che il seguente script:

```sql
SELECT CreateClonedTable('MAIN', 'regioni', 'regioni_new', 1, '::ignore::geom');
ALTER TABLE "regioni_new" ADD COLUMN "grande_Andy" TEXT;
SELECT AddGeometryColumn ('regioni_new','geom',6708,'POINT','XY');
INSERT INTO "regioni_new" (pk_uid,"cod_reg","den_reg","geom")
SELECT NULL,"cod_reg","den_reg",ST_centroid (ST_Transform(geom,6708))
FROM "regioni";
```

non funziona in spatialite_gui se il terminatore `;` non è quello desiderato,
ma come faccio a capirlo??

se lo script lo scrivessi direttamente in spatialite_gui non riscontro problemi ma se copiassi parte della script da github [(`SELECT AddGeometryColumn ('pti_pill','geom',3003,'POINT','XY');`](https://github.com/pigreco/pill/blob/e70518cd7601218f94130052d48f61c5f8bb3d62/pti_pill.sql#L26) e incollassi in NotePad++ lo script non funziona.

[db_test.zip](https://github.com/opendatasicilia/tansignari/files/3152518/db_test.zip)

[script_sql_difettoso.txt](https://github.com/opendatasicilia/tansignari/files/3152525/script_sql_difettoso.txt)

lo script, da rinominare in .sql, va richiamato da spatialite_gui ed eseguito come script sql:
ho provato anche cambiando encoding ma nulla; eseguendo lo script compare il seguente messaggio
![image](https://user-images.githubusercontent.com/7631137/57298560-cf9b1100-70d2-11e9-924f-af478e1d2fac.png)
cioè non esegue nulla!!!

**Comment by aborruso** [comment]
Caro @pigreco è dura.

In unix con `cat -vt ` puoi stampare anche i caratteri nascosti di un file.

Se faccio il copia e incolla da Github a notepad++ e creo un file  il tuo script è:

```
SELECT CreateClonedTable('MAIN', 'regioni', 'regioni_new', 1, '::ignore::geom')M-MM->^M
ALTER TABLE "regioni_new" ADD COLUMN "grande_Andy" TEXTM-MM->^M
SELECT AddGeometryColumn ('regioni_new','geom',6708,'POINT','XY')M-MM->^M
INSERT INTO "regioni_new" (pk_uid,"cod_reg","den_reg","geom")^M
SELECT NULL,"cod_reg","den_reg",ST_centroid (ST_Transform(geom,6708))^M
FROM "regioni"M-MM->^M
```

Se invece incollo in spatialite e poi metto io a mano i pungo e virgola, poi incollo in un nuovo file in notepad++ e salvo invece ho:

```
SELECT CreateClonedTable('MAIN', 'regioni', 'regioni_new', 1, '::ignore::geom');^M
ALTER TABLE "regioni_new" ADD COLUMN "grande_Andy" TEXT;^M
SELECT AddGeometryColumn ('regioni_new','geom',6708,'POINT','XY');^M
INSERT INTO "regioni_new" (pk_uid,"cod_reg","den_reg","geom")^M
SELECT NULL,"cod_reg","den_reg",ST_centroid (ST_Transform(geom,6708))^M
FROM "regioni";^M
```

Quindi è vero, c'è una differenza. A me visto così sembra diciamo un baco di spatialitegui, che non è capace di interpretare bene il carattere. Lo dico perché non capita con altri programmi.
Ma c'è da approfondire

**Comment by aborruso** [comment]
Dopo che incolli in notepad++ dovresti avere il default utf-8

![image](https://user-images.githubusercontent.com/30607/57305355-39bab280-70e1-11e9-8dfa-6de1bbede4a8.png)

Salva il file e poi converti l'encoding in ANSI

![image](https://user-images.githubusercontent.com/30607/57305409-548d2700-70e1-11e9-9366-60fca45318d4.png)

Salva e poi dovresti poter usare quel codice sia copia incollado su spatialitegui, sia lanciandolo come script.

Fammi sapere

**Comment by pigreco** [comment]
> Fammi sapere

Funziona!!!

![image](https://user-images.githubusercontent.com/7631137/57306129-910d5280-70e2-11e9-9c1b-7809e15df43d.png)

quindi occorre fare questo giro tortuoso!

grazie

**Comment by pigreco** [comment]
ecco una mia vecchia discussione sull'argomento in lista GFOSS

http://gfoss-geographic-free-and-open-source-software-italian-mailing.3056002.n2.nabble.com/SPLIT-LINES-WITH-POINTS-THE-SPATIALITE-WAY-aiuto-per-script-SQL-td7597916.html
