### ISSUE TITLE
File csv - come ottenere la somma di due colonne

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#67]
Dalla ML di Spagetti Open Data https://groups.google.com/forum/#!topic/spaghettiopendata/87nI_CoU_ME

Per duplicare l'esperienza di [Brussels](http://brussels-diversity.jetpack.ai/), distribuzione della popolazione straniera residente per quartiere, con i dati di Milano, ho scaricato i dati dal portale del comune, [cittadini residenti](http://dati.comune.milano.it/dataset/ds27-popolazione-residenti-cittadinanza-quartiere-serie-storica) ed ho estratto solo i residenti del 2018 [ds27_pop_sto_quartiere_2018.zip](https://github.com/opendatasicilia/tansignari/files/3167330/ds27_pop_sto_quartiere_2018.zip).
Per distribuire i residenti nei vari quartieri, occore il totale per ogni singola etnia, o meglio il totale per genere (maschi e femmine) per ogni quartiere.

Visto che il file csv contine 131612 righe c'è un modo veloce per ottenere i totali per etnia/nazionalità e  per genere (maschi e femmine) per ogni quartiere.

**Comment by aborruso** [comment]
@gbvitrano aggiungi 4 righe di esempio di output che vorresti?

**Comment by gbvitrano** [comment]
output pricipale dovrebbe essere più o meno cosi
Quartiere, Genere, Cittadinanza, Tot. Residenti

![2019-05-10_19h12_46](https://user-images.githubusercontent.com/20488693/57544488-c373b580-7357-11e9-8c0d-22ddf805dded.jpg)

![2019-05-10_19h12_57](https://user-images.githubusercontent.com/20488693/57544489-c4a4e280-7357-11e9-8082-548b754952af.jpg)

da questo poi si dovrebbe ricavare un db come quello Brussels, accorpando le varie nazionalità, per realizzare la mappa

**Comment by aborruso** [comment]
Quindi va bene così?

![image](https://user-images.githubusercontent.com/30607/57545208-ee5f0900-7359-11e9-9998-c545fdc2af24.png)

**Comment by gbvitrano** [comment]
@aborruso credo di avaer capito come fare grazie al tuo esempio https://asciinema.org/a/245472 utilizzando le tabelle pivot. grazie grazie :-)
