### ISSUE TITLE
come far apparire il menù a tendina su Read the Docs per selezionare le diverse versioni di progetto presenti su GitHub

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#68]
salve
posto che su un progetto GitHub ho due o più versioni di contenuti da rappresentare su Read the Docs, mi domando come fare in modo da visualizzare un menù a tendina sul progetto renderizzato in HTML su Read the Docs.

In pratica vorrei far visualizzare quello che il Team Trasformazione Digitale fa visualizzare nel caso del CAD (foto sotto).
![image](https://user-images.githubusercontent.com/3757525/58126995-a28f4800-7c14-11e9-8e29-e4515b56e55a.png)

Su GitHub mi creo i **branch** e fino a qui credo di esserci.
Sul pannello di controllo di Read the Docs (readthedocs.io) mi appare **branch-1** (di prova) che mi sono creato su GitHub. Ma non riesco a capire come far visualizzare sul progetto renderizzato in HTML di RTD la selezione - ad esempio - tra `master` e `branch-1` che ho creato per prova.

Qui: https://github.com/cirospat/rtd-schematipo/tree/master
il progetto prova su GitHub dove c'è `master` e `branch-1`

Qui: https://schema-tipo.readthedocs.io/it/latest/
il progetto prova renderizzato su RTD che ha come sorgente `master`

Qui: https://schema-tipo.readthedocs.io/it/branch-1/index.html
il progetto prova renderizzato su RTD che ha come sorgente `branch-1`

Dovrei poter selezionare le due versioni dall'homepage del progetto renderizzato in HTML su Read the Docs. Ma non capisco come fare. Non capisco se è un istruzione da dare nel file `layout.html` di GitHub, oppure sul file `themeoverride.css`, oppure sul file `conf.py`.

In sostanza mi sto addentrando nella visualizzazione su Read the Docs delle versioni del progetto presenti su GitHub.

Please help. Spero di essermi spiegato in maniera chiara. Diversamente sono pronto a fornire ulteriori chiarimenti di esposizione del mio problema.
Thanks per l'attenzione.
Ciro

**Comment by cirospat** [comment]
in effetti noto che il Team Trasformazione Digitale nel progetto GitHub del CAD ha solo un `branch` ma tanti `tag` . 
Ogni tag corrisponde a una versione di CAD.
Non ho capito come si crea il `tag` su GitHub online.
Ho capito come si creano i `branch` su GitHub online.

**Comment by gbvitrano** [comment]
link del Team Trasformazione Digitale...?

**Comment by aborruso** [comment]
Caro @cirospat con i temi standard la cosa appare in automatico.

È basata su branch e primariamente su tag https://docs.readthedocs.io/en/stable/versions.html

I tag si creano sicuramente da riga di comando. Magari si fa pure da interfaccia, ma non l'ho mai fatto

**Comment by cirospat** [comment]
Gianni ecco il link
https://docs.italia.it/italia/piano-triennale-ict/codice-amministrazione-digitale-docs/it/v2017-12-13/

Dove puoi visionare il menù a tendina.

Il mer 22 mag 2019, 09:32 Andrea Borruso <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
Il modello RTD di base, lo prevede by default in basso a sinistra. Vedere ad esempio il mitico [csvkit](https://csvkit.readthedocs.io/en/latest/)

![image](https://user-images.githubusercontent.com/30607/58165725-a65cb200-7c88-11e9-9e15-a2e68abc5a9b.png)

**Comment by cirospat** [comment]
Grazie @aborruso
Studio i riferimenti che mi hai dato. 
Cmq il mio obiettivo è disporre di un menù a tendina in home page sull'esempio del Team. 
Grazie.

**Comment by aborruso** [comment]
Caro Ciro,

On Wed, 22 May 2019 at 12:03, ciro spataro <notifications@github.com> wrote:

> Grazie @aborruso <https://github.com/aborruso>
> Studio i riferimenti che mi hai dato.
> Cmq il mio obiettivo è disporre di un menù a tendina in home page
> sull'esempio del Team.
>

giuro che l'avevo capito. Ma non mi sono spiegato.

Volevo sottolineare come usando i tag e un tema classico di RTD, hai un
menu a tendina con le versioni.
Di default è in basso a sinistra e contiene le versioni e altre info.

Baci

-- 
___________________

Andrea Borruso
website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by cirospat** [comment]
Scusa @aborruso
Sono io che non avevo capito. Poi con lo screenshot che hai inviato ho
capito.

Il mio cappuccio era vedere il menù a tendina nella stessa posizione (più o
meno) dove lo ha posizionato il Team sul CAD. Ma immagino sia complesso per
il file layout.html e cmq non è una cosa importante.
Mi basta quello che mi hai postato tu come esempio di visualizzazione del
versionamento.
Grazie molto.

Il mer 22 mag 2019, 12:06 Andrea Borruso <notifications@github.com> ha
scritto:

**Comment by pablopers** [comment]
Caro Ciro,
credo sia una componente del tema di docs italia [https://github.com/italia/docs-italia-theme](url) 
quindi o prendi tutto il pacchetto [https://testx-ciro.readthedocs.io/en/latest/](url) 
oppure tieni il menù come dal tema standard (come illustrava Andrea). 
Ho provato a copiare qualche pezzettino di codice come questo: 
`# The version info for the project you're documenting, acts as replacement for`
`# |version| and |release|, also used in various other places throughout the`
`# built documents.`
`#`
`# The short X.Y version.`
`version = settings_doc_version`
`# The full version, including alpha/beta/rc tags.`
`release = settings_doc_release`
ma fallisce la compilazione in RTD proprio perché non trova la definizione di "settings_doc_version"   [https://readthedocs.org/projects/testx-ciro/builds/9108123/](url) 
Se Comunque posso esserti di aiuto in qualche modo fammi sapere! 
"proud to be your friend"

**Comment by cirospat** [comment]
Grazie @pablopers
Per il tuo tempo che mi dedichi. 
Studio quanto mi hai scritto. E cerco di capire. 
Certo che se ho altre cose da domandarti per capire, lo faccio con piacere :)
Un abbraccio

**Comment by gbvitrano** [comment]
@cirospat  con il tema di base che usiamo noi puoi spostare il blocco della versione che si trova nel file versions.html nel file layout.html o dove più ti piace.
![immagine](https://user-images.githubusercontent.com/20488693/58233909-95ba4380-7d3d-11e9-8b6c-0d0b7c21c3cb.png)

In questo caso il  file layout.html deve essere configurato per ospitare un menù orizonate responsive. 
![immagine](https://user-images.githubusercontent.com/20488693/58234752-90f68f00-7d3f-11e9-926e-c641ede45f30.png)

**Comment by cirospat** [comment]
grazie @gbvitrano 
mi potresti inviare il link di ixmaps su read the docs così vedo l'effetto?
Grazie

**Comment by cirospat** [comment]
@gbvitrano 
secondo me ci vorrebbe un menù a tendina qui dove si trova `branch-1` nella foto di sotto
![image](https://user-images.githubusercontent.com/3757525/58247098-205c6c00-7d59-11e9-96f3-608716169b91.png)
in maniera tale che uno da lì può andare facilmente nelle varie versioni.
Che ne pensi? Si può inserire l'elemento menù a tendina che si lega alle versioni di documentazione su Github?

**Comment by gbvitrano** [comment]
> 
> 
> grazie @gbvitrano
> mi potresti inviare il link di ixmaps su read the docs così vedo l'effetto?
> Grazie

https://ixmapsdoc.readthedocs.io/it/latest/
il menù a tendina cmq va costruito usadano sempre i tag, bisogna....provare...provare provare :-)

**Comment by aborruso** [comment]
La chiudo, stiamo cambiando piattaforma
