### ISSUE TITLE
[GIS] Come trasferire info da un layer/file ad un altro

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#71]
Buona sera,
sto tentando di realizzare con QGIS un file con i quartieri di Palermo, utilizzando i dati delle zone censuarie dell'istat. 
Qui il dataset [territorio_palermo_test.zip](https://github.com/opendatasicilia/tansignari/files/3214252/territorio_palermo_test.zip) nel file gpkg ci sono due file, uno con le UPL ovvero Unità di primo livello e il file con le zone censuarie.
Al file UPL, ho aggiunto la colonna delle **Circoscrizioni** e la colonna dei **Quartieri**

Vorrei trasferire le info del file UPL al file delle zone censuarie, in modo da ottenere un unico file con le info delle **Sezione**, **UPL**, **Circoscrizione** e **Quartiere**.

Ho provato ad usare il comando **Unisci attributi per posizione** ma non tutte le info vengono trasferite.

Dove sbaglio...?

**Comment by pigreco** [comment]
Per trasferire le info di un layer ad un altro (layer sovrapposti) QGIS mette a disposizione un geo-algoritmo, `Unisci attributi per posizione` con alcuni predicati geometrici (Interseca, contiene, tocca ecc...),  presente negli strumenti di processing.

Nel caso specifico di sovrapposizione di poligoni e per evitare problemi sui confini in comune, si consiglia di creare un vettore intermedio come i centroidi dei poligoni (meglio i **punti sulla superficie** che ricadranno sicuramente all'interno dei poligoni).

STEP:

1. da processing cercare `Punto sulla superficie` e selezionare il layer **Sezioni Censuarie ISTAT 2011** ottenendo un layer (in memoria) dal nome **Punto**;
2. da processing cercare `Unisci attributi per posizione` segui screenshot di sotto (tra i vettori `Punto` e `UPL` e predicato geometrico **interseca**):

![image](https://user-images.githubusercontent.com/7631137/58310228-66233e00-7e06-11e9-8776-0dff536a85c6.png)

3. JOIN tra il layer **Sezioni Censuarie ISTAT 2011** e **Punto** usando il campo `fid` come campo unione;
4. salvare il layer per rendere permanente la JOIN.

**Comment by gbvitrano** [comment]
Grazie @pigreco
