### ISSUE TITLE
[GIS] Compositore di stampe QGIS, clippare una mappa dentro un poligono

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#74]
Buongiorno :-)
C'è il modo di poter clippare una mappa dentro un poligono?
sarebbe utile per fare una sorta di lente di ingrandimento di una determinata zona.
Grazie :-)
![Popolazione residente Palermo 2018](https://user-images.githubusercontent.com/20488693/58379612-154a4b80-7fa6-11e9-81c3-34574e8f56ef.png)

**Comment by pigreco** [comment]
Ciao @gbvitrano,
un modo semplice e veloce è quello di sovrapporre, alla parte zoomata, una forma (per esempio un ellisse) e di aumentare lo spessore della linea fino a coprire tutte le parti non desiderate; se l'ellisse lo disegnassi come un cerchio otterresti il seguente effetto:

![image](https://user-images.githubusercontent.com/7631137/58379720-cb626500-7fa7-11e9-8c48-e57958ffc7b8.png)

allego minitutorial con video demo:

[![video](https://img.youtube.com/vi/Vggvl7rTZYo/0.jpg)](https://youtu.be/Vggvl7rTZYo "Video DEMO QGIS")

spunto preso da qui: (Anita Graser <3)
https://anitagraser.com/2016/05/01/how-to-create-round-maps-in-print-composer/

**Comment by gbvitrano** [comment]
Grazie @pigreco ci provo subito :-)

**Comment by gbvitrano** [comment]
Fatto :-) grazie grazie
![Popolazione residente Palermo 2018 - SubRegioni](https://user-images.githubusercontent.com/20488693/58380692-82fd7400-7fb4-11e9-9757-bd8da3380c07.png)

**Comment by gbvitrano** [comment]
e con un barbatrucco al quadrato abbiamo anche il bordo :-) 
![03 - Popolazione residente Palermo 2018 - SubRegioni](https://user-images.githubusercontent.com/20488693/58380940-3c117d80-7fb8-11e9-92cd-5561a1e541b1.png)
