### ISSUE TITLE
[script] ciclo for su specifiche cartelle

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#75]
In una cartella `gr_funzioni` ho `n` sottocartelle (ma non tutte devono essere prese nel ciclo) e per ognuna di queste ho una cartella `funzioni` che contiene `m` file md (markdown); per ogni file `md` (tranne il file README.md) dovrei appendere il seguente testo:

```
---
## Esempio/i correlato/i

```

o meglio:

`\n\n---\n## Esempio/i correlato/i\n`

La cartella in esame è `gr_funzioni` si trovi qui: https://github.com/gbvitrano/HfcQGIS/tree/master/gr_funzioni
e le sottocartelle sono queste:
```
Aggregates/funzioni,
Array/funzioni,
Arrays/funzioni,
Colore/funzioni,
Condizioni/funzioni,
Conversioni/funzioni,
Corrispondenza fuzzy/funzioni,
Data e ora/funzioni,
Generale/funzioni,
Geometria/funzioni,
Layer della mappa/funzioni,
Maps/funzioni,
Matematica/funzioni,
Operatori/funzioni,
Rasters/funzioni,
Record e attributi/funzioni,
Relazioni/funzioni,
Stringhe di testo/funzioni
```
Ho creato questo script che acchiappa **tutte** le sottocartelle in `gr_funzioni` :

```bash
#!/bin/bash

set -x
# cerco tutti i file *.md all'interno della cartella e sottocartelle dove lancio lo script e li accodo nel file toto.csv
find -name *.md >> toto.csv
# elimino le righe che contengono README.md
sed -i "/.*README.md/d" toto.csv

# ciclo per appendere il testo tra doppi apici
for i in $(cat toto.csv); do
   echo -e "\n\n---\n## Esempio/i correlato/i\n" >> "$i"
done
```

come realizzare il ciclo solo per le cartelle elencate sopra??

**Comment by aborruso** [comment]
Ciao totò,
ecco un modo

```bash
#!/bin/bash

set -x

# file con la lista delle cartelle su cui lavorare
input="./listaCartelle.txt"

# per ogni nome di cartella
while IFS= read -r line
do
# entra nella sottocartella funzioni
  cd "./$line/funzioni"
# a tutti file markdown per nome non iniziano per README, aggiungi una stringa
  fd -e md '^[^README]' -x  bash -c "echo -e '\n\n---\n## Esempio/i correlato/i\n' >>{}"
# ritorna alla cartella radice
  cd ../../
done < "$input"
```

Faccio uso della mitica [fd](https://github.com/sharkdp/fd), che si può installare [così](url).

Lo script è da inserire dentro `gr_funzioni`.

**Comment by pigreco** [comment]
Grazie @aborruso,
ottima soluzione.
👍
