### ISSUE TITLE
[GIS] Sommare i dati di una colonna in base all'attributo (Somma se)

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#76]
Buongiorno :-)
Vorrei provare a eleaborare una mappa a densità di punti con i dati delle elezioni europe del 2019 di Palermo, ma potrebbe tornare utilile anche per altre elezioni.

Con QGIS partendo dalla localizzazione delle sezioni di voto (seggi elettorali)  e dalle UPL (unità di primo livello), ho aggiunto le info delle UPL, usando il comando **Unisci attributi per posizione** ottenedo questo nuovo file [seggi_elettorali_con_info_territorio.zip](https://github.com/opendatasicilia/tansignari/files/3224520/seggi_elettorali_con_info_territorio.zip)

Al nuovo file dei seggi elettorali ottenuto  ho fatto una join con i dati sulle elezioni europee del 2019, esempio [affluenze_23.zip](https://github.com/opendatasicilia/tansignari/files/3224436/affluenze_23.zip) ho ottenuto una nuova tabella.

La join va fatta con il campo **sezione** del file seggi eletorali e con il campo **_NUMERO** del file affluenze_23

![2019-05-27_14h31_34](https://user-images.githubusercontent.com/20488693/58430888-9ccdb280-80ab-11e9-8b7a-ed94f5830b25.png)

**La domanda è:**
Come ottenere un nuovo file/tabella con la la somma delle colonne 1,2, 3 **affluenze_23_xxxx** in base all'attributo delle colonna A **Id_Quartiere**? una sorta di **somma se** dei fogli di calcolo.

La tabella in uscita in questo caso dovrebbe passare da 600 a 25 righe, una per ogni quartiere o 55 se la somma viene fatta usando le UPL

**Comment by pigreco** [comment]
@gbvitrano 
una delle soluzione cha amo usare in questi casi è quella tramite i **Virtual Layer** usando la seguente query:

```sql
SELECT Id_Quartiere, SUM (_TOTVOT) AS totvot, SUM (_TOTVOTF) AS totvotF,SUM (_TOTVOTM) AS totvotM
FROM affluenze_23 a JOIN seggi_elettorali_con_info_territorio s ON (a._NUMERO=s.sezione)
GROUP BY 1;
```
non occorre fare una JOIN tra le tabelle in quanto lo faccio direttamente nella query.

Il risultato è questa tabella:

Id_Quartiere|totvot|totvotF|totvotM
-----|----|----|----
1|3323|1585|1738
2|2837|1328|1509
3|11910|5737|6173
4|7028|3395|3633
5|9159|4588|4571
6|12088|5931|6157
7|7442|3755|3687
8|8444|4476|3968
9|19212|10116|9096
10|10696|5503|5193
11|14155|6791|7364
12|4392|2077|2315
13|11668|5543|6125
14|11563|5716|5847
15|4411|2150|2261
16|2530|1203|1327
17|11240|5654|5586
18|5672|2721|2951
19|10513|5069|5444
20|17914|9290|8624
21|7384|3578|3806
22|6563|3223|3340
23|7413|3603|3810
24|9010|4498|4512
25|2921|1371|1550

**Comment by gbvitrano** [comment]
Grazie @pigreco era esattamente quelle che avevo in mente, ma non sapevo come fare :-)
adesso provo a farlo :-)
grazie grazie
