### ISSUE TITLE
[visidata] come ordinare un campo che contiene versioni di software

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#77]
Ho questo [0] file CSV con vari campi (`nro,data,nome,versione,categoria,descrizione`).
Come ordinare il campo `versione` in senso crescente (QGIS_2.0.0, QGIS_2.2.0, QGIS_2.4.0 ecc..) usando [Visidata ](http://visidata.org/man/)(con la combinazioni di tasti `AltGr + ]` ottengo la tabella di sotto**)??

versione|count|percent|histogram
--------|-----|-------|-----
QGIS_2.0.0|55|6.15|*****************
QGIS_2.10.0|30|3.35|*********
QGIS_2.12.0|47|5.25|***************
QGIS_2.14.0|66|7.37|*********************
QGIS_2.16.0|93|10.39|******************************
QGIS_2.18.0|23|2.57|*******
QGIS_2.2.0|31|3.46|**********
QGIS_2.4.0|19|2.12|******
QGIS_2.6.0|39|4.36|************
QGIS_2.8.0|34|3.80|***********
QGIS_3.0.0|154|17.21|**************************************************
QGIS_3.2.0|73|8.16|***********************
QGIS_3.4-LTR|77|8.60|*************************
QGIS_3.6.0|96|10.73|*******************************
QGIS_3.8.0|58|6.48|******************

**la tabella è il risultato ottenuto usando `shift+f` sulla tabella [0] con visidata (sul campo versione)

**EDIT**: corretto un errore nel CSV
[0] 
[changelog_qgis_200to380_data.zip](https://github.com/opendatasicilia/tansignari/files/3334617/changelog_qgis_200to380_data.zip)

**Comment by aborruso** [comment]
Caro totò,
uno dei modi è fare una sorta di zero padding, applicando le regex. E questo lo fai in visidata e in tutti gli altri luoghi che supportano regex.

In visidata:

- vai nella colonna versione;
- fai SHIFT + f;
- con la prima colonna attiva lancia trova e sostituisci  con `gz*`
- come formula in basso scrivi `^(.+)\.([0-9])\.(.*)$/\1.0\2.\3`

Otterrai delle versioni ordinabili in modo crescente. Rimane fuori il caso della LTR, ma basta cambiare regex o fare due trova e sostituisci.

Fammi sapere

**Comment by pigreco** [comment]
@aborruso grazie per la rapida risposta.
seguendo il tuo suggerimento:

versione|count|percent|histogram
--------|-----|-------|-----
QGIS_2.00.0|55|6.15|*****************
QGIS_2.02.0|31|3.46|**********
QGIS_2.04.0|19|2.12|******
QGIS_2.06.0|39|4.36|************
QGIS_2.08.0|34|3.80|***********
QGIS_2.10.0|30|3.35|*********
QGIS_2.12.0|47|5.25|***************
QGIS_2.14.0|66|7.37|*********************
QGIS_2.16.0|93|10.39|******************************
QGIS_2.18.0|23|2.57|*******
QGIS_3.00.0|154|17.21|**************************************************
QGIS_3.02.0|73|8.16|***********************
QGIS_3.06.0|96|10.73|*******************************
QGIS_3.08.0|58|6.48|******************
QGIS_3.4-LTR|77|8.60|*************************

cosi facendo ottengo un numero di versione che non ha senso (QGIS_2.02.0 in realtà è QGIS_2.2.0) non si potrebbe usare un altro campo per ordinare (per esempio la data) ma visualizzando lo schema di sopra??

**Comment by aborruso** [comment]
Totò ora sono lontano dal PC.

Puoi fare una copia della colonna, così lasci l'etichetta come ti piace, e
agisci sulla copia.

Se c'è una data (poi ci guardo), si potrà ordinare anche per data.

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il gio 27 giu 2019, 14:10 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
rieccomi @pigreco, c'è la data:

- impostala come campo data con `@`
- poi metti come campi primari, data e versione
- poi raggruppa globalmente con `g+SHIFT+f`
- poi ordina per data

![image](https://user-images.githubusercontent.com/30607/60266646-b8192100-98e8-11e9-80e7-6d1d82744961.png)

**Comment by pigreco** [comment]
caro @aborruso oggi ho imparato cose belle, grazie

nel file originale le date sono scritte nel formato `dd/mm/YYYY` un formato che i software non digeriscono bene, per ovviare ho fatto:

- nella colonna data: gz*
- usata questa formula `^([0-9]+)\/([0-9]+)\/([0-9]+)$/\3-\2-\1`
- la formula riordina il formato in `YYYY-mm-dd`
- poi, `@` per dirgli che la colonna data è un formato data;
- poi `SHIFT+ !` sui campi primari, data e versione;
- poi raggruppo globalmente con `g+SHIFT+f`
- poi ordino per data.
- FATTO!!!

RISULTATO:
![image](https://user-images.githubusercontent.com/7631137/60269443-c36f4b00-98ee-11e9-9888-3aee6a11a614.png)
