### ISSUE TITLE
[scraping] come scaricare un insieme di file.zip dagli archivi ISTAT

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#78]
Oggi ho visto questo tweet [0] di **Maurizio Napolitano** e mi chiedevo come scaricare facilmente tutto l'archivio di file zippati [1] e poi [2].

![image](https://user-images.githubusercontent.com/7631137/60348083-24feea80-99bf-11e9-89b9-f44bd17412a1.png)

[0] https://twitter.com/napo/status/1144583972422373377
[1] https://www.istat.it/it/archivio/231601
[2] https://www.istat.it/it/archivio/222527

**Comment by aborruso** [comment]
Caro @pigreco ,
in bash potresti fare così:

```bash
# scarica la pagina
curl "https://www.istat.it/it/archivio/231601" | \
# estrai tramite CSS selector i tag <a> che stanno dentro un oggetto con classe "bordo_unico"
scrape -be '.bordo_unico a' | \
# trasforma l'output in JSON, estrai l'href dei tag a, anteponi la stringa per trasformarlo nell'URL di download
xq  -r '"https://www.istat.it/"+.html.body.a[]."@href"' | \
# passa l'output a xargs e usalo per lanciare un download per ogni riga di output
xargs -I _ wget _
```

I requisiti sono:
- scrape https://github.com/aborruso/scrape-cli
- yq https://github.com/kislyuk/yq

Per capire come funziona lo puoi eseguire a blocchi.

Puoi iniziare con `curl "https://www.istat.it/it/archivio/231601" | scrape -be '.bordo_unico a'` e vedere che tira fuori. E poi aggiungere gli altri pezzi.

Per costruire queste cose, devi ispezionare il codice e capire come sono distinguibili da tutto il resto (in termini di HTML/CSS) gli elementi che cerchi.

Sui CSS Selector, basta cercare. Un esempio è https://www.w3schools.com/cssref/css_selectors.asp

**Comment by pigreco** [comment]
Grazie @aborruso 

ho messo tutto assieme in un unico script che unzippa alla fine del download:

## https://www.istat.it/it/archivio/231601 - storiche

```
#!/bin/bash

set -x

# scarico tutto in *.zip
curl "https://www.istat.it/it/archivio/231601" | scrape -be '.bordo_unico a' | xq  -r '"https://www.istat.it/"+.html.body.a[]."@href"' | xargs -I _ wget _
# unzippo tutto nella cartella estratti
7za x "*.zip" -o"estratti"
```

## https://www.istat.it/it/archivio/222527 - recenti

```
#!/bin/bash

set -x

# scarico tutto in *.zip
curl "https://www.istat.it/it/archivio/222527" | scrape -be '.bordo_unico a' | xq  -r '.html.body.a[]."@href"' | xargs -I _ wget _
# unzippo tutto nella cartella estratti2
7za x "*.zip" -o"estratti2"
```

PS: occorre installare **p7zip**

`sudo apt-get install p7zip-full`

**Comment by gbvitrano** [comment]
Si possono scaricare solo i file che che sono contenuti sempre nella tabella **.bordo_unico** ma nelle celle color #F0F0F0? sono i file medo dettagliati
![2019-06-29_08h24_29](https://user-images.githubusercontent.com/20488693/60380517-46a3b480-9a47-11e9-9bc9-bf97efc34096.png)

**Comment by aborruso** [comment]
@gbvitrano una dei punti del galateo è un invito a provare a risolvere in modo autonomo.

Hai fatto qualche test? Quale? Che risultato ottieni?

Con scrape (che è molto comodo per queste cose) puoi fare query usando "CSS Selector" o "XPATH. Che hai provato?

Fammi sapere

**Comment by gbvitrano** [comment]
ho provato **curl "https://www.istat.it/it/archivio/222527" | scrape -be '.bordo_unico  .#F0F0F0 a' | xq  -r '.html.body.a[]."@href"' | xargs -I _ wget _**  ma non funziona 

![2019-06-29_09h04_09](https://user-images.githubusercontent.com/20488693/60380883-ca13d480-9a4c-11e9-964e-b05c547b8ac6.png)

**Comment by aborruso** [comment]
Caro @gbvitrano la tua query è sbagliata, perché cerchi una classe che si chiama `#F0F0F0`, che è un valore di una proprietà, non è una classe.

Se tu cerchi tutti i tag `a`, dentro le la cui proprietà `bgcolor` è uguale al valore `#F0F0F0`:

- come CSS Selector puoi usare `td[bgcolor="#F0F0F0"] a`
- come XPATH `//td[@bgcolor="#F0F0F0"]//a`

**Comment by gbvitrano** [comment]
** curl "https://www.istat.it/it/archivio/222527" | scrape -be 'td[bgcolor="#F0F0F0"] a' | xq  -r '.html.body.a[]."@href"' | xargs -I _ wget _** 
funziona :-)  garzie greazie

**Comment by gbvitrano** [comment]
Attibruto e valore 
**[attribute=value]**

![2019-06-29_09h47_36](https://user-images.githubusercontent.com/20488693/60381308-e0249380-9a52-11e9-8f8c-56559b1b49b8.png)

**Comment by aborruso** [comment]
@gbvitrano t'ansignari e ...

**Comment by pigreco** [comment]
@gbvitrano ti tocca fare ricetta.

**Comment by pigreco** [comment]
oppure, per scaricare solo quelli `generalizzati` basta applicare un filtro:

```
# scarica la pagina
curl "https://www.istat.it/it/archivio/222527" | \
# estrai tramite CSS selector i tag <a> che stanno dentro un oggetto con classe "bordo_unico"
scrape -be '.bordo_unico a' | \
# trasforma l'output in JSON, estrai l'href dei tag a, anteponi la stringa per trasformarlo nell'URL di download
xq  -r '.html.body.a[]."@href"' | \
# filtro su generalizzati
grep '/generalizzati' | 
# passa l'output a xargs e usalo per lanciare un download per ogni riga di output
xargs -I _ wget _

**Comment by aborruso** [comment]
Una ricetta, basata su questo caso, con i vari esempi, sarebbe bella cosa

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il sab 29 giu 2019, 17:41 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
ciao @aborruso 
> Una ricetta, basata su questo caso, con i vari esempi, sarebbe bella cosa

ok, tocca a me,
la scrivo volentieri.
