### ISSUE TITLE
[scraping] come scarica una sola tabella tra tante da un sito web

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#79]
In questo [sito](https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/) ci sono varie tabelle e per scaricarle tutte utilizzo questa ricetta:

```
curl -L "https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/" |  \
scrape -be '//table[contains(@class, 'ip')] |  \
vd -f html
```
ottenendo:
![image](https://user-images.githubusercontent.com/7631137/61583527-53dd2c00-ab39-11e9-908c-ead7052e7016.png)

ho provato a scaricare solo la prima utilizzando la seguente ricetta:

```
curl -L "https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/" |  \ 
scrape -be '//table[contains(@class, 'ip')]/tbody/tr/th[b = EUROPA]' |  \
vd -f html
```
ma non funziona e non ricevo nessun messaggio.
Cosa sbaglio??

![image](https://user-images.githubusercontent.com/7631137/61583561-22b12b80-ab3a-11e9-97d5-1b041ff452fd.png)

**Comment by gbvitrano** [comment]
![2019-07-21_09h44_30](https://user-images.githubusercontent.com/20488693/61588643-90437300-ab9f-11e9-9fb4-b02eff3cbba9.png)
Con google sheet la tabella viene caricata con questo codice

  `=IMPORTHTML("https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/","table",1)`

1 = Talella Europa
2 = Talella Africa

usando gli indici numerici di Xpath

adatta il codice che hai usato con usando gli indici numerici

**Comment by pigreco** [comment]
Grazie @gbvitrano per lo spunto, in effetti scrivendo

```
curl -L "https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/" |  \
scrape -be '//table[contains(@class, 'ip')][1]' | vd -f html
```
funziona, scarica solo la prima [1] tabella.

**Comment by aborruso** [comment]
Caro @pigreco ,
se ti interessa un elemento in particolare, devi vedere cosa lo rende diverso da tutti gli altri omologhi.

Uno è proprio l'ordine, quindi la prima tabella.

Un altro può essere legato a classi HTML o ID; ma queste tabelle non hanno ID associato e le classi mi sembrano le stesse.
Ma per esempio, se sei interessato a quella "Europa", è l'unica tra le tabelle che contiene in una cella la stringa "Romania".

Che in XPATH (per questo caso) è `//table[.//td[contains(., "Romania")]]`

**Comment by aborruso** [comment]
@pigreco se vuoi usare le righe di intestazione e selezionare la tabella che dentro il tag `<b>`, all'interno di una intestazione `<th>` contiene "EUROPA", in XPATH è

    //table[.//th/b[contains(., "EUROPA")]]

**Comment by aborruso** [comment]
@pigreco qualche nota sulla tua query

    //table[contains(@class, "ip")]/tbody/tr/th[b = EUROPA]

Questa contiene degli errori di sintassi, ma sopratutto non va bene come struttura, perché in qualche modo equivale a: estraimi la cella in cui dentro il tag b c'è scritto Europa, dentro una tabella con class uguale a "ip". Quindi la cella, e non la tabella.

Perché da sinistra verso destra in questo modo entri sempre più in profondità, e dalla tabella arrivi a una delle celle di intestazione.
Se la cella fosse stato il tuo obiettivo la sintassi (una delle tante) in ogni caso doveva essere 

    //table[contains(@class, "ip")]//tr/th/b[contains(., "EUROPA")]

`b` non è una proprietà del tag `th`, ma è un figlio di `th` e quindi devi usare `th/b`. 

In questa pagina ci sono esempi di base e didattici che mi piacciano, per comprendere la struttura https://www.w3schools.com/xml/xpath_syntax.asp

**Comment by pigreco** [comment]
@aborruso esatto, era quello che cercavo:

`//table[.//th/b[contains(., "EUROPA")]]`

funziona!!!

**Comment by gbvitrano** [comment]
in sintesi

**Scarica la prima tabella della pagina usando gli indici numerici di Xpath**

curl -L "https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/" | scrape -be '//table[contains(@class, 'ip')][1]' | vd -f html

**Scarica la tabella che contiene Romania in una cella**

`curl -L "https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/" | scrape -be '//table[.//td[contains(., "Romania")]]' | vd -f html`

**Scarica la tabella che contiene EUROPA nelle celle dell'intestazione**

`curl -L "https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/" | scrape -be '//table[.//th/b[contains(., "EUROPA")]]' | vd -f html`

**Scarica la tabella che contiene 56 righe**

`curl -L "https://www.tuttitalia.it/statistiche/cittadini-stranieri-2018/" | scrape -be '//table[count(tr)=56]' | vd -f html`

**Comment by pigreco** [comment]
Grazie a tutti per l'aiuto.

Appena posso scrivo ricetta.
