### ISSUE TITLE
Convertire data e ora in formato ISO datetime

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#80]
Buona sera... 
nel file allegato, sinistri a Palermo nel 2018 ci sono due colonne che riportano data e ora dell'incidente, con google sheet o altro applicazione si possono convertire le due colonne in un formato  ISO datetime come questo? **2018-01-28T11:39:13.000Z** 

[simistri_2018_00.zip](https://github.com/opendatasicilia/tansignari/files/3414994/simistri_2018_00.zip)
![immagine](https://user-images.githubusercontent.com/20488693/61596372-db42a200-ac02-11e9-8cdc-d328d74d63a3.png)

**Comment by aborruso** [comment]
Caro gb,
la cosa più semplice, se ti serve soltanto formattarla come stringa, è concatenare. Come qui https://docs.google.com/spreadsheets/d/15ABMvXQU9wGZ9tgU58I4sj_Ut-9t7wfvvN8bC9FZaqE/edit?usp=sharing

Come zona UTC l'ho lasciato come se fossimo tutti a Londra. Ci sarebbe da applicare il +1 e +2 di ora solare e legale.

Immagino che tu stia usando flourish: lì puoi adattare il formato a quello di input.

![image](https://user-images.githubusercontent.com/30607/61612165-03132380-ac5e-11e9-8ca2-ba51492bd058.png)


Ti basta questo?

**Comment by gbvitrano** [comment]
Si, grazie :-) è esattamente quello che mi serviva per la la mappa
