### ISSUE TITLE
È possibile scaricare i poligoni/linee/punti del layer X da un server arcgis - rest - services

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#81]
Buongiorno,
provo a scaricaricare le linee della Viabilità storica (Regie Trazzere) della provincia di Catania dal [server ArcGIS della Regione Sicila](http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer), utilizzando la Query 

![2019-07-24_08h23_30](https://user-images.githubusercontent.com/20488693/61770525-bfe7ba80-aded-11e9-9a4b-d78299ba69a5.png)
ma ottengo un errore 

![2019-07-24_08h23_43](https://user-images.githubusercontent.com/20488693/61770613-fa515780-aded-11e9-80e7-5a347ca35ab1.png)

La stessa query ha funzionato con le linee della [Provincia di Siracusa](http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/SR_Componenti_Paesaggio_2018/MapServer), dove sbaglio?

**Comment by aborruso** [comment]
Caro @gbvitrano ,
se guardi i Field di output del layer, non ci sono campi geometrici.

Si vedono nativamente senza fare sforzi, quando tra i campi ce ne è uno geometrico (come sotto).

![image](https://user-images.githubusercontent.com/30607/61773281-9d0cd480-adf4-11e9-9e56-a178059e223b.png)

Appena posso scrivo una modalità per superare (ove applicabile) l'ostacolo

**Comment by gbvitrano** [comment]
Quindi non ci sono le geometrie ma solo le tabelle. Ok Grazie

**Comment by aborruso** [comment]
Non sono esposte in modo diretto/nativo, ma ci sono dei modi per estrarle. Non appena posso, lo scrivo qui

**Comment by aborruso** [comment]
Caro gb,
il punto di partenza è partire dalla query "globale", che sfrutta una condizione sempre vera: tutti i record per cui e che restituisce in output tutti i campi:

<http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=1%3D1&returnGeometry=true&outSR=&outFields=*&f=html>

I pezzi importanti sono:

- `outFields=*`
- `where=1%3D1` (che è "where=1=1" con l'encoding applicato)

![image](https://user-images.githubusercontent.com/30607/61813339-bee27780-ae45-11e9-8826-4aca28af0038.png)

Tutti i servizi di API hanno di solito un limite di risultati e sono "paginati". Qui il limite è 500, e non vedo in output un ID con cui fare query di 500 in 500, ma puoi fare query per area e vedere se ne hai meno di 500: http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=443751.434391746%2C4100846.1495017%2C483565.298820498%2C4150846.54449411&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=&returnGeometry=true&outSR=&outFields=*&f=html

Di alcune di queste cose, ho scritto nel 2014 https://medium.com/tantotanto/take-the-best-use-the-rest-804915c08d94

La documentazione di questa versione del server invece è qui: http://map.sitr.regione.sicilia.it/ArcGIS/SDK/REST/index.html?catalog.html

Io di solito (per casi come questi) scarico sia JSON (per i dati), che KMZ. Ed è comodo con uno script.

**Comment by aborruso** [comment]
Aggiungo nota interessante: anche qui c'è il campo nascosto objectid e quindi si può ciclare di 500 in 500 sinché si hanno risultati.

Ecco una query con filtro su id http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid%3E10+AND+objectid%3C100&returnGeometry=true&outSR=&outFields=*&f=html

**Comment by pigreco** [comment]
Caro @aborruso,
come ringraziarti per queste perle?

Grazie per tutto ciò che fai, non solo per T'ansignari, e condividi con tutti. 👍

**Comment by gbvitrano** [comment]
@aborruso Grazie per tutte le info :-)
dalla tabella scaricata dal vecchio [server della Regione](http://map.sitr.regione.sicilia.it/gis/rest/services/Beni_Culturali/CT_componenti_paesaggio/MapServer/9)  mi sono accorto che nel layer ci sono 894 oggetti

![immagine](https://user-images.githubusercontent.com/20488693/61856638-d27ff380-aec2-11e9-8568-efdb151547c1.png)

per scaricarli ho usato la query con filtro su id, una volta con  **Where: objectid>0 AND objectid<500**
ed una seconda volta con **Where: objectid>500 AND objectid<1000**

![2019-07-25_10h02_29](https://user-images.githubusercontent.com/20488693/61856829-39051180-aec3-11e9-802b-4b3b0edd61ca.png)

ed eccoli tutti :-)

![2019-07-25_09h38_23](https://user-images.githubusercontent.com/20488693/61856943-74074500-aec3-11e9-8818-12390f36cfb0.png)

Grazie Grazie :-)

**Comment by aborruso** [comment]
> per scaricarli ho usato la query con filtro su id, una volta con Where: objectid>0 AND objectid<500
ed una seconda volta con Where: objectid>500 AND objectid<1000

Ma così non hai perso `objectid=500`?

**Comment by pigreco** [comment]
Caro @aborruso 

> Io di solito (per casi come questi) scarico sia JSON (per i dati), che KMZ. Ed è comodo con uno script.

visto che hai già pronto lo script, puoi condividerlo??

**Comment by aborruso** [comment]
caro @pigreco ,
ne ho uno vecchio, con cui scaricavo gli ulivi dalla Regione Puglia.

Quel server ha un limiti di 1000 in 1000, con un numero di record totale <301000.
In quel caso però l'output era geografico e andavo in append su uno shapefile.

Si può prendere come ispirazione.

```bash
DA=0
A=1001
while [  $DA -lt 301000 ]; do
	ogr2ogr -append pietro2.shp "http://webapps.sit.puglia.it/arcgis/rest/services/Operationals/UliviMonumentali/MapServer/0/query?where=objectid>%3D$DA+AND+objectid<%3D$A&outfields=*&f=pjson" OGRGeoJSON
	let DA=DA+1000
	let A=A+1000
done
```

**Comment by pigreco** [comment]
@aborruso ma lo script funziona o occorre installare o preparare qualcosa prima??

![image](https://user-images.githubusercontent.com/7631137/61874411-9fe8f180-aee8-11e9-8eb3-13442bbbd3c3.png)

**Comment by aborruso** [comment]
Totò non so se sia cambiata qualcosa nella sorgente. Ai tempi funzionava.

L'ho incollato come esempio, da cui prendere spunto e adattare se serve al
caso

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il gio 25 lug 2019, 14:29 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
Chiudo, è passato troppo tempo
