### ISSUE TITLE
Come fare diventare ";" separatore di campi al posto di "," in un file scaricato come formato CSV da Google Spreadsheet

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#82]
Come fare diventare il ";" separatore di campi al posto della "," in un file scaricato in formato CSV.

Mi serve sapere il metodo perchè il portale open data del comune di Palermo accetta solo file CSV con separatore di campi con `;` e non `,`.

Grazie

**Comment by aborruso** [comment]
Non c'è un modo nativo: il CSV di output da sheet è sempre con `,` come separatore.

Se usi libreoffice:

- salva in formato ODS da google sheet;
- apri il file ODS con libreoffice;
- fai salva con nome in CSV e scegli il `;` come separatore.

**Comment by cirospat** [comment]
grazie delle delucidazioni, mi serviranno per aggiornare un tutorial per il caricamento dataset sul portale open data.

**Comment by gbvitrano** [comment]
@cirospat per modificare il separatore in LibreOffice
![immagine](https://user-images.githubusercontent.com/20488693/61892682-9d988e80-af0c-11e9-9cda-f8b946199bda.png)

Appena clicchi su salva si aprirà la tendina che ti permette di cambiare alcuni parametri
![2019-07-25_18h44_59](https://user-images.githubusercontent.com/20488693/61892710-abe6aa80-af0c-11e9-8746-26277d204e72.png)

**Comment by cirospat** [comment]
grazie @gbvitrano 

abbiamo un problema con un file CSV i cui separatori di campi sono `;` che una volta caricato sul portale open data del comune di Palermo, genera un conflitto con l'endpoint dcat_ap_it https://opendata.comune.palermo.it/dcat/dcat.php (che come vedi da errore).

Il dataset in formato CSV incriminato è questo: https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1248
C'è qualcosa che non va in questo CSV, che litiga con l'endpoint dcat_ap_it https://opendata.comune.palermo.it/dcat/dcat.php
Il separatore di campi  `;` non è un problema, ma qualcos'altro non va.

Dobbiamo scoprire cosa è, piano piano.

**Comment by aborruso** [comment]
@cirospat questa la chiuderei. 

Ti tocca scrivere una miniguida su come impostare il separatore di un CSV con libreoffice.

Basta un'immagine come questa e qualche parola di commento

![image](https://user-images.githubusercontent.com/30607/62115840-6550d180-b2b9-11e9-8df5-cc8e67849972.png)

**Comment by aborruso** [comment]
@cirospat se puoi ricetta, altrimenti chiudi :(

**Comment by cirospat** [comment]
@gbvitrano o @aborruso please gentilmente puoi creare una cartella dentro ricette che possa ricondurre ad argomenti concernenti il  **formato CSV**?
Io da web non posso creare cartelle su Github.
Thanks

**Comment by gbvitrano** [comment]
[Cartella](https://github.com/opendatasicilia/tansignari/tree/master/ricette/csv) creata... ci scusiamo per il ritardo :-)
All'interno ho inserito un index.rst di sezione già collegato all'index generale.
Per indicizzare la/le ricette a tema **csv** basta semplicemente inerire sotto il **toctree** di sezione il nome del file della ricetta.

Esempio 

![2019-10-01_12h32_21](https://user-images.githubusercontent.com/20488693/65955141-c32fa000-e447-11e9-8aba-6bd1b613b2fb.png)

**Comment by cirospat** [comment]
_> Cartella creata... ci scusiamo per il ritardo :-)
> All'interno ho inserito un index.rst di sezione già collegato all'index generale.
> Per indicizzare la/le ricette a tema csv basta semplicemente inerire sotto il toctree di sezione il nome del file della ricetta._
Quello che scrivi Gianni è come passare da un dataset su google spreadsheet con **`;`** come separatore alla **`,`** cioè il contrario. 

L'issue iniziale era:
_Come fare diventare il **`;`** separatore di campi al posto della **`,`** in un file scaricato da google spreadsheet sul pc in formato CSV._
Cioè io ho un dataset in un google spreadsheet. Lo scarico come CSV e google me lo fa scaricare con la **`,`** come separatore di campi.
Io per pubblicare il CSV nel portale open data del comune ho necessità di avere il **`;`** come separatore di campi. Quindi devo capire come passare dalla **,** al **;** come separatore di campi.
Se lo posso fare direttamente da google spreadsheet.

La risposta all'issue iniziale se non sbaglio è quella di Andrea:
**Non c'è un modo nativo: il CSV di output da sheet è sempre con , come separatore.
Se usi libreoffice:
salva in formato ODS da google sheet;
apri il file ODS con libreoffice;
fai salva con nome in CSV e scegli il ; come separatore.**

**Comment by gbvitrano** [comment]
@cirospat il prodedimenti è sempre lo stesso, passarre da separatore **A** al separatore **B** o **C** è sempre lo stesso non cambia nulla.

**Comment by gbvitrano** [comment]
@cirospat se vuoi fare tutto googlesheets [qui c'è uno script](https://stackoverflow.com/questions/49248498/how-can-i-export-to-csv-with-pipe-delimiter) che puoi usare, ho verificato è funzione. 
Occhio che nello sheer **Parameters** dei sosstituire il pipe **|** con il semicolon **;**

![2019-10-05_13h43_37](https://user-images.githubusercontent.com/20488693/66254494-1de23800-e777-11e9-85a5-dedd33ae9684.png)

dopo il salvataggio di dirà dove il file viene salvato 

![2019-10-05_13h43_22](https://user-images.githubusercontent.com/20488693/66254499-33eff880-e777-11e9-864a-799cf9aa3f44.png)

**Comment by gbvitrano** [comment]
Secondo me la soluzione più semplice e alla portata di tutti resta la riscrittura con libreoffice :-)

**Comment by aborruso** [comment]
@cirospat promemoria per la ricetta, grazie

**Comment by aborruso** [comment]
chiudo è passato troppo tempo
