### ISSUE TITLE
[bash] uno script che fa i capricci

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#83]
È una semplice esercitazione per me, niente di urgente.

**URL:** http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9

**Query:** 
http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D0+AND+objectid+%3C%3D50&returnGeometry=true&outSR=&outFields=*&f=html

dalla query di sopra, appena copio ed incollo su Notepad++, scompaiono i segni `>` e `<` , perché??

`where=objectid+%3E%3D0+AND+objectid+%3C%3D50`

questo lo screen dell'URL originale
![image](https://user-images.githubusercontent.com/7631137/61968034-49a6ac00-afd7-11e9-9327-823c95ce48ff.png)

superato questo primo scoglio (aggiungo manualmente i segni `>` e `<`), creo questo script:

```bash
DA=0
A=50
while [  $DA -lt 1000 ]; do
ogr2ogr toto.shp "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+>%3E%3D$A+AND+objectid+<%3C%3D$DA&returnGeometry=true&outSR=&outFields=*&f=KMZ"
	let DA=DA+50
	let A=A+50
done;
```

lancio lo script: (./script.sh) e ottengo:

```
ERROR 1: JSON parsing error: unexpected character (at offset 0)
ERROR 1: JSON parsing error: unexpected character (at offset 0)
ERROR 1: Terminating translation prematurely after failed
translation of layer GeoJSONSeq (use -skipfailures to skip errors)
ERROR 1: JSON parsing error: unexpected character (at offset 0)
ERROR 1: JSON parsing error: unexpected character (at offset 0)
ERROR 1: Terminating translation prematurely after failed
translation of layer GeoJSONSeq (use -skipfailures to skip errors)
```

allora provo, per verifica lo script che segue (sarebbe il primo della serie):

```bash
curl -L "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D0+AND+objectid+%3C%3D50&returnGeometry=true&outSR=&outFields=*&f=KMZ" >output.kmz
```
FUNZIONA!!!

cosa sbaglio.

Grazie e buona serata.

**Comment by aborruso** [comment]
Caro Totò,
alcuni caratteri non sono validi negli URL e quindi deve esserne fatto l'encoding.

La tua query senza encoding sarebbe questa (ne metto una parte):

```
where=objectid >=0 AND objectid <=50&returnGeometry=true&outSR=&outFields=*&f=html
```

Ma un browser non la capirebbe e deve essere trasformata in 

```
where=objectid+%3E%3D0+AND+objectid+%3C%3D50&returnGeometry=true&outSR=&outFields=*&f=html
```

Ma chrome nella schermata ti fa vedere `objectid+>%3D0` e non quello che ho scritto qui sopra `objectid+%3E`. 

Se apri chrome sulla pagina della query, e poi lanci <kbd>F12</kbd> ti si aprono gli strumenti di sviluppo. Se apri il tab 1) network e poi lanci la query, vedrai qual è la 2) stringa vera che usa chrome.

![image](https://user-images.githubusercontent.com/30607/61969905-ebc89300-afdb-11e9-9e35-d2e4461a4c31.png)

Se fai tasto destro sul link e copi l'URL

![image](https://user-images.githubusercontent.com/30607/61970094-5a0d5580-afdc-11e9-87d3-4a2a9ab07db6.png)

Poi puoi lanciare tranquillamente ad esempio

    curl "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=%2B%3E%253D0&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D0+AND+objectid+%3C%3D50&returnGeometry=true&outSR=&outFields=*&f=html"

Quindi diciamo che di base chrome tratta diversamente ciò che l'occhio vede, dalla stringa che viene lanciata. E questo può portare confusione

**Comment by pigreco** [comment]
Non riesco,
ho usato il tuo ultimo url in questo scrip e non va:

```
DA=0
A=50
while [  $DA -lt 1000 ]; do
ogr2ogr -append toto.shp "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=%2B%3E%253D0&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D$DA+AND+objectid+%3C%3D$A&returnGeometry=true&outSR=&outFields=*&f=KMZ"
	let DA=DA+50
	let A=A+50
done;
```

**Comment by aborruso** [comment]
@pigreco  sotto uno script che funziona.

Gli faccio inserire in append nel file `toto.json`, gli output di 100 in 100, fino a stare sotto 900.
Ho inserito la stampa a schermo dei valori di `DA` e `A` che variano nel ciclo.

La parte importante è `where=objectid+%3E%3D$DA+AND+objectid+%3C%3D$A`, che decodificata diventa `where=objectid >=$DA AND objectid <=$A`

```bash
#!/bin/bash

rm ./toto.json

DA=0
A=101

echo "Il valore di DA è $DA"
echo "Il valore di A è $A"

while [ $DA -lt 900 ]; do
  curl "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D$DA+AND+objectid+%3C%3D$A&returnGeometry=true&outSR=&outFields=*&f=pjson" >>toto.json
  let DA=DA+100
  let A=A+100
  echo "Il valore di DA è $DA"
  echo "Il valore di A è $A"
done
```

**Comment by pigreco** [comment]
Buongiorno @aborruso,

dal tuo script - che funziona - ho solo cambiato il formato di output da `json` a `kmz`:

```
#!/bin/bash

rm ./toto.kmz

DA=0
A=101

echo "Il valore di DA è $DA"
echo "Il valore di A è $A"

while [ $DA -lt 900 ]; do
  curl "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D$DA+AND+objectid+%3C%3D$A&returnGeometry=true&outSR=&outFields=*&f=KMZ" >>toto.kmz
  let DA=DA+100
  let A=A+100
  echo "Il valore di DA è $DA"
  echo "Il valore di A è $A"
done
```
ma NON funziona, in pratica ottengo solo 100 elementi come se non facesse l'`append`

**Comment by pigreco** [comment]
@aborruso 
se sei d'accordo chiudo questa issue
