### ISSUE TITLE
[scripting] Scaricare kmz in loop da un server arcgis

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#84]
**URL** http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9

**Costruire QUERY:**
http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query

**SCRIPT:** per scaricare in loop
```bash
#!/bin/bash

rm ./toto.kmz

DA=0
A=101

echo "Il valore di DA è $DA"
echo "Il valore di A è $A"

while [ $DA -lt 900 ]; do
  curl "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D$DA+AND+objectid+%3C%3D$A&returnGeometry=true&outSR=&outFields=*&f=KMZ" >>toto.kmz
  let DA=DA+100
  let A=A+100
  echo "Il valore di DA è $DA"
  echo "Il valore di A è $A"
done
```

ma non funziona in quanto il file kmz contiene solo 95 elementi, come se non facesse l'`append` (`>>toto.kmz`)

**Comment by aborruso** [comment]
Caro @pigreco se provi a fare la query di soli [100 elementi in kmz](http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D0+AND+objectid+%3C%3D101&returnGeometry=true&outSR=&outFields=*&f=kmz) vedrai che è un file che pesa molto meno di quello che scarichi con il tuo loop.

Quindi l'append sembra funzionare. Ma il KMZ è un file binario (è un XML zippato) e quasi mai fai l'unione andando in append.

Quindi hai due possibilità:

- ho scarichi in loop `n` KMZ, ognuno con nome diverso, senza append (puoi mettere nel nome la variabile di loop `DA`), e poi (dopo la fine del cicli) fai il merge con uno strumento che sa aprire questi file binari e farne il merge (gdal/ogr);
- o a ogni ciclo, con uno strumento che sa aprire questi file binari vai in append su un formato spaziale in append, con uno strumento che sa fare tutto questo (gdal/ogr).

**Comment by pigreco** [comment]
Caro @aborruso grazie per gli spunti.

Se non erro gdal/ogr ha la libreria KML e non KMZ (che è il file zippato), ho provato a un-zippare il file KMZ con 7z da cli (con un sol file riesco, ma in loop no):

```
for i in *.kmz; do
	7z e *.kmz
done
```
Ho letto in [giro ](https://gis.stackexchange.com/questions/301469/merge-different-kmz-layers-to-a-unique-kmz-file-a-bash-script)che non è una cosa semplice, quindi per adesso lascio perdere in quanto non mi serve per lavoro era solo curiosità.

**Comment by pigreco** [comment]
Ho fatto un passo avanti e sembra funzionare:

```bash
#!/bin/bash
set -x

for i in *.kmz; 
do
  #crei una variabile che usi per estrarre nome e estensione
  filename=$(basename "$i")
  #estrai estensione
  extension="${filename##*.}"
  #estrai nome file
  filename="${filename%.*}"
	7z e ./$i
	mv ./doc.kml ./"$filename".kml 
done
```

**Comment by pigreco** [comment]
In un unico script Bash:

```bash
#!/bin/bash
set -x
#cancello se esiste
rm ./toto.kmz
#variabili
DA=0
A=101
#stampo a schermo le variabili
echo "Il valore di DA è $DA"
echo "Il valore di A è $A"
#ciclo 
while [ $DA -lt 900 ]; do
  curl "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D$DA+AND+objectid+%3C%3D$A&returnGeometry=true&outSR=&outFields=*&f=KMZ" >toto$DA.kmz
  let DA=DA+100
  let A=A+100
  echo "Il valore di DA è $DA"
  echo "Il valore di A è $A"
done;

for i in *.kmz; 
do
  #creo una variabile che uso per estrarre nome e estensione
  filename=$(basename "$i")
  #estraggo estensione
  extension="${filename##*.}"
  #estraggo nome file
  filename="${filename%.*}"
    #un-zippo
	7z e ./$i
	#rinomino
	mv ./doc.kml ./"$filename".kml 
	#unisco tutti i file
	ogr2ogr -f KML -update -append merged.kml ./"$filename".kml -nln merged
done;
#cancello i file kml e kmz che non mi servono
rm ./toto*.km*
```

**Comment by pigreco** [comment]
In un unico script Bash (seconda possibilità):

```bash
#!/bin/bash
set -x
rm ./toto.kmz

DA=0
A=101

echo "Il valore di DA è $DA"
echo "Il valore di A è $A"

while [ $DA -lt 900 ]; do
  curl "http://map.sitr.regione.sicilia.it/ArcGIS/rest/services/BCC_PIANI_PAESAGGISTICI/CT_Componenti_Paesaggio_2018/MapServer/9/query?text=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&where=objectid+%3E%3D$DA+AND+objectid+%3C%3D$A&returnGeometry=true&outSR=&outFields=*&f=KMZ" >toto$DA.kmz
    echo "Il valore di DA è $DA"
  echo "Il valore di A è $A"
  7z e ./toto$DA.kmz
  mv ./doc.kml ./toto$DA.kml 
  ogr2ogr -f KML -update -append merged.kml ./toto$DA.kml -nln merged
  let DA=DA+100
  let A=A+100
done;
#cancello i file kml e kmz che non mi servono
rm ./toto*.km*
```

**Comment by pigreco** [comment]
Grazie a tutti, chiudo!

Ricetta fatta!
