### ISSUE TITLE
[bash] assegnare il valore di grep a una variabile

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#85]
Da questo [forum ](https://www.hwupgrade.it/forum/archive/index.php/t-554025.html)ho letto che per assegnare l'output di `grep` ad una variabile occorre scrivere cosi:
```
echo "COUNT_* (Integer) = 12910" | nro=`grep  -Eo "[0-9]{1,}"`
```

ma non funziona, ovvero se scrivo:

`echo "$nro"`

non stampa nulla a schermo,

cosa sbaglio??

**Comment by aborruso** [comment]
Io farei così

```
nro=$(echo "COUNT_* (Integer) = 12910" | grep  -Eo "[0-9]{1,}")
echo "$nro"
```

**Comment by pigreco** [comment]
grazie mille, funziona!!
