### ISSUE TITLE
[bash] ogrinfo e file kml

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#86]
Buongiorno,
non capisco perché uno stesso script con `ogrinfo` dia risultati diversi al cambiare del file:

1. `ogrinfo ./merged.kml merged -sql "SELECT count(*) FROM merged"`

output:
```
INFO: Open of `./merged.kml'
      using driver `LIBKML' successful.
layer names ignored in combination with -sql.

Layer name: merged
Geometry: None
Feature Count: 1
Layer SRS WKT:
(unknown)
COUNT_*: Integer (0.0)
OGRFeature(merged):0
  COUNT_* (Integer) = 910
```
2. `ogrinfo ./toto0.kml toto0 -sql "SELECT count(*) FROM toto0"`

output:
`ERROR 1: SELECT from table toto0 failed, no such table/featureclass.`

allego i due file

[merged.zip](https://github.com/opendatasicilia/tansignari/files/3446492/merged.zip)
[toto0.zip](https://github.com/opendatasicilia/tansignari/files/3446493/toto0.zip)

**Comment by aborruso** [comment]
fai `ogrinfo toto0.kml -summary` e vedi come si chiama la tabella

**Comment by pigreco** [comment]
@aborruso 

>fai ogrinfo toto0.kml -summary e vedi come si chiama la tabella

ecco output:

```
INFO: Open of `toto0.kml'
      using driver `LIBKML' successful.
1: viabilità storica
```

**Comment by aborruso** [comment]
E quindi il layer da interrogare non è `toto0`

**Comment by pigreco** [comment]
la cosa si complica, ma vedo cosa riesco a tirar fuori.
grazie

**Comment by pigreco** [comment]
ho fatto varie prove, ma non riesco a tirar fuori nulla:

`ogrinfo toto0.kml "viabilità storica" -sql "SELECT count(*) FROM "viabilità storica""`

output:
```
INFO: Open of `toto0.kml'
      using driver `LIBKML' successful.
layer names ignored in combination with -sql.
ERROR 1: SELECT from table viabilità failed, no such table/featureclass.
```

**Comment by pigreco** [comment]
ho scoperto per caso che il nome del layer non è `viabilità storica` ma `viabilità_storica`
quindi lo script funziona:

`ogrinfo toto0.kml  -sql "SELECT count(*) FROM viabilità_storica"`

output:

```
INFO: Open of `toto0.kml'
      using driver `LIBKML' successful.

Layer name: viabilità_storica
Geometry: None
Feature Count: 1
Layer SRS WKT:
(unknown)
COUNT_*: Integer (0.0)
OGRFeature(viabilità_storica):0
  COUNT_* (Integer) = 101
```

**Comment by aborruso** [comment]
Caro @pigreco non puoi mettere `"` dentro `"`, perché è un carattere super speciale.

Quindi devi andare di escape

    ogrinfo toto0.kml -sql "SELECT count(*) FROM \"viabilità storica\""

**Comment by pigreco** [comment]
grazie @aborruso, funziona benissimo
