### ISSUE TITLE
Conversione json in GeoJSON o CSV

### ISSUE THREAD

**Issue by simomus** [opendatasicilia/tansignari#87]
Buongiorno, premetto che non sono esperto di gis o un programmatore, vi chiedo di avere pazienza... Sto realizzando su uMap la seguente mappa (mappa degli spazi culturali di Roma e del Lazio):
https://umap.openstreetmap.fr/it/map/gli-spazi-della-cultura-a-roma_348936.
Sto lavorando su una prima serie di layer basati su open data e Linked Open Data, tra cui quello dei "luoghi della cultura", i cerchietti rosso scuro ma anche le gocce rosso vivo, che è tratto da qui:
http://dati.beniculturali.it/dataset/dataset-luoghiLazio.json
http://dati.beniculturali.it/descrizione_dataset/
Per il layer con i cerchietti rosso scuro ho fatto una conversione brutale usando questo servizio:
http://convertcsv.com/json-to-csv.htm - **allego il csv qui**: [luoghidellacultura_mibac.zip](https://github.com/opendatasicilia/tansignari/files/3456095/luoghidellacultura_mibac.zip); mentre il layer con le gocce rosso vivo è una versione csv per cui ho avuto un gentilissimo supporto. Restano dei problemi però. Sotto ho incollato uno screenshot con uno dei popup del nuovo csv. Parte del testo scompare dietro il limite della scheda (problema fondamentale, che non sono riuscito a risolvere), e le ontologie descrittive a sinistra sono poco chiare e ridondanti. Si può fare qualcosa per rendere più presentabile il tutto? Qual è per il futuro il metodo migliore per questo genere di conversioni? Grazie mille!!

![immagine](https://user-images.githubusercontent.com/53560136/62282196-6f0c3d80-b44f-11e9-839f-869c6e952d8b.png)

**Comment by aborruso** [comment]
@simomus è arrivato un messaggio senza alcun testo, ma soltanto un oggetto.

Per favore inseriscilo, o in risposta per email o online qui https://github.com/opendatasicilia/tansignari/issues/87

Basta il testo che mi hai scritto in privato.

Grazie

**Comment by simomus** [comment]
@aborruso grazie, sto editando il commento: ho pubblicato inavvertitamente prima di scriverlo...

**Comment by simomus** [comment]
@aborruso così è ok?

**Comment by aborruso** [comment]
@simomus sì, allegherei però il tuo primo CSV di output

**Comment by simomus** [comment]
ok

**Comment by simomus** [comment]
@aborruso mi dice che non si possono allegare file formato csv. Possibile?

**Comment by aborruso** [comment]
@simomus zippalo e fai drag&drop :)

**Comment by simomus** [comment]
> 
> 
> @simomus zippalo e fai drag&drop :)

Fatto grazie!

**Comment by gbvitrano** [comment]
occhio che la mappa è modificabilre da chiunque... 

![immagine](https://user-images.githubusercontent.com/20488693/62286865-ed211200-b458-11e9-91b3-6f2cf02810c4.png)

Per risolvere il problema del popup con le info che spariscono dei impostare di default (quindi dalle impostazioni generali) per tutti i layer lo **Stile del contenuto del Popup** in  **Pannello laterale**

![immagine](https://user-images.githubusercontent.com/20488693/62287157-97009e80-b459-11e9-8ec0-fb8ef7b4ef1e.png)

e devi uniformare ** la chiave etichetta** 
![immagine](https://user-images.githubusercontent.com/20488693/62287461-27d77a00-b45a-11e9-9209-59a61a64508d.png)

in modo da non avere questa presentazione, che non fa capire nulla

![2019-08-01_12h34_46](https://user-images.githubusercontent.com/20488693/62287488-3faefe00-b45a-11e9-85c3-ec73fd92526e.png)

![2019-08-01_12h35_30](https://user-images.githubusercontent.com/20488693/62287494-4178c180-b45a-11e9-9aca-21d89fca5e63.png)

**Comment by gbvitrano** [comment]
Dove possibile dovresti uniformare anche il **Template del contenuto del popup**

![immagine](https://user-images.githubusercontent.com/20488693/62287717-f9a66a00-b45a-11e9-81f2-777cce4bb774.png)

**Comment by simomus** [comment]
> 
> 
> occhio che la mappa è editabile da chiunque...
> 
> ![immagine](https://user-images.githubusercontent.com/20488693/62286865-ed211200-b458-11e9-91b3-6f2cf02810c4.png)
> 
> Per risolvere il problema del popup con le info che spariscono dei impostare di default (quindi dalle impostazioni generali) per tutti i layer lo **Stile del contenuto del Popup** in **Pannello laterale**
> 
> ![immagine](https://user-images.githubusercontent.com/20488693/62287157-97009e80-b459-11e9-8ec0-fb8ef7b4ef1e.png)
> 
> e devi uniformare ** la chiave etichetta**
> ![immagine](https://user-images.githubusercontent.com/20488693/62287461-27d77a00-b45a-11e9-9209-59a61a64508d.png)
> 
> in modo da non avere questa presentazione, che non fa capire nulla
> 
> ![2019-08-01_12h34_46](https://user-images.githubusercontent.com/20488693/62287488-3faefe00-b45a-11e9-85c3-ec73fd92526e.png)
> 
> ![2019-08-01_12h35_30](https://user-images.githubusercontent.com/20488693/62287494-4178c180-b45a-11e9-9aca-21d89fca5e63.png)

Grazie @gbvitrano,  per quanto riguarda lo stile del contenuto avevo già provato ma dà lo stesso problema 
![immagine](https://user-images.githubusercontent.com/53560136/62287974-9ec14280-b45b-11e9-9e97-5b7e6250cd67.png)

**Comment by simomus** [comment]
Su chiave dell'etichetta e template del contenuto mi trovo in difficoltà perché in genere li gestisco bene se ho un file xlsx ma con un csv, soprattutto se così incasinato, mi perdo...

**Comment by gbvitrano** [comment]
si sono troppe info, devi personalizzare il contenuto del popup/pannello laterale

![immagine](https://user-images.githubusercontent.com/20488693/62287717-f9a66a00-b45a-11e9-81f2-777cce4bb774.png)

**Comment by simomus** [comment]
Quanto alle autorizzazioni pensavo di mantenerla per il momento editabile per facilitare il confronto, visto che non l'ho ancora diffusa. Ma se me lo sconsigliate in ogni caso, modifico l'impostazione.

**Comment by gbvitrano** [comment]
Usando il codice di umap puoi ottimizzare il tutto, vedo indirizzi http molto lunghi

![2019-08-01_12h59_51](https://user-images.githubusercontent.com/20488693/62288218-33c43b80-b45c-11e9-8f42-73392f518dd1.png)

**Comment by gbvitrano** [comment]
> 
> 
> Quanto alle autorizzazioni pensavo di mantenerla per il momento editabile per facilitare il confronto, visto che non l'ho ancora diffusa. Ma se me lo sconsigliate in ogni caso, modifico l'impostazione.

Se è una tua scelta lasciala cosi :-) pensanvo ad una svista

**Comment by simomus** [comment]
> 
> 
> Usando il codice di umap puoi ottimizzare il tutto, vedo indirizzi http molto lunghi
> 
> ![2019-08-01_12h59_51](https://user-images.githubusercontent.com/20488693/62288218-33c43b80-b45c-11e9-8f42-73392f518dd1.png)

Sì più o meno me la cavo con la formattazione quando ho xslx ma con csv mi impicco veramente... vuol dire che farò delle prove impiccandomici un po di più... :)

**Comment by aborruso** [comment]
@simomus e che cambia tra un CSV e XLS??

Qui forse ti mandano in confusione i nomi dei campi? Perché sia per CSV che XLS, per formattare devi sempre usare i nomi colonne e nient'altro.

**Comment by gbvitrano** [comment]
Come dice @aborruso devi ripulire i campi è tenere solo ciò che ti è utile

![2019-08-01_13h07_31](https://user-images.githubusercontent.com/20488693/62289019-f06acc80-b45d-11e9-9ecc-85f83fb36624.png)

domanda... è proprio necessario collegare i dati dinamicamente...? le info cambiamo nel tempo?

**Comment by simomus** [comment]
> 
> 
> @simomus e che cambia tra un CSV e XLS??
> 
> Qui forse ti mandano in confusione i nomi dei campi? Perché sia per CSV che XLS, per formattare devi sempre usare i nomi colonne e nient'altro.

A monte dei nomi incasinati di questo file è che faccio fatica a leggere i contenuti delle tabelle in csv. Quindi è solo per mia ignoranza. Cercherò di fare un po' di esercizio...

**Comment by simomus** [comment]
> 
> 
> Come dice @aborruso devi ripulire i campi è tenere solo ciò che ti è utile
> 
> ![2019-08-01_13h07_31](https://user-images.githubusercontent.com/20488693/62289019-f06acc80-b45d-11e9-9ecc-85f83fb36624.png)
> 
> domanda... è proprio necessario collegare i dati dinamicamente...? le info cambiamo nel tempo?

Diciamo che è comodo, perché credo sia un dataset in costante aggiornamento. E poi mi pare utile capire come si fa perché non immaginavo che su umap si potesse fare. Cmq sì, proverò a ripulire ma non saprei proprio come risolvere l'eccedenza del testo rispetto al campo del popup.

**Comment by simomus** [comment]
> 
> 
> > @simomus e che cambia tra un CSV e XLS??
> > Qui forse ti mandano in confusione i nomi dei campi? Perché sia per CSV che XLS, per formattare devi sempre usare i nomi colonne e nient'altro.
> 
> A monte dei nomi incasinati di questo file è che faccio fatica a leggere i contenuti delle tabelle in csv. Quindi è solo per mia ignoranza. Cercherò di fare un po' di esercizio...

Dubbio: ma voi suggerite di agire direttamente su umap o sulla tabella offline prima di caricarla?

**Comment by gbvitrano** [comment]
off-line puoi aggire solo sul file csv che hai caricato manualmete.

Per ottimizzare le info riportate nel popup/pannello devi 

Fai caricare solo i campi neseccari con l'editing di umap
![immagine](https://user-images.githubusercontent.com/20488693/62287717-f9a66a00-b45a-11e9-81f2-777cce4bb774.png)

**Comment by gbvitrano** [comment]
i link di questo layer non fanno altro che rimandarti su altro sito...
![immagine](https://user-images.githubusercontent.com/20488693/62290239-2c536100-b461-11e9-8a3b-b0737ab0d25d.png)

![immagine](https://user-images.githubusercontent.com/20488693/62290378-8a804400-b461-11e9-9d8c-a66fff7d2d39.png)

Per ottenere tutte le info dovresti fare una  [query](http://dati.beniculturali.it/sparql) ma bisogna essere esperti di LOD

**Comment by simomus** [comment]
> 
> 
> i link di questo layer non fanno altro che rimandarti su altro sito...
> ![immagine](https://user-images.githubusercontent.com/20488693/62290239-2c536100-b461-11e9-8a3b-b0737ab0d25d.png)
> 
> ![immagine](https://user-images.githubusercontent.com/20488693/62290378-8a804400-b461-11e9-9d8c-a66fff7d2d39.png)
> 
> Per ottenere tutte le info dovresti fare una [query](http://dati.beniculturali.it/sparql) ma bisogna essere esperti di LOD

Cioè se ho capito bene: devo fare editing della tabella direttamente su umap (eliminando le colonne) e selezionare i campi da visualizzare nel popup indicandoli nel template del contenuto, scremando tutti i campi che non generano testo ma soltanto url. Però non ho capito se è risolvibile il problema dell'eccedenza grafica del contenuto dalla scheda del popup.

**Comment by aborruso** [comment]
Ciao @simomus ecco alcune note più estese.

Inizio da una che ho già scritto: scrivi di non avere problemi con XLS, ma ne hai con i CSV. Salva il CSV in XLS :)<br>
Io non credo che tu abbia problemi con il formato, ma soltanto con una tabella così ricca. Le colonne ti servono tutte? Se no rimuovine qualcuna. I nomi delle colonne ti "confondondo"? Cambiagli nome.

Prima cosa: questi file non sono dei JSON, ma dei [JSON-LD](https://json-ld.org/), ovvero dei JSON per i Linked Data. Alcune note su questo:

- il file JSON è un formato che di base è molto più ricco in termini di struttura rispetto a un CSV. E infatti può contenere, come in questo caso, una struttura multi tabella; nel JSON-LD, per ogni ID, ci sono uno o più servizi e ad esempio l'ID 143478 ne ha ben 21 associati (qui i dati per tutti gli ID https://gist.github.com/aborruso/46b8e17ce0547df6ba36e235d050e102);
- il formato JSON-LD è per certi versi ancora più ricco, perché immaginato per i Linked Data. Quindi devi avere delle conosceze di base su questo mondo per muoverti con agilità. Trovare il tool, che fa per te la conversione alla cieca, magari ti produce un CSV usabile, ma di cui non sai comprendere in piene l'output.

Non sono un esperto di Linked Data e su questo altri ti possono dare consigli migliori, ma se cerchi un tool "per tutti", da usare per aprire e gestire questo formato, potresti provare [OpenRefine](http://openrefine.org/), uno strumento prezioso per fare pulizia, ristrutturazione, trasformazione e arricchimento di dati. Tra i formati che gestisce in import, c'è pure il JSON-LD.

![image](https://user-images.githubusercontent.com/30607/62354802-ee604680-b50d-11e9-889f-923fc7de2cef.png)


Una volta importato, potrai trasformare il file o esportarlo in CSV abbastanza usabile. Questo avrà delle colonne numerate, come quelle in fondo. Questo avviene quando in qualche modo delle tabelle annidate, come quella di sopra dei servizi.

Non so se ti ho aiutato, ma il tema è ricco.


```
@type:0
@type:1
accessCondition:hasAccessCondition:0
accessCondition:hasAccessCondition:0:@id
accessCondition:hasAccessCondition:1:@id
accessCondition:hasAccessCondition:2:@id
accessCondition:hasAccessCondition:3:@id
cis:hasDiscipline:0:@id
cis:hasDiscipline:1:@id
cis:hasDiscipline:2:@id
cis:hasDiscipline:3:@id
cis:hasDiscipline:4:@id
cis:hasDiscipline:5:@id
cis:providesService:0:@id
cis:providesService:10:@id
cis:providesService:11:@id
cis:providesService:12:@id
cis:providesService:13:@id
cis:providesService:14:@id
cis:providesService:15:@id
cis:providesService:16:@id
cis:providesService:17:@id
cis:providesService:18:@id
cis:providesService:19:@id
cis:providesService:1:@id
cis:providesService:20:@id
cis:providesService:2:@id
cis:providesService:3:@id
cis:providesService:4:@id
cis:providesService:5:@id
cis:providesService:6:@id
cis:providesService:7:@id
cis:providesService:8:@id
cis:providesService:9:@id
l0:description:0:@language
l0:description:0:@value
l0:description:1:@language
l0:description:1:@value
l0:description:@language
l0:description:@value
l0:identifier
potapit:hasTicket:0:@id
potapit:hasTicket:1:@id
smapit:hasOnlineContactPoint:0:@id
smapit:hasOnlineContactPoint:1:@id
smapit:hasOnlineContactPoint:2:@id
```

**Comment by simomus** [comment]
Grazie mille @aborruso  e @gbvitrano !! Appena ho un po' di tempo cerco di capirci qualcosa in generale con i JSON-LD, e sull'uso di OpenRefine. Per ora faccio una pulizia della tabella già caricata e poi vi sottopongo il risultato, sperando che la pulizia risolva anche il problema della visualizzazione parziale nel popup. A presto!

**Comment by simomus** [comment]
Buongiorno @aborruso e @gbvitrano, sono finalmente riuscito a sistemare la tabella (layer "Luoghi della cultura": https://umap.openstreetmap.fr/it/map/gli-spazi-della-cultura-a-roma_348936). Restano molte imperfezioni ma ora mi pare accettabile. Ho scelto di lasciare tutti i link per il momento, perché comunque rinviano a informazioni utili e soprattutto perché non ho il tempo di sostituirli con i relativi contenuti. Da quanto mi risulta non si trovano in giro visualizzazioni su mappa di questo dataset, quindi mi pare che non sia una fatica sprecata. Che ne pensate? Avete altri suggerimenti o dubbi? Cmq vi farò sapere quando avrò terminato questa mappa, o cmq quando deciderò di fermarmi... Grazie ancora!

**Comment by aborruso** [comment]
@simomus mi fa  piacere. Cosa hai fatto in particolare?

**Comment by simomus** [comment]
@aborruso scusa il ritardo della risposta ma sono stato impicciatissimo. Ho semplicemente seguito i vostri consigli, e cioè ho pulito la tabella direttamente su umap, sfrondando colonne e ridefinendo le etichette. Sono poi riuscito ad aggiustare la formattazione del popup mediante la funzione di definizione del template del contenuto, anche per quanto riguarda la sequenza delle informazioni. Insomma niente di trascendentale ma il risultato mi sembra se non altro accettabile ora. E perciò ti rinnovo il ringraziamento!!
