### ISSUE TITLE
[everything] come cercare file su win, tramite regex

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#88]
Buongiorno
per usare le espressioni regolari in **[everything](https://en.wikipedia.org/wiki/Everything_(software))** occorre fare qualcosa di particolare??

devo cercare tutti i file in una cartella con estensione `.tif` e quindi scrivo:

`D:\scansioni_copia_pubblica  ext:tif`   funziona!

di questi voglio solo quelli che iniziano per `f2` e quindi scrivo:

`D:\scansioni_copia_pubblica  ext:tif  ^f2` ma non funziona!

cosa sbaglio??

**Comment by pigreco** [comment]
Ho trovato una prima soluzione ma non so se è generalizzabile:

`D:\scansioni_copia_pubblica  ext:tif f2*`  funziona!!

cerca tutti i file con estensione `tif`, iniziano per `f2` e si trovano nella cartella (e sottocartelle) specificata

**Comment by aborruso** [comment]
Caro @pigreco ,
prova con (cerca anche nelle sottocartelle)

    D:\scansioni_copia_pubblica ext:tif regex:^f2

La sintassi è molto molto ricca http://www.voidtools.com/support/everything/searching/

Un modo visuale per scoprirla è l'advanced search

![image](https://user-images.githubusercontent.com/30607/63634089-fa917c80-c651-11e9-9596-fdea77ed52c7.png)

**Comment by pigreco** [comment]
Grazie funziona perfettamente!
