### ISSUE TITLE
Google Sheets - Importadata file csv con separatore ;

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#89]
Come importare da remoto un file csv  in google sheet che usa il **semicolon** (**;**) come separatore di campo?

Di default google sheet con **IMPORTDATA**  importa i dati di un **url** specificato in formato .csv (valori **separati da virgole**) o .tsv (valori **delimitati da tabulazioni**).

quindi per importare un file  basta posizionarsi in cella qualsiasi e scrivere:

**IMPORTDATA("url")**

url - L'url da cui recuperare i dati in formato .csv o .tsv, incluso il protocollo (ad es. http://)

**IMPORTDATA("http://www.census.gov/2010census/csv/pop_change.csv")**

Ma se nel file che vogliamo importare è stato usato **semicolon** (**;**) come separatore di campo... come in questo [caso](https://opendata.comune.palermo.it/ws.php?id=1905&fmt=csv) ?

Con la sintassi di base...

`=IMPORTDATA("https://opendata.comune.palermo.it/ws.php?id=1905&fmt=csv")`

... otteniamo questo risultato 

![2019-08-29_11h20_29](https://user-images.githubusercontent.com/20488693/63928050-32803180-ca4f-11e9-84ea-56568ff8decb.png)

Per far caricare correttamente il file occorre specificare nella formula che il separatore di campo è **semicolon** (**;**)

Qui la nuova sintassi della formula: 

**IMPORTDATA("url", ";")**

`=IMPORTDATA("https://opendata.comune.palermo.it/ws.php?id=1905&fmt=csv", ";")`

![2019-08-29_11h27_46](https://user-images.githubusercontent.com/20488693/63928548-074a1200-ca50-11e9-8043-ef01818d5b9e.png)

Fatto... :-)

**Comment by aborruso** [comment]
La cosa incredibile è che nella documentazione ufficiale non è indicato https://support.google.com/docs/answer/3093335?hl=en

**Comment by cirospat** [comment]
quindi Gianni ha scritto una documentazione utile alle funzionalità del
Google spreadsheet, ma che Google non ha pubblicato.
Gianni......se ti prendono a Google, raccomandami!


*Ciro Spataro*
cirospat@gmail.com
cirospat.readthedocs.io





Il giorno gio 29 ago 2019 alle ore 11:37 Andrea Borruso <
notifications@github.com> ha scritto:

**Comment by gbvitrano** [comment]
è la fortuan del principiante... :-)
e poi seguo una [regola di base ](https://youtu.be/I-qEoWw3uKM) :-)

**Comment by aborruso** [comment]
Gli ho scritto https://support.google.com/docs/thread/13092222?hl=en

**Comment by gbvitrano** [comment]
> 
> 
> Gli ho scritto https://support.google.com/docs/thread/13092222?hl=en

Ho scoperto un **bub** ora verra corretto :-)  :-)

**Comment by cirospat** [comment]
ora arriva la risposta da Google:
*per questa importante interazione ai servizi Google, la invitiamo, a lei e
GBVitrano, gratuitamente a Mountain View per il prossimo I/O e le paghiamo
il volo. *








Il giorno gio 29 ago 2019 alle ore 11:56 Giovan Battista Vitrano <
notifications@github.com> ha scritto:
