### ISSUE TITLE
Wordpress: il nuovo Wordpress a blocchi non visualizza i git

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#9]
Prima dell'ultimo aggiornamento di Wordpress riuscivo ad usare i `git` per la visualizzazione di script, espressioni ed altro; 
![image](https://user-images.githubusercontent.com/7631137/52534393-48433900-2d41-11e9-94ee-0bd87bb4974c.png)

dopo l'aggiornamento è cambiato l'editor dei testi (ora funziona come quello di Medium - a blocchi) e non riesco più a visualizzare correttamente i `git`, incollando il link del `git` vedo:
![image](https://user-images.githubusercontent.com/7631137/52534453-e46d4000-2d41-11e9-8df5-1fa0ac355141.png) oppure 
![image](https://user-images.githubusercontent.com/7631137/52534467-0ebefd80-2d42-11e9-9325-ef077d5b03ce.png)

è possibile rimediare in qualche modo??

grazie

**Comment by pigreco** [comment]
Una prima soluzione:
da impostazioni (in alto a destra, i tre puntini in verticale) selezionare `editor classico`
![image](https://user-images.githubusercontent.com/7631137/52534623-4038c880-2d44-11e9-9da5-f0098a0239ef.png)

**Comment by pigreco** [comment]
La soluzione trovata sopra non è ottimale in quanto NON permette più di modificare immagini inserite in precedenza.
Occorre capire come e se è possibile usare il nuovo editor (a blocchi) e le git!!! :-(

**Comment by gbvitrano** [comment]
Per tornare ad evere il vecchio editor occore installare il plugin [Classic Editor ](https://it.wordpress.org/plugins/classic-editor/) sui site ospistati da Worldpress è tra le impostazioni

**Comment by pigreco** [comment]
Ciao Gianni e grazie per il suggerimento 
ma il piano che ho io non mi permette di installare nessun plugin:
![image](https://user-images.githubusercontent.com/7631137/52642917-32b64680-2edc-11e9-9e2a-f4c7783fdbad.png)

**Comment by aborruso** [comment]
Ciao @pigreco io al tuo posto proverei a scrivere tutto in markdown. E così dovresti poter mettere per bene un po' di codice insieme al testo.

![image](https://user-images.githubusercontent.com/30607/52695311-76589100-2f6c-11e9-81b4-63e3c0a9eaba.png)

**Comment by pigreco** [comment]
Ciao @aborruso 
ho chiuso issue perché avevo perso le speranze nel trovare una soluzione,
ma grazie alla tua bella freccia rossa (sono parecchio invidioso :stuck_out_tongue_closed_eyes:) vedo una luce in fondo al tunnel.

provo e ti aggiorno

grazie

**Comment by pigreco** [comment]
Ciao Andrea,
attivando l'opzione 'usa Markdown' riesco solo a fare questo (copio ed incollo script)

![image](https://user-images.githubusercontent.com/7631137/52786221-9ebeb900-305a-11e9-8ad2-2981d4856482.png)

secondo me è una regressione.

Pazienza.
