### ISSUE TITLE
[Gis] Come dividere poligoni 

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#90]
Buongiorno :-)
Per aggiornare la [mappa delle fontanelle](http://palermohub.opendatasicilia.it/fontanelle_pa.html) con l'analisi sulle isocrone fatta da @aborruso "devo" per motivi grafici :-) rovinare un po i file...
Dai due file Tp 300 e T 600 devo ricavarene uno solo e con poligoni/geometrie divise.
Come prima cosa ho fatto la **Differenza** tra Tp 600 e Tp 300 ed ottengo questo risultato, ma sembra essere un unico poligono.

![2019-08-31_11h39_14](https://user-images.githubusercontent.com/20488693/64062399-31353d00-cbe6-11e9-8ca1-174622ca8c8c.png)

Come posso dividere il poligono in più parti?

**Comment by aborruso** [comment]
@gbvitrano se ho capito la tua richiesta, in QGIS puoi fare come in figura

![image](https://user-images.githubusercontent.com/30607/64062508-68f0b480-cbe7-11e9-98e5-31ebea095bf4.png)

**Comment by pigreco** [comment]
@gbvitrano molto probabilmente i due file tp_300 e tp_600 sono il risultato di un `merge`, forse se utilizzi i singoli file (per ogni fontanella) ottieni il risultato che vuoi.

**Comment by gbvitrano** [comment]
Grazie per i consigli,  risolto :-) :-) 

![Screenshot_2019-08-31 Analisi - Isolinee - Fontanelle acqua potabile Comune di Palermo - 2019 - uMap](https://user-images.githubusercontent.com/20488693/64062923-95a7ca80-cbed-11e9-97af-2be0fb3669c8.jpg)

**Comment by aborruso** [comment]
@gbvitrano due cose:

- scrivi sempre due parole sul come hai risolto, altrimenti la issue rimane poco utile;
- una mini ricetta, la scriverei

**Comment by gbvitrano** [comment]
Non avendo i singoli file come suggerito da @pigreco ho optato per la soluzione di @aborruso da parti singole a parti multiple, ho trovato il comando tra gli **strumenti di processing**

![2019-08-31_12h54_40](https://user-images.githubusercontent.com/20488693/64062999-99881c80-cbee-11e9-8fb3-edc0f9d9263a.png)

Ottenuto il risultato ho aggiunto altre info ai poligoni :-)
