### ISSUE TITLE
[spatialite_gui] file csv manda in crash spatialite_gui

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#91]
In SpatiaLite_gui (sto utilizzando la gui 2.0.0 devel e spatialite 4.3a) è possibile importare file csv:
 `Menu File | Advanced | Load CSV/TXT`

Utilizzando questo file csv:
https://github.com/opendatasicilia/FontanellePalermo/blob/master/risorse/csv_fontanelle/Fontane_indirizzo_link_gmaps.csv

Spatialite_gui, dopo aver settato la maschera per importare il file (vedi sotto), si chiude senza nessun messaggio, alla riapertura del database non ha importato nulla.

ecco alcune prove sul settaggio del file csv:

![image](https://user-images.githubusercontent.com/7631137/64233649-f4728a00-cef4-11e9-9364-3f4c77b7011e.png)

![image](https://user-images.githubusercontent.com/7631137/64233684-02c0a600-cef5-11e9-9762-a9f950fe1403.png)

**Comment by aborruso** [comment]
@pigreco non ho la tua versione di spatialite.

Con quella indicata più in bassa, e con questi parametri (che sono a mio avviso quelli corretti per questo file), si importa correttamente.

![image](https://user-images.githubusercontent.com/30607/64234138-f38e2800-cef5-11e9-93c2-2c5d0fd45559.png)


![image](https://user-images.githubusercontent.com/30607/64234094-e07b5800-cef5-11e9-8566-8876872eecf7.png)

**Comment by pigreco** [comment]
Caro @aborruso 
confermo, nella nuova spatialite_gui e spatialite 5 funziona. :-)

grazie
