### ISSUE TITLE
come ottenere un file in formato CSV partendo da uno in formato JSON

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/tansignari#92]
salve
ho necessità di trasformare questo dataset in formato JSON:
https://www.palermocapitalecultura.it/wp-json/eventon/events
in un file in formato CSV.

Ho cercato in giro sul web e ho trovato un articolo utile in merito:
https://medium.com/@paulgambill/how-to-import-json-data-into-google-spreadsheets-in-less-than-5-minutes-a3fede1a014a
che prevede la costruzione di uno [script](https://gist.github.com/chrislkeller/5719258) dentro un foglio Google Spreadsheet per dare poi nella cella il comando
**`=importJSON(“http://.........com", “/date”, “noInherit, noTruncate”)`**
Da notare che normalmente (di default) il comando **`=importJSON`** non è previsto da Google Spreadsheet.

Voglio condividere con voi questo articolo e capire insieme quale è la soluzione più facile da adottare. 
L'obiettivo finale è pubblicare sul portale open data del comune di Palermo il dataset degli eventi di Palermo capitale italiana della cultura 2018. Giusto per non perdere la memoria.

Grazie

**Comment by gbvitrano** [comment]
Dai un'occhita a questo [video ](https://www.youtube.com/watch?v=EXKhVQU37WM) spiega come importare un json su google sheet con l'aiuto di uno script

**Comment by gbvitrano** [comment]
articoli molto interessanti:

https://medium.com/@nifreddo/importare-i-dati-json-in-un-googlespreadsheet-gli-open-data-di-arpa-veneto-48a342c2cc50

https://medium.com/@aborruso/ne-approfitto-per-mostrare-come-farlo-a-riga-di-comando-usando-jq-65f21801bce3

**Comment by cirospat** [comment]
> Dai un'occhita a questo [video ](https://www.youtube.com/watch?v=EXKhVQU37WM) spiega come importare un json su google sheet con l'aiuto di uno script

ho seguito il tutorial @gbvitrano 
ho creato lo script nel google spreadsheet
https://docs.google.com/spreadsheets/d/1we3pNjNkU0wv5bv-a5QfUkCYf9Hi7bcOHMyS8vKwDCc/edit?usp=sharing
ma mi funziona solo il primo campo "event", gli altri campi non mi appaiono seguendo il comando
`IMPORTJSON(URL, Object)`
infatti se scrivo: 
`=IMPORTJSON("https://www.palermocapitalecultura.it/wp-json/eventon/events","events/name")`
mi da "Node not Available" ma sono sicuro sbaglierò nella sintassi delle dipendenze degli oggetti.

**Comment by aborruso** [comment]
Caro Ciro,
la risposta che consente di farlo con pochi click, senza approfondire molto non mi viene subito.

Appunto qui una procedura che sfrutta [jq](https://github.com/stedolan/jq) e [Miller](https://github.com/johnkerl/miller):

```bash
# scarica gli eventi
curl "https://www.palermocapitalecultura.it/wp-json/eventon/events" >eventi.json
# estrai dati di base eventi
<eventi.json jq '[.events|to_entries[]|[.key,(.value += {id:.key})]]|.[][1].value|del(.event_type?)|del(.repeats?)|del(.event_type_2?)'  | \
mlr --j2c unsparsify >eventiTmp.csv
# estrai info sul tipo evento
<eventi.json jq '[.events|to_entries[]|[.key,(.value += {id:.key})]]|.[][1].value|{id:.id,event_type:.event_type?}'  | \
mlr --j2c unsparsify >eventiTipo.csv
mlr -I --csv reshape -r "type" -o item,value then filter '$value!=""' then cut -x -f item \
then nest --implode --values --across-records --nested-fs "|" -f value then rename value,tipo eventiTipo.csv
# unisci dati di base con tipo evento e imposta il ";" come separatore
mlr --csv --ofs ";" join -u -j id  -f eventiTmp.csv eventiTipo.csv >eventi.csv 
```

Produce un CSV con il `;` come separatore di campo (come lo vuole il portale del comune). Come encoding è `UTF-8`, ma non ho idea quale sia quello che usa input il comune.

Lo script sembra "complesso" e me ne scuso. Io l'ho eseguito su Linux, dentro Win10.
Aldilà del facile o del difficile, file come i JSON sono da modificare con strumenti dedicati. Io sono disponibile a fare qualche ora di didattica.

Per il momento mi fermo qui.

[Questo](https://github.com/opendatasicilia/tansignari/files/3665355/eventi.zip) l'output.

Appena trovo un attimo vedo di capire con google sheet.

![image](https://user-images.githubusercontent.com/30607/65815386-0f33d800-e1ef-11e9-847d-7394890be4df.png)

**Comment by cirospat** [comment]
grazie @aborruso 
non ho premura nel raggiungere l'obiettivo prefissato.
Posso aspettare di capire come ottenere il CSV dal JSON su Google spreadsheet. Sicuramente con uno script. Così imparo e replico nel futuro.
Grazie per il tempo.

**Comment by gbvitrano** [comment]
io trovo 2933 eventi, avrò fatto sicuramente qualche errore :-) 

![2019-09-28_14h14_37](https://user-images.githubusercontent.com/20488693/65816319-57a4c300-e1fa-11e9-8001-981763526c1a.png)

**Comment by aborruso** [comment]
@gbvitrano gli eventi sono 2484 (la prova è con `<eventi.json jq '.events|length'`).

In ogni caso, sbagliavo una cosa, perché facevo l'inner join e non il left tra eventi e tipo evento. Ma non tutti gli eventi hanno un "tipo" associato, quindi con l'inner tagliavo quelli senza tipo.

@cirospat ho aggiornato il CSV nella mia risposta, adesso è corretto

**Comment by gbvitrano** [comment]
@aborruso 2484 eventi... ci sono riuscito :-)  :-) annidato c'era anche l'evento **Città Metropolitana** con il codice evento **1562**, ho usato excel e visidata per il **Melt** sulle colonne dei vari codici degli eventi, ho convertito le date di inizio e fine evento.

[eventi_palermo_capitale_cultura_2018.zip](https://github.com/opendatasicilia/tansignari/files/3665925/eventi_palermo_capitale_cultura_2018.zip)

ps. @cirospat non caricare il mio file sul portale opendata, potrebbe contenere errori, il mio è solo un esercizio :-)

**Comment by gbvitrano** [comment]
Studiando... su può fare anche google sheet :-)
![2019-09-28_22h57_09](https://user-images.githubusercontent.com/20488693/65822388-52b83180-e243-11e9-91e5-830b0b83677e.png)

**Comment by aborruso** [comment]
@cirospat a questo punto verifica con Gianni e se ok ti tocca scrivere la ricetta e poi chiudere issue

**Comment by gbvitrano** [comment]
google sheet non è la soluzione... troppo lentoooooooooooooooo sono solo 50 righe....

![2019-09-29_09h32_13](https://user-images.githubusercontent.com/20488693/65828532-211f8480-e29c-11e9-9cee-bdc035964374.png)

**Comment by gbvitrano** [comment]
Domanda... se vuoi mettere nel portale opendata del comune i dati sugli eventi di Palermo Capitale della Cultura 2018...Perchè non caricare direttamente il json sul portale opendata? 

[eventi_palermo_capitale_cultura_2018_json.zip](https://github.com/opendatasicilia/tansignari/files/3666470/eventi_palermo_capitale_cultura_2018_json.zip)

**Comment by cirospat** [comment]
> Domanda... se vuoi mettere nel portale opendata del comune i dati sugli eventi di Palermo Capitale della Cultura 2018...Perchè non caricare direttamente il json sul portale opendata?
> 
> [eventi_palermo_capitale_cultura_2018_json.zip](https://github.com/opendatasicilia/tansignari/files/3666470/eventi_palermo_capitale_cultura_2018_json.zip)

@gbvitrano buongiorno
sul pannello di controllo del portale open data, nella finestra dei formati del dataset non c'è `JSON`.

Ecco lo screenshot
![image](https://user-images.githubusercontent.com/3757525/65828875-03ecb500-e2a0-11e9-8f5a-cf7b165a7354.png)

**Comment by cirospat** [comment]
_> @gbvitrano gli eventi sono 2484 (la prova è con `<eventi.json jq '.events|length'`).
> 
> In ogni caso, sbagliavo una cosa, perché facevo l'inner join e non il left tra eventi e tipo evento. Ma non tutti gli eventi hanno un "tipo" associato, quindi con l'inner tagliavo quelli senza tipo.
> 
> @cirospat ho aggiornato il CSV nella mia risposta, adesso è corretto_

@aborruso ho caricato il file CSV che hai ottenuto tu su un foglio Google:
[https://docs.google.com/spreadsheets/d/1kuM520svj-J2cDlNTKbIhGj30Y5_uNceH0syGbtZMBg/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1kuM520svj-J2cDlNTKbIhGj30Y5_uNceH0syGbtZMBg/edit?usp=sharing)

ci sono troppi errori:

- lat e long in formati numerici strani (ho già impostato foglio di lavoro su Regno Unito)
- nella stessa colonna "ID" ci sono informazioni di carattere diverso
- nella colonna "start" e "end" non ci sono formati date
- nella colonna "details" ci sono formattazioni HTML

Se si potesse lavorare direttamente sul foglio Google, sarebbe ideale così poi una volta pulito tutto scarico in CSV e pubblico sul portale open data. Siete in modifica.
Senza premura.

**Comment by gbvitrano** [comment]
> 
> 
> > Domanda... se vuoi mettere nel portale opendata del comune i dati sugli eventi di Palermo Capitale della Cultura 2018...Perchè non caricare direttamente il json sul portale opendata?
> > [eventi_palermo_capitale_cultura_2018_json.zip](https://github.com/opendatasicilia/tansignari/files/3666470/eventi_palermo_capitale_cultura_2018_json.zip)
> 
> @gbvitrano buongiorno
> sul pannello di controllo del portale open data, nella finestra dei formati del dataset non c'è `JSON`.
> C'è `GEOJSON`. Va bene lo stesso?
> 
> Ecco lo screenshot
> ![image](https://user-images.githubusercontent.com/3757525/65828875-03ecb500-e2a0-11e9-8f5a-cf7b165a7354.png)

Non credo, non pui mettere il file in formato zip come sono messi i gtfs di amat?

**Comment by gbvitrano** [comment]
> Se si potesse lavorare direttamente sul foglio Google, sarebbe ideale così poi una volta pulito tutto scarico in CSV e pubblico sul portale open data. Siete in modifica.
> Senza premura.

@cirospat non c'è il pulsante magico... ogni cosa è futto di studio e tempo e fatica, su google sheet si può fare è molto molto lento rispetto alla tecnica di usata da @aborruso o all'esempio fatto da me con excel e visidata.
Studia la struttura del json, guarda la formuletta che ho usato sullo sheet e vedrai che la si accenerà la lampadina :-) :-) ci sono arrivato io :-) :-)

**Comment by cirospat** [comment]
> > Se si potesse lavorare direttamente sul foglio Google, sarebbe ideale così poi una volta pulito tutto scarico in CSV e pubblico sul portale open data. Siete in modifica.
> > Senza premura.
> 
> @cirospat non c'è il pulsante magico... ogni cosa è futto di studio e tempo e fatica, su google sheet si può fare è molto molto lento rispetto alla tecnica di usata da @aborruso o all'esempio fatto da me con excel e visidata.
> Studia la struttura del json, guarda la formuletta che ho usato sullo sheet e vedrai che la si accenerà la lampadina :-) :-) ci sono arrivato io :-) :-)

Gianni hai ragione :)
Devo studiarmi un po di struttura del Json. Mi farà bene sicuramente.
E appena capisco posso pubblicare il dataset sul portale OD.
Mi avete dato ottimi input di partenza.
Mi metto di buzzo.

**Comment by gbvitrano** [comment]
su google sheet la formula base è **IMPORTJSON(url, xpath)**
se dai un'occhita alla struttura del json ti rendi conto di come è organizzato
![2019-09-28_21h56_21](https://user-images.githubusercontent.com/20488693/65829399-7dd36d00-e2a5-11e9-934c-3e442aa1dabf.png)

A differenze delle altre volte questo import è un po dicervo... apri un nuovo sheet crei una riga intestazione con tutti i nomi della struttura del json

![2019-09-29_10h40_51](https://user-images.githubusercontent.com/20488693/65829445-ed495c80-e2a5-11e9-9ed2-b8ada9e70901.png)

nella colonna **Id_evento** fai caricare tutti gli eventi usando 
`=IMPORTJSON("https://www.palermocapitalecultura.it/wp-json/eventon/events","events" )`

una volta che hai popolato la colonna ****Id_evento** con questa formuletta otterrai il nome
`=IMPORTJSON("https://www.palermocapitalecultura.it/wp-json/eventon/events",(CONCATENATE("events/",A2,"/","name") )
)`

**(CONCATENATE("events/",A2,"/","name")** qusto altro non è che Xpath della formula
dove **A2** rappresenta l'id evento

Sarebbe come scrivere questa:
`=IMPORTJSON("https://www.palermocapitalecultura.it/wp-json/eventon/events", "events/22234/name")`

per evitare di ripere l'id evento e velocizzare le operazioni xpath lo scrivo concatenando i vari campi

per ottere tutto il file ti basta cambiare di volta in volta la parte finale del (CONCATENATE("events/",A2,"/","XXXXXXXXXXX")

**Comment by cirospat** [comment]
Grazie Gianni.

Il dom 29 set 2019, 10:54 Giovan Battista Vitrano <notifications@github.com>
ha scritto:

**Comment by gbvitrano** [comment]
**Node not Available** non è un errore, significa che il dato cercato non c'è 
Ottenuti tutti i dati copiali in altro foglio, altrimenti ogni volta che chiudi le informazioni si perdono e riparte l'import

A questo punto devi convertire la data di inizio e fine dell'evento

**Comment by gbvitrano** [comment]
Se dopo aver costruito la seconda riga del foglio, la prima sono le intestazioni...
**Id_evento** `=IMPORTJSON("https://www.palermocapitalecultura.it/wp-json/eventon/events","events" )`
ti restituisce #RIF niente panico :-)
fai caricare gli eventi in un nuovo folgio e li richiami nella colonna **Id_evento** 
con `=Sheet4!A2` o con il nome del foglio che hai dato tu :-)

**Comment by gbvitrano** [comment]
Ps... noi siamo molto privilegiati... non tutti gli impegati comunali hanno un **help desk** 24/7 con professionisti come @aborruso e @pigreco, la formazione dell'impiegato non è uno spreco di tempo ma un investimento da parte del Comune.
I software cambiano velocemente... la formazione resta. :-) senza non si va da nessuna parte... il pulsante magico ancora non esiste... e quando esisterà **noi umani** non sareno più utili...ma è solo una mia opinione personale...

**Comment by aborruso** [comment]
Caro @cirospat,
un consiglio di base è in fase di import disabilitare tutte le interpretazioni automatiche dei formati.
Poi il formato, se serve, lo puoi cambiare dopo.

Di base, almeno a prima lettura, quindi sempre così (cambiando il separatore del caso):

![image](https://user-images.githubusercontent.com/30607/65831469-18d64200-e2ba-11e9-8877-d97a3fe454ec.png)

Questo mi porta a questo sheet: https://docs.google.com/spreadsheets/d/1aT0OiJ9PAM2OZhR_3FKolynTpr5DNlAzV1zNvc7DBZ4/edit#gid=0 

 
> ci sono troppi errori:

La gran parte non sono errori, ma è come sono i dati in origine. Ti rispondo sotto per punti.

> 
> * lat e long in formati numerici strani (ho già impostato foglio di lavoro su Regno Unito)

Qui ci sono degli errori, perché se vedi min e max di lat e lon ci sono valori folli. Credo siano pochi casi. E questo non dipende, né dal formato, né dallo strumento. I dati sono in origine errati

![image](https://user-images.githubusercontent.com/30607/65831540-001a5c00-e2bb-11e9-865c-2d5b78055040.png)


> * nella stessa colonna "ID" ci sono informazioni di carattere diverso

Mi dici (nel mio sheet) un caso in cui in ID ci sono info di carattere diverso. Questo campo a me sembra ok.

> * nella colonna "start" e "end" non ci sono formati date

È il formato più classico con cui si conservano le date in un db: è lo [unix timestamp](https://www.wikiwand.com/it/Tempo_(Unix)). Si archiviano così e poi si mostrano all'utente diversamente. Il JSON qui è il formato di archivio, che poi sul web veniva convertito automaticamente.

In uno sheet puoi applicare un formula come `C2/86400 + DATE(1970,1,1)`, dove C2 è la cella che contiene il valore. Ho aggiunto la colonna `ConversioneEsempio`.

> * nella colonna "details" ci sono formattazioni HTML

Anche questo non è un errore. Sono dati raccolti, per poi essere formattati sul web. Si possono appiattire rimuovendo tutti i tag.

Baci

**Comment by gbvitrano** [comment]
il medoto con google sheet non va bene, troppe richieste fanno andare in errore lo script 

![2019-09-29_16h42_14](https://user-images.githubusercontent.com/20488693/65834125-28648380-e2d8-11e9-842a-2f091b6e531c.png)

**Comment by aborruso** [comment]
Aggiungo una buona lettura sui campi con date https://towardsdatascience.com/dates-times-calendars-the-universal-source-of-data-science-trauma-92a887fdedd1
