### ISSUE TITLE
Convertire molti file markdown in PDF

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#93]
Ho una cartella con molti file markdown e dovrei convertirli in PDF, usando VScode ho trovato una estensione (Markdown PDF) che permette la conversione ma un file per volta.

Come potrei ovviare??

**Comment by pigreco** [comment]
Dopo qualche ricerca nel web ho trovato questa risposta in [`stackoverflow.com`](https://stackoverflow.com/questions/14899283/converting-multiple-markdown-files-with-links-to-pdf) dove consigliano di usare `Pandoc`:

`pandoc *.md -o result.pdf`

ma ottengo un errore:

`pdflatex not found. Please select a different --pdf-engine or install pdflatex`

anche installando `pdflatex` : `sudo apt install texlive-latex-base`

non riesco a fare la conversione.

**Comment by pigreco** [comment]
Ho provato anche un'altra soluzione:
convertire da *.md in *.odt: `pandoc *.md  -o output.odf `, funziona ma le immagini (contenute nel md) vengono deformate e il file risulta odf risulta inutilizzabile:

![image](https://user-images.githubusercontent.com/7631137/67166008-e46f1680-f38b-11e9-8185-52066143819a.png)

**Comment by aborruso** [comment]
> convertire da *.md in *.odt: `pandoc *.md -o output.odf `, funziona ma le immagini (contenute nel md) vengono deformate e il file pdf risulta inutilizzabile:

Che comando pandoc hai usato? Senza sapere questo, è difficile dare un contributo.

Grazie

**Comment by pigreco** [comment]
Buongiorno @aborruso ,

> Che comando pandoc hai usato?

ho usato semplicemente questo comando:

`pandoc *.md -o output.odf`

**Comment by aborruso** [comment]
> ho usato semplicemente questo comando:
> 
> `pandoc *.md -o output.odf`

ok, purtroppo (come abbiamo visto), non è un comando completo, perché non contiene info sulle immagini.

**Comment by aborruso** [comment]
Caro @pigreco ho visto il tuo file di esempio:

- ci sono errori nei path HTML;
- mancano delle `"` nella definizione del `src` delle immagini.

Il metodo che ho ducumentato qui nell'opzione 2

```
pandoc -o output.odt --lua-filter=imgWidth.lua --reference-doc=myPandocTemplate.odt  02_installazione.md
```

prevede che le immagini siano inserite in sintassi markdown. Ti allego uno zip per replicare la cosa.
Contiene pure un output di esempio.

Se la cosa va bene, non ti resta che fare un loop in bash e creare gli odt. Con quelli poi c'è da trovare come generare dei PDF, ma immagino non sia complesso (con libreoffice stesso in batch è fattibile).

Saluti

[da_md_a_odt.zip](https://github.com/opendatasicilia/tansignari/files/3749527/da_md_a_odt.zip)

**Comment by gbvitrano** [comment]
Ho provato a sostituire il **--pdf-engine** di pandoc ma al momento non funziona!
ho installato **lualatex** ma non riesco a settarlo di default.
Provo a dare questo comando **pandoc *.md -o result.pdf --pdf-engine=lualatex** ma dice che lualatex non è installato. 

Per il momento mi arrendo con pandoc :-)

Ho trovato un plugin di vscode che potrebbe fare al caso tuo.
![immagine](https://user-images.githubusercontent.com/20488693/67224611-e095cf80-f431-11e9-89e0-bd242e8bf3e0.png)
è il plugin **[Markdown Converter
](https://marketplace.visualstudio.com/items?itemName=manuth.markdown-converter)**
una volta installato, premendo F1 e digitando *Markdown: Converter all Document* troverai il comando, come in figura.
![immagine](https://user-images.githubusercontent.com/20488693/67224840-60bc3500-f432-11e9-86fb-c9ea43411ae6.png)
Il plugin automaticamente converte tutti i file .md che si trovano nella cartella radice e sottocartelle varie. 
Per convertire un gruppo di cartelle specifiche ho aperto nuova un'area di lavoro sulla cartella di mio interesse. 
Esempio voglio convertire in pdf solo i file della cartella **ricette** su **tansignari**
![2019-10-21_18h50_25](https://user-images.githubusercontent.com/20488693/67225495-a75e5f00-f433-11e9-9b89-cc063aa4e9a3.png)

Apro la cartella in una nuova area di lavoro **F1** seleziono   **Markdown: Converter all Document**
e dopo qualche minuto (il mio pc e lento) tutti i file .md all'inertno di **ricette** sono stati convertiti in pdf :-) 
![2019-10-21_18h53_42](https://user-images.githubusercontent.com/20488693/67225781-1a67d580-f434-11e9-93ff-50430296ee10.png)

**Comment by gbvitrano** [comment]
Dopo aver provato diverse **--pdf-engine** con pandoc **xelatex** sembra funzionare ma a condizioni che i file .md siano formattati come suggerisce @aborruso 

per installare 
`sudo apt-get install texlive-xetex`

questo comando converte tutti i file .md presenti in una cartella in un unico file pdf
`pandoc *.md --pdf-engine=xelatex -o result.pdf`

per convertire un singolo file
`pandoc test.md --pdf-engine=xelatex -o test_pdf.pdf`

Occore approfondire la formattazione del pdf in uscita,  formato, caratteri, margini, ect

**Comment by gbvitrano** [comment]
@pigreco ho trovato questa [procedura](https://gist.github.com/rain1024/98dd5e2c6c8c28f9ea9d) per ubuntu, stranamente non mi dato problemi nell'installazione e il comando 
`pandoc *.md  -o result.pdf --pdf-engine=pdflatex`  funziona

funziona anche `pandoc *.md -o result.pdf`
forse **pdflatex** con questa procedura è tornato ad essere il pdf-engine predefinito

**Comment by gbvitrano** [comment]
Qui un test usando lo stesso file semicoln_googlesheets.md

[result_pandoc.pdf](https://github.com/opendatasicilia/tansignari/files/3754687/result_pandoc.pdf)
[result_vscode.pdf](https://github.com/opendatasicilia/tansignari/files/3754689/result_vscode.pdf)
