### ISSUE TITLE
Windows Terminal come impostare la cartella di start

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#94]
Ho appena installato **Windows Terminal (Preview)** version: 0.6.2951.0 sun Windows 10 build 18362

![image](https://user-images.githubusercontent.com/7631137/68653971-35a69c00-052d-11ea-9db6-be7f703b046b.png)

come lanciare il terminale da una cartella qualsiasi??
con bash bastava scrivere `bash` nella barra dei percorsi, come da gif animata:

![bash](https://user-images.githubusercontent.com/7631137/68654253-d09f7600-052d-11ea-864d-fe7ba402b18b.gif)

allego il file che ottengo da `settings`:

[profiles.txt](https://github.com/opendatasicilia/tansignari/files/3835066/profiles.txt)

**Comment by aborruso** [comment]
Non appena in explorer, prova a scrivere nella barra degli indirizzi wt.exe (anche solo wt)

**Comment by pigreco** [comment]
Caro @aborruso, grazie per la tempestiva risposta.

Ecco cosa accade da me:

- vado in una cartella qualsiasi del mio laptop;
- scrivo `wt` nella barra dei percorsi,
- dopo invio, si apre il terminale
- ma il percorso non è quello da cui lo ho lanciato:

![wt](https://user-images.githubusercontent.com/7631137/68655452-59b7ac80-0530-11ea-8076-29de9641dc8f.gif)

**Comment by aborruso** [comment]
Il tuo profile è molto diverso dal mio. Vedo che ti manca la starting directory.

L'ho modificato, ho aggiunto un parametro e ti ho messo Linux by default. Perché ti parte powershell.

Provalo https://gist.github.com/aborruso/ec6cfaf91e483babcc9984b34c971964

Qui le differenze con il tuo https://gist.github.com/aborruso/ec6cfaf91e483babcc9984b34c971964/revisions

**Comment by pigreco** [comment]
@aborruso
bingo, tutto risolto. 

ecco una piccola dimostrazione:

![wt_ok](https://user-images.githubusercontent.com/7631137/68656021-57098700-0531-11ea-8f5f-9eca4f5826cb.gif)

Grazie!

**Comment by pigreco** [comment]
@aborruso 

con questo terminale è possibile `scrollare`:

![wt_ok_scroll](https://user-images.githubusercontent.com/7631137/68656880-ed8a7800-0532-11ea-9f43-ca9d5634d79f.gif)
