### ISSUE TITLE
sqlite dentro jn, come cambiare formato output tabelle

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#95]
dal sito di [SQLite ](https://sqlite.org/cli.html#changing_output_formats)leggo:

```
sqlite> .mode column
sqlite> select * from tbl1;
one         two       
----------  ----------
hello       10        
goodbye     20        
sqlite>
```

in jupyter notebook NON riesco a farlo funzionare:
![image](https://user-images.githubusercontent.com/7631137/68932296-98e53800-0792-11ea-83be-dd098ed3867b.png)

vorrei vedere intestazione della tabella interrogata.

**Comment by aborruso** [comment]
Prova con 

```bash
sqlite3 -column -header nomedb.sqlite <<EOF
SELECT * from table limit 10;
EOF
```

**Comment by aborruso** [comment]
Il comando `.mode` non può funzionare, perché è pensato per la modalità interattiva e tu non sei in quella modalità

**Comment by pigreco** [comment]
@aborruso 
funziona, grazie.

![image](https://user-images.githubusercontent.com/7631137/68936086-1496b300-079a-11ea-8adb-f5a581e17177.png)

**Comment by aborruso** [comment]
Farei un capitolo sqlite qui https://tansignari.readthedocs.io/it/latest/ricette/index.html e gli metterei la prima ricetta "Come visualizzare a "colonne" l'output di una query nella shell" (aldilà del notebook)

**Comment by pigreco** [comment]
Caro @aborruso 

> Farei un capitolo sqlite qui https://tansignari.readthedocs.io/it/latest/ricette/index.html e gli metterei la prima ricetta "Come visualizzare a "colonne" l'output di una query nella shell" (aldilà del notebook)

provvedo subito 👍

**Comment by pigreco** [comment]
[qui](https://github.com/opendatasicilia/tansignari/blob/master/ricette/sqlite/visualizzare_colonne_output_shell.md) una bozza
