### ISSUE TITLE
[QGIS] Compositore di stampa - filtrare solo una parte di oggetti di una tabella

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari#96]
Buonasera,
Sto giocando con il compositore di stampe, provo a fare un pdf della mappe delle fontanelle.
Visto che la tabella è lunga ho pensato di ordinare e filtrare in base alle Circoscrizioni.
Come posso filtrare contemporaneamente le prima 4 circoscrizioni?

Visto che non ci riesco, in alternativa  avevo pensato di duplicare la tabella e filtrare singolarmente :-(

![immagine](https://user-images.githubusercontent.com/20488693/69561170-39b2cf00-0fad-11ea-90fc-4225ee8100b0.png)

**Comment by pigreco** [comment]
Ciao @gbvitrano 
puoi allegare i dati e il progetto, grazie.

**Comment by gbvitrano** [comment]
eccolo :-)

[fontanelle_webmaps.zip](https://github.com/opendatasicilia/tansignari/files/3887802/fontanelle_webmaps.zip)

**Comment by pigreco** [comment]
Caro @gbvitrano 
il campo `Cirocoscrizioni` è testuale e contiene valori I,II,III,IV,V,VI,VIIe VIII
puoi applicare tutti i filtri che vuoi, esempio:

- `"Circoscrizione" <=  'IV'` per ottenere tutti i record dalla I alla IV compresa;
- `"Circoscrizione" >  'IV'  and  "Circoscrizione" <=  'VI'` per ottenere tutti i record dalla IV (esclusa)  
 alla VI (inclusa)

![image](https://user-images.githubusercontent.com/7631137/69564664-b5b01580-0fb3-11ea-9eb0-cc455d966d48.png)

**Comment by gbvitrano** [comment]
Grazieeee
