### ISSUE TITLE
[shortcut] per avviare QGIS  senza plugin

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#97]
[QGIS ](https://qgis.org/it/site/)è un software Open Source (multipiattaforma) molto usato da chi lavoro nel mondo GIS,
una delle sue più apprezzate componenti è la possibilità di estendere la ""potenza" di analisi attraverso l'uso di `plugin`, che fanno una cosa sola ma bene.

L'avvio di QGIS è drasticamente rallentato dal numero di plugin installati, in quanto QGIS controlla, all'avvio appunto, tutti i plugin installati; esiste la possibilità di avviare QGIS tramite l'aggiunta di `--noplugins` alla stringa di avvio in modo da non caricare nessun plugin (anche quelli importanti come **processing**, ma alcune volte è molto utile.

esempio:

```
"C:\Program Files\QGIS 3.8\bin\qgis-bin.exe" --noplugins
```

L'idea è quella di creare una combinazione di tasti, personalizzabile, per avviare QGIS senza plugin.

**Comment by aborruso** [comment]
Caro @pigreco , in ambiente Windows, per creare tasti di scelta rapida personalizzai io utilizzo https://www.autohotkey.com/

Una volta scaricato e installato, dovrai creare un file di testo con estensione `.ahk` e scriverci dentro ad esempio:

```
#SingleInstance Force
#installKeybdHook
#Persistent
Return

; Lancia QGIS senza plugin attivi, utilizzando i tasti CTRL + ALT + q
^!q::
Run "C:\Program Files\QGIS 3.8\bin\qgis-bin.exe" --noplugins
```

Lo salvi ad esempio sul desktop e poi ci fai doppio click sopra. Rimarrà attivo in background.

Una volta fatto, prova a usare <kbd>CTRL</kbd> + <kbd>ALT</kbd> + <kbd>q</kbd>

**Comment by pigreco** [comment]
Testato, funziona benissimo!!

Grazie @aborruso 
![image](https://user-images.githubusercontent.com/7631137/70165153-b0914b80-16c2-11ea-9a8a-5d1ee5e1ead2.png)
