### ISSUE TITLE
[regex] pulizia nomi vie

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#98]
Ho un file CSV con un campo popolato con nomi di via più qualcosa che non mi serve:

```
Vicolo Sponta (00223)
via della madonna (99999)(ED 1a)
via della montagna(00237)(ED 1a)
via delle aie(00242)(ED 1a)
via delle aie(00187)(ED 1A)
via delle piagge (0021)ed.1
```
devo pulirli e togliere tutto quello che è dentro le parentesi, comprese le parentesi:

es:

da : `via della montagna(00237)(ED 1a)` a `via della montagna`

ho provato con [questo](https://regex101.com/r/4jfB3B/1): `^(.+)(\(.+\))` ma prende solo le ultime due parentesi;
poi ho risolto usando questa: `(\(.+\))` oppure per gruppi [questa](https://regex101.com/r/iCIMd0/3): `^(.+) *\(([0-9]+)\)(\((.+)\))*`

ma analizzando il file CSV trovo anche questo caso:

`via delle piagge (0021)ed.1`

che deve diventare: 

`via delle piagge`

in pratica devo conservare solo il nome della via, tutto il resto non serve.

**Comment by aborruso** [comment]
@pigreco che ne pensi di questa regex https://regex101.com/r/9pEjkw/1

Cancella tutto dalla prima parentesi in poi

**Comment by pigreco** [comment]
@aborruso, penso che devo studiare... e molto!!!

grazie, funziona!!!
