### ISSUE TITLE
[SQLITE] UPDATE restituisce valori errati

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari#99]
Ho tre vettori **LINESTRING** (`l_ass_proiezioni`, `l_complementari` e `rete_b`); i tre vettori hanno la seguente relazione spaziale:

`l_ass_proiezioni` + `l_complementari` = `rete_b` 

oppure

`l_ass_proiezioni` + `l_complementari` - `rete_b` = `delta`

per fare questa verifica creo il seguente script SQL

```sql
SELECT DropGeoTable( "verifica");
CREATE TABLE "verifica" 
("l_ass_proiezioni" real,
"l_complementari" real,
"rete_b" real,
"delta" real);

INSERT INTO "verifica" 
SELECT  st_length(st_union("geometry")), 0.0,0.0,0.0
FROM "l_ass_proiezioni";

UPDATE "verifica" SET "l_complementari" =
(SELECT  st_length(st_union("geometry")) 
FROM "l_complementari_elem");

UPDATE "verifica" SET "rete_b" =
(SELECT  st_length(st_union("geometry")) 
FROM "l_rete_b_to_projections_elem");

UPDATE "verifica" SET "delta" =
round(("l_ass_proiezioni" + "l_complementari_elem" - "rete_b"),3);
```

i primi quattro (compreso ROWID) campi sono popolati correttamente, mentre il campo `delta` è palesemente errato

![image](https://user-images.githubusercontent.com/7631137/71306608-d61c9580-23e2-11ea-9028-6d1404802f7d.png)

sembra che l'ultima `UPDATE` non lavori correttamente in quanto non fa le giuste operazioni, come se non considerassi `l_complementari`.

allego db:
[verifica.zip](https://github.com/opendatasicilia/tansignari/files/3991288/verifica.zip)

- Utilizzo Win 10 64b
- SpatiaLite_GUI 2.10 con Spatialite 5.0 beta1 e SQLite 3.28

**Comment by aborruso** [comment]
Caro @pigreco , non mi sembra che  esista il campo `l_complementari_elem"`.

Vedi se va con

```
"l_ass_proiezioni" + "l_complementari" - "rete_b"
```

**Comment by pigreco** [comment]
@aborruso, credo sia arrivato l'ora di usare gli occhiali.

grazie, funziona!!
